### ISSUE TITLE
Adding tls support to admin Dashboard

### ISSUE THREAD

**Issue by sfroment** [linkerd/linkerd#1018]
Hello,

There is no way to add tls to admin dashboard for the moment.

Best regards.

**Comment by hawkw** [comment]
Hi @sfroment, just wanted to let you know I have a PR open that adds this feature (#1502). Hopefully we can get it merged soon! :)

**Comment by sfroment** [comment]
Thanks a lot :) (buoyantio team your the best!) !!! I close this issue reopen if finally it isn't merged !

**Comment by hawkw** [comment]
Aww, thanks @sfroment, we appreciate it! ❤️ 

I'm pretty sure we'll get this merged by the next release. We're right at the beginning of a release cycle right now, though, so it'll probably be a couple of weeks out.

Thanks for your support!

**Comment by hawkw** [comment]
Merged in c5a3b42f7d8fac76d8b8928ff9a369e803fe7be7! @sfroment, when this is released, you'll be able to add TLS to the admin page by adding 
```yaml
tls:
   certPath: path/to/cert.pem
   keyPath: path/to/key.pem
``` 
under `admin:` in the configuration file. 

There's a sample configuration in [`linkerd/examples/admin-tls.yaml`](https://github.com/linkerd/linkerd/blob/master/linkerd/examples/admin-tls.yaml). Any options you can add to TLS server configurations elsewhere in linkerd are also valid here. Also, note that you can now add TLS to namerd's admin dashboard as well!

Let me know if you have any questions or issues!

**Comment by sfroment** [comment]
Thanks you so much for your work on this one https://github.com/linkerd/linkerd/issues/1289#issuecomment-314878636 <3 that was a Real pain for me and i believe many people arround l5d

**Comment by sfroment** [comment]
The only thing that i thinknis missing is à http based auth but i'll try to do it my self when i'll have the time to learn scala 🙈
