### ISSUE TITLE
Modularize static assets for admin dashboard

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#1035]
Currently, all static assets (such as js and templates) for the admin dashboard must be in the admin project.  This means that there isn't a good way for plugins which provide admin site functionality to add static assets.

We should come up with a modular way for plugins to provide static assets and move code and assets related to specific plugins out of the admin project and into the respective plugin projects.

This should be done in a way that supports bundling, minifying, uglifying, transpiling, testing, etc.

**Comment by esbie** [comment]
Canonical js modularity comes from npm modules, with dependencies defined in `package.json`. To combine the modules for use in the browser, usually a second build tool is used like browserify, webpack, or jspm. It's possible to use requirejs in this capacity, but probably lacks features of the newer build tools.

Generally this approach seems at odds with the linkerd plugin system being configured at runtime.
This approach also adds a build step into js development that wasn't there previously.
And as discussed previously I want to avoid duplicate build configs living in various places in the repo.

**Comment by adleong** [comment]
Not going to do this in the near term.  Closing for now.
