### ISSUE TITLE
test admin endpoints

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd#1036]
follow up from #1029, we should verify all admin endpoints are working, and then either fix or remove.

**Comment by rmars** [comment]
admin endpoints as seen at `http://localhost:9990/admin`

- [ ] /
- [ ] /admin/announcer
- [ ] /admin/contention
- [ ] /admin/lint
- [ ] /admin/lint.json
- [ ] /admin/metrics
- [ ] /admin/metrics.json
- [ ] /admin/metrics/prometheus
- [ ] /admin/ping
- [ ] /admin/pprof/contention
- [ ] /admin/pprof/heap
- [ ] /admin/pprof/profile
- [ ] /admin/registry.json
- [ ] /admin/server_info
- [ ] /admin/shutdown
- [ ] /admin/threads
- [ ] /admin/threads.json
- [ ] /admin/tracing
- [ ] /bound-names.json
- [ ] /config.json
- [ ] /delegator
- [ ] /delegator.json
- [ ] /favicon.png
- [ ] /files/
- [ ] /help
- [ ] /logging
- [ ] /logging.json
- [ ] /namerd
- [ ] /requests

**Comment by adleong** [comment]
@rmars is this done?

**Comment by rmars** [comment]
I think we still need to test `/admin/tracing`, `/admin/announcer` and `/admin/pprof/heap`

**Comment by klingerf** [comment]
Am going to call this one done.
