### ISSUE TITLE
Add docker stats to linkerd stats

### ISSUE THREAD

**Issue by stevej** [linkerd/linkerd#1064]
For debugging purposes, it would be really nice to see the container stats. Most importantly, it contains stats for whether we are being cpu throttled by cgroups.

Docker provides an easier API than trudging through `/sys` and `/proc`.

`echo -e "GET /containers/$CONTAINER_ID/stats HTTP/1.1\r\nHost: localhost\r\n" | nc -U /var/run/docker.sock -q -1`

To find the current container ID, we can look in `/proc/self/cgroup` and use a regex to pull out `.*/docker/([a-f0-9])$`, and then query the Docker Remote API, which is an HTTP/1.1 endpoint that returns chunked encoded JSON. The one configuration option we might need from a user is the socket address, either a unix domain socket or an IP:PORT. For a default value, we can make some educated guesses to try and find the domain socket and then try and fall back to localhost:4243

Once we have the JSON blob, we can add them as gauges and counters to a StatsReceiver.

**Comment by olix0r** [comment]
I'm skeptical that linkerd should be responsible for monitoring the underlying system.  Surely there's a way to configure this sort of monitoring directly with prometheus, etc?

**Comment by adleong** [comment]
@stevej are we okay to close this?

**Comment by stevej** [comment]
Yeah, I'll close this. We can revisit it at a later date if the need arises.
