### ISSUE TITLE
Namerd UI: distinguish between "active" path and possible alternatives

### ISSUE THREAD

**Issue by Ashald** [linkerd/linkerd#1074]
This is a follow-up on #604 . For the sake of demonstration the one can use the dtab from #604 or a slightly simplified one provided below.:

```
/bar=>/$/inet/456;
/foobar=>/bar | !;
/foobar=>/foo | !;
```

Expected behavior is such that resolution for `/foobar` must not succeed (due to explicit failure). This is how it works when you use the api:
```
$ curl -s "http://localhost:4180/api/1/resolve/bug?path=/foobar" | jq "."
{
  "type": "neg"
}
```
While the name resolution does fail Namerd UI shows that there are possible successful paths. This is great for debugging purposes (when you look how to fix your Dtab so it will give you desired result) but it's confusing when you trying to understand _how_ the Dtab works.

![screen shot 2017-02-15 at 20 49 06](https://cloud.githubusercontent.com/assets/397987/23003658/4c14a77e-f3c0-11e6-8fc0-f7079af87def.png)

Briefly discussing this with @adleong in Slack we agreed that both of use-cases mentioned above make sense so we need to distinguish between an "active path" and "possible paths".
There are at least 2 options:
1) Styling: somehow highlight the "active path" / gray out "alternative paths"
2) Add a toggle to switch between different modes where only "active path" is displayed or all possible paths

**Comment by adleong** [comment]
Hey @Ashald, would you mind updating the description here with what we discussed in slack?  Namely that the delegator UI should somehow indicate which path is the "active" path (but continue to display all branches)

**Comment by Ashald** [comment]
@adleong yeah, sure

**Comment by Ashald** [comment]
I'm wondering whether it can be handled like:
1) if there is a "successful active" path - highlight all steps in it with green
3) leave "possible alternatives" white all the way down
3) tint Neg/Fail with red
4) If there are no "successful path" - show all possible paths in red (all steps from the root to leaves)

Or would you prefer just a toggle to switch between "show only active path" / "show all possible paths"?

**Comment by Ashald** [comment]
👍👍👍
