### ISSUE TITLE
Use finagle grpc outside linkerd

### ISSUE THREAD

**Issue by teodor-pripoae** [linkerd/linkerd#1075]
Hi,

I'm planning to use the grpc-runtime in a different project. Is this library intended to be used also outside linkerd ?

Thank you,
Teodor

**Comment by olix0r** [comment]
Hi @teodor-pripoae. There's no reason that this _can't_ work outside this repo, but there's some work that needs to be done to make it easier.

1. Our repo has [special SBT configuration](https://github.com/linkerd/linkerd/blob/master/project/Grpc.scala) that builds the `protoc-gen-io.buoyant.grpc` protoc plugin.  You'll need to build this manually form our repo with `./sbt grpc-gen/assembly`.  This will produce a binary that should be placed on your $PATH.
2. You'll need to add the sbt-protobuf plugin and override it to use additional settings including:
```scala
  val grpcGenSettings =
    protobufSettings ++ inConfig(protobufConfig)(Seq(
      javaSource <<= (javaSource in Compile),
      scalaSource <<= (sourceManaged in Compile) { _ / "compiled_protobuf" },
      generatedTargets <<= scalaSource { d => Seq(d -> "*.pb.scala") },
      protocOptions <<= scalaSource { ss =>
        Seq(s"--io.buoyant.grpc_out=plugins=grpc:${ss.getCanonicalPath}")
      }
    )) ++ Seq(
      // Sbt has trouble if scalariform rewrites the generated code
      excludeFilter in ScalariformKeys.format := "*.pb.scala",
      coverageExcludedFiles := """.*\.pb\.scala""",

      // We don't need protobuf-java.
      libraryDependencies <<= libraryDependencies(_.filterNot(_.name == "protobuf-java"))
    )
```

This should really all be packaged as an SBT plugin, but I haven't had the time to do that.

Furthermore, the APIs are not very well documented yet, so please don't hesitate to ask questions here or in the #finagle room on slack.linkerd.io!

**Comment by teodor-pripoae** [comment]
Hi,

Thank you for your help !

I've been able to successfully run grpc client/server by using the code from `0.9.0-rc1`.  I've put an example on github here: https://github.com/teodor-pripoae/finagle-grpc-example.

I can see it doesn't work with finagle `6.42.0` yet. Are there any plans to support in the near future ?

Also, I spotted a bug involving tracing, currently all the spans for a server are in one big [trace](http://imgur.com/gzcqiEx).

**Comment by klingerf** [comment]
Hi @teodor-pripoae -- glad it's working for you. The h2 tracing issue is tracked in #732.

**Comment by olix0r** [comment]
@teodor-pripoae we'll upgrade to the newest finagle after the 0.9.0 this release.

**Comment by adleong** [comment]
finagle upgrade is tracked here: https://github.com/linkerd/linkerd/issues/1107

**Comment by teodor-pripoae** [comment]
Hi,

Is it currently possible to implement load balancing/circuit braker/service discovery on top of the grpc client ?

**Comment by adleong** [comment]
Yes, load balancing, circuit breaking, and service discovery should work with the grpc client.

**Comment by jbripley** [comment]
@olix0r has there been any progress of breaking out the gRPC generation into a separate SBT plugin yet? Otherwise, I'd like to help out with making that happen. We're planning to use this in a new gRPC based project at work, which means I can dedicate some time to help out with this.

**Comment by johnynek** [comment]
yeah, at Stripe we may also be interested in a finagle-grpc and could possibly spend some cycles on it. It there was a stand-alone project for that we would likely contribute some time to it (and at least send bug reports. :)

**Comment by penland365** [comment]
+1 to @jbripley and @johnynek - I know it's extra dev cycles for y'all, but it would be great if buoyant was able to break out a `finagle-grpc` so we can contribute some cycles to it. We're kicking off a new project as well and want to go full bore gRPC / Finagle / Linkerd with it.

**Comment by olix0r** [comment]
We'd really like to make it easier for others to work on our finagle-h2 and finagle-grpc implementations.  I'd like to propose the following:

1. We'll create a new repo with copies of linkerd's `finagle` and `grpc` subprojects.  The finagle project houses our h2 implementation and the grpc project has the protoc plugin, runtime library (that depends on the h2 impl, etc).
2. We'll probably need help putting together an SBT plugin.
3. Once we can publish all of this from the new repo, we'll update the linkerd repo to depend on these libraries.

Practically, we're not likely to make much progress on this until after linkerd-1.2.0 is released (unless we find some free time).  This is about 2 weeks out.  I've opened https://github.com/linkerd/linkerd/issues/1588 to track this.
