### ISSUE TITLE
OpenTracing support

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#1079]
At some point, we may want to have native support for opentracing in linkerd (i.e instead of / in addition to the l5d-ctx-trace header).  What would this look like?

**Comment by zhangmuxi** [comment]
Have you guys implemented this or not?

**Comment by klingerf** [comment]
Hey @zhangmuxi -- this is still unimplemented in Linkerd. You might be interested in following this opentracing issue, which has a bit more context around trace implementations in proxies: opentracing/specification#86.

**Comment by mqliang** [comment]
@olix0r @klingerf IIUC, currently, we already have a [linkerd-zipkin](https://github.com/linkerd/linkerd-zipkin) plugin, which is a linkerd telemeter plugins for writing trace data to zipkin, but this is dedicated to zipkin. And, we want implement a linkerd-opentracing plugin, which writes trace data to all tracing vendor, as long as it support opentracing?

**Comment by klingerf** [comment]
Hey @mqliang -- your understanding is correct. Right now Linkerd supports exporting tracing data in the Zipkin format, which can be collected by any Zipkin-compatible collector, such as Zipkin itself and Stackdriver. We'd need to add a separate telemeter plugin to export tracing data in the OpenTracing format, and that would enable OpenTracing-compatible collectors, such as Jaeger and LightStep.

**Comment by malafeev** [comment]
I think plugin is not enough. 
We need a filter to have access to http headers of incoming and outgoing requests.
Filter should:
1. Extract span context from http headers of incoming requests (and later use this span context as parent for created span)
2. Create span and inject it into http headers of outgoing request.
3. Call Trace.recordBinary("opentracing-span", span). It will be intercepted by OpenTracing linkerd plugin (using TelemeterInitializer)

The problem that there isn’t a way to inject arbitrary filters via plugin (https://discourse.linkerd.io/t/is-it-possible-to-set-common-client-and-server-filter-via-plugin/493/2?u=malafeev)

**Comment by SecretLiang** [comment]
@malafeev Then, how linkerd-zipkin plugin handle this? Hardcoding the HTTP header in the core codebase, instead of injecting via plugin? And you mentioned at https://discourse.linkerd.io/t/is-it-possible-to-set-common-client-and-server-filter-via-plugin/493/2?u=malafeev that you can create a PR, do you mean a PR that add filter to have access to http headers ?

**Comment by malafeev** [comment]
@SecretLiang linkerd-zipkin plugin based on finagle tracing (finagle inject/extract **b3** http headers).
I can create PR which will add Filter to inject/extract **opentracing** http headers.

**Comment by adleong** [comment]
Fixed by #2025
