### ISSUE TITLE
Linkerd UI is hard to use when it handles requests to a lot of different services

### ISSUE THREAD

**Issue by Ashald** [linkerd/linkerd#1099]
Although screenshot was taken with earlier version of Linkerd the latest one (0.9) essentially has the same issue as on screenshot below.

Maybe, it can solved with some kind of pagination and search? Or if there more than X services then replace a plain list with a search box with an auto-suggest where you can enter the name and hit an "add" button to add the graph to the page?...

![linkerd_lots_of_services](https://cloud.githubusercontent.com/assets/397987/23279204/5343db1e-f9e2-11e6-8294-ab546726b00c.png)

**Comment by Ashald** [comment]
@wmorgan @olix0r I promised to submit this issue a long time ago but just got a moment to process the screenshot :D

**Comment by wmorgan** [comment]
OMG

**Comment by adleong** [comment]
@Ashald #1274 may help with this.  what do you think?

**Comment by Ashald** [comment]
YES PLEASE! :)

BTW, how do you like an idea of an endpoint where you can see UI metrics for an individual service/client?

**Comment by olix0r** [comment]
@Ashald We'd probably take a pull request that did something like that! ;)

**Comment by adleong** [comment]
I like that idea a lot.  See: #1250

**Comment by adleong** [comment]
@Ashald have you tried the expiring clients in version 1.1.0 yet?  Do they address this issue?

**Comment by Ashald** [comment]
@adleong was out last week but hope to be able to check how it looks like this week. Will let you know - thanks!

**Comment by Ashald** [comment]
This helps tremendously - thanks a lot!

**Comment by wmorgan** [comment]
@Ashald great! Please close the ticket if you are satisfied :)
