### ISSUE TITLE
Usage counters with empty values

### ISSUE THREAD

**Issue by esbie** [linkerd/linkerd#1100]
A number of usage telemeters are reporting counters like: `"counters":[{"name":"srv_requests"},{"name":"srv_requests","value":325119},{"name":"srv_requests"}]` where a counter with no value is defined. 

If the router hasn't handled requests, let's omit the counter object for that router altogether

**Comment by esbie** [comment]
sort of related: it'd be nice to know which counter goes with which router

**Comment by adleong** [comment]
I can't reproduce this.  When I start a fresh linkerd and look at /admin/metrics/usage, this is what I see:

```
{
"pid": "abcb0f0e-dfdd-45ac-b64e-d19f80340343",
"linkerdVersion": "0.9.0-SNAPSHOT",
"osName": "Mac OS X",
"osVersion": "10.12.2",
"startTime": "2017-03-13T23:58Z",
"routers": [
{
"protocol": "http",
"interpreter": "",
"identifiers": [
"io.l5d.header"
],
"transformers": []
},
{
"protocol": "http",
"interpreter": "",
"identifiers": [
"io.l5d.header.token"
],
"transformers": []
}
],
"namers": [
"io.l5d.fs"
],
"counters": [
{
"name": "srv_requests",
"value": 0
},
{
"name": "srv_requests",
"value": 0
}
],
"gauges": [
{
"name": "jvm_mem",
"value": 970160320
},
{
"name": "jvm/gc/msec",
"value": 970160320
},
{
"name": "jvm/uptime",
"value": 115918
}
]
}
```

**Comment by rmars** [comment]
doesn't that give us counters per linkerd instance, rather than counters per individual configured router?

**Comment by rmars** [comment]
ohhhh nvm, you're replying to the first comment!

**Comment by esbie** [comment]
Hm, ok we'll have to do further investigation. My initial hypothesis of no traffic being the issue could be incorrect. We continue to see usage data with this symptom in loggly. Anecdotally I would say 25% of messages have this issue.

**Comment by rmars** [comment]
Btw I am able to reproduce this using the http example: ./sbt linkerd-examples/http:run - when I run the usage collector locally and look at the messages it sends, I see ` counters:<name:"srv_requests" > counters:<name:"srv_requests" value:2 >`

**Comment by esbie** [comment]
This looks like a grpc interpretation issue on the usage data collector side of things. Here's what I see:

counters from `admin/metrics/usage`:
```json
"counters":[{"name":"srv_requests","value":0},{"name":"srv_requests","value":0}]
```

counters from usage data collector:
```json
"counters":[{"name":"srv_requests"},{"name":"srv_requests"}]
```

Going to close this and open a ticket against the collector instead.
