### ISSUE TITLE
unrecognized syntax identifier "proto3". This parser only recognizes "proto2".

### ISSUE THREAD

**Issue by zillani** [linkerd/linkerd#1118]
I have cloned the repo on my linux ubuntu, and installed protoc, version 2.5. When I try to compile the linkerd using the following command I get the error "unrecognized syntax identifier "proto3". This parser only recognizes "proto2".

command: `./sbt linkerd/compile`

**Comment by zillani** [comment]
This helped! I have uninstalled the 2.x and upgraded to 3.x with proper instructions here, https://github.com/google/protobuf/blob/master/src/README.md

**Comment by wmorgan** [comment]
Great, glad you figured it out!
