### ISSUE TITLE
Stackoverflow tag request

### ISSUE THREAD

**Issue by zillani** [linkerd/linkerd#1120]
Can you guys please create a tag on stackoverflow, that will be helpful to post the questions :)

**Comment by wmorgan** [comment]
Great idea, but it looks like we'll need someone with over 1500 points to do that. Anyone a heavy StackOverflow user?

**Comment by DukeyToo** [comment]
Done - http://stackoverflow.com/questions/tagged/linkerd

**Comment by wmorgan** [comment]
@DukeyToo thank you very much!

**Comment by zillani** [comment]
@DukeyToo Awesome!
