### ISSUE TITLE
k8s namer should be case-agnostic

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#1123]
k8s services (all resources?) start must start with lowercase letters.  grpc services tend to have uppercase names.  If we make the k8s namer case-agnostic, this will all work smoothly with a simple:
```
/grpc/com/foo => /#/io.l5d.k8s/default/grpc ;
/svc => /$/io.buoyant.http.domainToPathPfx/grpc ;
```
to route a grpc service like com.foo.Bar to the "bar"service.

cc @christopheclc

**Comment by esbie** [comment]
good idea, when it's done we can update the grpc example too https://github.com/BuoyantIO/linkerd-examples/blob/master/gob/k8s/namerd/default.dtab

**Comment by chriswessels** [comment]
We're using gRPC and obviously service names are defined in PascalCase, and we'd like to define our k8s services with kebab-case.

For example, we may define our service name in our proto as `FraudModel`, and we'd like that to resolve to the `fraud-model` k8s service, but currently it only resolves to the `fraudmodel` service.

Is slightly more intelligent case conversion/resolution possible?

**Comment by esbie** [comment]
Not currently possible, but sounds like an easy rewriting namer to implement https://linkerd.io/config/0.9.1/linkerd/index.html#rewriting-namers

**Comment by chriswessels** [comment]
Thanks @esbie! Will take a look 😄
