### ISSUE TITLE
Upgrade to Scala 2.12

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#1128]
Creating this as a tracking ticket for upgrading the repo to 2.12. As part of this we'll also have to decide how long we continue to publish 2.11 artifacts after the upgrade.

**Comment by moderation** [comment]
The Finagle 6.41 [release notes](https://finagle.github.io/blog/2016/12/23/release-notes-6-41/) that mention the support for Scala 2.12.

> Scala 2.12 Support is Here
> Finagle, Util, Ostrich, Scrooge, and Twitter-Server are all now cross-compiled for Scala 2.11 and 2.12(!)

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd/pull/1257
