### ISSUE TITLE
Improve service name annotations in Zipkin UI

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#1132]
The Zipkin UI throws errors on service names that include transformers (e.g. `%/io.l5d.k8s.daemonset/default/incoming/l5d/#/io.l5d.k8s/default/http/hello`). Here's a sample error:

![screen shot 2017-03-08 at 3 02 17 pm](https://cloud.githubusercontent.com/assets/9226/23729767/a96d728a-0418-11e7-9caf-302b5cb0f761.png)

The dependency graph also looks pretty crazy, and the service names include node IPs, which makes for a pretty convoluted graph:

![screen shot 2017-03-07 at 3 51 22 pm](https://cloud.githubusercontent.com/assets/9226/23729861/2473ceac-0419-11e7-810a-2d06bb341b9c.png)

To fix this, I think we should switch away from using `dst.id` as the annotation endpoint service name on client spans, and instead use something more meaningful.

**Comment by rmars** [comment]
@klingerf do you still want to leave this open for tracking?

**Comment by klingerf** [comment]
Happy to close this, per @adleong's comment on #1135:

> It's inscrutable, but I think it's most correct and I prefer inscrutable to misleading.
