### ISSUE TITLE
linkerd routers should respond with request protocol, not the downstream response protocol

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#1133]
(am not entirely sure this writeup captures the issue, so please feel free to adjust as necessary)

Am seeing an issue running a linkerd http router in front of an HTTP/1.0 webserver. If I make an HTTP/1.1 request to linkerd, and it forwards it to a service that returns an HTTP/1.0 response, then the response from linkerd is also HTTP/1.0. In talking with @olix0r, I think it makes more sense for linkerd to still respond with HTTP/1.1, even if it received an HTTP/1.0 response.

Here's what the curl output looks like for this type of request:

```
$ http_proxy=$LINKERD_URL curl -v http://hello
* Rebuilt URL to: http://hello/
*   Trying 192.168.99.101...
* TCP_NODELAY set
* Connected to 192.168.99.101 (192.168.99.101) port 30665 (#0)
> GET http://hello/ HTTP/1.1
> Host: hello
> User-Agent: curl/7.50.3
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Type: text/html; charset=utf-8
< Content-Length: 39
< Server: Werkzeug/0.11.15 Python/2.7.12
< Date: Thu, 09 Mar 2017 00:16:21 GMT
< Via: 1.0 linkerd, 1.0 linkerd
* HTTP/1.0 connection set to keep alive!
< Connection: keep-alive
< 
* Curl_http_done: called premature == 0
* Connection #0 to host 192.168.99.101 left intact
Hello (172.17.0.9) world (172.17.0.10)!
```

This is using the hello world app from the linkerd-examples repo.

**Comment by olix0r** [comment]
Also note what the [spec says]:

> Intermediaries that process HTTP messages (i.e., all intermediaries other than those acting as a tunnel) MUST send their own HTTP-Version in forwarded messages.  In other words, they MUST NOT blindly forward the first line of an HTTP message without ensuring that the protocol version matches what the intermediary understands, and is at least conditionally compliant to, for both the receiving and sending of messages.  Forwarding an HTTP message without rewriting the HTTP-Version might result in communication errors when downstream recipients use the message sender's version to determine what features are safe to use for later communication with that sender.

**Comment by klingerf** [comment]
I've encountered another version of this issue, in the inverse. If I make an HTTP/1.0 request, and linkerd receives an HTTP/1.1 response, it sends the HTTP/1.1 response back to my client. Am not positive, but I think the right behavior in this situation would be for linkerd to return an HTTP/1.0 response.

For instance, with a router configured to forward to linkerd's admin port:

```
$ curl -v -0 localhost:4140/admin/ping
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4140 (#0)
> GET /admin/ping HTTP/1.0
> Host: localhost:4140
> User-Agent: curl/7.50.3
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Language: en
< Content-Length: 4
< Content-Type: text/plain;charset=UTF-8
< Via: 1.1 linkerd
< Connection: close
< 
* Curl_http_done: called premature == 0
* Closing connection 0
pong
```
