### ISSUE TITLE
Question: Does / will linkerd support websockets?

### ISSUE THREAD

**Issue by dls314** [linkerd/linkerd#1140]
Curious as in the title if linkerd supports websockets, and if not, will this be something that general TCP support might bring?

Thanks!

**Comment by klingerf** [comment]
Hey @dls314, thanks for the question, and apologies for the delay in responding. Linkerd doesn't have support for websockets. It's something that could be added in the future, but at present we're more focused on HTTP/2 streaming support.

We recently released the [linkerd-tcp](https://github.com/linkerd/linkerd-tcp), however, and websockets would be a good use case for that project. It's a TCP proxy, which can be used to proxy websocket connections. It won't give you all of the request-level features that you get with linkerd protocols, but it does handle service discovery and TLS, as well as connection-level observability.

**Comment by rohitnagpal88** [comment]
Any plan to include support for websockets in linkerd 1.x ? I do not like the idea of having to run another service like linkerd-tcp just to support a websocket connection.

**Comment by adleong** [comment]
Hi @rohitnagpal88!  As stated above, there aren't currently any plans to add websockets support to Linkerd 1.x
