### ISSUE TITLE
Soliciting linkerd CI requirements for Inclusive Integration with CNCF Projects

### ISSUE THREAD

**Issue by hh** [linkerd/linkerd#1141]
> "CNCF is helping develop a cloud native software stack that enables cross-cloud deployments. Cross-project CI that ensures ongoing interoperability is especially valuable." - Dan Kohn Executive Director CNCF

[[cncf-ci-public] CNCF CI Goals](https://lists.cncf.io/pipermail/cncf-ci-public/2017-February/000001.html)
[[cncf-ci-public] Soliciting CI requirements via Project GitHub Issues](https://lists.cncf.io/pipermail/cncf-ci-public/2017-March/000024.html)

This github issue is to provide a highly visible invite to be part of creating a cross-cloud cross-project CI within the diverse software communities of the Cloud Native Compute Foundation.

To fully understand our needs and expectations, some help documenting the current state of the linkerd CI and ongoing requirements of the linkerd community would be useful.

https://github.com/cncf/wg-ci/blob/master/projects/linkerd.mkd

As we collect linkerd and other project CI requirements, we'll use the @cncf/cncf-ci-working-group issue at https://github.com/cncf/wg-ci/issues/12 and encourage you to join the discussion on the [cncf-ci Mailing List](https://lists.cncf.io/mailman/listinfo/cncf-ci-public)

**Comment by siggy** [comment]
Hi @hh! I took a crack at documenting linkerd's current ci state, and where we'd like to take it, leveraging CNCF's infrastructure. Let us know if this is the direction you had in mind: https://github.com/cncf/wg-ci/pull/14

**Comment by klingerf** [comment]
@siggy Looks like cncf/wg-ci#14 was merged. Should we close this one as well?

**Comment by siggy** [comment]
@klingerf sgtm. all linkerd ci-related info for cncf is now at https://github.com/cncf/wg-ci/blob/master/projects/linkerd.mkd
