### ISSUE TITLE
Linkerd Namer for Rancher Cattle

### ISSUE THREAD

**Issue by dzirkler** [linkerd/linkerd#1146]
**_Enhancement request_**

I'd like to be able to have a namer consume the Rancher Cattle Metadata service that would allow linkerd within the cattle CNI managed network (ideally also in the docker and host networks too).

The metadata service appears to support long-blocking connections which unblock when the metadata is refreshed. This could be used to build a watcher. 

The following scenarios should all be considered (as well as `linkerd-->linkerd` paths):
``` Public --> Rancher LB --> linkerd --> service/container```
``` Public --> linkerd --> service/container```
``` Public --> linkerd --> Rancher LB --> service/container```

See Example blocking/wait call at: 
https://github.com/rancher/go-rancher-metadata/blob/master/metadata/change.go#L51

More info on Rancher Cattle Metadata Service:
https://docs.rancher.com/rancher/v1.5/en/rancher-services/metadata-service/

**Comment by adleong** [comment]
This would be awesome!  Definitely welcome any contributions from anyone with rancher experience.
