### ISSUE TITLE
Online configuration reloading

### ISSUE THREAD

**Issue by chrisboulton** [linkerd/linkerd#1152]
I just had a quick look through the source and could only find signal handlers for graceful shutdowns, so my assumption is right now this isn't supported (a tiny bit of me wants to believe it exists but is implemented in some manner other than process signals...)

I know reloading of graceful configuration reloads are somewhat problematic/challenging if people change routers or other port bindings, but I think this would be somewhat useful and it means those of us who manage our linkerd configuration with our configuration management and have one instance of linkerd per host don't temporarily lose an entire node when we need to deploy a new configuration update.

If others are looking for an interim solution, I'm probably going to "solve" this using [github/multibinder](https://github.com/github/multibinder) in the interim.

**Comment by esbie** [comment]
Tell me more about your use case! Our hope is that dynamic configuration happens by using namerd, in a manner similar to what's described here: https://blog.buoyant.io/2016/11/04/a-service-mesh-for-kubernetes-part-iv-continuous-deployment-via-traffic-shifting/

**Comment by chrisboulton** [comment]
Hey @esbie, yep - I agree with that WRT to namerd for dtabs etc. I was more thinking for the things that are less dynamic, such as the router definitions, telemetry settings, etc themselves.

**Comment by klingerf** [comment]
I think our overall approach to this will be to try to move more parts of the config to dynamic backing stores, rather than make the config itself reloadable. For instance routing policy can already be modified without restart by using namerd, and logging levels can be set via the admin logging page. I think we'll have a lot more of this type of configuration post-linkerd-1.0.0, and I'm going to close this in the meantime.

**Comment by olix0r** [comment]
to add some color here: lifecycle management, especially with regard to tearing things down, is quite difficult to get right. This isn't a "we'll never do this," though; probably just a "too complicated for the nearterm future."
