### ISSUE TITLE
Propagate client cert info to linkerd-fronted service

### ISSUE THREAD

**Issue by b-hoyt** [linkerd/linkerd#1153]
As a service behind a linkerd instance terminating TLS for me, I want information about the client certificate associated with the incoming request (maybe as a supplemental header?), so that I can make authorization decisions that aren't a good fit to be implemented in linkerd itself.

Pre-req is basic cert validation, which in turn has a dependency on [finagle bug fix RB_ID=910407](https://github.com/twitter/finagle/commit/08c2171dd2189c0bc3eddd5b7d8db67b03274fe5)

**Comment by rmichela** [comment]
Envoy has implemented this using the `forwarded-client-cert` header. It would be wonderful if linkerd also implemented this issue in the same way. Also see #1570. 

https://lyft.github.io/envoy/docs/configuration/http_conn_man/headers.html#x-forwarded-client-cert

**Comment by rmichela** [comment]
@cponomaryov What's the status of your `x-forwarded-client-cert` work?

**Comment by cponomaryov** [comment]
@rmichela Opened a PR #1656

**Comment by briansmith** [comment]
#1802 is related to this.
