### ISSUE TITLE
HTTP/2 stream memory leak

### ISSUE THREAD

**Issue by Oded-B** [linkerd/linkerd#1154]
With this config:
```
- kind: io.l5d.recentRequests
  sampleRate: 1.0
  capacity: 10
```

A linkerd instance @ 6 req/sec with 1G heap can have ~700mb allocated to a recentRequests related class:
![image](https://cloud.githubusercontent.com/assets/1616153/24257776/65b41bd8-0ff4-11e7-9a81-54e111d9c7e2.png)

**Comment by wmorgan** [comment]
Thanks @Oded-B ! Per Slack, we're looking into this.

**Comment by adleong** [comment]
I so far have not been able to reproduce this.  I'm able to do 25 req/s through a linkerd with the recent request telemeter and a sample rate of 1.0 with memory sitting steady at 93M.  

Is there anything unusual about your requests?  Could they be emitting extremely large trace annotations for some reason?

**Comment by Oded-B** [comment]
Hmm, not sure, the responses are relatively large, at about 1MB.
After the weekend I can try to see if I can send you a memory dump somehow.

**Comment by jeniag** [comment]
I did some digging into this and it doesn't seem to be telemetry related. Even with telemetry off, `Netty4ServerDispatcher` keeps a huge amount of streams open. 
It happens on linkerd 0.8.6 and 0.9.0. The client is java grpc and the server is c++ grpc (Tensorflow Serving).

![heap_dump](https://cloud.githubusercontent.com/assets/26772842/24465298/387ab79c-14b5-11e7-841c-c347bc80b0aa.png)

**Comment by jeniag** [comment]
This is a trace from the same machine @Oded-B used, but with tracing disabled. 
I can open a separate issue, but I added here because it might have been the underlying cause.

**Comment by adleong** [comment]
So far we haven't been able to reproduce this.  Any or all of the following would be helpful for us to dig in if you can provide it:

* Steps to reproduce
* Heap dump (when linkerd is in this state)
* linkerd config file
* dump of /admin/metrics.json (when linkerd is in this state)

**Comment by jeniag** [comment]
We managed to find a workaround for this issue, by recycling ManagedChannel objects on the java grpc client side. 
We could reliably reproduce this by running ~100 grpc requests per second reusing the same single ManagedChannel from a java process via localhost to linkerd running on the same host. The heap starts climbing immediately and continues at the same rate until linkerd crashes.

It seems like the grpc client opens new streams frequently and while I see end_stream messages sent from linkerd to the client, the stream objects remain in the hashmap the maps streamId to the streams.
(see Wireshark screen shots)
![increasing_stream_id_wireshark](https://cloud.githubusercontent.com/assets/26772842/24661433/0ad87d2e-195b-11e7-8850-da09f1f9e367.png)
![end_stream_wireshark](https://cloud.githubusercontent.com/assets/26772842/24661421/029e9a08-195b-11e7-89b7-0e892843ce8b.png)


All of the objects in the heap dump are reachable.
Unfortunately I can't provide a heap dump or the Wireshark recording - they contain actual traffic and therefore sensitive information.
Metrics and a config file are attached. They are not _exactly_ from the same time as the recording but its from a machine in a similar state.  However, the problem remains even if we change timeouts or provide different maxConcurrentRequests settings. 

[config.json.txt](https://github.com/linkerd/linkerd/files/893429/config.json.txt)
[metrics.json.txt](https://github.com/linkerd/linkerd/files/893430/metrics.json.txt)

**Comment by olix0r** [comment]
Thank you for the excellent, detailed bug report. I think this should give us enough to reproduce and investigate further.

**Comment by adleong** [comment]
Thanks for the great report!  I've been able to reproduce and I will update the ticket with my findings.

**Comment by zackangelo** [comment]
I also believe we're experiencing this issue. Our heap dump does not contain any sensitive information and would be happy to share it if it would help.

**Comment by klingerf** [comment]
Renamed this issue to "HTTP/2 stream memory leak", and we'll use it as a tracking ticket for fixing.
