### ISSUE TITLE
Reconcile HTTP/1.1 and HTTP/2 config kind ids

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#1176]
In working on our documentation, I've noticed some slight discrepancies in the kind ids for our http/1.1 and http/2 implementations, which I think we should fix as a breaking change.

In the linkerd/http project, we have:

File | ID
---- | --
HeaderIdentifierConfig.scala | `io.l5d.header`
HeaderTokenIdentifierConfig.scala | `io.l5d.header.token`
IngressIdentifier.scala | `io.l5d.http.ingress`
MethodAndHostIdentifierConfig.scala | `io.l5d.methodAndHost`
PathIdentifierConfig.scala | `io.l5d.path`
ResponseClassifiers.scala | `io.l5d.nonRetryable5XX`
ResponseClassifiers.scala | `io.l5d.retryableIdempotent5XX`
ResponseClassifiers.scala | `io.l5d.retryableRead5XX`

Whereas in the linkerd/h2 project, we have:

File | ID
---- | ---
HeaderPathIdentifier.scala | `io.l5d.headerPath`
HeaderTokenIdentifier.scala | `io.l5d.headerToken`
IngressIdentifier.scala | `io.l5d.h2.ingress`
ResponseClassifiers.scala | `io.l5d.h2.nonRetryable5XX`
ResponseClassifiers.scala | `io.l5d.h2.retryableIdempotent5XX`
ResponseClassifiers.scala | `io.l5d.h2.retryableRead5XX`

I'd like to suggest that we remove the protocol from these ids, and use the same id in both protocols for plugins that do roughly the same thing in each protocol. So this would mean:

* Rename `io.l5d.http.ingress` to `io.l5d.ingress`
* Rename `io.l5d.headerPath` to `io.l5d.path`
* Rename `io.l5d.headerToken` to `io.l5d.header`
* Rename `io.l5d.h2.ingress` to `io.l5d.ingress`
* Rename `io.l5d.h2.nonRetryable5XX` to `io.l5d.nonRetryable5XX`
* Rename `io.l5d.h2.retryableIdempotent5XX` to `io.l5d.retryableIdempotent5XX`
* Rename `io.l5d.h2.retryableRead5XX` to `io.l5d.retryableRead5XX`

Questions: Is this even possible? Do all plugins for a given initializer have to have a globally-unique identifier? Or can the IDs overlap as long as they're not part of the same protocol?

I'm also open to other suggestions too if we think there are better ways to go about.

**Comment by klingerf** [comment]
It also looks like `io.l5d.h2.nonRetryable5XX`, `io.l5d.h2.retryableIdempotent5XX` and `io.l5d.h2.retryableRead5XX` are not mentioned anywhere in our documentation. We should fix that as part of this change.

**Comment by klingerf** [comment]
Ok, I experimented with this a bit, and it looks like the ids must be globally unique for all instances of a given plugin. So we cannot have one response classifier id'd as `io.l5d.h2.nonRetryable5XX` for http, and a separate, h2 classifier with the same id.

Hence, I think we should change all of the h2 plugins to be scoped to `io.l5d.h2` (most already are). This would require:

* Renaming `io.l5d.headerPath` to `io.l5d.h2.path`
* Renaming `io.l5d.headerToken` to `io.l5d.h2.header.token`

Those identifiers feel more consistent (to me) to the HTTP/1.1 identifiers. We should also document all of the HTTP/2 response classifiers, which are currently not document. Happy to make this change if it works for other folks.

**Comment by adleong** [comment]
This sounds great!

**Comment by klingerf** [comment]
Ok, correction to my previous comment. It looks like response classifier IDs must be globally unique, but identifier IDs need only be unique per protocol. So we could have and `io.l5d.path` identifier for http, and a separate `io.l5d.path` identifier for h2. In that case... how do we feel about changing the h2 identifiers as follows:

* Rename `io.l5d.headerToken` to `io.l5d.header.token`
* Rename `io.l5d.headerPath` to `io.l5d.path`
* Rename `io.l5d.h2.ingress` to `io.l5d.ingress`

And for consistency I think we should also rename the http ingress identifier:

* Rename `io.l5d.http.ingress` to `io.l5d.ingress`

(sorry for all of the back-and-forth on this)

**Comment by olix0r** [comment]
I think we should rename the http identifers as well, then, to include `.http` ?

**Comment by esbie** [comment]
wfm, rename the ingress identifiers however you see fit
