### ISSUE TITLE
Leaking connection on 500 retrys

### ISSUE THREAD

**Issue by taer** [linkerd/linkerd#1178]
Posting this as a followup to a Slack conversation with Alex. This is against 0.9.0 of linkerd

We are noticing that linkerd's connection pool for certain endpoints grows rapidly during error conditions, then doesn't shrink. When the same app gets a burst of normal traffic, the pool shrinks back to 0 fairly quickly.

The timeline is:
* Request comes in. We send that request to linkerd.
* Linkerd returns an error to us after 20 seconds(our request timeout)
* Connection pool has ~83 idle connections that do not disappear
* metrics.json showed 83 500 status errors and 83 ResponseClassificationSyntheticException
* a `netstat -atpn | grep <L5d.pid> | grep CLOSE_WAIT` shows 83 sockets in CLOSE_WAIT
* It happened on Friday, and the connections are still there the following Monday

The service recovered, and is still working now. The connection pool number is correct, linkerd is holding onto CLOSE_WAIT sockets. This will eventually become an issue requiring a restart.

This happened 2 times, so the numbers in the attached metrics.json are a bit different. This also occurred on 3 separate linkerd instances at about the same time. The cause was the way the downstream app responded, but it affected 3 independent linkerds. Alex identified this in slack:
> I think you got stuck in a retry loop.  `"rt/cgp/dst/path/svc/live/appName/retries/total": 274,`  something about that one request triggered a 5xx response from the server and it kept being retried and failing until either the retry budget was exhausted or the request timed out
> it looks like there were 99 requests, 97 of which were successful, and 2 of which were failures and those failures triggered 274 retries

We have retryableRead500 tuned on, which is likely the reason for the large number of connections. This is a server in our staging environment, so it gets very little traffic. In the case of the error, a single request came in that caused 83 abandoned connections.

[metrics.json](https://github.com/linkerd/linkerd/files/893581/metrics.txt)
Compare number of connections in metrics with CLOSE_WAIT
```
root@ip-10-122-17-136:~# netstat -atpn | grep 3887 |grep CLOSE_WAIT |wc
    166    1162   16102
```
Showing all CLOSE_WAIT are to the server that errored out.
```
root@ip-10-122-17-136:~# netstat -atpn | grep 3887 |grep CLOSE_WAIT | grep 10.122.3.77:31392|wc
    166    1162   16102
```

And this server is still serving traffic on that ip:port. We just had some sort of disruption for this brief window.

I have the metrics being captured by datadog, so we have how the metrics changed on a 30 second window.
This shows the connection count
![connections](https://cloud.githubusercontent.com/assets/458866/24664304/ec543702-191f-11e7-9619-52947e9a7bd6.png)
This shows the count of 500 errors
![500statuscounter](https://cloud.githubusercontent.com/assets/458866/24664343/06d4148a-1920-11e7-8194-064e68bb22a8.png)
And this is the bytes_sent stat for the application
![bytespersec](https://cloud.githubusercontent.com/assets/458866/24664371/1bd1434e-1920-11e7-8c58-e6665f01097b.png)
 

# Debugging attempts
We attempted to see if using the connections would result in them being cleaned up. I flooded a server that had 159 connections and 159 sockets in CLOSE_WAIT. The pool grew to 360+, then returned back to 159

# Dead sockets
This is a sample of netstat showing the dead sockets that match the leaked connection counts
```
tcp        1      0 10.122.8.59:56734       10.122.3.77:31392       CLOSE_WAIT  4228/java       
tcp        1      0 10.122.8.59:35906       10.122.3.77:31392       CLOSE_WAIT  4228/java 
```

# Linkerd log
```2017/03/31 18:17:11 I 0331 18:17:11.572 UTC THREAD25 TraceId:4f2d95dc50b33383: FailureAccrualFactory marking connection to "#/consul/us-east-1-vpc-XXXX/live/appName" as dead
. Remote Address: Inet(/10.122.3.77:31392,Map())
2017/03/31 18:17:16 I 0331 18:17:16.862 UTC THREAD24 TraceId:4f2d95dc50b33383: FailureAccrualFactory marking connection to "#/consul/us-east-1-vpc-XXXX/live/appName" as dead
. Remote Address: Inet(/10.122.3.77:31392,Map())
2017/03/31 18:17:26 I 0331 18:17:26.970 UTC THREAD23 TraceId:4f2d95dc50b33383: FailureAccrualFactory marking connection to "#/consul/us-east-1-vpc-XXXX/live/appName" as dead
. Remote Address: Inet(/10.122.3.77:31392,Map())
2017/03/31 18:17:30 E 0331 18:17:30.874 UTC THREAD10: service failure
2017/03/31 18:17:30 com.twitter.finagle.IndividualRequestTimeoutException: exceeded 20.seconds to 0.0.0.0/4140 while waiting for a response for an individual request, excluding retries. Remo
te Info: Not Available
2017/03/31 18:17:30
2017/03/31 18:17:31 E 0331 18:17:31.060 UTC THREAD24 TraceId:4f2d95dc50b33383: service failure
2017/03/31 18:17:31 Failure(20.seconds, flags=0x03) with RemoteInfo -> Upstream Address: /127.0.0.1:54910, Upstream Client Id: Not Available, Downstream Address: /10.122.3.77:31392, Downstream Client Id: #/consul/us-east-1-vpc-XXXX/live/appName, Trace Id: 4f2d95dc50b33383.4f2d95dc50b33383<:4f2d95dc50b33383
2017/03/31 18:17:31 Caused by: com.twitter.util.TimeoutException: 20.seconds
2017/03/31 18:17:31     at com.twitter.util.Future$$anonfun$within$1.apply(Future.scala:992)
```

# Config file
```
admin:
  port: 9990
routers:
- protocol: http
  httpAccessLog: /opt/proxy/logs/access.log
  label: cgp
  timeoutMs: 2000
  identifier:
  - kind: io.l5d.header
    header: X-Route-Id
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd/4100
    namespace: header
  responseClassifier:
    kind: io.l5d.retryableRead5XX
  client:
    loadBalancer:
      kind: ewma
    failureAccrual:
      kind: io.l5d.successRate
      successRate: 0.9
      requests: 20
      backoff:
        kind: constant
        ms: 10000
  servers:
  - port: 4140
    ip: 0.0.0.0
```

**Comment by wmorgan** [comment]
Thanks for the very detailed report, @taer!

**Comment by taer** [comment]
Attaching the whole metrics.json. I sanitized it. The app with a problem is named 
rt/cgp/dst/id/#/consul/us-east-1-vpc-XXXX/live/appWithProblem

[metrics.txt](https://github.com/linkerd/linkerd/files/894650/metrics.txt)
```
root@ip-10-122-17-136:~# netstat -atpn | grep 3887|grep CLOSE_WAIT|wc
    166    1162   16102
```

**Comment by fantayeneh** [comment]
On this same issue we realized that `chunked` error responses are responsible in the first place for
the unusual high number of connection created.

```
test("chunked error responses should not create new connection for each retries") {
    val stats = new InMemoryStatsReceiver
    val tracer = NullTracer

    val downstream = Downstream.mk("dog") { _ =>
        val rsp = Response()
        rsp.status = Status.InternalServerError
        rsp.setChunked(true)
        rsp.close()
        rsp
    }

    val label = s"$$/inet/127.1/${downstream.port}"
    val dtab = Dtab.read(s"/svc/dog => /$label;")
    val yaml =
      s"""|routers:
          |- protocol: http
          |  dtab: ${dtab.show}
          |  responseClassifier:
          |    kind: io.l5d.retryableRead5XX
          |  servers:
          |  - port: 0
          |""".stripMargin
    val linker = Linker.load(yaml)
      .configured(param.Stats(stats))
      .configured(param.Tracer(tracer))
    val router = linker.routers.head.initialize()
    val server = router.servers.head.serve()
    val client = upstream(server)

    try {

      val req = Request()
      req.host = "dog"
      val errrsp = await(client(req))
      assert(errrsp.status == Status.InternalServerError)
      assert(stats.counters.get(Seq("http", "srv", "127.0.0.1/0", "requests")) == Some(1))
      assert(stats.counters.get(Seq("http", "dst", "id", label, "requests")) == Some(101))
      assert(stats.counters.get(Seq("http", "dst", "id", label, "connects")) == Some(1), "expecting only one connects to downstream server")


    } finally {
      await(client.close())
      await(downstream.server.close())
      await(server.close())
      await(router.close())
    }

  }
```
This fails 
```
Expected :Some(1) expecting only one connects to downstream server
Actual   :Some(101)
```

The same test passes if we return the following response
```
 val downstream = Downstream.mk("dog") { _ =>
        val rsp = Response()
        rsp.status = Status.InternalServerError
        rsp
    }

```
We will continue investigating this but any input on why this is happening is greatly appreciated

**Comment by olix0r** [comment]
thanks @fantayeneh! this is helpful

**Comment by taer** [comment]
Managed to get a node.js driver to reproduce this.
```
const http = require('http')
const port = 3000

const requestHandler = (request, response) => {
  console.log(Date.now())
  response.writeHead(500, {'Content-Type': 'text/plain'})
  response.write("Help Me")
  response.end()
}

const server = http.createServer(requestHandler)

server.listen(port, (err) => {
  if (err) {
    return console.log('something bad happened', err)
  }

  console.log(`server is listening on ${port}`)
})
```

If you hit this service via linkerd with the 
```
responseClassifier:
    kind: io.l5d.retryableRead5XX
``` 
enabled, you'll get 20 seconds of retry as expected, but then you'll have about 100 connections orphaned. Eventually, the node server gives up and closes the socket. But linkerd never finishes it's read, and the sockets will go into CLOSE_WAIT as above.

If we remove the `retryableRead5XX` and hit linkerd via a loop
```for i in `seq 1 100` ; do curl   localhost:4140/hello & done```
You'll get < 100 connections, but they are drained properly.

**Comment by wmorgan** [comment]
Thanks for the repro, @taer! That is super helpful.

**Comment by adleong** [comment]
After some investigation, this appears to be related to retries when the responses are chunk encoded.  My current theory is that when a chunk encoded response is retried, linkerd never actually reads the chunks of the discarded response and since the response has unread chunks, the connection is never released.

I will attempt to test this theory and put together a fix.  I'll update this issue as I know more.

**Comment by leozc** [comment]
Not claim to be 100% related to this issue

```root@ip-172-16-22-62:/home/ubuntu# lsof -p 2414 | grep CLOSE_W | sed -e 's/.*>//' | sort | uniq -c
142 ip-172-16-31-45.ec2.internal:http (CLOSE_WAIT)
997 ip-172-16-31-70.ec2.internal:http (CLOSE_WAIT)
1 ip-172-16-31-75.ec2.internal:http (CLOSE_WAIT)
190 ip-172-16-32-14.ec2.internal:http (CLOSE_WAIT)
523 ip-172-16-32-21.ec2.internal:http (CLOSE_WAIT)
48 ip-172-16-33-91.ec2.internal:http (CLOSE_WAIT)
the IPs that have the high number of CLOSE_WAITs are service ELBs (172.16.3*, i.e. prod-xxxx.foobar.net). i could not find these IPs in any of the obvious ELBs.
Here it is run on a current routing instance:
root@ip-172-16-22-228:/home/ubuntu# lsof -p 2438 | grep CLOSE_W | sed -e 's/.*>//' | sort | uniq -c
27 ip-172-16-32-83.ec2.internal:http (CLOSE_WAIT)
27 ip-172-16-33-95.ec2.internal:http (CLOSE_WAIT)
```

essentially we see large number of CLOSE_WAIT (which is fine , finagle behavior) and some CLOSE_WAIT to dead ELB.

Any concern  - and will these CLOSE_WAIT connection being reclaim ?

**Comment by adleong** [comment]
I've posted what I believe is a fix at https://github.com/linkerd/linkerd/pull/1256

@taer @fantayeneh @leozc I would love your help testing this fix a verifying if it solves the issue for you.  Let me know if you'd like me to build a binary or docker image for you.

@fantayeneh I wasn't able to reproduce this with non-chunked responses.  Do you have a sample implementation of a server that causes this?

**Comment by fantayeneh** [comment]
@adleong Here it is
```
    val downstream = Downstream.mk("dog") { _ =>
      val rsp = Response()
      rsp.status = Status.InternalServerError
      val body = (1 to 1000).map(_ => "Hello Linkerd").mkString("\n")
      rsp.setContentString(body)
      rsp.close()
      rsp
    }
```

**Comment by adleong** [comment]
@fantayeneh thanks!  I've verified that my fix works on that service.  Apparently linkerd will automatically chunk messages and that is what's happening here (this was a surprise to me!)

**Comment by adleong** [comment]
I've closed this as I believe that https://github.com/linkerd/linkerd/issues/1256 fixes the issue.  Please reopen this if you see this behavior again.
