### ISSUE TITLE
Dark Traffic Use Case

### ISSUE THREAD

**Issue by Disturbing** [linkerd/linkerd#1186]
Hey There!

First time submitting something here and spoke to peeps in the Slack channel was pointed to bring the conversation here.

The goal with Linkerd + Kubernetes + gRPC that I have in mind is called *Dark Traffic* after speaking to @olix0r 

**The example use case I would like to build on Linkerd is the following:**

1. Create two microservices with gRPC.
1a. Microservice A has Login, Register and Forgot Password API definitions.
1b. Microservice B _extends_ MicroserviceA's API and has LoginWithFB as a definition.
1c. Say we want to 'combine' these two microservices in a single microservice called 'coopscode'

2.  When gRPC connects to coopscode, Linkerd should automatically authenticate for both MicroserviceA + MicroserviceB under the hood for the respective clients so future proxy forwarding can occur.

3. Linkerd handles a single gRPC session/connection and provides a controller functionality to proxy Method Level requests to the desired Microservice under the hood.
3a. /microservice/Login => MicroserviceA/Login 
3b. /microservice/LoginWithFB => MicroserviceB/Login

**Why is this cool? What is the goal?**

1. Be able to code a single microservice with multiple languages
2. Mix-in serverless and Lamda functions to build microservices.
3. Most apps need small tweaks when you add another app to use the same microservice.  Making a microservice flexible enough for this usually is tough and the world ends up copy/pasting a microservice to get the functionality needed

**Comment by klingerf** [comment]
Hey @Disturbing, thanks for the detailed write up! If I understand correctly, you want gRPC clients to connect to Linkerd, and Linkerd to route some endpoints to MicroserviceA, and other endpoints to MicroserviceB. This should already be possible using Linkerd's Dtab functionality. You would just need the client to use a combined service definition, and then break out the endpoints in your Dtab. Something like:

```
/svc/combinedapp/Login => /srv/serviceA/Login
/svc/combinedapp/LoginWithFB => /srv/serviceB/LoginWithFB
```

**Comment by Disturbing** [comment]
Awesome.

I will test this out and let you know if it works. Didn't know auth session
handling worked across two separate grpc instances yet. Was thinking
Linkerd had to broadcast the auth to both services so that it works
flawlessly since essentially multiple http2 connections and grpc sessions
are under the hood.

Will give it a run and report the results in the next week.

**Comment by adleong** [comment]
Hi @Disturbing.  I don't think this is actually related to dark traffic.  I'm going to close this issue for now but please feel free to open a new one if @klingerf's suggestion doesn't work for you.
