### ISSUE TITLE
X-Forwarded-Host - support for including

### ISSUE THREAD

**Issue by ewilde** [linkerd/linkerd#1189]
## Summary
Add support for `X-Forwarded-Host` header

## Context
In some circumstances it is useful for upstream services to know the original host. For example imagine an api that returns the following json:

```json
{
  "type": "articles",
  "id": "1",
  "attributes": {
    "title": "Rails is Omakase"
  },
  "relationships": {
    "author": {
      "links": {
        "self": "http://example.com/articles/1/relationships/author",
        "related": "http://example.com/articles/1/author"
      },
      "data": { "type": "people", "id": "9" }
    }
  },
  "links": {
    "self": "http://example.com/articles/1"
  }
}
```

Without access to  a `X-Forwarded-Host` header the application would need to store the value `http://example.com`. This leads to extra unnecessary configuration

Further reading and context:

- [X-Forwarded-Host on Mozilla developer network](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host)

## Possible Implementation
Looking at the documenation it seems like we could add a new kind `host` to the existing [Forwarded Header](https://linkerd.io/config/0.9.1/linkerd/index.html#http-servers).

### Adding the Forwarded header

|Key| Default Value|	Description|
|-----|------------------|------|
|by	|{kind: requestRandom}|	The labeler to use with the router’s server address|
|for	|{kind: requestRandom} |	The labeler to use with the upstream client’s address|
|host	|{kind: requestRandom} |	The labeler to use with the host header, either `host` or `connectionRandom` |

 Additionaly a new labeler kind `host` could be added to write the host unobfuscated.

**Comment by adleong** [comment]
Linkerd already adds a `host` key to the `Forwarded` header.  Does that satisfy your use case?

**Comment by Ashald** [comment]
We have a very similar situation where we need to let the backend application know what host was used by the original user. It can be injected by the web-servers such as Apache/Nginx if there is one but when there are no web-server in front this becomes problematic.

As [Wikipedia says](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields), this is
> a de facto standard for identifying the original host requested by the client in the Host HTTP request header, since the host name and/or port of the reverse proxy (load balancer) may differ from the origin server handling the request.

and to the best of my knowledge there are tons of applications out there that rely on it.

**Comment by Ashald** [comment]
@adleong I didn't see `labelers` docs before so reading through right now but is it possible to have `host` key one very request set to the actual value?

Also, one of the problems is that, as I mentioned before, there are tons of applications that rely on `X-Forwarded-Host` so in terms of backward compatibility it'd be great if it was possible to inject it as well.

**Comment by olix0r** [comment]
For more context on why we use `Forwarded` and not `X-Forwarded-For` see [RFC 7239](https://tools.ietf.org/html/rfc7239).  Basically, X-Forwarded-* is ambiguous in many scenarios, and this RFC lays out a standard that avoids these ambiguities.

**Comment by ewilde** [comment]
@adleong thanks for that I wasn't aware of the `host` key. For reference if you configure the `addForwardedHeader` i.e.:

```yaml
  servers:
  - port: 4140
    addForwardedHeader:
      by: {kind: "ip:port"}
      for: {kind: ip}
```

You will get the following `Forwarded` headers added, example value:

`Forwarded: by="172.16.238.9:4140";for=172.16.238.254;host=linkerd:4140`

I couldn't see the `host` key mentioned in the docs, should I update the docs?

**Comment by ewilde** [comment]
I've also observed that if the `X-Forwarded-Host` is already set, linkerd forwards it on. Which in my particular case solves my scenario. I have [kong api gateway](https://getkong.org/) infront of linkerd and have used the request transformer to add the `X-Forwarded-Host` header

**Comment by klingerf** [comment]
@ewilde It sounds like you're able to work around this. We'll also update the docs to include a description of the `host` key, but in the meantime I'll close this issue. Feel free to reopen though if need be.

**Comment by Ashald** [comment]
I'm wondering whether it's theoretically possible to extended labelers functionality in a way that it will allow setting any sorts of headers on demand...

**Comment by conanconstantine** [comment]
hey guys, do you know how to change the links in the payload (JSON API) based on the X-Forwarded-Host?
