### ISSUE TITLE
New interpreter that reads dtab from a k8s configmap

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#1198]
Let's add another interpreter, similar to the [file-system interpreter](https://linkerd.io/config/head/linkerd/index.html#file-system), that reads dtab from a Kubernetes ConfigMap. We should be able to setup a watch on the API object in order to pick up any changes.

**Comment by klingerf** [comment]
I had started on this change awhile ago but didn't finish. You can see my branch here:

https://github.com/linkerd/linkerd/compare/kl/configmap-interpreter

I wanted to go back and refactor the changes in k8s/resources.scala, since I felt like my implementation was really messy. Let me know if you have any questions about it.

**Comment by hawkw** [comment]
Great, thanks @klingerf! I'll let you know if I have any trouble.

**Comment by hawkw** [comment]
Implemented in #1603! 🎉
