### ISSUE TITLE
investigate flakey FsTest

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd#1203]
from https://circleci.com/gh/linkerd/linkerd/4437:
```
./sbt test

...

[info] FsTest:
[info] - sanity
[info] - service registration
[info] - parse config
[info] - id is bound name
[info] - supports weights *** FAILED ***
[info]   unexpected addr: Pending (FsTest.scala:99)
```

**Comment by olix0r** [comment]
This isn't strictly a unit test, because it's testing that the file system watcher works.  I assume this is a timing issue, where we the fs watcher doesn't observe any updates in time for the test.

I took off the _bug_ label and created a new _flakey_ label.

**Comment by adleong** [comment]
I think this was fixed in https://github.com/linkerd/linkerd/pull/1238

Please reopen if you see it again.
