### ISSUE TITLE
Add tests for the admin javascript

### ISSUE THREAD

**Issue by gtcampbell** [linkerd/linkerd#121]
To prevent issues like #119, it would be good if we had some level of automated testing for our admin UI. I think unit tests would be sufficient here (rather than something like Webdriver).

**Comment by esbie** [comment]
I'm fine adding tests, just a note thought that #119 could be a browser-compat issue, which would not necessarily be caught by unit tests

**Comment by esbie** [comment]
sbt plugin option: https://github.com/sbt/sbt-mocha

**Comment by olix0r** [comment]
We added eslint to CI, but we still probably want better unit testing

**Comment by siggy** [comment]
Fixed in https://github.com/linkerd/linkerd/pull/873
