### ISSUE TITLE
Improved propagation for retries of upstream connectivity errors in a linker-to-linker setup

### ISSUE THREAD

**Issue by chrisboulton** [linkerd/linkerd#1210]
This is something that came up in Slack here and I just wanted to capture it so it doesn't get lost: https://linkerd.slack.com/archives/C0JV5E7BR/p1491836572164525

Essentially, consider a linkerd setup & request as follows: `node A: [service A -> linkerd A] -> node B: [linkerd B -> service B]`

Typically, in this setup you would have a port transformer on `linkerd A` to ensure traffic is sent to `linkerd B` when we want to talk to `service B`. On `linkerd B`, we'd have a localhost transformer that for the resolved request the list of instances of `service B` is filtered down to the one that exists on `node B`.

If `service B` goes away in the time between `linkerd A` has decided to route the request to `linkerd B`, and the request never even touches `service B`, a HTTP 5xx will be returned.

If you have a very liberal retry policy (and an app that supports idempotent PUT/POST requests), you'll likely be fine: `linkerd A` will re-resolve the request and try again. Most of us can't do that, however. If  you don't retry requests, the failure will propagate all the way through to `service A`, even though it should always be safe for `linkerd A` to try again, because the request never made it through to `service B`.

The proposal here is to implement a mechanism for an upstream linkerd to notify those downstream that a request can safely be retried under these circumstances (via a HTTP header for the HTTP routers, for example)

Hopefully the above makes some sense.

**Comment by olix0r** [comment]
Good timing! Alex [just posted a review](https://github.com/linkerd/linkerd/pull/1185) which introduces the _l5d-success-class_ response header.

**Comment by adleong** [comment]
There are no such things as coincidences 😉 
Right now my review just sets l5d-success-class to a number indicating success, partial success, or failure.  We should make that richer or add another header to indicate retryability.

**Comment by rnorth** [comment]
We encountered the same issue and were actually wondering about suggesting an alternative solution. Our use case is actually two-fold:

* As above, when service B fails (or starts to shutdown) before our namer is updated, we DO want linkerd A to attempt a retry when linkerd B indicates a failure. It seems that linkerd B returns a 503 status code when it's failed to establish a connection to the service.
* Secondly, we also want to implement back pressure via service instances returning 429 status codes when overloaded. Similarly, if service B returns a 429 response, we want linkerd _A_ to attempt a retry against another linkerd-service pair.

So our current approach is to create an alternative response classifier for linkerd Abased on `io.l5d.retryableRead5XX`. The difference is that a 503 response and a 429 response will always be regarded as retryable regardless of method. This seems to be working pretty nicely in our test environment so far - we were actually wondering about contributing this back!

I can see how `l5d-success-class` could help us with the first scenario but probably wouldn't help with the second. What do you think?

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd/pull/1229

**Comment by adleong** [comment]
@rnorth: A response classifier that always treats 503s and 429s as retryable sounds like a good idea and it sounds like it solves issue 2 quite nicely.  We'd love if you wanted to contribute that back!
