### ISSUE TITLE
Port namerd's thrift interface to netty4

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#1240]
As part of #1239, we realized that namerd's `io.l5d.thriftNameInterpreter` interface still uses netty3, which requires openssl for serving the interface with tls. We should move that interface to netty4, and then switch namerd's base docker image to match linkerd's base docker image (library/openjdk:8-jre-alpine), which does not include openssl.

**Comment by adleong** [comment]
Unfortunately, moving to netty4 while still supporting pkcs#1 keys means that we need to use the LegacyKeyServerEngineFactory which depends on openssl.  We can't switch docker images until we drop support for pkcs#1.

**Comment by siggy** [comment]
Related: #1366.
