### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by rothgar** [linkerd/linkerd#1243]
The 2nd command in the getting started on Kubernetes makes two assumptions that can cause problems (they did for me)
Specifically looking at this command
```
open http://$(kubectl get svc l5d -o jsonpath="{.status.loadBalancer.ingress[0].*}"):9990
```
found [here](https://linkerd.io/getting-started/k8s-daemonset/)

1. `open` is not a command that exists anywhere except on macOS. It doesn't work in Windows or Linux.
2. The daemonset that was deployed sets up the l5d service as a loadbalancer which assumes the user has a cloud provider set and a load balancer available. In my case (bare metal) I have no load balancer.

One possible solution is to have people use the [helm chart available](https://github.com/kubernetes/charts/tree/master/stable/linkerd) so they can configure the service type or you can tell people to manually download the manifest and edit it as needed.

**Comment by wmorgan** [comment]
Thanks for pointing this out, @rothgar!

**Comment by siggy** [comment]
We've pushed a fix to our private docs repo. Expect to see the change on the docs site shortly.
