### ISSUE TITLE
Need config file for linkerd-1.0.0 (k8s daemonset)

### ISSUE THREAD

**Issue by zillani** [linkerd/linkerd#1247]
As the many field names have been changed, need a config file for the new release 1.0.0 as the documentation still points to 0.9.1 config for k8s daemonset.
https://raw.githubusercontent.com/linkerd/linkerd-examples/master/k8s-daemonset/k8s/linkerd.yml

**Comment by klingerf** [comment]
Hey @zillani, thanks for reporting this. I just merged linkerd/linkerd-examples#122, which ports all of the example configs to 1.0.0. Have another look and let us know if you run into any issues.

**Comment by zillani** [comment]
Awesome! thanks @klingerf
