### ISSUE TITLE
Throughput limitation

### ISSUE THREAD

**Issue by danielBreitlauch** [linkerd/linkerd#1251]
Linkerd seams to have a inherent throughput limitation.
There are 3 machines involved. One machine with Linkerd installed and two other machines with the target service.
When I am calling just one target service instance directly w/o Linkerd, I get 60k requests/s.
On the other hand calls through a local Linkerd to both instances yield just 26k requests/s.
I can disable one of the service machines such that Linkerd is only going to one target machine and this is not changing any throughput.
Another test contained running 2 Linkerd instances locally. Both instances did the same as before and got both 22k req/s (so total from this machine 44k req/s).

So Linkerd is not saturating the target service nor the network nor the the local host resources.
Why does it not get more throughput?
Do you know of this limitation; did anybody see something similar?

**Comment by wmorgan** [comment]
Hi @danielBreitlauch. There are many reasons this might happen. We'll need many more details to be helpful.

How are you running Linkerd? In a Docker container, or as a JVM process? What are the nature of these requests? HTTP, Thrift, something else? Are they concurrent? If they're HTTP, are you doing keepalives or restarting the connection every time? Are they big requests? Small? Chunked? Are you using TLS? What's the CPU usage and memory footprint of Linkerd at this point?

We've been able to get a single instance to ~40k HTTP RPS under ideal conditions.

You might find this doc useful: https://github.com/linkerd/linkerd/wiki/Debugging-network-performance

**Comment by danielBreitlauch** [comment]
It is running as a jvm process.
The requests are http get requests generated with wrt. The connection is kept alive. Tls is off. And the server responds with a simple 200 no data.

Machine resource wise:
The CPU was under medium load and the jvm footprint was minimal ~100mb. The resources were certainly enough to run a second linkerd instance and get nearly the same throughout in addition to the first instance.

**Comment by stevej** [comment]
For your different test scenarios, are they all going through the networking stack? It sounds like they are but I want to make sure localhost isn't a factor.

TBH, I haven't seen a 26k RPS throughput limitation with linkerd, I routinely test near gigabit ethernet's limits.

Would you mind sharing with us your metrics during one of your test runs? You can find it in the linkerd admin instance under `/admin/metrics.json` You should be able to attach it to a comment on this github issue.

Also, it would be helpful to know which version of linkerd you're using, which JVM you're using. (the easiest way is probably with `ps auxwww |grep linkerd`), and your config file.

Thanks!

**Comment by stevej** [comment]
Also, how much CPU use did you see at 26k RPS?

**Comment by danielBreitlauch** [comment]
Linkerd version: 0.9.1
jvm: HotSpot 1.8.0_111
The CPU usage was 50% equally over 32 cores. Soft irqs where a bit higher but not too much.
The traffic definitely goes to another host through a gigabit network.

Concerning the metrics. I did the test already a while ago. I will atach them as soon as I do the test again.

**Comment by stevej** [comment]
I spent some time this morning running load tests on the last 9 months of linkerd releases (at 10k qps) and there's definitely been a mild performance regression. I'm going to test at 40k again and try and replicate this 26k qps bottleneck.
![A CDF plot of linkerd latency 0.7.5 vs 1.0.0](https://cloud.githubusercontent.com/assets/5834/25916398/50a5d11e-3579-11e7-9b75-79bf4d635e6a.png)

**Comment by stevej** [comment]
Here are some representative `slow_cooker` log lines from my testing

```
0.7.5 2017-05-10T18:18:55Z  99065/0/0 100000  99% 10s   0 [ 11  19  36   73 ]   73
0.8.0 2017-05-10T17:27:10Z  97720/0/0 100000  97% 10s   0 [ 12  30  45   97 ]   97
0.8.2 2017-05-10T18:09:01Z  96489/0/0 100000  96% 10s   0 [ 13  33  51  233 ]  233
0.8.6 2017-05-10T17:45:39Z  98578/0/0 100000  98% 10s   0 [ 12  25  42  232 ]  232
0.9.1 2017-05-10T17:59:17Z  88270/0/0 100000  88% 10s   0 [ 15  45  65  248 ]  248
1.0.0 2017-05-10T18:38:10Z  84635/0/0 100000  84% 10s   0 [ 16  51  70  129 ]  129
```

**Comment by stevej** [comment]
I did some digging into whether there is a throughput limitation: with linkerd 1.0, I was able to sustain 65k qps with a few caveats: linkerd needed 22 cores and I had to use 1000 connections from my load testing tool. (I'll note that the Google Cloud network offers a lot of bandwidth on a large core VM so I didn't need to configure any fancy bonding to go over 1Gbps)

So our verdict is: there isn't strictly a throughput limitation but there is a performance regression that's making high qps harder to achieve without more cores and sockets.

**Comment by stevej** [comment]
Thanks to this ticket, we're going to prioritize tracking down the source of the regression, we should have an update in a few weeks. Thank you!

**Comment by adleong** [comment]
We're continuing to investigate this.  We believe #1381 is related.
