### ISSUE TITLE
grpc-go helloworld app causes the h2 dispatcher to fail

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#1289]
I've been testing linkerd's gRPC support with v1.3.0 of both of the official [grpc-go](https://github.com/grpc/grpc-go/tree/master/examples) and the [grpc-java](https://github.com/grpc/grpc-java/tree/master/examples) example apps. Both apps successfully return a response, but the go app causes linkerd to log a "dispatcher failed" error. The same dispatch error does not show up when using the java app.

I'm using the following linkerd config:

```yaml
routers:
- protocol: h2
  experimental: true
  dtab: |
    /svc/* => /$/inet/localhost/50051;
  servers:
  - port: 4140
```

That forwards all traffic from 4140 to 50051, where the example servers are running.

I then followed the instructions in both projects to run the example server, and modified the example client to call port 4140, instead of 50051. Running the go client successfully returns a response, but in linkerd's logs, I see:

```
E 0510 00:19:07.027 UTC THREAD144: [S L:/127.0.0.1:4140 R:/127.0.0.1:63351] dispatcher failed
com.twitter.finagle.ChannelClosedException: ChannelException at remote address: /127.0.0.1:63351. Remote Info: Not Available
	at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelInactive(ChannelTransport.scala:186)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at com.twitter.finagle.netty4.channel.ChannelRequestStatsHandler.channelInactive(ChannelRequestStatsHandler.scala:36)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:390)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at com.twitter.finagle.netty4.channel.ChannelStatsHandler.channelInactive(ChannelStatsHandler.scala:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
	at java.lang.Thread.run(Thread.java:745)
```

The same error does not appear when using the java client, which also returns successfully.

**Comment by klingerf** [comment]
Just adding a bit more info. Looking at the inbound/outbound frames for each request, the grpc-java client and the grpc-go client are almost identical, except that the java client also sends:

```
TRACE 0509 18:32:08.889 PDT finagle/netty4-1:
----------------INBOUND--------------------
[id: 0x82ec2c7f, L:/127.0.0.1:4140 - R:/127.0.0.1:64590] GO_AWAY: lastStreamId=0, errorCode=0, length=0, bytes=
------------------------------------
TRACE 0509 18:32:08.896 PDT finagle/netty4-1:
----------------OUTBOUND--------------------
[id: 0x82ec2c7f, L:/127.0.0.1:4140 - R:/127.0.0.1:64590] GO_AWAY: lastStreamId=3, errorCode=0, length=0, bytes=
------------------------------------
```

And the go client does not. Here are the full frame dumps:

<details>
  <summary>grpc-go client frames</summary>
  <pre><code>
  TRACE 0509 18:25:09.363 PDT finagle/netty4-1:
  ----------------OUTBOUND--------------------
  [id: 0x16d309ca, L:/127.0.0.1:4140 - R:/127.0.0.1:64529] SETTINGS: ack=false, settings={}
  ------------------------------------
  TRACE 0509 18:25:09.375 PDT finagle/netty4-1:
  ----------------INBOUND--------------------
  [id: 0x16d309ca, L:/127.0.0.1:4140 - R:/127.0.0.1:64529] SETTINGS: ack=false, settings={}
  ------------------------------------
  TRACE 0509 18:25:09.377 PDT finagle/netty4-1:
  ----------------OUTBOUND--------------------
  [id: 0x16d309ca, L:/127.0.0.1:4140 - R:/127.0.0.1:64529] SETTINGS: ack=true
  ------------------------------------
  TRACE 0509 18:25:09.378 PDT finagle/netty4-1:
  ----------------INBOUND--------------------
  [id: 0x16d309ca, L:/127.0.0.1:4140 - R:/127.0.0.1:64529] WINDOW_UPDATE: streamId=0, windowSizeIncrement=983025
  ------------------------------------
  TRACE 0509 18:25:09.385 PDT finagle/netty4-1:
  ----------------INBOUND--------------------
  [id: 0x16d309ca, L:/127.0.0.1:4140 - R:/127.0.0.1:64529] HEADERS: streamId=1, headers=DefaultHttp2Headers[:method: POST, :scheme: http, :path: /helloworld.Greeter/SayHello, :authority: localhost:4140, content-type: application/grpc, user-agent: grpc-go/1.3.0, te: trailers], padding=0, endStream=false
  ------------------------------------
  TRACE 0509 18:25:09.661 PDT finagle/netty4-1:
  ----------------INBOUND--------------------
  [id: 0x16d309ca, L:/127.0.0.1:4140 - R:/127.0.0.1:64529] DATA: streamId=1, padding=0, endStream=true, length=12, bytes=00000000070a05776f726c64
  ------------------------------------
  TRACE 0509 18:25:09.681 PDT finagle/netty4-1:
  ----------------INBOUND--------------------
  [id: 0x16d309ca, L:/127.0.0.1:4140 - R:/127.0.0.1:64529] SETTINGS: ack=true
  ------------------------------------
  TRACE 0509 18:25:09.741 PDT finagle/netty4-1:
  ----------------OUTBOUND--------------------
  [id: 0x16d309ca, L:/127.0.0.1:4140 - R:/127.0.0.1:64529] HEADERS: streamId=1, headers=DefaultHttp2Headers[:status: 200, content-type: application/grpc, l5d-success-class: 1.0, via: h2 linkerd], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
  ------------------------------------
  TRACE 0509 18:25:09.743 PDT finagle/netty4-1:
  ----------------OUTBOUND--------------------
  [id: 0x16d309ca, L:/127.0.0.1:4140 - R:/127.0.0.1:64529] DATA: streamId=1, padding=0, endStream=false, length=18, bytes=000000000d0a0b48656c6c6f20776f726c64
  ------------------------------------
  TRACE 0509 18:25:09.748 PDT finagle/netty4-1:
  ----------------OUTBOUND--------------------
  [id: 0x16d309ca, L:/127.0.0.1:4140 - R:/127.0.0.1:64529] HEADERS: streamId=1, headers=DefaultHttp2Headers[grpc-status: 0, grpc-message: ], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=true
  ------------------------------------
  </pre></code>
</details>

<details>
  <summary>grpc-go server frames</summary>
  <pre><code>
  TRACE 0509 18:25:09.684 PDT finagle/netty4-2:
  ----------------OUTBOUND--------------------
  [id: 0xe1eb88b4, L:/127.0.0.1:64530 - R:localhost/127.0.0.1:50051] SETTINGS: ack=false, settings={ENABLE_PUSH=0}
  ------------------------------------
  TRACE 0509 18:25:09.704 PDT finagle/netty4-2:
  ----------------OUTBOUND--------------------
  [id: 0xe1eb88b4, L:/127.0.0.1:64530 - R:localhost/127.0.0.1:50051] HEADERS: streamId=3, headers=DefaultHttp2Headers[:method: POST, :scheme: http, :path: /helloworld.Greeter/SayHello, :authority: localhost:4140, content-type: application/grpc, user-agent: grpc-go/1.3.0, te: trailers, l5d-dst-service: /svc/localhost:4140, via: h2 linkerd, l5d-dst-client: /$/inet/localhost/50051], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
  ------------------------------------
  TRACE 0509 18:25:09.714 PDT finagle/netty4-2:
  ----------------OUTBOUND--------------------
  [id: 0xe1eb88b4, L:/127.0.0.1:64530 - R:localhost/127.0.0.1:50051] DATA: streamId=3, padding=0, endStream=true, length=12, bytes=00000000070a05776f726c64
  ------------------------------------
  TRACE 0509 18:25:09.722 PDT finagle/netty4-2:
  ----------------INBOUND--------------------
  [id: 0xe1eb88b4, L:/127.0.0.1:64530 - R:localhost/127.0.0.1:50051] SETTINGS: ack=false, settings={}
  ------------------------------------
  TRACE 0509 18:25:09.723 PDT finagle/netty4-2:
  ----------------OUTBOUND--------------------
  [id: 0xe1eb88b4, L:/127.0.0.1:64530 - R:localhost/127.0.0.1:50051] SETTINGS: ack=true
  ------------------------------------
  TRACE 0509 18:25:09.723 PDT finagle/netty4-2:
  ----------------INBOUND--------------------
  [id: 0xe1eb88b4, L:/127.0.0.1:64530 - R:localhost/127.0.0.1:50051] WINDOW_UPDATE: streamId=0, windowSizeIncrement=983025
  ------------------------------------
  TRACE 0509 18:25:09.723 PDT finagle/netty4-2:
  ----------------INBOUND--------------------
  [id: 0xe1eb88b4, L:/127.0.0.1:64530 - R:localhost/127.0.0.1:50051] SETTINGS: ack=true
  ------------------------------------
  TRACE 0509 18:25:09.724 PDT finagle/netty4-2:
  ----------------INBOUND--------------------
  [id: 0xe1eb88b4, L:/127.0.0.1:64530 - R:localhost/127.0.0.1:50051] HEADERS: streamId=3, headers=DefaultHttp2Headers[:status: 200, content-type: application/grpc], padding=0, endStream=false
  ------------------------------------
  TRACE 0509 18:25:09.741 PDT finagle/netty4-2:
  ----------------INBOUND--------------------
  [id: 0xe1eb88b4, L:/127.0.0.1:64530 - R:localhost/127.0.0.1:50051] DATA: streamId=3, padding=0, endStream=false, length=18, bytes=000000000d0a0b48656c6c6f20776f726c64
  ------------------------------------
  TRACE 0509 18:25:09.741 PDT finagle/netty4-2:
  ----------------INBOUND--------------------
  [id: 0xe1eb88b4, L:/127.0.0.1:64530 - R:localhost/127.0.0.1:50051] HEADERS: streamId=3, headers=DefaultHttp2Headers[grpc-status: 0, grpc-message: ], padding=0, endStream=true
  ------------------------------------
  </pre></code>
</details>

<details>
  <summary>grpc-java client frames</summary>
  <pre><code>
  TRACE 0509 18:32:08.318 PDT finagle/netty4-1:
  ----------------OUTBOUND--------------------
  [id: 0x82ec2c7f, L:/127.0.0.1:4140 - R:/127.0.0.1:64590] SETTINGS: ack=false, settings={}
  ------------------------------------
  TRACE 0509 18:32:08.329 PDT finagle/netty4-1:
  ----------------INBOUND--------------------
  [id: 0x82ec2c7f, L:/127.0.0.1:4140 - R:/127.0.0.1:64590] SETTINGS: ack=false, settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
  ------------------------------------
  TRACE 0509 18:32:08.330 PDT finagle/netty4-1:
  ----------------OUTBOUND--------------------
  [id: 0x82ec2c7f, L:/127.0.0.1:4140 - R:/127.0.0.1:64590] SETTINGS: ack=true
  ------------------------------------
  TRACE 0509 18:32:08.332 PDT finagle/netty4-1:
  ----------------INBOUND--------------------
  [id: 0x82ec2c7f, L:/127.0.0.1:4140 - R:/127.0.0.1:64590] WINDOW_UPDATE: streamId=0, windowSizeIncrement=983041
  ------------------------------------
  TRACE 0509 18:32:08.340 PDT finagle/netty4-1:
  ----------------INBOUND--------------------
  [id: 0x82ec2c7f, L:/127.0.0.1:4140 - R:/127.0.0.1:64590] SETTINGS: ack=true
  ------------------------------------
  TRACE 0509 18:32:08.375 PDT finagle/netty4-1:
  ----------------INBOUND--------------------
  [id: 0x82ec2c7f, L:/127.0.0.1:4140 - R:/127.0.0.1:64590] HEADERS: streamId=3, headers=DefaultHttp2Headers[:authority: localhost:4140, :path: /helloworld.Greeter/SayHello, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.3.0, grpc-accept-encoding: gzip], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
  ------------------------------------
  TRACE 0509 18:32:08.630 PDT finagle/netty4-1:
  ----------------INBOUND--------------------
  [id: 0x82ec2c7f, L:/127.0.0.1:4140 - R:/127.0.0.1:64590] DATA: streamId=3, padding=0, endStream=true, length=12, bytes=00000000070a05776f726c64
  ------------------------------------
  TRACE 0509 18:32:08.867 PDT finagle/netty4-1:
  ----------------OUTBOUND--------------------
  [id: 0x82ec2c7f, L:/127.0.0.1:4140 - R:/127.0.0.1:64590] HEADERS: streamId=3, headers=DefaultHttp2Headers[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip, l5d-success-class: 1.0, via: h2 linkerd], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
  ------------------------------------
  TRACE 0509 18:32:08.877 PDT finagle/netty4-1:
  ----------------OUTBOUND--------------------
  [id: 0x82ec2c7f, L:/127.0.0.1:4140 - R:/127.0.0.1:64590] DATA: streamId=3, padding=0, endStream=false, length=18, bytes=000000000d0a0b48656c6c6f20776f726c64
  ------------------------------------
  TRACE 0509 18:32:08.881 PDT finagle/netty4-1:
  ----------------OUTBOUND--------------------
  [id: 0x82ec2c7f, L:/127.0.0.1:4140 - R:/127.0.0.1:64590] HEADERS: streamId=3, headers=DefaultHttp2Headers[grpc-status: 0], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=true
  ------------------------------------
  TRACE 0509 18:32:08.889 PDT finagle/netty4-1:
  ----------------INBOUND--------------------
  [id: 0x82ec2c7f, L:/127.0.0.1:4140 - R:/127.0.0.1:64590] GO_AWAY: lastStreamId=0, errorCode=0, length=0, bytes=
  ------------------------------------
  TRACE 0509 18:32:08.896 PDT finagle/netty4-1:
  ----------------OUTBOUND--------------------
  [id: 0x82ec2c7f, L:/127.0.0.1:4140 - R:/127.0.0.1:64590] GO_AWAY: lastStreamId=3, errorCode=0, length=0, bytes=
  ------------------------------------
  </pre></code>
</details>

<details>
  <summary>grpc-java server frames</summary>
  <pre><code>
  TRACE 0509 18:32:08.655 PDT finagle/netty4-2:
  ----------------OUTBOUND--------------------
  [id: 0x1fca26c1, L:/127.0.0.1:64591 - R:localhost/127.0.0.1:50051] SETTINGS: ack=false, settings={ENABLE_PUSH=0}
  ------------------------------------
  TRACE 0509 18:32:08.686 PDT finagle/netty4-2:
  ----------------OUTBOUND--------------------
  [id: 0x1fca26c1, L:/127.0.0.1:64591 - R:localhost/127.0.0.1:50051] HEADERS: streamId=3, headers=DefaultHttp2Headers[:authority: localhost:4140, :path: /helloworld.Greeter/SayHello, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.3.0, grpc-accept-encoding: gzip, l5d-dst-service: /svc/localhost:4140, via: h2 linkerd, l5d-dst-client: /$/inet/localhost/50051], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
  ------------------------------------
  TRACE 0509 18:32:08.701 PDT finagle/netty4-2:
  ----------------OUTBOUND--------------------
  [id: 0x1fca26c1, L:/127.0.0.1:64591 - R:localhost/127.0.0.1:50051] DATA: streamId=3, padding=0, endStream=true, length=12, bytes=00000000070a05776f726c64
  ------------------------------------
  TRACE 0509 18:32:08.811 PDT finagle/netty4-2:
  ----------------INBOUND--------------------
  [id: 0x1fca26c1, L:/127.0.0.1:64591 - R:localhost/127.0.0.1:50051] SETTINGS: ack=false, settings={MAX_CONCURRENT_STREAMS=2147483647, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
  ------------------------------------
  TRACE 0509 18:32:08.811 PDT finagle/netty4-2:
  ----------------OUTBOUND--------------------
  [id: 0x1fca26c1, L:/127.0.0.1:64591 - R:localhost/127.0.0.1:50051] SETTINGS: ack=true
  ------------------------------------
  TRACE 0509 18:32:08.811 PDT finagle/netty4-2:
  ----------------INBOUND--------------------
  [id: 0x1fca26c1, L:/127.0.0.1:64591 - R:localhost/127.0.0.1:50051] WINDOW_UPDATE: streamId=0, windowSizeIncrement=983041
  ------------------------------------
  TRACE 0509 18:32:08.834 PDT finagle/netty4-2:
  ----------------INBOUND--------------------
  [id: 0x1fca26c1, L:/127.0.0.1:64591 - R:localhost/127.0.0.1:50051] SETTINGS: ack=true
  ------------------------------------
  TRACE 0509 18:32:08.852 PDT finagle/netty4-2:
  ----------------INBOUND--------------------
  [id: 0x1fca26c1, L:/127.0.0.1:64591 - R:localhost/127.0.0.1:50051] HEADERS: streamId=3, headers=DefaultHttp2Headers[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
  ------------------------------------
  TRACE 0509 18:32:08.867 PDT finagle/netty4-2:
  ----------------INBOUND--------------------
  [id: 0x1fca26c1, L:/127.0.0.1:64591 - R:localhost/127.0.0.1:50051] DATA: streamId=3, padding=0, endStream=false, length=18, bytes=000000000d0a0b48656c6c6f20776f726c64
  ------------------------------------
  TRACE 0509 18:32:08.869 PDT finagle/netty4-2:
  ----------------INBOUND--------------------
  [id: 0x1fca26c1, L:/127.0.0.1:64591 - R:localhost/127.0.0.1:50051] HEADERS: streamId=3, headers=DefaultHttp2Headers[grpc-status: 0], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=true
  ------------------------------------
  </pre></code>
</details>

**Comment by olgert** [comment]
Similar behavior with gRPC [examples](https://github.com/grpc/grpc/tree/master/examples/python/helloworld) for Python ([grpcio](https://github.com/grpc/grpc/tree/master/src/python/grpcio)).

**Comment by klingerf** [comment]
Hmm, I just tried this again with `log.level=DEBUG`, and the java example is encountering the ChannelClosedException, but not logging it at `log.level=INFO`. The go example is encountering _two_ ChannelClosedExceptions, only one of which is logged at `log.level=INFO`.

With debug logging enabled, here's the full output from a grpc-java request:

```
D 0524 22:33:22.344 UTC THREAD226: [S L:/127.0.0.1:4140 R:/127.0.0.1:57957 S:3] initialized stream
D 0524 22:33:22.346 UTC THREAD226 TraceId:837caa668db03a27: [C L:/127.0.0.1:57955 R:/127.0.0.1:11111 S:5] initialized stream
D 0524 22:33:22.353 UTC THREAD225 TraceId:837caa668db03a27: [C L:/127.0.0.1:57955 R:/127.0.0.1:11111 S:5] stream closed
D 0524 22:33:22.356 UTC THREAD226: [S L:/127.0.0.1:4140 R:/127.0.0.1:57957 S:3] stream closed
D 0524 22:33:22.365 UTC THREAD226: [S L:/127.0.0.1:4140 R:/127.0.0.1:57957] resetting all streams: Reset.Cancel
D 0524 22:33:22.366 UTC THREAD226: [S L:/127.0.0.1:4140 R:/127.0.0.1:57957] transport closed
com.twitter.finagle.ChannelClosedException: ChannelException at remote address: /127.0.0.1:57957. Remote Info: Not Available
  at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelInactive(ChannelTransport.scala:186)
  (stacktrace truncated)
```

And here's the full output from a grpc-go request:

```
D 0524 22:32:38.938 UTC THREAD222: [S L:/127.0.0.1:4140 R:/127.0.0.1:57942 S:1] initialized stream
D 0524 22:32:38.942 UTC THREAD222 TraceId:25c7760be0628380: [C L:/127.0.0.1:57934 R:/127.0.0.1:11111 S:5] initialized stream
D 0524 22:32:39.062 UTC THREAD220 TraceId:25c7760be0628380: [C L:/127.0.0.1:57934 R:/127.0.0.1:11111 S:5] stream closed
D 0524 22:32:39.066 UTC THREAD222: [S L:/127.0.0.1:4140 R:/127.0.0.1:57942 S:1] stream closed
E 0524 22:32:39.069 UTC THREAD222: [S L:/127.0.0.1:4140 R:/127.0.0.1:57942] dispatcher failed
com.twitter.finagle.ChannelClosedException: ChannelException at remote address: /127.0.0.1:57942. Remote Info: Not Available
  at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelInactive(ChannelTransport.scala:186)
  (stacktrace truncated)
D 0524 22:32:39.069 UTC THREAD222: [S L:/127.0.0.1:4140 R:/127.0.0.1:57942] go away: GoAway.InternalError
D 0524 22:32:39.069 UTC THREAD222: [S L:/127.0.0.1:4140 R:/127.0.0.1:57942] resetting all streams: Reset.Cancel
D 0524 22:32:39.070 UTC THREAD222: [S L:/127.0.0.1:4140 R:/127.0.0.1:57942] transport closed
com.twitter.finagle.ChannelClosedException: ChannelException at remote address: /127.0.0.1:57942. Remote Info: Not Available
  at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelInactive(ChannelTransport.scala:186)
  (stacktrace truncated)
```

**Comment by ale-batt** [comment]
Same issue, any solution ?

**Comment by wmorgan** [comment]
@ale-batt are you still seeing this with Linkerd 1.1?

**Comment by ale-batt** [comment]
@wmorgan yes, running with docker 1.1.0

**Comment by wmorgan** [comment]
@ale-batt thanks!

**Comment by urtrcc** [comment]
The  csharp client have same issue . how to solve it ?

**Comment by urtrcc** [comment]
@wmorgan  did you solve this issue? I'm so confused with this issue。

**Comment by hawkw** [comment]
@urtrcc this issue is on my to-do list; I'll be starting on it shortly. Sorry to keep you waiting!

**Comment by klingerf** [comment]
And just to clarify, I think the issue is that Linkerd logs the exception when it shouldn't; Linkerd still successfully serves these requests, even when the client closes the connection. So I'm pretty sure the fix is just to clean up the logs.

**Comment by urtrcc** [comment]
@hawkw  Thank you so much!

**Comment by urtrcc** [comment]
@klingerf  I'm not sure csharp client have same issue ,but i got  same exception message log from Linkerd .
and  Linkerd version is 1.1.1.

This is  Linkerd  error log : 

![image](https://user-images.githubusercontent.com/8131263/28098947-e66bc840-66eb-11e7-8214-46e5dff757a8.png)

**Comment by hawkw** [comment]
I've done some research, and it looks like this is _technically_ a bug in the gRPC client implementation(s) that cause this behavior.

This error is occurring when the client closes a connection but fails to send a GOAWAY frame. According to the HTTP/2 spec:
> Endpoints SHOULD always send a GOAWAY frame before closing a connection so that the remote peer can know whether a stream has been partially processed or not. For example, if an HTTP client sends a POST at the same time that a server closes a connection, the client cannot know if the server started to process that POST request if the server does not send a GOAWAY frame to indicate what streams it might have acted on.

Since the clients are in error (because they don't comply to the spec), I think it's reasonable for linkerd to complain about this? I can see about changing the log message to something more informative than a stack trace, though.

**Comment by hawkw** [comment]
Hi @urtrcc, @olgert, and @ale-batt, just wanted to let you all know that I've pushed up a fix for this issue (#1498), hopefully we can get it merged shortly!

**Comment by olgert** [comment]
@hawkw Changing log message looks good to me. Thanks!

**Comment by hawkw** [comment]
Aaaand merged (99d06576c65de6e2e9db3d5987d2a4cbd2a14870). You should see this in the next release. :)

**Comment by urtrcc** [comment]
@hawkw  Thanks to fixed it! and what time is next release?

**Comment by ale-batt** [comment]
@hawkw Thanks ! When it will be on docker ?

**Comment by hawkw** [comment]
@urtrcc and @ale-batt, we cut release v1.1.2 _right_ before I merged these changes in, so I'm afraid I can't give you an exact time-frame. It'll probably be within two weeks or so, though!
