### ISSUE TITLE
Package update required in DC/OS universe

### ISSUE THREAD

**Issue by christtrc** [linkerd/linkerd#1293]
I noticed linkerd version in  DC/OS universe repo is 0.8.6, namerd version is 0.7.0. Is there a plan recently to update to the latest 1.0.0 version?

**Comment by siggy** [comment]
Hi @christtrc. linkerd is at 1.0.0 in DC/OS universe master:
https://github.com/mesosphere/universe/tree/version-3.x/repo/packages/L

What version of DC/OS are you on? 1.8/1.9? Is your universe up to date?

**Comment by christtrc** [comment]
Sorry! I had a mistake with universe repo, i did not notice __10__ in https://github.com/mesosphere/universe/tree/version-3.x/repo/packages/L， and my dc/os universe use a local repo which was not updated.
