### ISSUE TITLE
http://localhost:9990/admin/metrics/prometheus returns 404

### ISSUE THREAD

**Issue by oysterpack** [linkerd/linkerd#1305]
version: 1.0.1

According to the documentation "linkerd provides a metrics endpoint, **/admin/metrics/prometheus**, ..."
However, http://localhost:9990/admin/metrics/prometheus returns back a 404.

Has the URI changed ?

NOTE: This is the first time I am using linkerd, so I don't know if the documention is out of date, or if this is a "real" issue ... either way it is a bug :)

**Comment by siggy** [comment]
@oysterpack you're correct this is a documentation issue. you need to add a section to your linkerd config like this:

```yaml
telemetry:
- kind: io.l5d.prometheus
```

example:
https://github.com/linkerd/linkerd-examples/blob/master/linkerd-tcp/linkerd.yml#L1

i'm going to close this for now and get a fix going in our docs repo.

**Comment by zhangyou1010** [comment]
get it
