### ISSUE TITLE
http filters

### ISSUE THREAD

**Issue by magg** [linkerd/linkerd#1311]
Can I create HTTP filters or rules in linkerd, like when a specific header is present, delay or throw an error?

**Comment by samek** [comment]
depends on what you want to achieve .. 
https://github.com/linkerd/linkerd-examples/tree/master/plugins/header-classifier
There are 2 examples of plugins you probably might want to look into the identifier plugin.

**Comment by elecnix** [comment]
You can identify requests using a header, then match it in your dtab with [negative resolution or failure](https://linkerd.io/in-depth/dtabs/#negative-failure-empty-resolutions).

**Comment by magg** [comment]
@samek I was looking to do something similar to what envoy does: https://lyft.github.io/envoy/docs/configuration/http_filters/fault_filter.html

But I want to do this in linkerd

**Comment by siggy** [comment]
@magg: @elecnix is correct, you can use header-classifiers, or per-request headers to accomplish this.

I'm going to close this issue. I've moved this topic to our new [forum](https://discourse.linkerd.io). If you have more questions/comments, let's keep the conversation going over there:
https://discourse.linkerd.io/t/per-request-overrides-using-http-headers/66
