### ISSUE TITLE
thriftMethodInDst not compatible with thrift compact protocol

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#1318]
When I try to send a compact buffered thrift request through this router:

```yaml
router:
- protocol: thrift
  label: /host/thrift-buffered
  dtab: |
    /host => /#/io.l5d.fs;
    /svc  => /host/thrift-buffered;
  thriftMethodInDst: true
  client:
    thriftFramed: false
    thriftProtocol: compact
  servers:
  - port: 4142
    ip: 0.0.0.0
    thriftFramed: false
    thriftProtocol: compact
```

It fails with:

```
W 0516 21:51:33.364 UTC THREAD19: Exception propagated to the default monitor (upstream address: /127.0.0.1:55072, downstream address: n/a, label: 0.0.0.0/4142).
org.apache.thrift.protocol.TProtocolException: Bad version in readMessageBegin
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:214)
	at io.buoyant.router.thrift.Identifier.suffix(Identifier.scala:22)
	at io.buoyant.router.thrift.Identifier.apply(Identifier.scala:31)
	at io.buoyant.router.thrift.Identifier.apply(Identifier.scala:12)
	at io.buoyant.router.RoutingFactory$RoutingService.apply(RoutingFactory.scala:159)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:18)
	at io.buoyant.router.Thrift$Router$IngestingFilter$.apply(Thrift.scala:43)
	at io.buoyant.router.Thrift$Router$IngestingFilter$.apply(Thrift.scala:41)
```

The issue is that the message is misidentified as binary protocol and the binary deserializer is used instead of the compact deserializer.

This appears to have broken between the linkerd 0.9.1 release and the linkerd 1.0.0 release -- the router config pasted above works in 0.9.1 and fails in 1.0.0.

**Comment by klingerf** [comment]
The issue appears to be that the thrift protocol was previously set as a param on the router stack, but it's now set on the client stack instead. I think the correct fix is to move the `thriftProtocol` option back to the router config, and remove it from the server and client configs. Since linkerd does not modify payloads, I don't think it's possible configure a router client and server with different protocols and have it still successfully route the request. Consolidating the two places where protocol is configured back into one should hopefully fix this, but other ideas also welcome.

**Comment by adleong** [comment]
I think it may be technically possible to have a server and client with different protocols because linkerd deserializes and re-serializes the thrift request.  That said, being able to bridge two different thrift protocols seems like a very niche feature and I'm not aware of anyone doing this or wanting to be able to do it.  So in the interest of simplification, I'd be in favor of consolidating this property on the router.
