### ISSUE TITLE
Improve styling of dtab rules in the dtab playground

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd#1321]
From William's comment in #523:

> I still don't like styling of rules as button-looking things that aren't actually buttons. I'd much prefer to remove the border, and align the rules around the central " => ".

I think this could look weird with prefixes of varying length, but maybe we could instead put a border around each dentry/do something else to make it look less like buttons.

**Comment by esbie** [comment]
Totally! These prefixes used to be (maybe still are?) clickable. They highlight associated resolution steps. We should take that functionality out if/when we unbutton-ify things.

**Comment by franziskagoltz** [comment]
@wmorgan - Going through a backlog of linkerd issues, this came up. Do you still feel like the button look needs to be removed? The fields do have button-like functionality, as they highlight the associated resolution steps when clicked. Image below. 

I spoke with risha and siggy about it, they both refer to asking you if this is still something we want to change.
![screen shot 2018-01-10 at 4 33 38 pm](https://user-images.githubusercontent.com/12401925/34840077-bf294eee-f6b8-11e7-9b9e-17ee88998af0.png)

**Comment by wmorgan** [comment]
Blast from the past. I will defer this decision to @sterlingwhite.

**Comment by wmorgan** [comment]
(And I don't think I realized they were clickable when I originally made this issue.)
