### ISSUE TITLE
Namerd doesn't close observations when Linkerd disconnects over `io.l5d.mesh`

### ISSUE THREAD

**Issue by Ashald** [linkerd/linkerd#1329]
We were able to confirm this behavior by:
1) Starting a "fresh" instance of Namerd not used by anybody
2) Start a "fresh" instance of Linkerd and make it talk to the Namerd using `io.l5d.mesh`
3) Resolve 10 distinct names (existing and non-existing). And record number of active observations.
4) Terminate Linkerd and verify that number of active observations is not decreasing even as time passes.

We were able to measure "active observations" easily due to the issue described in https://github.com/linkerd/linkerd/issues/1328 - essentially, each name observation increased number of open connection to Consul by 15 since it involved observation of a namespace. So we were measuring the number of open observations by number of open connections to Consul.

**Comment by Ashald** [comment]
cc @adleong

**Comment by adleong** [comment]
I wasn't able to reproduce this.  Here's what I tried:

1. Start a fresh namerd with consul dtab storage and mesh interface
2. Start linkerd and attempt to resolve 5 names (1 existing and 4 non-existing)
3. From the namerd stats note the number of connections to consul: `"clnt//$/inet/localhost/8500/connections": 5,`
4. Shutdown linkerd
5. From the namerd stats, notice that the number of connections to consul has dropped to 0: `"clnt//$/inet/localhost/8500/connections": 0,`

**Comment by Ashald** [comment]
If that's the case maybe we've got it in a wrong way. Let's close it for now and if we will be able to reproduce it we will re-open the issue. Thanks!

**Comment by adleong** [comment]
Sounds good!
