### ISSUE TITLE
mutual ssl authentication

### ISSUE THREAD

**Issue by kigsmtua** [linkerd/linkerd#1331]
I been have assigned to look for api gateway that fits our requirements, linkerd fits all of them apart from authentication.
The requirements is to use mutual ssl for authentication then add ssl cert info in the request header
From the documentation I can not tell  whether linkerd can do that , any help on this or insights?

**Comment by wmorgan** [comment]
Hi @kigsmtua. Mutual auth will probably be a part of the next release. You can follow along here: https://github.com/linkerd/linkerd/pull/1319
