### ISSUE TITLE
Make linkerd not phone home

### ISSUE THREAD

**Issue by kalyan02** [linkerd/linkerd#1360]
Linkerd phones home - hourly. This is not ok.

As per this : 
https://github.com/linkerd/linkerd/blob/a22b060c0ab7864f672ff9b48fa874cf91bf49b3/linkerd/core/src/main/scala/io/buoyant/linkerd/telemeter/UsageDataTelemeter.scala#L200

We only spotted this because our prod environment is firewalled and this exception started showing up in our logs.

```
D 0607 16:05:03.033 UTC THREAD83: ChannelStatsHandler caught an exception
org.jboss.netty.channel.ConnectTimeoutException: connection timed out: stats.buoyant.io/104.28.23.233:443
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:139)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:83)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by wmorgan** [comment]
You can turn this off easily. See  https://linkerd.io/config/1.0.2/linkerd/index.html#usage

**Comment by kalyan02** [comment]
While I understand the flag turns it off, it is not OK on principle, that it is enabled by default and set to aggressively post metrics hourly.

**Comment by wmorgan** [comment]
I hear you. What do you suggest instead?

**Comment by kalyan02** [comment]
I see few possibilities:
1. Disable this complete. Remove all code
2. Disable by default. Enable it optionally.
3. Make it very very obvious in documentation that this is enabled by default.
4. Make it less aggressive and configurable.

Am also unsure how security auditors will take to it in its current form.

**Comment by wmorgan** [comment]
Thanks! Appreciate the thoughtful feedback. I would be open to PRs for options 3 and 4.

**Comment by samek** [comment]
@kalyan02 When I started using linkerd I went through the documentation and I saw it. 
I also had a look what exactly is sent out when it calls  home .. which is not something that you should really worry about. 

Anyway we all have a great piece of software here for free and If guys from linkerd decided that this information is important to them this is the least what we can do - to keep it on. 

This is my opinion. 

btw. you can always disable it.

**Comment by wmorgan** [comment]
FWIW, I totally understand @kalyan02's point of view. I am also uncomfortable with software that phones home. But we use these metrics to justify investment in Linkerd, so... we have to walk a fine line here.

We need to keep this enabled by default, but I would like it to be very obvious how to turn it off, and very clear about what it sends. (We've also tried very hard to make sure the info it sends is non-identifying.)

**Comment by wmorgan** [comment]
Just to summarize for future passersby, I'd be open to accepting PRs for better documentation around this feature and more configuration surface area around it.

**Comment by mkavanagh** [comment]
I appreciate that you are trying to be transparent as possible with this but I still think this is a surprising thing for server software to be doing. The data being sent is identifying because it necessarily includes the source IP address, it's an unnecessary risk from a user perspective to expose the OS version, and the fact this has been done means I feel I have to carefully audit every linkerd release I deploy to confirm that nothing else "surprising" has been added.

I don't know any other examples of commercially backed F/OSS server software that have opt-out phone home functionality - I'd be glad to be enlightened with examples I'm unaware of though, because I'd always want to disable that functionality in any production environment.
