### ISSUE TITLE
proxy loop issue in linkerd

### ISSUE THREAD

**Issue by edio** [linkerd/linkerd#1411]
Hello,

linkerd suffers from a so called _proxy loop_ issue, when it tries to proxy request where target address is the proxy itself or if request eventually reaches the proxy after interim hops.

STR:
1. run linkerd with the following router configured
```
routers:
- protocol: http
  label: proxyissue
  dstPrefix: /http
  servers:
  - port: 4140
    ip: 0.0.0.0
  dtab: |
      /http=>/$/io.buoyant.hostportPfx/split;
      /split=>/$/inet;
```
2. make a request to `localhost:4140` using executed linkerd instance as a proxy

AR: linkerd starts spawning threads until original request timeouts, OOM happens or request gets too large (due to large `Via` header value)
ER: I'd expect linkerd to detect proxy loop and return 400 with explanation that proxy loop is detected

Some thoughts on approaches to resolve the issue.

Linkerd already adds `Via` header. So 2 approaches:

1) actual loop detection algorithm
Con: we'd need then to update linkerd to put some unique identifier instead of `linkerd $version` to `Via` header. Potentially slow

2) heuristic: `Via` header value length <= threshold 
Con: can give false positives if infrastructure is built that way, that large number of hops is occasionally required. But practically hardly ever possible.

I checked if it's possible to workaround issue with delegations or plugins, and that's what I've found:

1) plugin
generally not possible due to https://github.com/linkerd/linkerd/issues/1255
If at least namer was allowed to check headers, we might return some `/failure#` from it, while having delegation `/failure#=>!`

2) dtab
this one could fix the issue for loops of length 1
Something like this 
```/inet#=>/$/inet;
/inet#/localhost/4140=>!;
```
It is by no means a general solution, because there might be many names which are resolved to `127.0.0.1`
So the only thing we can do atm, is to add delegation `/inet#/*/4140=>!` and we should remember then, that `4140` is reserved even if no linkerd is running on host.

Both dtab and plugins won't allow returning code other than 502.

So it seems, that it is linkerd core, that should contain logic for proxy loop detection.

**Comment by wmorgan** [comment]
Thanks @edio! Great writeup and thank you for all the alternatives. We'll take a look.

**Comment by adleong** [comment]
related to #87

**Comment by zaharidichev** [comment]
@edio Excuse me if this is a silly question, but why would you consider adding an unique identifier to the Via header to be a slow approach. I assume this unique identifier is unique per proxy instance. Correct? To me this seems like a viable solution to the problem, right?

**Comment by edio** [comment]
@zaharidichev, I meant, that the whole solution, as described there, would be slower. We'd have to parse the header on every hop and execute some loop detection algorithm. Whether it's significant overhead I don't know.

FWIW, we've been running for 2 years on prod using DTab to prevent proxy loops and on practice haven't faced any issues so far
```
/$/inet/localhost/4140=>!;
/$/inet/localhost/4141=>!;
/$/inet/localhost/4142=>!;
```
