### ISSUE TITLE
Spurious log message for HEAD /admin/ping

### ISSUE THREAD

**Issue by rmichela** [linkerd/linkerd#1412]
I'm testing the liveliness of linkerd. I'm not interested in the word "pong" returned by the endpoint. I'm making a HEAD request to /admin/ping to get only the HTTP response code, since that's the only part that matters. 

Every time I make the request, linkerd logs the following useless log message:
`E 0617 00:08:35.145 UTC THREAD34: Received response to HEAD request (Request("HEAD /admin/ping", from /127.0.0.1:15000)) that contained a static body of length 4. Discarding body. If this is desired behavior, consider adding HeadFilter to your service`

**Comment by wmorgan** [comment]
Thanks, @rmichela! Looks like this message originates in Finagle's [ResponseConformanceFilter](https://github.com/twitter/finagle/blob/master/finagle-http/src/main/scala/com/twitter/finagle/http/codec/ResponseConformanceFilter.scala). I'll leave it to the experts to determine how easy this is to fix.

**Comment by rmichela** [comment]
As an alternative, you could update the /admin/ping handler to return an empty response when a HEAD request is made.

**Comment by hawkw** [comment]
Hi @rmichela, just wanted to let you know that this issue was fixed in 797716b73acee0b5ab647ad9976a0627aaf5354a – we now return an empty response for HEAD requests. It'll be in the next release. Thanks for reporting!
