### ISSUE TITLE
Istio with linkerd guide/blogpost

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#1417]
Tutorial of how to set up Istio with linkerd.

**Comment by esbie** [comment]
https://linkerd.io/getting-started/istio/

**Comment by UnwashedMeme** [comment]
I came across https://linkerd.io/getting-started/istio/ yesterday found it interesting and trying to find more got to here. The big question I'm trying to figure out is "Why?" or "What does this setup offer that is better than running istio with envoy or linkerd standalone?"

I'm seeing a whole bunch of issues open on improving integration and from what I've found linkerd is a bit closer to envoy and istio is providing a larger control plane?

**Comment by adleong** [comment]
That's correct that Linkerd and Envoy are very similar in the role they fill and have quite a bit of feature overlap.  Linkerd also has a control plane in the form of [Namerd](https://github.com/linkerd/linkerd/tree/master/namerd).

Istio is a very new project and is evolving rapidly so it's tough to compare with Linkerd and draw any meaningful conclusions.  One of the reasons one might choose Linkerd is that it's been around a bit longer and has a wide array of companies already using it in production.  That said, Istio is super interesting and we're excited to be involved.

**Comment by nitishm** [comment]
Why is the doc no longer available at https://linkerd.io/getting-started/istio/ ?

**Comment by wmorgan** [comment]
@nitishm we're no longer maintaining that integration (which never made it out of experimental status anyways).
