### ISSUE TITLE
h2 should use SingletonPool

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#1425]
I believe that our h2 implementation currently uses finagle's default connection pooling logic, but this would have adverse affects when using a multiplexed protocol like h2.  Luckily, finagle offers a singletonpool to prevent multiple connections from being established to a single endpoint.  We should use it!  I expect this may resolve some issues we've been trying to debug around h2 connection management.

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd/pull/1444
