### ISSUE TITLE
How to pass existing zipkin trace to linkerd

### ISSUE THREAD

**Issue by cchatfield** [linkerd/linkerd#1428]
I am trying to pass an already initiated trace (outside of linkerd) to linkerd. Looking at the code and documentation, it seems like I need to base64 encode something and pass in via the l5d-ctx-trace header. Unfortunately, I am unable to determine how to make this work.

An example TraceId 

'x-b3-parentspanid': '2b4e2bf6f8c66e69',
'x-b3-sampled': '1',
'x-b3-spanid': '94d2daf00839b43a',
'x-b3-traceid': 'e534a82e27a8222c'

Can you point me in the right direction on how to pass pre existing trace information to linkerd?

I am using node.js. Some attempts below
`
let trace = traceHeaders['_spanId'] + '.' + traceHeaders['_parentId']['value'] + '<:' +  traceHeaders['_traceId']['value'];
let trace = traceHeaders['_spanId'] + traceHeaders['_parentId']['value'] + traceHeaders['_traceId']['value'];
let trace = traceHeaders['_traceId']['value'];
additionalHeaders['l5d-ctx-trace'] = Buffer.from(trace, 'utf8').toString('base64');`

**Comment by klingerf** [comment]
Hey @cchatfield, we use finagle's `TraceId.serialize` method to serialize the trace id to bytes, which are passed via the `l5d-ctx-trace` header. You can see how the serialize method works [here](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/tracing/Id.scala#L74).

More generally though, we mostly expect users of linkerd to forward the `l5d-ctx*` headers without modification. The idea is that linkerd will produce it's own traces of the request path, and you're welcome to use a different set of headers, such as open tracing or zipkin's `x-b3*`, which linkerd will forward without modification. This unfortunately means that they two traces will not be linked, however. 

If it seems like a common use case that folks would want to supply their own trace ids to linkerd, we could probably do this more ergonomically than requiring you to set the encoded `l5d-ctx-trace` header. Of the top of my head, maybe we could accept a plaintext `l5d-trace` header, and use that value to create the encoded `l5d-ctx-trace` header that's returned with the response. We do something similar already for the `l5d-dtab` header.

**Comment by cchatfield** [comment]
In my case, traces can start from the UI. With these traces, it's important to capture the full correlated trace including the spans from linkerd. I think your suggestion of creating a plain text header might be a little easier than the encoded serialized one for linkerd.

I did get the tracing to pass correctly by serializing in the form needed by linkerd.

Here is a snippet that works for node.js services.

    const ByteBuffer = require('bytebuffer');

    public traceToLinkerdPackedHeader():string{
      let flagBytes = [0, 0, 0, 0, 0, 0, 0, 6];
      let serialized = ByteBuffer.concat([this.getByteArray(this.traceId.spanId),this.getByteArray(this.traceId.parentId), this.getByteArray(this.traceId.traceId), flagBytes]);

      return serialized.toBase64();
    }
    private getByteArray(id: string ){
      let array = Buffer.from(id, 'utf8');
      let byteArray  = [];
      for (let i = 0; i < 16; i = i + 2) {
        let parsed = parseInt(id.slice(i, i + 2), 16);
        parsed = parsed & 255;
                
        if (parsed > 127) {
          parsed = -((parsed & 127) ^ 127) - 1;
        }
                
        byteArray.push(parsed);
      }

      return byteArray;
    }

**Comment by klingerf** [comment]
Glad to hear you got it working! I went ahead and opened #1447 to make it easier to set trace ids on inbound requests, and will close this issue out.
