### ISSUE TITLE
Support k8s services of type: ExternalName

### ISSUE THREAD

**Issue by esbie** [linkerd/linkerd#1430]
Istio uses ExternalName services to [direct egress traffic](https://istio.io/docs/tasks/egress.html#configuring-the-external-services). These services don't appear in the SDS (although they DO show up in RDS), so we need another way to handle these in the IstioInterpreter or IstioNamer. 

Tangentially, it looks like the EndpointsNamer doesn't handle externalName correctly either.

**Comment by esbie** [comment]
More investigation on this today:

The services show up in RDS with routes rewritten/redirected to egress cluster. From there I *think* the current the egress cluster routes to the FQDN, which kubedns has a CNAME for that points outside the cluster.

There's no way to get `externalName` from the istio pilot apis, so the only options I see are (1) Talk to the k8s api directly to get this information or (2) blindly rely on kubedns CNAME w/o knowing if the route is external or not. Or (3), whatever alex comes up with :)

**Comment by adleong** [comment]
Do the external clusters exist in SDS?

**Comment by esbie** [comment]
No, they don't... so currently the identifier returns `/svc/dest/externalbin.default.svc.cluster.local/::/http`  but `/#/io.l5d.k8s.istio/reviews.default.svc.cluster.local/::/http` fails to resolve and returns "No hosts"

**Comment by adleong** [comment]
I think (1) and (2) are both valid.  For (1) we would probably have to write an ExternalNameNamer or something like that....

**Comment by esbie** [comment]
Deprioritizing this feature until after mvp. Istio users can already reach external apis w/o external name services
