### ISSUE TITLE
Make k8s ingress controller class configurable

### ISSUE THREAD

**Issue by esbie** [linkerd/linkerd#1433]
Ingress resources [meant for istio](https://istio.io/docs/tasks/ingress.html#configuring-ingress-http) are annotated with `kubernetes.io/ingress.class: istio`, and linkerd ignores them to avoid ingress controller collisions. If istio uses linkerd as its ingress controller, linkerd should be configured to read the istio annotated resources.

**Comment by esbie** [comment]
Fixed as part of #1440

**Comment by sozuuuuu** [comment]
Reopening this issue because linkerd ingress controller class is configurable in code but not exposed to configuration file.

linkerd slack channel conversation:
- https://linkerd.slack.com/archives/C0JV5E7BR/p1500870468909826
- https://linkerd.slack.com/archives/C0JV5E7BR/p1500918310662653

**Comment by pcalcado** [comment]
@sozuuuuu could you look at #1584 and let me know what you think of it? Maybe this is the most relevant file: 

https://github.com/linkerd/linkerd/blob/221d343a6d24cc82299e0ba018b627fd42540731/linkerd/docs/protocol-http.md#ingress-identifier

**Comment by pcalcado** [comment]
Fixed on  #1584
