### ISSUE TITLE
Discrepancy between client and server connection counts in h2 linker-to-linker setup

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#1434]
Related to #1395. When the second linkerd in a linker-to-linker setup stops accepting requests, we've observed a mismatch in the number of connections reported by the first linkerd's client and the second linkerd's server.

From the client's perspective, it looks like this:

![screen shot 2017-06-21 at 5 04 42 pm](https://user-images.githubusercontent.com/9226/27411756-990495fc-56a4-11e7-9bc5-984d2c696922.png)

After the linkerd `10.196.0.42` stops accepting requests, the linkerd running on `10.196.1.125` reports a fixed number of ~450 client connections.

From the server's perspective, however, it looks like this:

![screen shot 2017-06-21 at 5 04 13 pm](https://user-images.githubusercontent.com/9226/27411817-20a9b73a-56a5-11e7-8e67-4f0209fad280.png)

The linkerd running on `10.196.0.42` reports a steadily increasing number of server connections, exceeding 2000. I would expect the number of connections reported by the client and the server to be equal but they are clearly not.

**Comment by klingerf** [comment]
Digging a bit more deeply into this, unless I'm misunderstanding these stats, I'd expect the number of connections at any given time to equal the number of connects minus the number of closes. This is also clearly not the case.

For the client running on `10.196.1.125`, I see:

![screen shot 2017-06-21 at 5 35 55 pm](https://user-images.githubusercontent.com/9226/27412513-fd6b6944-56a9-11e7-8b19-8a90b5c2bd46.png)

The number of client connections remains basically constant, but the rate of closes _exceeds_ the rate of connects, which does not seem correct.

For the server running on `10.196.0.42`, I see:

![screen shot 2017-06-21 at 5 47 01 pm](https://user-images.githubusercontent.com/9226/27412555-3955311a-56aa-11e7-8d3d-ae02a9dc847e.png)

This also seems problematic. Initially, the number of connections grows at the same rate as connects, and there are no closes, so the stats appear to line up. After awhile, however, the connect and close rates remain constant, but the number of connections drops.

**Comment by adleong** [comment]
Fixed by #1444
