### ISSUE TITLE
GCE LoadBalancer is pending indefinitely

### ISSUE THREAD

**Issue by verdverm** [linkerd/linkerd#1438]
Not sure the preferred repo to open an issue on, originally here: https://github.com/linkerd/linkerd-examples/issues/148

---

I've followed along several of the blog posts in the "A Service Mesh for Kubernetes" series. Each time, the LoadBalancer is not created and the IP is pending indefinitely.

Maybe I am missing a service account / the correct permissions on the VMs

**Comment by siggy** [comment]
Closing per https://github.com/linkerd/linkerd-examples/issues/148#issuecomment-310512139.
