### ISSUE TITLE
FailureAccrual backoff only uses the default values

### ISSUE THREAD

**Issue by hammerOwen** [linkerd/linkerd#1439]
I was playing with the failure accrual example and found that no matter what settings you put in the backoff configuration. 
I have tried using both constant and jittered backoff with a server that will send back 500 errors for all requests. Neither of the settings are used and the default values of jittered with a minimum of 500 ms and a maximum 30000ms.

**Comment by wmorgan** [comment]
Thanks @hammerOwen! We'll take a look.

**Comment by hawkw** [comment]
Okay, an update: as of 7f8c027ef7f07e6c67cb97be8de5e4e778e157c9, I've added a great deal of unit tests for the parsing of failure accrual configs, and I can say with some certainty that this bug is not in config parsing.

**Comment by hawkw** [comment]
Hi @hammerOwen, just wanted to let you know that I added a fix for this issue in 038c223bf55b854d18c5771555fae690b1ea9290. It should be in the next release. Thanks for reporting!
