### ISSUE TITLE
h2 traffic is not balanced across backend instances

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#1441]
Relates to #1395, #1434.

I've been running repeated h2 tests in a linker-to-linker setup with 3 backends. In many tests I've noticed wide variation in the volume of traffic sent to the inbound linkerds for each backend. For instance:

![screen shot 2017-06-23 at 12 02 32 pm](https://user-images.githubusercontent.com/9226/27496768-499d8f78-580c-11e7-88a3-0a0085e4dc22.png)

The top line is total requests, and the bottom 3 are requests per inbound linkerd instance.

Here are the stats for the three linkerd instances in this setup:

* [slow.txt](https://github.com/linkerd/linkerd/files/1098810/slow.txt) (yellow in graph above)
* [faster.txt](https://github.com/linkerd/linkerd/files/1098811/faster.txt) (orange in graph above)
* [fastest.txt](https://github.com/linkerd/linkerd/files/1098812/fastest.txt) (blue in graph above)

There is not a notable difference in `rt/h2-in/server/0.0.0.0/5159/request_latency_ms` stats for each of the 3 instances, so I don't think the imbalance is based on observed latency.

It's also interesting that a weighting decision seems to be made, and then is maintained for hours before the ratio changes.

**Comment by klingerf** [comment]
Wanted to add a screenshot of a test where imbalanced traffic leads to an overall performance degradation when one of the backends stops serving requests:

![screen shot 2017-06-23 at 3 09 03 pm](https://user-images.githubusercontent.com/9226/27502849-0a1e004c-582c-11e7-8d3d-37b40818bbbf.png)

You can see that one of the three backend instances was serving 50% of traffic, and when it stopped serving traffic, linkerd's overall success rate dropped to 50%, rather than removing the instance from the load balancer pool.

**Comment by klingerf** [comment]
With @adleong's fix from #1444 applied, this issue has changed somewhat, although there's still a wider distribution of requests than I would typically expect.

Unsurprisingly, the traffic balance changes based on choice load balancer. Here's a comparison in a test setup of ~85 rps balanced over 3 backends:

![screen shot 2017-06-29 at 2 48 53 pm](https://user-images.githubusercontent.com/9226/27713967-0dfa75e0-5ce3-11e7-8307-1d84809e7014.png)

The balancing behavior also seems to be impacted by request cancelations. Here's the same setup, but with roughly 1 request per second being canceled:

![screen shot 2017-06-29 at 2 30 20 pm](https://user-images.githubusercontent.com/9226/27713995-389cf3cc-5ce3-11e7-9837-17eb44f9db75.png)

In this case the variability in the default load balancer is pretty extreme.

**Comment by adleong** [comment]
It's not surprising to me that cancellations would cause more chaotic latency distributions and therefore more chaotic behavior of latency aware load balancers.

**Comment by klingerf** [comment]
I pulled the loadbalancer stats from an instance that was sending unbalanced h2 traffic across 3 backends, and they look like this:

```
"rt/h2-out/client/.../loadbalancer/adds": 3,
"rt/h2-out/client/.../loadbalancer/algorithm/p2c_least_loaded": 1,
"rt/h2-out/client/.../loadbalancer/available": 3,
"rt/h2-out/client/.../loadbalancer/busy": 0,
"rt/h2-out/client/.../loadbalancer/closed": 0,
"rt/h2-out/client/.../loadbalancer/load": 2035,
"rt/h2-out/client/.../loadbalancer/max_effort_exhausted": 0,
"rt/h2-out/client/.../loadbalancer/meanweight": 1,
"rt/h2-out/client/.../loadbalancer/rebuilds": 1,
"rt/h2-out/client/.../loadbalancer/removes": 0,
"rt/h2-out/client/.../loadbalancer/size": 3,
"rt/h2-out/client/.../loadbalancer/updates": 1,
```

**Comment by klingerf** [comment]
Have seen this same behavior with an HTTP/1.1 test as well:

![screen shot 2017-07-01 at 4 09 57 pm](https://user-images.githubusercontent.com/9226/27766043-0e961e96-5e78-11e7-9083-67268839ed5c.png)

And here are the loadbalancer stats for that client:

```
"rt/http-out/.../loadbalancer/adds": 3,
"rt/http-out/.../loadbalancer/algorithm/p2c_least_loaded": 1,
"rt/http-out/.../loadbalancer/available": 3,
"rt/http-out/.../loadbalancer/busy": 0,
"rt/http-out/.../loadbalancer/closed": 0,
"rt/http-out/.../loadbalancer/load": 3,
"rt/http-out/.../loadbalancer/max_effort_exhausted": 0,
"rt/http-out/.../loadbalancer/meanweight": 1,
"rt/http-out/.../loadbalancer/rebuilds": 1,
"rt/http-out/.../loadbalancer/removes": 0,
"rt/http-out/.../loadbalancer/size": 3,
"rt/http-out/.../loadbalancer/updates": 1,
```
