### ISSUE TITLE
large baseDtab causes latency increase

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd#1442]
## Problem

We've observed very large dtabs (20,000 to 200,000 entries) causing at least 5x latency increases. The root cause appears to be linkerd recomputing a hash code on `baseDtab` for every request.

### 2 line dtab

```bash
$ wrk -d 60 -t 4 --latency -c 100 -H "Host: default" http://localhost:4140/
Running 1m test @ http://localhost:4140/
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    55.55ms   82.98ms 744.88ms   85.11%
    Req/Sec     1.79k   809.73     5.25k    66.30%
  Latency Distribution
     50%    7.76ms
     75%   86.75ms
     90%  178.84ms
     99%  348.94ms
  427820 requests in 1.00m, 1.05GB read
  Socket errors: connect 0, read 51, write 8, timeout 0
Requests/sec:   7119.97
Transfer/sec:     17.95MB
```

### 200,000 line dtab

```bash
$ wrk -d 60 -t 4 --latency -c 100 -H "Host: default" http://localhost:4140/
Running 1m test @ http://localhost:4140/
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.53s   351.85ms   2.00s    61.42%
    Req/Sec    12.28     10.79    80.00     84.71%
  Latency Distribution
     50%    1.62s
     75%    1.84s
     90%    1.94s
     99%    1.99s
  2103 requests in 1.00m, 5.30MB read
  Socket errors: connect 0, read 59, write 0, timeout 1722
Requests/sec:     34.99
Transfer/sec:     90.31KB
```

### yourkit cpu usage

![screen shot 2017-06-23 at 3 22 19 pm](https://user-images.githubusercontent.com/236915/27502411-b42b72f8-5828-11e7-8a41-bde5e5fbc2da.png)

## Proposed Solution

Push the `baseDtab` down into an interpreter, hash code will no longer be computed in the request path. linkerd will no longer have `baseDtab`, similar to a linkerd+namerd configuration. This will cause an internal API breaking change in the interpreter.

**Comment by esbie** [comment]
cool find! we also may need to jump some hoops so that the linkerd dtab playground works with the new interpreter (currently you can't change the dtab for namerd/istio interpreters in the ui)
