### ISSUE TITLE
Feature - support zero downtime config changes

### ISSUE THREAD

**Issue by DukeyToo** [linkerd/linkerd#1449]
Currently, changing the linkerd config yaml file does not take effect without restarting the linkerd process.  However, restarting the process will lose any connections that are initiated in the time between shutting down and starting up again.  This means that (unless we want to lose some traffic during config changes), we cannot push new linkerd config to existing machines.  

Both haproxy and nginx both have solutions to this - in effect you can specify new configs in both of these and either restart without connections lost (haproxy) or reload the config (nginx) without shutting down.  Linkerd has an `/admin/shutdown` endpoint, but to my understanding (and in my testing) this is a graceful shutdown, but does not prevent loss of connections in the time between shutdown and subsequent restart.

If neither the haproxy or the nginx approach is workable, another solution I have seen is to offer an `/admin/offline` endpoint that tells the healthcheck to fail, but does not affect anything else.  This causes any load balancer that uses that health check to eventually mark the node down and quit sending traffic.  At that point, it can be safely restarted and once the linkerd process comes up again, the health check will pass again and the load balancer will add it back.   This solution requires some additional scripting work to orchestrate everything, but it is workable.

**Comment by olix0r** [comment]
What configuration are you changing frequently? Our goal is to push all of the things that change frequently outside of the main configuration.

**Comment by DukeyToo** [comment]
Mostly we have tweaked the client and service parameters, for example change the service `totalTimeoutMs`/`responseClassifier` or client failure params.  It is not something we have a need to do often - as you say, most of the stuff that changes often is outside of that config, in namerd in our case.

**Comment by wmorgan** [comment]
Would this also apply to upgrading Linkerd itself?

**Comment by olix0r** [comment]
@DukeyToo we have some plans to make the service/client configurations dynamic -- as a first step, as separate configuration files that are watched for changes, and later even integrated into the namerd API.  I definitely agree it's a valuable feature.

**Comment by DukeyToo** [comment]
@wmorgan Not for us - we do deploys of a whole new cluster of machines in that scenario.  It is a  zero-downtime in many cases - it is managed outside of linkerd though, and it is slow (hours instead of minutes).

**Comment by wmorgan** [comment]
Ok. Longer-term I think we'll support this via an API (see https://blog.buoyant.io/2017/05/24/a-service-mesh-for-kubernetes-part-x-the-service-mesh-api/ for some notes on this). In the short term, we could consider consider `/admin/offline`-style behavior for graceful shutdown.

**Comment by MrTravisB** [comment]
Any chance this can get another look? As long as linkerd config contains router and telemetry info and namerd config contains namer info this will be a problem. Namerd can at least be solved with a rolling update. Linkerd DaemonSet however result in actual downtime during a rolling update.

**Comment by wmorgan** [comment]
@MrTravisB PRs weclome :)

**Comment by zackangelo** [comment]
We've been struggling to get by without this for a while, but we're running enough traffic through linkerd now where it'd probably be worth trying to implement. 

@olix0r @adleong thoughts on trying to do this the same way HAProxy does it? 
https://www.haproxy.com/blog/truly-seamless-reloads-with-haproxy-no-more-hacks/

Basically we'd set `SO_REUSEPORT` on the server sockets which would let multiple PIDs bind and accept connections on same socket. We'd then change our restart behavior to bring up a 2nd linkerd, wait for it to be healthy, then gracefully shutdown the old linkerd. 

It looks like Netty has support for this sockopt on the kernels that support it (mainly linux 3.9+). I'm going to have to do some more digging on how we'd make this a configurable option on linkerd servers (or if we'd even want it to be configurable?). 

Thoughts?
