### ISSUE TITLE
namerd deployment documentation

### ISSUE THREAD

**Issue by rickardrosen** [linkerd/linkerd#1454]
I want to integrate linkerd with consul SD, and using namerd seems worth exploring.

Deploying and using linkerd seems fairly well documented, but I can't seem to find any docs regarding deployment of the namerd service.

Looking at the diagram it looks like the namerd process is not sidercared/co-processed but rather external to the containers or services.

In short I have the following questions:
- Can any number of namerd instances be started simultaneously?
- If so, does it make sense to keep one instance per container host (docker hosts in this case)?
- ...or does it make more sense to run the namerd process on the consul cluster nodes directly?
 
I'm hoping someone can nudge me in the right direction! =)

**Comment by esbie** [comment]
Since more than one person has asked for this, we should consider what kind of docs update would make this more clear.

We suggest deploying at least 3 instances of namerd in its own cluster. A basic namerd config is in https://blog.buoyant.io/2016/11/04/a-service-mesh-for-kubernetes-part-iv-continuous-deployment-via-traffic-shifting/ to get you started.

**Comment by wmorgan** [comment]
Agreed, namerd is generally undocumented, both deployment but also when you do / don't need it. 

@rickardrosen just to answer your immediate questions:
* Yes, any number of instances can be started simultaneously. All the hard coordination logic is deferred to the backing store; namerd is an API layer on top of that.
* You could run one per host but that's probably overkill. Our typical deployment is to run N >= 3 (usually N == 3) as a separate service somewhere.
* On consul cluster nodes vs as a separate thing: up to you!

Let's keep this ticket open in the meanwhile to track documenting this, as @esbie suggests.

**Comment by rickardrosen** [comment]
@wmorgan thanks!

If I understand things I should be able to fire up a few docker instances of namerd with consul as a backend and these containers should essentially be stateless?

**Comment by wmorgan** [comment]
@rickardrosen yes that's right. Consul does all the hard work. :)

**Comment by adleong** [comment]
https://linkerd.io/advanced/namerd/
