### ISSUE TITLE
disabling the usage reporter results in higher latency

### ISSUE THREAD

**Issue by stevej** [linkerd/linkerd#1476]
Adding the following to a linkerd config file run with linkerd 1.1.0 results in a latency hit

```
usage:
  enabled: false
```

Here are the quantiles from a million RPS test:

```
> quantile(l100_usage_default$latency_ms, c(0.5,0.9,0.95,0.99,0.999))
  50%   90%   95%   99% 99.9% 
   12    19    27    44    66 
> quantile(l100_usage_disabled$latency_ms,c(0.5,0.9,0.95,0.99,0.999))
  50%   90%   95%   99% 99.9% 
   14    27    36    54    78 
```
![latency_from_disabling_usage_reporter](https://user-images.githubusercontent.com/5834/27974259-18864310-6312-11e7-8b2d-a632a18c0a80.png)

**Comment by olix0r** [comment]
I can't even venture a guess at why this would be the case.

**Comment by stevej** [comment]
This test is invalid because it tested two different versions. I didn't notice that until I re-ran the numbers.
