### ISSUE TITLE
Hello-world example not working in k8s 1.6.4, coreos

### ISSUE THREAD

**Issue by pbagchi** [linkerd/linkerd#1483]
Filling issue per request from @wmorgan in slack.

I was following https://blog.buoyant.io/2016/10/04/a-service-mesh-for-kubernetes-part-i-top-line-service-metrics/.
The only change I had was in linkerd.yml file where instead of using LoadBalancer, I used NodePort as the type.
When I tried `http_proxy=$INGRESS_LB:4140 curl -s http://hello`, it didn't work - there was no response. I found [this](https://groups.google.com/forum/#!topic/linkerd-users/HtnuQarb3Z0) and using hello-world-legacy worked. 
The issue mentioned that hello-world-legacy was for older versions of Kubernetes, however, my kubernetes version in 1.6.4 on coreos. 
```
core@k8s-master-0 ~/kubernetes/linkerd-tutorials/part1 $ kubectl --version
Kubernetes v1.6.4+coreos.0
```
Here's the list of pods and the value of http_proxy on one of the hello pods:
```
core@k8s-master-0 ~/kubernetes/linkerd-tutorials/part1 $ kubectl get pod
NAME                READY     STATUS    RESTARTS   AGE
hello-359xq         1/1       Running   0          1d
hello-gfgm3         1/1       Running   1          1d
hello-qp88n         1/1       Running   1          1d
l5d-1v34l           2/2       Running   2          1d
l5d-57dc1           2/2       Running   0          1d
l5d-7fqng           2/2       Running   0          1d
l5d-8pm57           2/2       Running   2          1d
l5d-95h5w           2/2       Running   0          1d
l5d-fc216           2/2       Running   0          1d
l5d-g4qq0           2/2       Running   2          1d
l5d-hk4zm           2/2       Running   0          1d
l5d-l3zgv           2/2       Running   2          1d
l5d-r91mn           2/2       Running   0          1d
l5d-wpv41           2/2       Running   0          1d
l5d-xr5f6           2/2       Running   0          1d
l5d-zjrhk           2/2       Running   2          1d
linkerd-viz-zsnhr   2/2       Running   0          1d
world-v1-8tk1f      1/1       Running   0          1d
world-v1-kvx47      1/1       Running   1          1d
world-v1-nrprr      1/1       Running   0          1d
core@k8s-master-0 ~/kubernetes/linkerd-tutorials/part1 $ kubectl exec hello-359xq env | grep http_proxy
http_proxy=k8s-worker-9:4140 
```

**Comment by adleong** [comment]
Hi @pbagchi!

Our default configuration assumes that node names are addresses resolvable from a pod.  ie that you could log into a pod and run `ping k8s-worker-9` or `curl k8s-worker-9:4140`.  If this is not the case, then the hello-world-legacy configuration is more appropriate.

**Comment by adleong** [comment]
I'm closing this issue as inactive.  If you are still experiencing this issue, please reopen or create a post on discourse.linkerd.io
