### ISSUE TITLE
Strange gRPC hangs

### ISSUE THREAD

**Issue by vadimi** [linkerd/linkerd#1501]
Hello,

I'm having the following issue with my linkerd setup (version `1.1.1`). I have grpc client and service connected through linkerd. The client and linkerd are deployed to AWS, the service is deployed in our local environment and there is VPN between them. When I start all apps - everything works fine, linkerd handles everything correctly. But after some period of inactivity I start seeing the following errors in linkerd logs:

`
I 0713 03:11:32.758 UTC THREAD26 TraceId:4e34ebdfb4c1afa4: FailureAccrualFactory marking connection to "$/io.buoyant.rinet/50040/some_host" as dead. Remote Address: Inet(some_host/10.240.222.226:50040,Map())
`

`
E 0713 03:26:25.497 UTC THREAD24: [C L:/10.172.69.139:50798 R:some_host/10.240.222.226:50040] dispatcher failed
com.twitter.finagle.ConnectionFailedException: Connection timed out at remote address: some_host/10.240.222.226:50040. Remote Info: Not Available
	at com.twitter.finagle.ChannelException$.apply(Exceptions.scala:257)
	at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.exceptionCaught(ChannelTransport.scala:190)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
`

After that all client calls just hang (and eventually throw errors due to deadlines). After linkerd restart everything operates normally again. It looks like something in our network terminates tcp connections after some period of time and linkerd cannot detect that for some reason and keeps sending data over that broken connection.

**Comment by adleong** [comment]
Whoa, that's pretty weird.  It sounds like getting a TCP dump might be the best way to dig into what's going on and see if Linkerd is being properly informed of the connection state.

https://linkerd.io/overview/help/

**Comment by adleong** [comment]
Closing this as inactive.  If you're still having the issue, please reopen or post on discourse.linkerd.io
