### ISSUE TITLE
End to end tests intermittently fail due to timeouts

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd#1504]
I'm seeing a weird issue where the test `UsageDataTelemeterEndToEndTest ` seems to fail about 1/2 to 3/4ths of the time with the message:

```scala
operation timed out after 2.seconds (UsageDataTelemeterEndToEndTest.scala:23)
```

This is happening both on my dev machine and on CI – I've had to re-run several [spuriously-failed](https://circleci.com/gh/linkerd/linkerd/5301) [CI builds](https://circleci.com/gh/linkerd/linkerd/5302). Issue appears to persist both on my dev branch and on `master`.

**Comment by hawkw** [comment]
I've been rerunning this test against `master` over and over on my laptop and I don't think it's passed a single time, so far?

**Comment by esbie** [comment]
I ran `./sbt e2e:test` on master on my laptop a number of times and `UsageDataTelemeterEndToEndTest` passed every time (although other* tests intermittently failed)

* MuxEndToEndTest, HttpEndToEndTest, TlsEndToEndTest, RouterEndToEndTest

**Comment by hawkw** [comment]
@esbie issue renamed :)

**Comment by hawkw** [comment]
This seems like it's probably the same issue as/linked to #1225?
