### ISSUE TITLE
Don't require port to be an Int in HostColonPort

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#1511]
The HostColonPort matcher used by the hostportPfx and porthostPfx namers requires that the port be an Int.  For example `google.com:80`.  If we lift this restriction, then it would be able to accept port names like `foo.default:http`.  This would allow us to write dtabs that let users specify the destination port name in the Host/Authority header.  Ideally, we could update the standard k8s service mesh dtab to something like:

```
        /ph  => /$/io.buoyant.rinet ;                     # /ph/80/google.com -> /$/io.buoyant.rinet/80/google.com
        /k8s => /#/io.l5d.k8s.http ;                      # /k8s/default/http/foo -> /#/io.l5d.k8s.http/default/http/foo
        /host => /#/nsSvcPortToK8s ;                      # /host/default/foo/http -> /k8s/default/http/foo
        /hp  => /host/default ;                           # /hp/foo/http -> /host/default/foo/http
        /hp  => /$/io.buoyant.http.domainToPathPfx/host ; # /hp/foo.default/http -> /host/default/foo/http
        /ph  => /#/phToHp ;                               # /ph/http/foo.default -> /hp/foo.default/http
        /svc => /ph/80 ;                                  # /svc/foo.default -> /ph/80/foo.default
        /svc => /$/io.buoyant.porthostPfx/ph ;            # /svc/foo.default:http -> /ph/http/foo.default
```

Which allows users to specify both the destination port and destination namespace `foo.<namespace>:<port>` (and defaults to `default` and `80` for namespace and port respectively).

**Comment by hawkw** [comment]
@adleong what's a reasonable token to parse the port with? alphanumerics-only?

**Comment by adleong** [comment]
This is the regex that Kubernetes uses for port names: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L40
