### ISSUE TITLE
h2 success stat name does not match http success stat name

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#1521]
This is a follow-up to #1507. The new h2 stats code exports the success counter as "successes", but for consistency with finagle's metrics, I think it should be "success".

For instance, looking at a linkerd router running from latest master, I see this stat from an `http` router:

```
  "rt/http/server/0.0.0.0/7272/success" : 0,
```

And these stats for an `h2` router:

```
  "rt/h2/server/0.0.0.0/6262/request/stream/stream_successes" : 0,
  "rt/h2/server/0.0.0.0/6262/response/stream/stream_successes" : 0,
  "rt/h2/server/0.0.0.0/6262/stream/stream_successes" : 0,
  "rt/h2/server/0.0.0.0/6262/successes" : 0,
```

Looking at the same stats from the linkerd 1.1.2 release, I see:

```
  "rt/http/server/0.0.0.0/7272/success" : 0,
  "rt/h2/server/0.0.0.0/6262/success" : 0,
```

So for backwards compatibility, we need to switch all of those "successes" metrics back to "success".

**Comment by hawkw** [comment]
Agh. Grammar backwards compatibility. I'll fix that!
