### ISSUE TITLE
investigate upstream service not showing up in stats

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd#1533]
Following this example:
https://github.com/linkerd/linkerd-examples/tree/master/istio/helloworld-minikube

The "hello" service never appears in stats:
```bash
$ curl -s $(minikube ip):$(kubectl get svc l5d -o jsonpath="{.spec.ports[2].nodePort}")/admin/metrics/prometheus|grep hello|wc -l
       0
```

**Comment by esbie** [comment]
yeah I was noticing that also
