### ISSUE TITLE
Mistyping in docs?

### ISSUE THREAD

**Issue by ihac** [linkerd/linkerd#1535]
It's a trivial issue that I've found some reference links quite strange in Linkerd's docs.

Like section [k8s-configuration](https://linkerd.io/config/1.1.2/linkerd/index.html#k8s-configuration), it uses `(the k8s guide)[https://linkerd.io/doc/latest/k8s/] ` for an external reference. But AFAIK, `[the k8s guide](https://linkerd.io/doc/latest/k8s/)` should be the proper way to refer url in MD.

Same in [k8s-external-configuration](https://linkerd.io/config/1.1.2/linkerd/index.html#k8s-external-configuration), [k8s-namespaced-configuration](https://linkerd.io/config/1.1.2/linkerd/index.html#k8s-namespaced-configuration), [daemonset-kubernetes](https://linkerd.io/config/1.1.2/linkerd/index.html#daemonset-kubernetes).

I's not sure if I missed something or got it wrong. If so, hope it doesn't bother you much.

**Comment by wmorgan** [comment]
Thanks for pointing that out! Whoops!
