### ISSUE TITLE
NamerD rest api throws 400 bad request error with character encoding as part of content-type

### ISSUE THREAD

**Issue by jiju-git** [linkerd/linkerd#1536]
Namerd rest api gives 400 bad request error for PUT and POST requests.
This is happening when the content type header includes the character encoding. 
Content-Type=application/json;charset=UTF-8 results in bad request. When the content type was set to "application/json" with no encoding info it works. Including character encoding as part of content-type header is the default behavior of most rest clients, and UTF-8 is default encoding for application/json and anyone would expect it to work.

Log from my app
URI         : {}:http://localhost:4180/api/1/dtabs/eureka-service
Method      : {}:PUT
Headers     : {}:{Content-Type=[application/json;charset=UTF-8], Content-Length=[69]}
Request body: {}:[{"dst":"/$/inet/192.168.112.72/8080","prefix":"/svc/EUREKA-BRIDGE"}]
==========================request end================================================
org.springframework.web.client.ResourceAccessException: I/O error on PUT request for "http://localhost:4180/api/1/dtabs/eureka-service": Server returned HTTP response code: 400 for URL: http://localhost:4180/api/1/dtabs/eureka-service; nested exception is java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost:4180/api/1/dtabs/eureka-service

**Comment by wmorgan** [comment]
Thanks for the report, @jiju-git. We'll take a look!
