### ISSUE TITLE
Add support for host in Forwarded header

### ISSUE THREAD

**Issue by zackangelo** [linkerd/linkerd#1547]
Augment existing support for populating the `Forwarded` header (https://linkerd.io/config/1.1.2/linkerd/index.html#adding-the-forwarded-header) to add the `host` field. 

Relevant RFC: https://tools.ietf.org/html/rfc7239#section-5.3

**Comment by fantayeneh** [comment]
I think `host` is already being forwarded.

https://github.com/linkerd/linkerd/blob/1e2c1e42bf38477648361376523baee0bcc58bfb/router/http/src/main/scala/io/buoyant/router/http/AddForwardedHeader.scala#L26

**Comment by wmorgan** [comment]
@fantayeneh thanks. @zackangelo can you confirm you are not seeing the `host` field in this header in 1.1.3?
