### ISSUE TITLE
io.l5d.ingress fails to match a host with a port number

### ISSUE THREAD

**Issue by mejran** [linkerd/linkerd#1553]
The io.l5d.ingress identifier matches the full host including port number against the ingress resource hosts. The ingress resource however only contains hosts, no ports, so any requests with a port number fail to match. For example, if a request is sent to http://test.com:80 no ingress rule will match even if there is one for test.com.

**Comment by wmorgan** [comment]
@mejran thanks for the report. We'll take a look.

**Comment by adleong** [comment]
@esbie do you know if the ingress controller spec (such as it is) says anything about this?  Is there any mechanism to do anything with the provided port, or should it always be ignored?

**Comment by esbie** [comment]
I think @mejran might be right on this one. From https://kubernetes.io/docs/api-reference/v1.7/#ingressrule-v1beta1-extensions:
> Host is the fully qualified domain name of a network host, as defined by RFC 3986. Note the following deviations from the "host" part of the URI as defined in the RFC: 1. IPs are not allowed. Currently an IngressRuleValue can only apply to the IP in the Spec of the parent Ingress. 2. The : delimiter is not respected because ports are not allowed. Currently the port of an Ingress is implicitly :80 for http and :443 for https. Both these may change in the future.
