### ISSUE TITLE
Documentation still points to Dtab-local instead of l5d-dtab (low priority)

### ISSUE THREAD

**Issue by amanjeev** [linkerd/linkerd#1554]
Page: 
https://linkerd.io/overview/faq/ 

Section: 
HOW DOES LINKERD HANDLE SERVICE ERRORS?

Text:
When the configured namers cannot resolve a service to handle the request, linkerd responds with `400 Bad Request`. This could be caused by misconfiguration of linkerd, problems with service discovery, or by an incorrect `Dtab-local` header attached to the request.

I believe since `Dtab-local` is not supported, this should be changed to `l5d-dtab`.

**Comment by wmorgan** [comment]
@amanjeev thanks for pointing that out! We'll take care of it.

**Comment by klingerf** [comment]
@amanjeev Thanks for spotting this! Have deployed the docs site with a fix.
