### ISSUE TITLE
Very slow thrift call through linkerd

### ISSUE THREAD

**Issue by owensk** [linkerd/linkerd#1555]
I'm experiencing a very slow thrift call through linkerd. When I make the request directly against the thrift service, it returns in ~4 seconds. When I make the same request to linkerd, it takes ~270 seconds to complete.

The return value from the thrift services is ~2.3 million characters.

Any guidance or solutions would be greatly appreciated.

**Comment by wmorgan** [comment]
Thanks @owensk!

**Comment by adleong** [comment]
Would you mind providing your `:9990/admin/metrics.json` for an instance of linkerd that is experiencing this issue?  That will help us identify the problem.

As far as I know, thrift doesn't have any notion of streaming or chunked encoding.  This means that linkerd must buffer the entire message in memory.  It's possible this memory pressure is causing linkerd to do a lot of GC.

**Comment by owensk** [comment]
I have no idea why but I can't reproduce this anymore. I'll close and re-open if it arises again. Thanks.
