### ISSUE TITLE
io.l5d.ingress doesn't treat ingress path as prefix for matching

### ISSUE THREAD

**Issue by mejran** [linkerd/linkerd#1557]
It seems that io.l5d.ingress does a regex match against the path in the ingress yaml. However, the nginx implementation and most examples seem to assume that that a prefix match is done.
For example:
```  - host: test.com
    http:
      paths:
      - path: /
        backend:
          serviceName: test.com
          servicePort: http
```
Should match test.com/foo and not just test.com/.

**Comment by esbie** [comment]
Agreed that most implementations favor prefix match. We are attempting to adhere to the ingress spec https://kubernetes.io/docs/api-reference/v1.7/#ingressrule-v1beta1-extensions which states: 

> Path is an extended POSIX regex as defined by IEEE Std 1003.1, (i.e this follows the egrep/unix syntax, not the perl syntax) matched against the path of an incoming request. Currently it can contain characters disallowed from the conventional "path" part of a URL as defined by RFC 3986. Paths must begin with a '/'. If unspecified, the path defaults to a catch all sending traffic to the backend.

There's a pretty big back and forth at https://github.com/kubernetes/ingress/issues/555 on what the behavior should be.
