### ISSUE TITLE
Cannot create K8s ingress in GKE

### ISSUE THREAD

**Issue by perspectivus1** [linkerd/linkerd#1561]
I successfully created a Linkerd ingress controller on **Google Cloud Engine** based on instructions provided here: [https://buoyant.io/2017/04/06/a-service-mesh-for-kubernetes-part-viii-linkerd-as-an-ingress-controller/](https://buoyant.io/2017/04/06/a-service-mesh-for-kubernetes-part-viii-linkerd-as-an-ingress-controller/).

However, when I create an actual ingress that targets the above controller it fails to start. The Google Container Engine webpage provides input that it is creating the ingress, but assigns **no external IP**.

I have an **nginx ingress controller** on the same cluster (for which I successfully created ingresses), but the ingress that fails explicitly specifies the Linkerd ingress controller using the `kubernetes.io/ingress.class: "linkerd"` annotation.

Any ideas?

**Comment by esbie** [comment]
Hi @perspectivus1!

I don't totally understand your failure case yet. Is the problem that there's no address when `kubectl get ingress -o wide`? Syncing the ip is a neat feature that the k8s folks have implemented, but I'm not sure the other controllers have. Either way it's not required in order for the ingress controller to work. For that blog post we recommend using the ip of `kubectl get svc l5d`.

Let me know your thoughts

**Comment by esbie** [comment]
Also if this is how most folks want to use ingress controllers, we should add address syncing to linkerd

**Comment by perspectivus1** [comment]
Hi @esbie,

`kubectl get ingress -o wide` returns no external IP either:
```
NAME                HOSTS     ADDRESS         PORTS     AGE
nginx-ingress       *         35.189.224.x    80        1d
linkerd-ingress     *                         80        1d
```
I then used the l5d service's external address (`kubectl get svc l5d -n l5d-system`) on port 80. It works like a charm and forwards requests to the service configured in my ingress. Thanks for your help!

What I don't understand is how I can manage **multiple Linkerd ingresses** if a single IP address and a single port are assigned to all. Do you join the rules from all ingresses? What if there are conflicting rules? Do you do this even when the ingresses reside in different namespaces?

Thanks again

**Comment by esbie** [comment]
Good question. Yes, l5d looks over all ingresses in all namespaces (unless you specify a specific namespace in the l5d config). For conflicting rules, whichever one l5d arbitrarily finds first is the one it uses, order not guaranteed.

**Comment by adleong** [comment]
Hi @perspectivus1, does that clear everything up for you?  Should we close this issue?

**Comment by perspectivus1** [comment]
Everything is clear @adleong. Thanks.
