### ISSUE TITLE
Remove or improve statsd telemeter

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#1578]
The current statsd telementer makes a network call for every stat update which has serious performance problems.  This can be reduced by sampling, but this causes issues with the quality of data.  We should improve this by removing the ability to sample and replace it with some kind of buffering or we should remove this telemeter entirely in favor of the influxdb telemeter.

**Comment by hawkw** [comment]
Okay, now that  #1589 is merged, what else is necessary to consider this issue finished for 1.2.0?
