### ISSUE TITLE
Routing information over the http api to check maintenance state of hosts

### ISSUE THREAD

**Issue by danielBreitlauch** [linkerd/linkerd#1583]
We are using linkerd with a consul namerd. Host maintenance is managed by consul health checks.
At the moment we have to set a host to maintenance in consul and wait to be sure consul distributed the state and all linkerds picked it up. So atm we just wait seconds to ensure a host is not called anymore. Most of the time it is fast but sometimes we waited 10 seconds and it was not enough. Without any checks we have to prepare for the worst case witch is very long.

It is weird that there is no way to check linkerds routing information.
It would be a reasonable api extension to be able to check the set of routing hosts per service.

Thx,
Daniel

**Comment by adleong** [comment]
You should be able to see the address list through the dtab UI in the linkerd admin site.  This UI is powered by a json delegator UI that could also query directly.

**Comment by klingerf** [comment]
Also, if you're looking for a programatic was to verify this, you can use namerd's addr API to get all of the addresses for a given concrete name. More info here:

https://linkerd.io/config/1.1.3/namerd/index.html#get-api-1-addr-lt-namespace-gt

By way of example:

```
$ curl -s <namerd-ip>:4180/api/1/addr/default?path=%2F%23%2Fio.l5d.k8s%2Ftest%2Fhttp%2Fweb2 | jq -S .
{
  "addrs": [
    {
      "ip": "10.196.0.61",
      "meta": {
        "nodeName": "gke-..."
      },
      "port": 7272
    },
    {
      "ip": "10.196.6.168",
      "meta": {
        "nodeName": "gke-..."
      },
      "port": 7272
    },
    {
      "ip": "10.196.6.177",
      "meta": {
        "nodeName": "gke-..."
      },
      "port": 7272
    }
  ],
  "meta": {},
  "type": "bound"
}
```

**Comment by danielBreitlauch** [comment]
Sorry for not responding for some time. Asking namerd directly is indeed the solution I was not seeing.
I will try this soon. Thx for the hint.

**Comment by danielBreitlauch** [comment]
Sorry to reopen this but is there a way to ask the "namerd" bundled into linkerd via http too? Our setup consists of linkerds asking local consul agents. There is no need to have separate namerd instances.

**Comment by klingerf** [comment]
@danielBreitlauch Sorry for the delay. It's a bit less ergonomic, but you should be able to use the linkerd admin site's delegator.json endpoint to do something similar.

For instance, here's an identical request to my previous example, running against linkerd instead of namerd:

```
$ curl -H "Content-Type: application/json" -X POST -d '{"namespace":"outgoing","path":"/#/io.l5d.k8s/test/http/web2","dtab":""}' -s <linkerd-ip>:9990/delegator.json | jq -S .bound.addr
{
  "addrs": [
    {
      "ip": "10.196.3.233",
      "meta": {
        "nodeName": "gke-..."
      },
      "port": 7272
    },
    {
      "ip": "10.196.4.165",
      "meta": {
        "nodeName": "gke-..."
      },
      "port": 7272
    },
    {
      "ip": "10.196.3.193",
      "meta": {
        "nodeName": "gke-..."
      },
      "port": 7272
    }
  ],
  "meta": {},
  "type": "bound"
}
```

Am going to close this issue if that's ok by you.

**Comment by danielBreitlauch** [comment]
Yeah I am doing that now. It just does not feel like an official api. It is not documented and could go away/ change any time.

Thx for the example, I hope you consider adding it to the api.

On a side note, how is it supposed to be done to take routes out? Just assuming it happens instant? Or like we did before with sleeps? How often does linkerd check the consul agent btw?

**Comment by klingerf** [comment]
Linkerd uses Consul's blocking queries to subscribe to events as soon as they happen. So once an instance is removed from Consul, Linkerd should stop sending it traffic almost immediately.

If you have any follow-up questions, mind posting them to [discourse.linkerd.io](https://discourse.linkerd.io/)? We'll do a better job staying on top of them if you post them there.
