### ISSUE TITLE
Improve handling of Consul failures

### ISSUE THREAD

**Issue by Ashald** [linkerd/linkerd#1593]
## Filing a linkerd issue ##

Issue Type:

- [x] Bug report
- [x] Feature request

**What happened**:
Upon Consul failure (in this case, unexpected 403 response) Namerd produced Addr.Fail and wasn't able to resolve any names. Presumably Namerd saw valid responses from Consul before Consul entered failed state.

**What you expected to happen**:
1) Produce a human-friendly message about namer/dtab-store failures in logs/admin-ui rather than just stacktraces
2) Stabilize Consul-related activities so that once there was a successful result never return failure again

**Environment**:
Linkerd/Namerd `v1.1.3`

**Comment by hawkw** [comment]
I've opened a PR #1597 that stabilizes the Consul observation activities in `ConsulDtabStore`. Hopefully that should solve this issue.

If we want to start retrying 403s, I think that will require additional changes, but this should fix the issue for now?

**Comment by Ashald** [comment]
Thanks for a quick reply! I think #1597 is an important update (and I believe it can be improved even more ignoring "empty" replies to guard against possible situations of empty KV store during disaster recovery) but I think there is more to the issues than that.

First of all, pardon me, I forgot to mention that we use a custom Consul DtabStore that already has stabilization in place. I'm more concerned with namers.

To add to that, I think that it's safe to say that we expect that Linkerd/Consul will be properly configured and therefore anything but 2XX status codes most probably will highlight some misconfiguration. And rather than blindly retrying on such statuses it would help logging some human-friendly warnings so that operator will be able to spot the issues (misconfiguration or an issue with Consul) and resolve it more quickly.

**Comment by hawkw** [comment]
> First of all, pardon me, I forgot to mention that we use a custom Consul DtabStore that already has stabilization in place. I'm more concerned with namers.

Yeah, @adleong cleared that up for me [here](https://github.com/linkerd/linkerd/pull/1597#issuecomment-323467287); sorry about that, that was a misunderstanding on my end – I was afraid such a simple fix was probably too good to be true.

I'll start looking at making these changes to Consul namers.

**Comment by Ashald** [comment]
C'mon, there is nothing you should be sorry about. ;) That's in fact my fault not giving enough details within the original issue description. And having stabilization for DtabStore is also important IMO.
Thanks for looking into the issue!

**Comment by hawkw** [comment]
Hi again @ashald, I've added some modifications to PR #1597, hopefully it now makes the changes you originally requested?

**Comment by Ashald** [comment]
Great, thanks! I think this definitely should improve stability in face of Consul failures and give us more perspective on what exactly is happening! Looking forward to seeing this in next release. :)

**Comment by hawkw** [comment]
Okay, that's good to hear! 😀 Please let me know if there's anything that still needs additional changes; wasn't entirely sure what cases should _not_ fall back but I think I got it right?

**Comment by Ashald** [comment]
Well, as far as I understand, we shouldn't fall-bak only when we have a normal reply (200 OK with a proper index), everything else is safe to be considered untrustworthy.

**Comment by hawkw** [comment]
Yeah, what I meant was that in the current implementation, there are a few error cases, such as when Consul didn't return an index,
https://github.com/linkerd/linkerd/blob/e1002c6f1b11ca17d86dc24b1347aa685b1547e2/namer/consul/src/main/scala/io/buoyant/namer/consul/SvcAddr.scala#L82-L87
where we don't fall back to the last known-good state and still return `Addr.Failed`. I thought it seemed reasonable to only fall back from errors where it seems plausible that we could eventually resume observation safely?

**Comment by hawkw** [comment]
Hi @Ashald, just wanted to let you know I've merged https://github.com/linkerd/linkerd/commit/ef38c6ad20071a57294bae863923aae99572b5dd, it should be in Linkerd 1.2.0, which we're hoping to release by the 31st!
