### ISSUE TITLE
Consul: query service by specific health states

### ISSUE THREAD

**Issue by blacktoe** [linkerd/linkerd#1601]
The consul namer currently allows filtering nodes by a binary health status via the `useHealthCheck` parameter. Consul however has the concept of `passing`, `warning` and `critical` health statuses, the consul API can also be queried with the `any` state where no filtering is desired. 

A new parameter (like `healthCheckStatuses`?) could be added to the consul namer to allow more precise filtering of consul nodes by one or more health statuses, passed as a comma separated list.

We are particularly interested in this feature so that we can implement a fall back pool for a service which includes only nodes in the warning state (and not the critical state). See also https://discourse.linkerd.io/t/configuring-a-fall-back-consul-namer/243/3. 

The [consul API](https://www.consul.io/api/health.html) does not currently allow for listing a services nodes directly by health status, but does include the health statuses of each node in a separate top level array which could be used to filter results. Such an approach is used in [consul template](https://github.com/hashicorp/consul-template/blob/master/dependency/health_service.go) for example.

**Comment by adleong** [comment]
This sounds pretty reasonable to me!  Are you interested in submitting a PR for this?

**Comment by amitsaha** [comment]
Cool, we will work on it and submit a PR. Thanks @adleong

**Comment by amitsaha** [comment]
hey @adleong do you mind taking a look at the in progress PR please?

**Comment by hawkw** [comment]
Hi @amitsaha, @adleong is currently out of the office. I'm running point on the 1.2.0 release & would be happy to go over your PR if you like. When it's ready for review, we might want to loop @esbie in as well.

**Comment by hawkw** [comment]
And #1608 is merged! Thanks to @blacktoe for all the work on this!

**Comment by amitsaha** [comment]
Hi @hawkw thanks for the merge! Are we looking at this being in the upcoming 1.2.0 release?

**Comment by hawkw** [comment]
@amitsaha yes, that's correct! We're looking at cutting 1.2.0 by September 14th, if not before.

**Comment by amitsaha** [comment]
Thanks, perfect.
