### ISSUE TITLE
gRPC memory leak

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd#1613]
Refer to https://github.com/linkerd/linkerd/pull/1598#issuecomment-323488710. It looks like @adleong's commit 9deb5f7 revealed a memory leak in long-running gRPC streams. This leak was probably already there, but wasn't being reached because the flow-control issue fixed in 9deb5f7 was preventing us from reaching a state in which it could occur.

@klingerf did some investigation of a heap dump (see https://github.com/linkerd/linkerd/pull/1598#issuecomment-325006851) and it looks like unbounded `AsyncQueue` creation might be the cause of this leak. I talked it over w/ Alex & we suspect that long streams probably cause a future chain that gets longer and longer, probably  in `StreamProxy` or `BufferedStream`.

**Comment by hawkw** [comment]
Quick update: I'm about 80% certain I know what's going on. It looks like the issue is related to `BufferedStream`/`ClassifiedRetryFilter` interaction. `ClassifiedRetryFilter.apply()` has a lot of calls to `BufferedStream.fork()`, and it seems that as a long stream remains open, the `ClassifiedRetryFilter` repeatedly forks the stream, and the list of `_forks` (a `List[AsyncQueue[Frame]]`) on the `BufferedStream` grows and grows and grows. Note that forks are added to the list but never removed.

My guess is that we can probably find a fix by discarding old forks that are no longer in use?

**Comment by hawkw** [comment]
Another update: @adleong and I have been debugging this for the last 3 days; Alex found the leak yesterday:
> it’s a bug with `BufferedStream::fork::read` and `pull`
> if 2 forks read, that will cause 2 `pul`ls which will create 2 pollers
> when a frame arrives, it will be fanned out to both forks and the `fork::read` will be satisfied
> but 1 poller will remain on the underlying q
> then, presumably, both forks will call read again
> and now you have 3 pollers on the underlying q

I have a preliminary version of a fix: 6ce546c77cff03585ea64c99e54a4c34e2594352

**Comment by wmorgan** [comment]
Nice.
