### ISSUE TITLE
High CPU load and many netty errors for Namerd 1.1.3

### ISSUE THREAD

**Issue by robb-foster-ck** [linkerd/linkerd#1627]
Issue Type:

- [ X] Bug report
- [ ] Feature request

**What happened**:
We have deployed Namerd 1.13 in K8S 1.7, in a container running CentOS 7.2.1511 (3.10.0-327.36.3.el7.x86_64) and Java 8 (OpenJDK Runtime Environment (build 1.8.0_141-b16), OpenJDK 64-Bit Server VM (build 25.141-b16, mixed mode)).  In a cluster which is not serving any traffic yet, with 13 Linkerd instances, we have noticed that the JVM is taking about 2 vCPUs on a pretty consistent basis, and the following error is showing up very frequently in the logs

> WARN 0907 14:59:49.169 UTC finagle/netty4-27: Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@2f00ccf2.

We are using the io.l5d.namerd interpreter.

**What you expected to happen**:
Very low CPU utilization and not to see the above error in the log.

**How to reproduce it (as minimally and precisely as possible)**:
From Googling, it seems to be related to the combination of netty4 as packaged in Namerd and our version of the OS.

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files: 1.1.3
- Platform, version, and config files (Kubernetes, DC/OS, etc): K8S 1.7
- Cloud provider or hardware configuration:  72 vCPU/128GB physical server
- OS:  CentOS 7.2.1511 (3.10.0-327.36.3.el7.x86_64)
- Java: Java 8 (OpenJDK Runtime Environment (build 1.8.0_141-b16), OpenJDK 64-Bit Server VM (build 25.141-b16, mixed mode))
- Namerd Interpreter: io.l5d.namerd

**Comment by wmorgan** [comment]
@robb-foster-ck thanks for the report! We'll take a look.

**Comment by adleong** [comment]
We believe that this is due to a kernel bug as described in https://github.com/netty/netty/issues/2616

Can you try testing this on one of the following kernel versions to see if this resolves the issue?
* 3.10.45
* 3.14.10
* 3.15

**Comment by robb-foster-ck** [comment]
Sorry, but I can't in any practical way.  The version of the OS that we are running is the only one that's approved for use in production and development.

**Comment by adleong** [comment]
I don't think there's much we can do about this from our side.
