### ISSUE TITLE
prometheus: export Finagle stats as Prometheus histograms

### ISSUE THREAD

**Issue by ccmtaylor** [linkerd/linkerd#1643]
## Filing a linkerd issue ##

Issue Type:

- [ ] Bug report
- [x] RFC
- [x] Feature request

**What happened**:

I configured namerd to use prometheus for telemetry, and `stat`s were exported as prometheus summaries, which means that I can't meaningfully aggregate latency quantiles across linkerd instances.

**What you expected to happen**:

I'd like linkerd to expose stats as histograms (maybe in addition, or as a replacement for the existing summaries), so that it is possible to aggregate quantiles for dashboards.

**Anything else we need to know?**:

The prometheus docs [explain](https://prometheus.io/docs/practices/histograms/#quantiles) fairly thoroughly explain the tradeoffs between histograms and quantiles. At SoundCloud, we've almost completely moved away from summaries for latency measurements, since they don't allow for meaningful aggregation across instances (e.g. the average of all 99th percentiles of service instances a very different thing than the 99th percentile latency across all instances).

I took a look at the code, and afaict, this should be possible, since finagle internally keeps stats as a `Seq[BucketAndCount]`. Turning each `BucketAndCount` into a time-series with appropriate names and labels would expose the Histogram in a form that prometheus can use.

**Environment**:
- linkerd/namerd version, config files: v1.2.1
- Platform, version, and config files (Kubernetes, DC/OS, etc): n/a
- Cloud provider or hardware configuration: n/a

**Comment by adleong** [comment]
Yes, I think you are correct that this can be derived from the raw histograms (BucketAndCount).  Are you interested in working on this feature?

**Comment by ccmtaylor** [comment]
sorry for the late response.

> Are you interested in working on this feature?

I could spend some time on this tomorrow if you're interested. It looks like it might be a chunk of work, so I wanted to ask before I go ahead. I haven't looked into how many buckets finagle keeps internally for each stat, so this might cause the count of timeseries to increase quite a lot.

Do you think I should replace the summaries by histograms? This will break dashboards that expose the summaries (though those dashboards probably aren't showing what people think they are, unless there's only one linkerd instance).
