### ISSUE TITLE
Support `source.xyz` Istio attributes

### ISSUE THREAD

**Issue by pcalcado** [linkerd/linkerd#1645]
In order to support Mixer features, Linkerd must augment request with many of the `source.` attributes from [Istio's vocabulary](https://istio.io/docs/reference/config/mixer/attribute-vocabulary.html).

### Must have:
- `source.ip`
- `source.service`
- `source.name`
- `source.labels`

### Should have:
- `source.namespace`
- `source.domain`
- `source.uid`
- `source.user`

**Comment by pcalcado** [comment]
Some prior art here: https://github.com/linkerd/linkerd/issues/1410#issuecomment-309193732

**Comment by adleong** [comment]
It was my (perhaps incorrect) understanding that the mixer could fill in (some? all?) of these attributes if given souce.uid.  source.uid should be sufficient to derive the other attributes using the k8s api.
