### ISSUE TITLE
prometheus: Add the ability to configure a prefix

### ISSUE THREAD

**Issue by amitsaha** [linkerd/linkerd#1655]
Issue Type:

- [ ] Bug report
- [x] Feature request

Currently, the prometheus metrics are of the form `namer:xx` and `rt:xx` and so on. Based of this [discourse discussion](https://discourse.linkerd.io/t/prometheus-metrics-namespacing/297/5), it would be useful to have a configurable prometheus metrics prefix. The default will still be no prefix.

**Comment by wmorgan** [comment]
@amitsaha thanks for filling this!

**Comment by amitsaha** [comment]
@wmorgan happy to have been able to get my colleague to work on a PR as well :)

**Comment by hawkw** [comment]
Closed by #1657
