### ISSUE TITLE
Good tutorial for k8s needed (including namerd)

### ISSUE THREAD

**Issue by sokoow** [linkerd/linkerd#1659]
Issue Type:

- [ ] Bug report
- [X ] Feature request

**What happened**:
So, it's very hard to navigate your docs and get a working k8s implementation with namerd. I tried 
applying these two yamls together:

```
kubectl apply -f https://raw.githubusercontent.com/linkerd/linkerd-examples/master/k8s-daemonset/k8s/linkerd.yml
kubectl apply -f https://raw.githubusercontent.com/linkerd/linkerd-examples/master/k8s-daemonset/k8s/namerd.yml
```

But that doesn't respect namerctl created dtabs. It only sees the ones created in the configmap. Document it a bit more please. 

Also, a bit more explanation is needed on how dtabs work, where do you put hostnames, service names and so on, it's still a bit confusing. 

**What you expected to happen**:

Have a working yaml that deploys linkerd+namerd and namerctl could create working dtab files.

**How to reproduce it (as minimally and precisely as possible)**:

Install it youtself or give it to somebody who sees it for first time.

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files: latest
- Platform, version, and config files (Kubernetes, DC/OS, etc): kube 1.7.3
- Cloud provider or hardware configuration: aws

**Comment by sokoow** [comment]
FYI i'm referring to this article: https://buoyant.io/2016/11/04/a-service-mesh-for-kubernetes-part-iv-continuous-deployment-via-traffic-shifting/?__hstc=249056664.9082b41d8a52a00a19ebd6f40131c9a2.1507023894299.1507023894299.1507023894299.1&__hssc=249056664.5.1507023894299&__hsfp=584158062

**Comment by esbie** [comment]
Hi @sokoow! Thank you for your suggestion. The article you linked to instructs users to deploy `linkerd-namerd.yml`, not `linkerd.yml`. If you have additional issues or feature requests for linkerd-examples (or the blog posts that reference them), please file them in the linkerd-examples repo https://github.com/linkerd/linkerd-examples
