### ISSUE TITLE
io.l5d.mesh interpreter fails to resolve daemonset transformer

### ISSUE THREAD

**Issue by esbie** [linkerd/linkerd#1660]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
See https://discourse.linkerd.io/t/linkerd-namerd-cni-setup-help/313 for additional details.
In a linkerd + namerd CNI setup, namerd successfully resolves the daemonset transformer, but linkerd does not.

namerd:
![screen shot 2017-10-02 at 4 52 26 pm](https://user-images.githubusercontent.com/41829/31145636-2c81104a-a839-11e7-8629-a80750ffbbe3.png)
linkerd:
![screen shot 2017-10-02 at 4 52 15 pm](https://user-images.githubusercontent.com/41829/31145641-2fee17c8-a839-11e7-84e1-e2f4c9903f95.png)

**Environment**:
- linkerd/namerd version, config files: v 1.2.1
- Platform, version, and config files (Kubernetes, DC/OS, etc): kubernetes + flannel CNI

**Comment by esbie** [comment]
Confirmed via https://discourse.linkerd.io/t/io-l5d-mesh-issue/318/3 that the issue does not occur with the io.l5d.namerd.http interpreter

**Comment by ethanrubio** [comment]
Is there anything that I can provide to get a better diagnose? I'd like to see if I can do anything to push this forward since the `io.l5d.mesh` API becomes the preferred method soon.

**Comment by hawkw** [comment]
Hi @ethanrubio, I was actually just sitting down to start looking into this issue. I'll definitely let you know if there's anything else we need from you!

**Comment by siggy** [comment]
@ethanrubio we've posted a working linkerd+namerd+daemonset+cni+tls configuration example. would it be possible to test this configuration against your environment to confirm it works?

https://github.com/linkerd/linkerd-examples/blob/master/k8s-daemonset/k8s/linkerd-namerd-cni-tls.yml

**Comment by ethanrubio** [comment]
@siggy is there a corresponding namerd config that goes with this linkerd config?

**Comment by siggy** [comment]
@ethanrubio yup: https://github.com/linkerd/linkerd-examples/blob/master/k8s-daemonset/k8s/namerd.yml
