### ISSUE TITLE
Update CONTRIBUTING.md regarding CLA requirement

### ISSUE THREAD

**Issue by caniszczyk** [linkerd/linkerd#1686]
Since linkerd is part of CNCF, the CLA requirement is optional.

I'd recommend just removing the mention in the CONTRIBUTING.md:
https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md

At a minimum, all we need is ALv2+DCO

**Comment by wmorgan** [comment]
I'm ok with this.

**Comment by wmorgan** [comment]
Specifically, I'm ok with switching to DCOs entirely.
