### ISSUE TITLE
H2 "open_streams" metric may not be accurate

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd#1693]
I've noticed a potential issue with the `open_streams` metric reported by HTTP/2 routers. It seems that the way this is currently implemented, the metric will also count reset and failed streams as "open", which seems potentially incorrect.

The `open_streams` metric is currently implemented as a gauge that samples the size of the `streams` map:
https://github.com/linkerd/linkerd/blob/b5cd1c168873d1d668b5f4fdbd729a44122135d2/finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala#L42-L44

When a stream is closed successfully, it is removed from the map, which is fine:
https://github.com/linkerd/linkerd/blob/b5cd1c168873d1d668b5f4fdbd729a44122135d2/finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala#L65-L69

However, when a stream is reset or fails, rather than removing from the map, it is _replaced_ with a stream in a reset/failed state:
https://github.com/linkerd/linkerd/blob/b5cd1c168873d1d668b5f4fdbd729a44122135d2/finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala#L71-L97
These replacements don't effect the size of the `streams` map which is sampled by the `open_streams` metric, meaning that reset and failed streams will continue to count as "open".

Is this correct behaviour for this metric? Do we want streams in reset or failed states to count as "open"?

**Comment by hawkw** [comment]
cc @adleong, @olix0r

**Comment by hawkw** [comment]
I think we probably don't want to count these streams as "open", and we could easily change the `open_streams` gauge to only count streams in the `StreamOpen` state. We might want to also add new metrics to track streams in the reset and failed states.

I'd be happy to make these changes but would like a confirmation that the current behaviour is incorrect first.

**Comment by adleong** [comment]
`tracked_streams` might be a better name for this gauge.  I think we want to keep this as it indicates how many streams we are tracking in the hashmap.  

Adding gauges for streams in particular states (open, reset, etc) sounds good in theory, but I worry about needing to iterate over the entire hashmap to compute this...

**Comment by hawkw** [comment]
> `tracked_streams` might be a better name for this gauge.  I think we want to keep this as it indicates how many streams we are tracking in the hashmap.  

Do you think renaming this gauge at this point would be a compatibility issue?

> Adding gauges for streams in particular states (open, reset, etc) sounds good in theory, but I worry about needing to iterate over the entire hashmap to compute this...

We could, at least, count streams in each state in one iteration, but I'm fairly sure even a single iteration is still costlier than `.size()`...alternatively, we could add counters that are updated when a stream transitions from one state into another, and have the gauges sample those counters?

**Comment by adleong** [comment]
Closed until we decide what we want to do.
