### ISSUE TITLE
Kubernetes ingress memory leak

### ISSUE THREAD

**Issue by sgrankin** [linkerd/linkerd#1694]
Issue Type:  Bug report

**What happened**:
Slow memory leak while using linkerd as a kubernetes ingress.

**What you expected to happen**:
No memory leak :)

**How to reproduce it (as minimally and precisely as possible)**:
Appears to consistently reproduce in our configuration:
- Linkerd 1.3.1 docker image (original & modified with updated java8 jdk)
- Configuration as in https://gist.github.com/sgrankin/360471146e7c273fecce48e859d498e5 and with several 'default' and non-'default' namespace ingress  configurations inside kubernetes. 
- Not sure if there's a particular trigger since the start of the leak appears slow.
- Typical heap size (note the Y axis is logarithmic): 
<img width="855" alt="screen shot 2017-11-07 at 17 03 05" src="https://user-images.githubusercontent.com/1015617/32520549-62ced2e8-c3de-11e7-9ce8-d3ec2340969a.png">

**Anything else we need to know?**:
- I have heap dumps of a few hours after process start and then 15 hours later that I can provide (directly—I don't think there's anything confidential in there but would prefer to avoid posting publicly).
- Via the heap dumps, I believe a (the?) potential leak may be  here: https://github.com/linkerd/linkerd/blob/35db8060ae4d3398381b5bed285f1c42b3956cb6/k8s/src/main/scala/io/buoyant/k8s/Watchable.scala#L294 I think the closure is holding a reference to `this`, which is holding a reference to `as: AsyncStream[T]`, keeping the full stream in memory.  (Not sure why the growth is non-linear though...)

**Environment**:
- linkerd/namerd version, config files:
1.3.1, config attached above.
- Platform, version, and config files (Kubernetes, DC/OS, etc):
v1.7.6+coreos.0
- Cloud provider or hardware configuration:
AWS

**Comment by hawkw** [comment]
Hi @sgrankin, thanks for reporting! I think the theory you've proposed seems quite possible, but would love to take a look at your heap dumps to confirm.

**Comment by sgrankin** [comment]
@hawkw emailed to you @buoyant.io.  Thanks!

**Comment by sgrankin** [comment]
@hawkw I ended up trying out some fixes; the AsyncStream seems to have been the leaked object, but the leak I theorized was not the (only?) one.  I couldn't track down how it was leaking though, so I hacked up a non-AsyncStream based variant of the watch code.  It's been running for 2 days on our dev deployment with steady heap usage and no stale endpoint issues (so far).

The change is here: https://github.com/sgrankin/linkerd/commit/a454fa0dc6edfec3781e1237343e9a1ad5802c42
If this looks like a good approach to you, I can clean it up and submit a PR.

**Comment by hawkw** [comment]
Hi @sgrankin, once again, thanks for your help. We'll take a look at your changes and get back to you on that as soon as possible!

**Comment by wmorgan** [comment]
@sgrankin yes, thank you for digging into this!

**Comment by adleong** [comment]
@sgrankin this looks great!  I've skimmed your change and I agree with the general approach.  I'd like to review it in greater detail so if you could create a PR against Linkerd that would be greatly appreciated and we can go through the nitty-gritty details there.
Thank you!!!

**Comment by sgrankin** [comment]
Sorry for the delay—just finally got some time this weekend to clean up the diff.  PR opened at #1714

**Comment by hawkw** [comment]
🙌 thanks @sgrankin!
