### ISSUE TITLE
Ability to see how linkerd would resolve a request

### ISSUE THREAD

**Issue by obeattie** [linkerd/linkerd#1732]
Issue Type:

- [ ] Bug report
- [x] Feature request

As [discussed in Slack briefly](https://linkerd.slack.com/archives/C0JV5E7BR/p1507222184000355) before, it would be extremely useful (I'd go so far as to say it's very important for us) to be able to query linkerd to see how it would route a request for a given path.

We have seen a number of cases where linkerd has gotten in a "stuck" state and continues to route requests to endpoints which have been replaced. This is possibly related to #1730 but I am not _sure_ if they're the same. In any case that is not what this ticket is about. Until we can track down the root cause of these issues, we have built a script that can identify _which_ linkerd pods are in such a state and restart them. To do this, it currently relies on using the `/delegator.json` endpoint of the admin UI, but I understand this bypasses the local caches linkerd would normally use when routing traffic. #1731 also prevents this from being completely useful.

What I would like is some form of endpoint I can call with a path, and it will return the set of addresses to which it may route such a request.

Again sorry for the brief description; very happy to elaborate on this further if helpful.

**Comment by wmorgan** [comment]
We have a really cool idea for this that @dadjeibaah is working on now. Stay tuned!

**Comment by wmorgan** [comment]
@obeattie we're going to blow your mind with this
