### ISSUE TITLE
sbt compile errors: MixerClient reference shadowing

### ISSUE THREAD

**Issue by aidansteele** [linkerd/linkerd#1735]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:

I cloned linkerd from this repo, ran `./sbt compile` and got [this](https://gist.github.com/aidansteele/866e1268229b1944725cf181a9a6df0c) output. Ctrl+f for `[error]` to see the errors. The juiciest appears to be:

```
[error] /Users/aidan/dev/oss/linkerd/istio/src/main/scala/io/buoyant/k8s/istio/IstioRequestAuthorizerFilter.scala:6: imported `MixerClient' is permanently hidden by definition of object MixerClient in package istio
[error] import io.buoyant.k8s.istio.mixer.MixerClient
```

**What you expected to happen**:

I expected `linkerd` to be built. Interesting enough, I read further down the BUILD.md instructions and realised that `./sbt linkerd/assembly` is the command I _actually_ wanted. This command worked without any errors and produced a working executable.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ git clone https://github.com/linkerd/linkerd.git
$ cd linkerd
$ ./sbt compile
```

**Anything else we need to know?**:

**Environment**:
Commit 7c8499b9a0738211c9b160e9683479dbc2f78dee
MacOS 10.13.1

Happy to provide more info, try different PRs, etc if needed :)

**Comment by adleong** [comment]
Hi @aidansteele 

I'm able to run `./sbt compile` on current Linkerd master (7c8499b9a0738211c9b160e9683479dbc2f78dee) and I don't see the error that you reported.

Have you tried running `./sbt clean`?  Could there potentially be something wrong in your ivy cache?

**Comment by adleong** [comment]
Closing this since I can't repro.
