### ISSUE TITLE
Jaeger tracing support

### ISSUE THREAD

**Issue by jippi** [linkerd/linkerd#1771]
Issue Type:

- [ ] Bug report
- [x] Feature request

**What happened**:

Wanted to use Jaeger Tracing, only support for Zipkin

**What you expected to happen**:

Jaeger Tracing support

**How to reproduce it (as minimally and precisely as possible)**:

- ??? 
- profit

**Anything else we need to know?**:

**Comment by wmorgan** [comment]
Hi @jippi! Thanks for the feature request! You might be interested in the discussion that's happening on #1079.

**Comment by jippi** [comment]
@wmorgan thanks! we currently use `linkerd-zipkin` to get tracing data into jaeger, it seem to work pretty nice :)

**Comment by adleong** [comment]
Closing as a duplicate of #1079
