### ISSUE TITLE
Namerd thrift interface keeps watches open indefinitely

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#1779]
Once Namerd watches a name, that observation is cached and kept open indefinitely.  Once Namerd has no pending requests for a name, it is safe for Namerd to move that observation to its inactive cache, however, the inactive cache has no TTL.

We should add a configurable TTL to the inactive cache such that unwatched observations are eventually closed.

**Comment by mmrozek** [comment]
@adleong, what should be the default value of the TTL? I could take care of this issue.

**Comment by adleong** [comment]
@mmrozek good question.  the most conservative thing to do would be to make this configurable with the default being no TTL (ie make the default the same as the current behavior).  Once a few users are running in prod using TTLs and don't experience any issues, we could then consider changing the default.  What do you think about that?

**Comment by mmrozek** [comment]
I am not sure if it is the best option. Users rely on default values (especially when they don't know which value should be used). It could cause hard to find performance issues (users may don't realise that they have the problem in this place). Perhaps better idea is to set default to some long (but not infinite) time. Ex. if ttl unit will be seconds, we could set default to 604800 - 1 week. What do you think?

**Comment by mmrozek** [comment]
I made a PR - https://github.com/linkerd/linkerd/pull/1923. @adleong if you decide that you prefer different behaviour by default, I will change that.

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd/pull/1923
