### ISSUE TITLE
Pass Stack.Params to DtabStore plugins

### ISSUE THREAD

**Issue by edio** [linkerd/linkerd#1800]
Issue Type:

- [ ] Bug report
- [x] Feature request

**What happened**:
Right now it is not possible to record any stats from `DtabStore` plugins, because namerd doesn't pass `Stack.Params` to `DtabStoreConfig.mkDtabStore`

**What you expected to happen**:
`Stack.Params` should be passed as with the rest of plugins

PR is to follow shortly

**Comment by deebo91** [comment]
Thanks for creating the issue @edio. Looking forward to your PR
