### ISSUE TITLE
x-forwarded-client-cert doesn't forward SAN DNS names, only one URIName record is forwarded

### ISSUE THREAD

**Issue by shakti-das** [linkerd/linkerd#1802]
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [ ] Bug report
- [x] Feature request

**What happened**:
x-forwarded-client-cert containing SAN DNS names are not forwarded, only URIName records are forwarded. 

https://github.com/linkerd/linkerd/blob/b390b5b16549ccb2d34d00480390364517ab9246/router/base-http/src/main/scala/io/buoyant/router/http/ForwardClientCertFilter.scala#L30

The ForwardClientCertFilter explicitly filters out SAN name types other than URI. For mutual TLS authentication, we would also need the DNS name type related alt name to be forwarded as part of XFCC SAN string: http://www.docjar.com/html/api/sun/security/x509/GeneralNameInterface.java.html

**What you expected to happen**:
SAN DNS name type values should also be passed on as part of the SAN string in the XFCC header.

**How to reproduce it (as minimally and precisely as possible)**:
Create a certificate which has DNS="something" entries in the SAN. Run the ForwardClientCert and you can notice.

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files:
- Platform, version, and config files (Kubernetes, DC/OS, etc):
- Cloud provider or hardware configuration:
1.3.5

**Comment by deebo91** [comment]
Thanks for filing this issue @shakti-das! We will take a look.

**Comment by shakti-das** [comment]
I was working on a PR for the fix but had a basic doubt on what value is expected when there are multiple GenericName type values in the SAN. Like:

Subject Alternative Name:
URI: https://xyz.com DNS: xyz.com DNS: www.xyz.com 

Right now the XFCC SAN values only picks up "https://xyz.com" as it's a single name type. But if we want to add multiple types here, then should it be something like:

XFCC: Hash:....;SAN:https://xyz.com,xyz.com,www.xyz.com;....
or
XFCC: Hash:....;SAN:"URI:https://xyz.com,DNS:xyz.com,DNS:www.xyz.com"

**Comment by briansmith** [comment]
@shakti-das Thanks for reporting this. I agree with you that it would be good to expose the DNS Name entries too.

Basically, the X-Forwarded-Client-Cert feature was implemented as described in https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers.html#x-forwarded-client-cert, which also doesn't consider the DNS name entries.

In order to extend it to support DNS names, I suggest that we include one `DNS:<dns name>` entry for each DNS name. If there are three DNS names, a.example.com, b.example.com, c.example.com, then the header field value would include "DNS:a.exmaple.com;DNS:b.example.com;DNS:c.example.com" in addition to the other information.

 WDYT?

**Comment by shakti-das** [comment]
Agree, NameType:NameValue combination provides better details than just NameValue list.

**Comment by briansmith** [comment]
In the case where the certificate has both URI names, we have to use "SAN:" instead of "URI:" for backward compatibility, e.g. SAN:https://example.com;DNS:a.example.com;DNS:b.example.com.

**Comment by shakti-das** [comment]
Like this?
`
before x-forwarded-client-cert: Hash=468ed33be74eee6556d90c0149c1309e9ba61d6425303443c0748a02dd8de688;SAN=https://example.com  

after x-forwarded-client-cert: Hash=468ed33be74eee6556d90c0149c1309e9ba61d6425303443c0748a02dd8de688;SAN="SAN:https://example.com;DNS:example.com"
`

It still won't be backward compatible as earlier anyone using the SAN field from XFCC would have just parsed a single string assuming one URI value. Now, extracting the same SAN string from XFCC would return a delimiter separated string which needs to be parsed again.

The SAN in the actual certificate file looks like:
            X509v3 Subject Alternative Name: 
                URI:https://buoyant.io, DNS:buoyant.io

Will it be better for the future to keep it in the same format in XFCC SAN value as well?

**Comment by shakti-das** [comment]
Since this was replicated from envoy behavior, raised an issue for envoy as well to get some more clarity:  https://github.com/envoyproxy/envoy/issues/2535

**Comment by briansmith** [comment]
> after x-forwarded-client-cert: `Hash=468ed33be74eee6556d90c0149c1309e9ba61d6425303443c0748a02dd8de688;SAN="SAN:https://example.com;DNS:example.com"`

No, I'm thinking it should be like this:

```
Hash=468ed33be74eee6556d90c0149c1309e9ba61d6425303443c0748a02dd8de688;SAN=https://example.com,DNS=example.com.
```

Basically "SAN=" would prefix each URI and "DNS=" would prefix each DNS name. Presumably we could have "Email=" for email addresses too.

**Comment by shakti-das** [comment]
But that would make it part of the XFCC value and not SAN as SAN itself is an element of the XFCC value.

**Comment by briansmith** [comment]
> But that would make it part of the XFCC value and not SAN as SAN itself is an element of the XFCC value.

I understand that. Basically, we never should have named "SAN" as "SAN" but instead should have named it "URI". I'm suggesting we take "SAN" to mean "URI" for backward compatibility only, and use "DNS" for DNS names (and "Email" for email names). It's inconsistent but I think this is the clearest design given backward compatibility concerns. If you have an alternate suggestion, I am open to it.

**Comment by shakti-das** [comment]
From a backward compatibility point of view, it's definitely the cleanest way. And considering XFCC is a non-standard header we should be able to capture this information in doc and comments.

My thought was if we can specify the value to intuitively convey that the DNS entries are part of Subject Alternate Name in the actual certificate, that would have been great. 

Did a quick search in Envoy on config attribute verify_subject_alt_name, it seems envoy is considering all the SAN entires as a single list irrespective of type: https://github.com/envoyproxy/envoy/search?p=1&q=verify_subject_alt_name&type=&utf8=%E2%9C%93

**Comment by shakti-das** [comment]
@briansmith The backward compatible approach that you proposed looks best, should I send out a PR for this which has DNS entries as part of the XFCC? Like:

`Hash=468ed33be74eee6556d90c0149c1309e9ba61d6425303443c0748a02dd8de688;SAN=https://example.com;DNS=example.com`

**Comment by briansmith** [comment]
The advantage of implementing the Envoy approach is that any code that works with Envoy would automatically work with Linkerd. The disadvantage of the Envoy approach is that every application that tries to parse the SAN fields has to implement a check "is this a DNS name or a URI or an email address or what?"

The advantage of the way I propose is that such parsing is avoided. The disadvantage of the approach I suggested is that any app transitioning from Envoy -> Linkerd would have  to be modified to do do it a slightly different way.

@adleong @wmorgan What do you think?

**Comment by wmorgan** [comment]
I'd rather have the better approach (that doesn't require parsing). A smooth Envoy -> Linkerd transition is not very important to the project IMO.

**Comment by wmorgan** [comment]
@shakti-das would you be interested in submitting a PR following @briansmith's proposed format?

**Comment by shakti-das** [comment]
Sorry for the late response, was out on vacation. I will send out a PR for it soon. Thanks.
