### ISSUE TITLE
dtabFile bug

### ISSUE THREAD

**Issue by xiaobin** [linkerd/linkerd#1803]
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
namerd version: 1.3.5, config files:

Here is the configuration for dtab I am using:

````
namers:
- kind: io.l5d.fs
  rootDir: linkerd/examples/io.l5d.fs

routers:
- protocol: http
  interpreter:
    kind: io.l5d.fs
    dtabFile: linkerd/examples/example.dtab
  servers:
  - port: 4140`
example.dtab is：
`/svc/service-auth => /$/inet/LHSJ-master/9999;
/http/*/* => /svc;
```
`
view page is：
![image](https://user-images.githubusercontent.com/2536602/35788511-725fbb22-0a70-11e8-9cb3-5dbf2bd19684.png)

I open the url：http://127.0.0.1:4140/service-auth/demo，info：
`No hosts are available for /svc/127.0.0.1:4140, Dtab.base=[], Dtab.local=[]. Remote Info: Not Available`

but，i using：
`
```
admin:
  port: 9990

routers:
- protocol: http
  label: http-proxy
  identifier:
    kind: io.l5d.path
    segments: 1
    consume: true
  dtab: |
    /svc/service-auth => /$/inet/LHSJ-master/9999;
    /http/*/* => /svc;
  servers:
  - ip: 0.0.0.0
    port: 2100
```
`
this everything is normal。
now I feel：

![image](https://user-images.githubusercontent.com/2536602/35788585-0c27b480-0a71-11e8-9ca0-6fac2e3cbc33.png)

**Comment by xiaobin** [comment]
Sorry, the problem is with me.
I modified the configuration：
`
namers:
- kind: io.l5d.fs
  rootDir: linkerd/examples/io.l5d.fs

routers:
- protocol: http
  identifier:
    kind: io.l5d.path
    segments: 1
    consume: true
  interpreter:
    kind: io.l5d.fs
    dtabFile: linkerd/examples/example.dtab
  dtab: |
    /svc/service-media=>/$/inet/LHSJ-slave/9999;
    /http/*/*=>/svc
  servers:
  - port: 4140

telemetry:
- kind: io.l5d.prometheus
- kind: io.l5d.recentRequests
  sampleRate: 1.0
  capacity: 10
- kind: io.l5d.tracelog
  sampleRate: 1.0
  level: TRACE
`
this work ok！

**Comment by wmorgan** [comment]
Glad to hear you got it working. Closing this issue.
