### ISSUE TITLE
Continued memory leaks in 1.3.4 and 1.3.5

### ISSUE THREAD

**Issue by yennifehrrr** [linkerd/linkerd#1804]
Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:
Upgrading linkerd's grpc-runtime lib from 1.1.2 to 1.3.4 (even 1.3.5) for use in making calls to an upstream gRPC service is causing memory leaks. In a 30 minute load test, with netty's leak detection turned to advanced (sampling 1% of buffers), I see 3 separate memory leak stack traces. 

**What you expected to happen**:
gRPC client calls should emit no memory leaks.

**How to reproduce it (as minimally and precisely as possible)**:
My gRPC client creation looks as follows (config object is obv specific to my needs):
```
    val stack = H2.client
      .withLabel(config.name)
      .withMaybeTlsSupport(config.useTls, config.tlsValidation, config.address, config.tlsCertificates)
      .configured(FailFastFactory.FailFast(enabled = config.failFast))
      .withTransport.connectTimeout(config.connectionTimeout)
      .withRequestTimeout(config.requestTimeout)
      .withKeepAlive(config.keepAlive)
      .withSession.maxIdleTime(config.connectionMaxIdleTime)
      .withSessionQualifier.consecutiveFailuresFailureAccrual(config.markDeadAfterFailCount, Stream.continually(config.markForDeadDuration))
      .withResponseClassifier(config.responseClassifier)
      .configured(Transporter.HttpProxy(config.maybeHttpProxy, None))
      .configured(Transporter.SocksProxy(config.maybeSocksProxy, None))

    val rawClient = ClientBuilder()
      .name(config.name)
      .dest(s"${config.address.getHostString}:${config.address.getPort}")
      .stack(stack)
      .timeout(config.timeout)
      .retryPolicy(config.retryPolicy)
      .reportTo(ClientStatsReceiver)
      .daemon(true)
      .build()
```

And my usage of the h2 client is strictly for unary to unary rpc calls:
```
private val rpc = UnaryToUnary(h2Client, path, requestCodec, responseCodec)
private val rpcAsService = FinagleService.mk[Req, Rsp](rpc(_))
```

**Anything else we need to know?**:
A standard load test is 30 minutes, bouncing between 120 req/sec and 20 req/sec to the upstream gRPC service. 
[sample-memory-leak.log](https://github.com/linkerd/linkerd/files/1690223/sample-memory-leak.log)

**Environment**:
- Version: `grpc-runtime` v. `1.3.4` and `1.3.5`
- Platform/Cloud Provider/Hardware: AWS EC2. Image: `CentOS 6 x86_64`. Instance Type: `m3.xlarge`

**Comment by yennifehrrr** [comment]
NOTE: This may be TMI, but coupling this linkerd version upgrade with `com.twitter.finagle.netty4.trackReferenceLeaks` set to `true` (to track reference leaks in metrics), resulted in 0 memory leaks; but corrupted the incoming protobuf intermittently, resulting in various `InvalidProtocolBufferException`s, so perhaps there is some correlation between whatever is causing the invalid protobufs when the flag is turned on, and the memory leak when it is turned off.

**Comment by wmorgan** [comment]
@yennifehrrr thanks for the detailed report! Bummer we still have a few leaks floating around. We'll dig into this.

**Comment by adleong** [comment]
Thanks for this report @yennifehrrr!  There are some additional pieces of information that will help us track this down:

1. Are you able to isolate the exact Linkerd version where the leak started?  There have a been a number of large changes/releases between 1.1.2 and 1.3.4 so pinpointing this to an exact release where the leak was introduced would be very helpful.
2. Do you see any symptoms other than the Netty leak reports?  Do you see RSS grow over time?  Are you able to capture a heap dump when memory usage is severely high?
3. Are you able to produce a stand-alone program that we could compile and run that exhibits the issue?

**Comment by adleong** [comment]
Hi @yennifehrrr, are you able to collect and provide any of the information above?

**Comment by yennifehrrr** [comment]
Hi @adleong , sorry this dropped off my list for a bit, but yes.
1. I upgraded directly from 1.1.2 to 1.3.3/4/5, and all of them suffered from memory leaks, but did not try the versions in between 1.1.2 and 1.3.3.
1. I can capture a heap dump, will do when I get a spare moment.
1. A standalone app will be a little difficult, as I'd also need a gRPC endpoint that serves protobuf out in the open for you to test against. We generally don't provide this kind of data to third parties.

**Comment by pcalcado** [comment]
@yennifehrrr 
Thanks! We're waiting for the heap dump, but I think that on (3) @adleong was suggesting that you have a small app that reproduces the issue that we can run in our test lab. Maybe if you stip out all of your business logic from this particular applications and make them just blindly passthrough data?

**Comment by yennifehrrr** [comment]
@pcalcado yup working on that heapdump. Once again, tricky because it may have confidential info in there... 😕 but I'll analyze first and see if it's safe to pass over. For the standalone app, this particular issue is when we use linkerd to make gRPC calls for protobuf payloads. So to reproduce, I think we'd need both an app making the calls and gRPC service open to the public serving these requests.

**Comment by yennifehrrr** [comment]
Hi @pcalcado @adleong I've taken a heap dump, but realized that all of our client secrets are in there and I don't have clearance to provide to 3rd parties. Is there anything else I can do to help?

**Comment by siggy** [comment]
Noting `UnpoolHandler` is in the stack trace of each leak access record. We should consider this part of the code for removal.

**Comment by adleong** [comment]
Hi @yennifehrrr, we have fixed a number of h2 memory leaks in version 1.3.7.  Can you try again with the latest version and let us know if you still see this?  Thanks!

**Comment by yennifehrrr** [comment]
@adleong oh great! The past load test looks promising; I'm going to keep one going for about half a day to a day, to make sure. Will keep you posted!

**Comment by yennifehrrr** [comment]
Hi @adleong It's looking a lot better, but running the load test for ~24 hrs, I'm still seeing a subtle climb:
<img width="1319" alt="screen shot 2018-04-17 at 10 33 00 am" src="https://user-images.githubusercontent.com/7081755/38895249-80c4d3d0-425d-11e8-8495-9596468886e8.png">
I'm going to keep the load test running overnight to see if the growth is continuous. This looks pretty different from prod where memory is flat over the same time interval.
<img width="1197" alt="screen shot 2018-04-17 at 10 35 48 am" src="https://user-images.githubusercontent.com/7081755/38895322-c2bbf278-425d-11e8-8feb-b335fc9f7ddb.png">

**Comment by yennifehrrr** [comment]
Confirmed continuous memory increase over a ~two-day period. It does seem somewhat better than before.

**Comment by adleong** [comment]
Ah, darn. Thanks for checking, @yennifehrrr.  One more thing to try: can you try setting the JVM flags from this PR: https://github.com/linkerd/linkerd/pull/1889

**Comment by yennifehrrr** [comment]
Sorry, I forgot to update! I tried with the flags for about a day, and didn't see much difference, but this issue is hard to spot because memory creeps up slowly. I'll try running the load test for the whole weekend this weekend.

**Comment by chrisgoffinet** [comment]
@yennifehrrr The memory usage graph, is that JVM heap usage or RSS usage?

**Comment by adleong** [comment]
I'm going to close this ticket due to inactivity.  Please re-open if you are still experiencing these memory leaks when running with the new settings.

**Comment by yennifehrrr** [comment]
Hi! Sorry I've been MIA, this was not on my radar for awhile. I re-ran for a whole wknd with the flags, and the results look promising tho not conclusive. When we get a chance I'm going to release this upgrade with the flags to a canary server and let it run for a day to see how things are. Will update then, thank you for your hard work on this!

**Comment by yennifehrrr** [comment]
Hi @adleong et al, just to put the final nail in this, we just canaried this over the weekend with the flags mentioned, and it looks great! We're pushing a full deployment today. Thanks to everyone for their help!!

**Comment by adleong** [comment]
Awesome!!!
