### ISSUE TITLE
namerd admin interface hangs

### ISSUE THREAD

**Issue by hynek** [linkerd/linkerd#1812]
## Filing a Linkerd issue ##

Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:

I’ve configured namerd to work with consul and expose a namer service as mesh and it works: the dtab I set in `namerd/dtabs/default` appears instantly in all linkerds.

I can also fetch `/admin/ping`:

```
$ curl https://10.6.180.250:9991/admin/ping
pong
```

And metrics (both `/admin/metrics.json` and my configured prometheus) work too.

However if I want to fetch the admin interface itself, it hangs forever:

```
curl -v https://10.6.180.250:9991/
*   Trying 10.6.180.250...
* Connected to 10.6.180.250 (10.6.180.250) port 9991 (#0)
* found 149 certificates in /etc/ssl/certs/ca-certificates.crt
* found 687 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: XXX (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=XXX
* 	 start date: Mon, 12 Feb 2018 10:34:40 GMT
* 	 expire date: Sat, 11 Feb 2023 10:35:08 GMT
* 	 issuer: CN=XXX
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET / HTTP/1.1
> Host: 10.6.180.250:9991
> User-Agent: curl/7.47.0
> Accept: */*
>
```

There are **no** log entries neither in the consul nor in the namerd log.

**What you expected to happen**:

Not to hang? :)

**How to reproduce it (as minimally and precisely as possible)**:

Configure as I did, curl /.

**Anything else we need to know?**:

Until I got the consul configuration right, the interface *did* load with an error telling me that no namespaces were found (as a side note, the documentation around namerd and its integration with linkerd and other services was not quite up to the level of what I got used to from linkerd's docs – I needed additional guidance otherwise I’d still be stumbling).

**Environment**:
- linkerd/namerd version, config files:

namerd.yml:

```yaml
---
admin:
  port: 9991
  ip: 10.6.180.250
  tls:
    certPath: /etc/ssl/certs/XXX.crt
    keyPath: /etc/ssl/private/XXX.pkcs8


namers:
  - kind: io.l5d.consul
    includeTag: true
    useHealthCheck: true


storage:
  kind: io.l5d.consul
  token: XXX
  readConsistencyMode: stale
  pathPrefix: /namerd/dtabs


interfaces:
  - kind: io.l5d.mesh
    ip: 10.6.180.250
    port: 4321


telemetry:
  - kind: io.l5d.prometheus
    path: /admin/metrics/prometheus
    prefix: namerd_
```

namerd: 1.3.5
consul: 1.0.1

Querying consul works without any problems:

```
$ curl -v -H "x-consul-token: XXX" "http://localhost:8500/v1/kv/?recurse=true"
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8500 (#0)
> GET /v1/kv/?recurse=true HTTP/1.1
> Host: localhost:8500
> User-Agent: curl/7.47.0
> Accept: */*
> x-consul-token: XXX
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Consul-Index: 137959041
< X-Consul-Knownleader: true
< X-Consul-Lastcontact: 0
< Date: Tue, 13 Feb 2018 14:34:53 GMT
< Content-Length: 524
<
* Connection #0 to host localhost left intact
[{"LockIndex":0,"Key":"namerd/dtabs/","Flags":0,"Value":null,"CreateIndex":137788444,"ModifyIndex":137788444},{"LockIndex":0,"Key":"namerd/dtabs/default","Flags":0,"Value":"L3N2YyAgICAgICAgICAgICAgID0+IC8kL2lvLmJ1b3lhbnQuaHR0cC5kb21haW5Ub1BhdGg7CgovYWcvdm0vbDVkL3Byb2QgICAgPT4gLyMvaW8ubDVkLmNvbnN1bC8ubG9jYWwvZW52LXByb2Q7Ci9hZy92bS9sNWQvb3RlICAgICA9PiAvIy9pby5sNWQuY29uc3VsLy5sb2NhbC9lbnYtb3RlOwovYWcvdm0vbDVkL3N0YWdpbmcgPT4gLyMvaW8ubDVkLmNvbnN1bC8ubG9jYWwvZW52LXN0YWdpbmc7","CreateIndex":137788454,"ModifyIndex":137801542}]
```

- Platform, version, and config files (Kubernetes, DC/OS, etc):

Ubuntu Xenial, since this is an isolation namerd issue, the rest shouldn’t matter.

- Cloud provider or hardware configuration:

LXC running on metal. More than 1 GB of RAM free.

**Comment by deebo91** [comment]
@hynek thanks so much for filing this detailed report. These kinds of issues make debugging linkerd/namerd much easier. We will take a look at this issue as soon as we can. Also, if you have any suggestions on where you would love to see more detail in namerd's documentation, please do let us know!

**Comment by hynek** [comment]
JFTR, just tested with consul 1.0.6 and the problem persists.

**Comment by wmorgan** [comment]
@hynek we're taking a look at this

**Comment by klingerf** [comment]
Hey @hynek, thanks for such a detailed report! I've been trying to reproduce this issue locally, and haven't been able to exactly. But I did notice something in your setup that seems potentially problematic, based on the contents of your consul KV store:

```
[
  {
    "CreateIndex": 137788444,
    "Flags": 0,
    "Key": "namerd/dtabs/",
    "LockIndex": 0,
    "ModifyIndex": 137788444,
    "Value": null
  },
  {
    "CreateIndex": 137788454,
    "Flags": 0,
    "Key": "namerd/dtabs/default",
    "LockIndex": 0,
    "ModifyIndex": 137801542,
    "Value": "L3N2YyAgICAgICAgICAgICAgID0+IC8kL2lvLmJ1b3lhbnQuaHR0cC5kb21haW5Ub1BhdGg7CgovYWcvdm0vbDVkL3Byb2QgICAgPT4gLyMvaW8ubDVkLmNvbnN1bC8ubG9jYWwvZW52LXByb2Q7Ci9hZy92bS9sNWQvb3RlICAgICA9PiAvIy9pby5sNWQuY29uc3VsLy5sb2NhbC9lbnYtb3RlOwovYWcvdm0vbDVkL3N0YWdpbmcgPT4gLyMvaW8ubDVkLmNvbnN1bC8ubG9jYWwvZW52LXN0YWdpbmc7"
  }
]
```

The first key in that list is "namerd/dtabs/", which is also the folder where the second key, "namerd/dtabs/default", is located. When testing locally, if I create the first key first and the second key second, then namerd's admin UI doesn't hang, but it does tell me that there are no namespaces found:

![image](https://user-images.githubusercontent.com/9226/36238223-24549bb2-11b6-11e8-81ff-a9043c85f70a.png)

If I use the consul API to delete the first key:

```
$ curl -X DELETE http://localhost:8500/v1/kv/namerd/dtabs/
true
```

And then bounce namerd, its admin interface successfully loads the namespace from the second key:

![image](https://user-images.githubusercontent.com/9226/36238419-55dc84aa-11b7-11e8-81d9-c6b777e78347.png)

Am not positive you're experiencing the same issue, but can you try applying the same fix in your setup (delete the `namerd/dtabs/` key and restart namerd)?

---

When playing around with this locally, I setup a docker-compose env that might be useful. You can find it here:

[consul-issue.tar.gz](https://github.com/linkerd/linkerd/files/1726287/consul-issue.tar.gz)

There are some instructions for reproducing the issue in the README.

**Comment by Ashald** [comment]
Wow, @klingerf, great catch! I tried to repeat your steps and was able to reproduce the issue exactly as  @hynek reported it! In my case, as well as in @hynek's case, Consul has ACLs enabled with default policy set to "deny-all" and ACL permissions set to
```
key "namerd/dtabs/" { policy = "write" }
```
which may explain the difference in behavior we see.

Let me see if I can figure out what causes it...

**Comment by hynek** [comment]
I can confirm that deleting everything and creating `namerd/dtabs/default` in one step fixes the problem for me. Thanks everyone and good luck fixing. :)

**Comment by Ashald** [comment]
The cause of the issue as well as the fix turned out to be embarrassingly simple and _it looks like_ this issues has been in place since first implementation of the store that I pushed almost 2 years ago. 😞

**Comment by klingerf** [comment]
@hynek Thanks for confirming that the workaround works -- that's great! And huge thanks to @Ashald for putting together the fix. I tested the changes from #1816 in my local repro, and they do indeed fix the issue that I was seeing.

**Comment by wmorgan** [comment]
W00t!
