### ISSUE TITLE
no backoff in consul namer on unexpected exceptions if there's previous state and on ConnectionFailedException

### ISSUE THREAD

**Issue by edio** [linkerd/linkerd#1821]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:

Every name in consul namer is backed by an infinite loop in `SvcAddr`, that obtains connection to consul and long polls for updates.
Some of the erros are handled by `infiniteRetryFilter` inside of buoyant consul API, and in this case back-off is used.

Other errors are handled in infinite loop inside of `SvcAddr` and do NOT have any back-offs.

In production environment this means that in case of specific intermittent issues with host where namerd is running or with consul agent it talks to, namerd will retry without back-off, potentially causing more harm to the infrastructure.

**What you expected to happen**:

Back-off are used for all type of retries

**How to reproduce it (as minimally and precisely as possible)**:

```
--- a/namer/consul/src/test/scala/io/buoyant/namer/consul/ConsulNamerTest.scala
+++ b/namer/consul/src/test/scala/io/buoyant/namer/consul/ConsulNamerTest.scala
@@ -686,4 +686,23 @@ class ConsulNamerTest extends FunSuite with Awaits {
     assert(stats.counters.get(Seq("service", "updates")).contains(1))
     assert(stats.counters.get(Seq("lookups")).contains(1))
   }
+
+  test("Namer doesn't use back-off") {
+    class TestApi extends CatalogApi(null, "/v1") {
+      override def serviceNodes(
+        serviceName: String,
+        datacenter: Option[String] = None,
+        tag: Option[String] = None,
+        blockingIndex: Option[String] = None,
+        consistency: Option[ConsistencyMode] = None,
+        retry: Boolean = false
+      ): Future[Indexed[Seq[ServiceNode]]] = Future.exception(Failure("failed", new ConnectionFailedException()))
+    }
+    val stats = new InMemoryStatsReceiver
+    val namer = ConsulNamer.untagged(testPath, new TestApi(), new TestAgentApi("acme.co"), stats = stats)
+    @volatile var state: Activity.State[NameTree[Name]] = Activity.Pending
+
+    namer.lookup(Path.read("/dc1/servicename/residual")).states respond { state = _ }
+  }
+
 }
```

This is of course synthetic. On practice `ConnectionFailedException` is thrown if new port can't be allocated to make a request to consul.

Also any exception thrown by `ConsulApi`/`HealthApi` will cause retry without back-off if there is previously known state in `SvcAddr`.

**Environment**:
- linkerd/namerd version, config files:
1.3.4

**Comment by adleong** [comment]
Thanks for filing this!  In other situations like this, we apply the backoff in the Var.async loop by calling `Future.sleep(backoff).flatMap { _ => loop(index) }` instead of just `loop(index)`.  See `ThriftNamerClient` for an example of this.  We should do this in `SvcAddr` too.

**Comment by edio** [comment]
@adleong, I prepared a PR, that uses the same backoff stream that is used inside ConsulApi.

There's a still an edge case, if system flaps between "consul returned 500", and "cannot allocate socket for outbound connection", then we'll be stuck in the first values of the backoffs Stream (and by default it's 1ms --- effectively, no backoff).

Ideal solution, I believe, would be to handle all retries in a single place. However, this means exception being thrown (means expensive stack unwinding) on every bad response from consul, which may become a problem on its own if we observe many names and consul goes down. So with that, ConsulApi should be changed to return `Either` of parsed response or status code if response is different from expected (without attempting to parse the resposne in this case), so that client could decide whether to retry or not.

**Comment by adleong** [comment]
I think the idea solution would be to actually remove the `infiniteRetryFilter` altogether and use the `loop` cases to handle those retries.  A very similar thing was done in this PR: https://github.com/linkerd/linkerd/pull/1703/files

**Comment by edio** [comment]
@adleong that's what I implied, by saying "handling in single place".

But, as I mentioned, this means exception being thrown on every 5xx from consul because json parsing will be attempted. And I'd prefer to avoid that.

So some ConsulApi redesign is also required.

Or am I missing something?
