### ISSUE TITLE
Linker-to-linker architecture in DC/OS falsely responding 200

### ISSUE THREAD

**Issue by jacob-go** [linkerd/linkerd#1834]
Issue Type:
Bug report.

**What happened**:
I've deployed a linker-to-linker architecture in my DC/OS environment, you can read in more detail and see config files here: https://discourse.linkerd.io/t/upgrading-linkerd-as-a-proxy-on-dc-os/516

In a short manner: I have a linkerd-internal that acts as a proxy for each agent in the cluster and a linkerd-external service that acts as a LB for the cluster. Wherever I want to reach some other cluster, my dtab supports a shift that passes me through the external Linkerd to that cluster. 

The problem started when I've made different tests trying to find out what would happen when we'll restart the internal proxy without doing anything to any of the services sitting on those agents, nor touching the external Linkerd. So basically I've created a situation where the different services in the cluster are healthy but not all instances of every service has a proper proxy to communicate, and every service is trying to reach something in another cluster (through the external Linkerd).  

I've seen a strange behaviour, where the external Linkerd responds with 200 status (meaning - the request passed to the other cluster) but with empty body (meaning - something happened the prevented external Linkerd to pass the body to the proxy). I see that about 2% of responses are without body. 

**What you expected to happen**:
Because linkerd-internal, linkerd-external and every other service in the cluster all have multiple instances - I would expect that I'll get all responses with a proper status and a proper body. Or, at least, I would expect that if one of the linkers can't write a body - I would get a 500 status to allow retries to happen (now I can't even test the retries feature, since all statuses are 200). 

**How to reproduce it (as minimally and precisely as possible)**:
two full config files are here: https://discourse.linkerd.io/t/upgrading-linkerd-as-a-proxy-on-dc-os/516?u=jacobgo

**Anything else we need to know?**:
https://discourse.linkerd.io/t/upgrading-linkerd-as-a-proxy-on-dc-os/516

**Environment**:
- linkerd/namerd version, config files: 
[dev_ssl_internal copy.txt](https://github.com/linkerd/linkerd/files/1759414/dev_ssl_internal.copy.txt)
[dev_ssl_external (1) copy (1).txt](https://github.com/linkerd/linkerd/files/1759415/dev_ssl_external.1.copy.1.txt)

- Platform, version, and config files (Kubernetes, DC/OS, etc): DC/OS
- Cloud provider or hardware configuration: AWS

**Comment by siggy** [comment]
@jacob-go Appreciate all the detail. We're still digging into this on our side.

The tighter the reproduction case you can provide, the faster we can solve this. Ideally a specific set of config files and commands that reliably demonstrate the issue. For example:
```bash
dcos marathon app add linkerd-interal.json
dcos marathon app add linkerd-external.json
dcos marathon app add testapp.json

while true; do curl -X POST "http://marathon.mesos:8080/v2/linkerd/restart?force=true" -H "accept: application/json"; sleep 30; done &

http_proxy=$NODE:3128 curl -o /dev/null -s -w "%{http_code}\n" http://testapp
```
... or, something like a self-contained docker-compose environment would be even better.

**Comment by jacob-go** [comment]
Sent you via mail (the one on your profile here) all the details @siggy

**Comment by adleong** [comment]
Hi @jacob-go are you still investigating this?  Are you able to provide us with a more self-contained reproduction environment so that we can repro and help investigate?

**Comment by jacob-go** [comment]
Sorry I didn't updated, we were aggressively testing all of the layers to see what's really going on.

**Comment by adleong** [comment]
@jacob-go does https://github.com/linkerd/linkerd/issues/1887 capture the issues the you're running into?  can this issue be closed?

**Comment by jacob-go** [comment]
I want to make the same restart tests with the proper graceful timeout
config, I'll let you know in the next 48 hours

**Comment by adleong** [comment]
Great!
