### ISSUE TITLE
Can't seem to discover namerd using multiple Zookeeper hosts

### ISSUE THREAD

**Issue by etotten** [linkerd/linkerd#1835]
Issue Type:
- [ ] Bug report
- [x] Feature request

**What happened**:
We have namerd announcing itself to a zookeeper ensemble; thus, we'd like to point linkerd at namerd using all of the hosts in the ensemble and have it manage the handling of bad zookeeper hosts efficiently.

The current work-around is to have a round robin DNS entry, but this will slow things down in the case of a bad zookeeper host.

Here is an example config snippet that works, but just has one host...
```
  interpreter:
    kind: io.l5d.namerd
    dst: "/$/com.twitter.serverset/myhost01:2181/discover/yada/yada/namerd:thrift"
```
When I tried comma separated to allow for many...
```
  interpreter:
    kind: io.l5d.namerd
    dst: "/$/com.twitter.serverset/myhost01:2181/discover/yada/yada/namerd:thrift,/$/com.twitter.serverset/myhost02:2181/discover/yada/yada/namerd:thrift,/$/com.twitter.serverset/myhost03:2181/discover/yada/yada/namerd:thrift"
    namespace: haproxy-ext
```

...I get this error...
```
end of input expected but ',' found at '/$/com.twitter.serverset/yada...
com.fasterxml.jackson.databind.JsonMappingException: end of input expected but ',' found at '/$/com.twitter.serverset/myhost01:2181/discover/yada/yada/namerd:thrift,/$/com.twitter.serverset/myhost02:2181/discover/yada/yada/namerd:thrift,/$/com.twitter.serverset/myhost03:2181/discover/yada/yada/namerd:thrift'
 at [Source: java.io.StringReader@741f8dbe; line: 52, column: 10] (through reference chain: io.buoyant.linkerd.Linker$LinkerConfig["routers"]->com.fasterxml.jackson.module.scala.deser.BuilderWrapper[0]->io.buoyant.linkerd.protocol.HttpConfig["interpreter"]->io.buoyant.namerd.iface.NamerdInterpreterConfig["dst"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:1313)
	at io.buoyant.config.ConfigDeserializer.catchMappingException(Parser.scala:27)
	at io.buoyant.config.types.PathDeserializer.deserialize(PathDeserializer.scala:11)
	at io.buoyant.config.types.PathDeserializer.deserialize(PathDeserializer.scala:8)
```
Also I tried a list, but that doesn't work either...
```
  interpreter:
    kind: io.l5d.namerd
    dst:
      - "/$/com.twitter.serverset/myhost01:2181/discover/yada/yada/namerd:thrift"
      - "/$/com.twitter.serverset/myhost02:2181/discover/yada/yada/namerd:thrift"
      - "/$/com.twitter.serverset/myhost03:2181/discover/yada/yada/namerd:thrift"
```

**What you expected to happen**:
I'd expect to provide a list like like this:
```
  interpreter:
    kind: io.l5d.namerd
    dst:
      - "/$/com.twitter.serverset/myhost01:2181/discover/yada/yada/namerd:thrift"
      - "/$/com.twitter.serverset/myhost02:2181/discover/yada/yada/namerd:thrift"
      - "/$/com.twitter.serverset/myhost03:2181/discover/yada/yada/namerd:thrift"
```

**How to reproduce it (as minimally and precisely as possible)**:
Include the above interpreter configs with valid hostnames/ports in an otherwise valid linkerd config and then try and start linkerd.

**Environment**:
- linkerd/namerd version, config files:
linkerd 1.2.1 (rev=33cbb9b6c4fac89d27a94ff34197026aa28577ea) built at 20170914-171152
Finagle version 6.45.0 (rev=fadc80cdd804f2885ebc213964542d5568a4f485) built at 20170609-103217

- Platform, version, and config files (Kubernetes, DC/OS, etc):
Mesos/Aurora open source

- Cloud provider or hardware configuration:
AWS

**Comment by adleong** [comment]
Hi @etotten!  Can you try something like this in your Linkerd config:

```
namers:
- kind: io.l5d.serversets
  zkAddrs:
  - host: myhost01
    port: 2181
  - host: myhost02
    port: 2181
  - host: myhost03
    port: 2181

routers:
- interpreter:
    kind: io.l5d.namerd
    dst: "/#/io.l5d.serversets/discover/yada/yada/namerd:thrift
  ...
```

I believe this will use the locally configured serversets namer to discover Namerd, and then use the namers configured in Namerd to do all request routing.  

Please give that a try and let me know how it goes!

**Comment by etotten** [comment]
Howdy @adleong. Yes, it worked. Using the namers config for the zk hosts and removing the host from the interpreter dst did allow us to use all the zk boxes w/o making a round robin DNS entry.

Thanks!

**Comment by olix0r** [comment]
🎈

**Comment by vw75** [comment]
Hi @etotten would you mind sharing how to configure namerd announcing itself to a zookeeper ensemble? I am trying to do implement the same scenario but not able to figure out the configuration for namerd service to announce itself to zk ensemble.
