### ISSUE TITLE
Consul errors cause entire request to time out

### ISSUE THREAD

**Issue by MrTravisB** [linkerd/linkerd#1836]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
When a Consul route is found, if the datacenter does not exist, the entire request times out.

Sample dtabs:

    /consul => /#/io.l5d.consul/real-dc;
    /consul => /#/io.l5d.consul/nonexistent-dc;
    /srv => /consul;

**What you expected to happen**:
Given the above dtabs, I'd expect that when `/#/io.l5d.consul/nonexistent-dc/[SERVICE]` is evaluated it will fail because `nonexistent-dc` doesn't exist. But it should then evaluate `/#/io.l5d.consul/real-dc/[SERVICE]` which should succeed. Instead it times out and doesn't evaluate any rules after the failing one.

**How to reproduce it (as minimally and precisely as possible)**:
Use above dtab. Replace `real-dc` with the name of your existing datacenter.

**Anything else we need to know?**:
Nothing in the namerd logs except failed requests to Consul trying to retrieve the nonexistent datacenter.

**Environment**:
- linkerd/namerd version, config files:
linkerd & namerd 1.3.5

Consul namer config

    kind: io.l5d.consul
    host: x.x.x.x
    port: 8500
- Platform, version, and config files (Kubernetes, DC/OS, etc):
Kubernetes 1.9.2
Consul 0.6.4
- Cloud provider or hardware configuration:
Google Cloud

**Comment by adleong** [comment]
I haven't had a chance to look into this in depth but my instinct here would be to update the Activity to `NameTree.Neg` when we get a "dc doesn't exist" error but continue to run the polling loop in case the DC ever comes into existence.
