### ISSUE TITLE
Chunked encoding is being sent to HTTP 1.0 clients

### ISSUE THREAD

**Issue by hynek** [linkerd/linkerd#1847]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:

I’ve been explained, that a proper Proxy should always speak HTTP 1.1 up and down, no matter what the client speaks.

However: I’ve run into the case that when a client, that I have no control over (in my case ddclient) requests HTTP 1.0, the request is transformed into an HTTP 1.1 request and the upstream server takes advantage of having HTTP 1.1 and serves a chunked response that the client can’t handle.

**What you expected to happen**:

Either

- don't modify the request (like e.g. HAProxy which I made to talk upstream directly for now)
- de-chunk responses if you know you’re speaking to an HTTP 1.0 client

Ideally both. :)

**How to reproduce it (as minimally and precisely as possible)**:

I’m not sure how to give you an upstream server that reacts to the HTTP version. But in practice it looks like this:

```
GET /nic/update?hostname=XXX&myip=1.2.2.2 HTTP/1.0
Host: XXX
Connection: close
Authorization: Basic XXX

HTTP/1.0 200 OK
Server: gunicorn/19.7.1
Date: Fri, 02 Mar 2018 18:30:05 GMT
Connection: close
Content-Type: text/plain; charset=UTF-8
X-Request-ID: 0399f0a381cd4b7ca8e63fce6d4ff070
X-Served-By: dev-dev-dev

good 1.2.2.2
```

vs

```
GET /nic/update?hostname=XXX&myip=1.2.2.2 HTTP/1.1
Host: XXX
Connection: close
Authorization: Basic XXX

HTTP/1.1 200 OK
Server: gunicorn/19.7.1
Date: Fri, 02 Mar 2018 18:30:34 GMT
Connection: close
Transfer-Encoding: chunked
Content-Type: text/plain; charset=UTF-8
X-Request-ID: d4da77308a6c45a88a3b461b945e9a0d
X-Served-By: dev-dev-dev

C
good 1.2.2.2
0
```

ddclient chokes on the `C` and `0`.

**Comment by wmorgan** [comment]
Thanks for capturing this, @hynek!

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd/pull/1904
