### ISSUE TITLE
Docker images critical security issues

### ISSUE THREAD

**Issue by mrezaei00** [linkerd/linkerd#1855]
Issue Type:
- [x] Bug report
- [ ] Feature request

**What happened**:
The Docker images available on Docker Hub have some critical issues that's concerning for our rollout to a production environment.

Latest Linkerd version critical issues (taken from https://hub.docker.com/r/buoyantio/linkerd/tags/latest/):
![image](https://user-images.githubusercontent.com/7763122/37053968-77171736-2132-11e8-9f90-3d83edfeea28.png)
![image](https://user-images.githubusercontent.com/7763122/37053987-81971c60-2132-11e8-8bb9-e7d729e0a63d.png)
![image](https://user-images.githubusercontent.com/7763122/37054000-8aef7474-2132-11e8-912a-5f10215b7b86.png)

Similar critical issues for Namerd noted in https://hub.docker.com/r/buoyantio/namerd/tags/latest/

**What you expected to happen**:
For a production grade software we cannot have any critical package issues:
* Is there any plan to actively update these issues?
* What's the update cycle for security issues?
* Can one contribute toward security issues?

**Environment**:
- linkerd/namerd version, config files: latest version of both services, 
- Platform, version, and config files (Kubernetes, DC/OS, etc): Kubernetes 1.7
- Cloud provider or hardware configuration: GCE on GCP

**Comment by olix0r** [comment]
@mrezaei00 Thanks for the report.

We build Linkerd on the [published OpenJDK images](https://hub.docker.com/_/openjdk/).  If upgrading the JRE image will resolve these issues, we'll happily upgrade; but the Linkerd project is not interested in maintaining its own JRE images.

**Comment by olix0r** [comment]
I should also note that, due to licensing, we can only distribute docker images with OpenJDK. From what I've seen, many production users build their own linkerd image on Oracle JRE base images (usually maintained within that organization).

**Comment by sankate** [comment]
Is it fine if we update the `Build.md` to add a section which describes `Building docker images locally`

Is it as simple as replacing OpenJDK in the circleci config file? Or do we have to do something else?
 https://github.com/linkerd/linkerd/blob/243db9b10dfe49e6127350d4367318c6ac6fedab/.circleci/config.yml#L9

**Comment by olix0r** [comment]
The circleci config is not relevant, but changing the value of `dockerJavaImage` at build-time will use a different base image (and this should be configurable without editing LinkerdBuild.scala, though I can't quite figure out how to do that at the moment).

I agree that we should update BUILD.md with instructions on how to build on different docker images.
