### ISSUE TITLE
Linkerd-to-Linkerd not working for outgoing request to hello-world example

### ISSUE THREAD

**Issue by eroji** [linkerd/linkerd#1859]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
I am following the steps for configuring Linkerd on Kubernetes on-prem cluster with Flannel CNI. I applied the [linkerd-cni](https://raw.githubusercontent.com/linkerd/linkerd-examples/master/k8s-daemonset/k8s/linkerd-cni.yml) and the [hello-world ](https://raw.githubusercontent.com/linkerd/linkerd-examples/master/k8s-daemonset/k8s/hello-world.yml) definitions with a minor change to use ClusterIP instead of LoadBalancer. From what I can see, everything is installed correctly. However, when attempting to simulate a request to the hello-world service, it fails with the following error.

```
> http_proxy=10.100.31.26:4140 curl -s http://hello
No hosts are available for /svc/hello, Dtab.base=[/srv=>/#/io.l5d.k8s/default/http;/host=>/srv;/svc=>/host;/host/world=>/srv/world-v1], Dtab.local=[].
Remote Info: Not Available
```
Kubelet logs on the worker node shows
```
Mar  8 17:40:10 kube-worker-01 journal: W 0309 01:40:10.070 UTC THREAD31 TraceId:9d023e99ac3d6823: k8s ns default service l5d endpoints resource does not exist, assuming it has yet to be created
Mar  8 17:40:10 kube-worker-01 journal: I 0309 01:40:10.141 UTC THREAD31 TraceId:9d023e99ac3d6823: %/io.l5d.k8s.daemonset/default/incoming/l5d/#/io.l5d.k8s/default/http/hello: name resolution is negative (local dtab: Dtab())
Mar  8 17:40:10 kube-worker-01 journal: E 0309 01:40:10.171 UTC THREAD31 TraceId:9d023e99ac3d6823: service failure: com.twitter.finagle.NoBrokersAvailableException: No hosts are available for /svc/hello, Dtab.base=[/srv=>/#/io.l5d.k8s/default/http;/host=>/srv;/svc=>/host;/host/world=>/srv/world-v1], Dtab.local=[]. Remote Info: Not Available
Mar  8 17:40:10 kube-worker-01 journal: I 0309 01:40:10.288 UTC THREAD28 TraceId:9d023e99ac3d6823: %/io.l5d.k8s.daemonset/default/incoming/l5d/#/io.l5d.k8s/default/http/hello: name resolution is negative (local dtab: Dtab())
```

**What you expected to happen**:
It should return with "Hello world" with IP of the pods serving the services.

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy CNI version of Linkerd (with ClusterIP)
- Deploy hello-world app
- Attempt to curl the ClusterIP and outgoing port of request to http://hello

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files: 1.3.6
- Platform, version, and config files (Kubernetes, DC/OS, etc): Kubernetes 1.9.3 with Flannel
- Cloud provider or hardware configuration: On-prem

**Comment by eroji** [comment]
Interestingly, if I test the route using dtab, it seems to point to the pod IPs and port correctly however fails to complete.

![image](https://user-images.githubusercontent.com/13228540/37186220-2d05f158-22f9-11e8-85a6-a74b8e62f19d.png)

However, looking at kubectl, it shows that the services has no ClusterIP at all.

```
NAME             TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
svc/hello        ClusterIP   None         <none>        7777/TCP   1h
svc/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP    24d
svc/world-v1     ClusterIP   None         <none>        7778/TCP   1h
```

**Comment by adleong** [comment]
Hi @eroji!

It looks like Linkerd is able to find the hello pods fine but isn't able to find a Linkerd pod on the same host.  It will be looking for a service called `l5d` with a port named `incoming` in the `default` namespace.  

Did you perhaps deploy Linkerd into a different namespace?  If so, you'll need to update this block in your Linkerd config to reference the namespace where Linkerd is deployed:

```
        transformers:
        - kind: io.l5d.k8s.daemonset
          namespace: default
          port: incoming
          service: l5d
          hostNetwork: true
```

**Comment by eroji** [comment]
Thank you!

**Comment by eroji** [comment]
That did the trick. Thank you!
