### ISSUE TITLE
TLS Doesn't Work with SHA512 Certs

### ISSUE THREAD

**Issue by Capitrium** [linkerd/linkerd#1861]
**Issue Type**:

- [x] Bug report
- [ ] Feature request

**What happened**:
Requests error out when sending via linkerd secured with tls when using certificates using `SHA512`. We've followed [the guide](https://buoyant.io/2016/10/24/a-service-mesh-for-kubernetes-part-iii-encrypting-all-the-things/), which works with the provided sample certs, but breaks when we substitute our own certs generated with `SHA512` instead of `SHA256`.

**What you expected to happen**:
`SHA512` certs should work the same as `SHA256`.

**How to reproduce it (as minimally and precisely as possible)**:
Use the `openssl` commands provided [here](https://buoyant.io/2016/03/24/transparent-tls-with-linkerd/#generating-certificates), and the `openssl.cfg` file provided [here](https://gist.github.com/klingerf/d43738ac98b6bf0479c47987977a7782), substituting the algorithm with `SHA512` (i.e. `default_md = sha512`). Make a request and observe the errors:
```
E 0309 15:23:41.199 UTC THREAD120 TraceId:0ea20f703404c448: service failure: Failure(null at remote address: /10.0.24.7:4141. Remote Info: Not Available at remote address: /10.0.24.7:4141. Remote Info: Not Available, flags=0x09) with RemoteInfo -> Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /10.0.24.7:4141, Downstream label: %/io.l5d.k8s.daemonset/linkerd/incoming/l5d/#/io.l5d.k8s/default/http/consumer, Trace Id: 0ea20f703404c448.0ea20f703404c448<:0ea20f703404c448
I 0309 15:28:50.204 UTC THREAD68 TraceId:9023d4a952049423: FailureAccrualFactory marking connection to "%/io.l5d.k8s.daemonset/linkerd/incoming/l5d/#/io.l5d.k8s/default/http/consumer" as dead. Remote Address: Inet(/10.0.24.7:4141,Map(nodeName -> ip-10-0-24-7.ec2.internal))
```

**Anything else we need to know?**:
We posted [this](https://discourse.linkerd.io/t/linkerd-tls-not-conforming-to-x509v3/580) on the forums while debugging the issue.

**Environment**:
- linkerd/namerd version, config files:
  - linkerd 1.3.6
  - linkerd config:
```
admin:
  ip: 0.0.0.0
  port: 9990

namers:
- kind: io.l5d.k8s
  host: localhost
  port: 8001

telemetry:
- kind: io.l5d.prometheus
- kind: io.l5d.recentRequests
  sampleRate: 0.25

usage:
  orgId: linkerd-examples-daemonset

routers:
- protocol: http
  label: outgoing
  dtab: |
    /srv        => /#/io.l5d.k8s/default/http;
    /host       => /srv;
    /svc        => /host;
  interpreter:
    kind: default
    transformers:
    - kind: io.l5d.k8s.daemonset
      namespace: linkerd
      port: incoming
      service: l5d
      hostNetwork: true
  servers:
  - port: 4140
    ip: 0.0.0.0
  service:
    responseClassifier:
      kind: io.l5d.http.retryableRead5XX
  client:
    tls:
      commonName: linkerd
      trustCerts:
      - /io.buoyant/linkerd/certs/cacertificate.pem

- protocol: http
  label: incoming
  dtab: |
    /srv        => /#/io.l5d.k8s/default/http;
    /host       => /srv;
    /svc        => /host;
  interpreter:
    kind: default
    transformers:
    - kind: io.l5d.k8s.localnode
      hostNetwork: true
  servers:
  - port: 4141
    ip: 0.0.0.0
    tls:
      certPath: /io.buoyant/linkerd/certs/certificate.pem
      keyPath: /io.buoyant/linkerd/certs/key.pk8
```
- Platform, version, and config files (Kubernetes, DC/OS, etc):
  - Kubernetes 1.9.3
  - CoreOS 1632.3.0 
- Cloud provider or hardware configuration: AWS

**Comment by rmars** [comment]
Thanks for the detailed bug report, @Capitrium - we'll take a look!

**Comment by adleong** [comment]
@briansmith I could use some SSL expertise in understanding what the `default_md` is used for when generating pkcs#8 keys and how to configure the Netty SSLContext to be able to handle such keys.  Is the message digest the same as the cipher?

**Comment by briansmith** [comment]
> @briansmith I could use some SSL expertise in understanding what the default_md is used for when generating pkcs#8 keys and

In the openssl.cfg file, there are two places where sha256 is mentioned, as there are two `default_md` settings. The first time I experimented with this, I only saw & changed one of them, in the `[ CA_default ]` section, but the one that seems to matter here is the one in the `[ req ]` section.

After I changed *both* instances of `sha256` to `sha512`, then I re-ran the `openssl req` command that was linked to, and then I ran ` openssl x509 -in certificates/cacertificate.pem -text` which showed that the certificate is using `Signature Algorithm: sha512WithRSAEncryption`

> how to configure the Netty SSLContext to be able to handle such keys. Is the message digest the same as the cipher?

Are you able to reproduce the failure in this bug report? If so, it would be helpful if you could tell me the exact steps to reproduce, preferably without Kubernetes, starting from "I just downloaded Linkerd and I don't even know how to start it or how to given the configuration file to it." That would help me figure out what Netty stuff I need to learn to answer this question.

**Comment by adleong** [comment]
Thanks, @briansmith!  I've dug into this a bit more and I cannot reproduce it.

@Capitrium here are the steps that I am taking and I am unable to reproduce the issue:

Using this `openssl.cfg`:

```
dir = certificates

[ ca ]
default_ca = CA_default

[ CA_default ]
serial = $dir/serial
database = $dir/index.txt
new_certs_dir = $dir/newcerts
certificate  = $dir/cacert.pem
private_key = $dir/private/cakey.pem
default_days = 36500
default_md  = sha512
preserve = no
email_in_dn  = no
nameopt = default_ca
certopt = default_ca
policy = policy_match

[ policy_match ]
commonName = supplied
countryName = optional
stateOrProvinceName = optional
organizationName = optional
organizationalUnitName = optional
emailAddress = optional

[ req ]
default_bits = 2048
default_keyfile = priv.pem
default_md = sha512
distinguished_name = req_distinguished_name
req_extensions = v3_req
encyrpt_key = no

[ req_distinguished_name ]

[ v3_ca ]
basicConstraints = CA:TRUE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always

[ v3_req ]
basicConstraints = CA:FALSE
subjectKeyIdentifier = hash
```
I run the following commands:

```
$ mkdir -p certificates/private
$ mkdir -p certificates/newcerts
$ echo 1000 > certificates/serial
$ touch certificates/index.txt
$ openssl req -x509 -nodes -newkey rsa:2048 -config openssl.cfg \
                    -subj '/C=US/CN=My CA' -keyout certificates/private/cakey.pem \
                    -out certificates/cacertificate.pem
$ openssl req -new -nodes -config openssl.cfg -subj "/C=US/CN=alex" \
                    -keyout certificates/private/alexkey.pem \
                    -out certificates/alexreq.pem
$ openssl ca -batch -config openssl.cfg -keyfile certificates/private/cakey.pem \
                    -cert certificates/cacertificate.pem \
                    -out certificates/alexcertificate.pem \
                    -infiles certificates/alexreq.pem
$ openssl pkcs8 -topk8 -nocrypt -in certificates/private/alexkey.pem  -out certificates/private/alexkey.pk8
```

I then use this `linkerd.yml` config:

```
namers: []

routers:
- protocol: http
  label: outgoing
  dtab: /svc => /$/inet/localhost/4141
  servers:
  - port: 4140
  client:
    tls:
      trustCerts:
      - certificates/cacertificate.pem
      commonName: alex

- protocol: http
  label: incoming
  dtab: /svc => /$/inet/localhost/9990
  servers:
  - port: 4141
    tls:
      certPath: certificates/alexcertificate.pem
      keyPath: certificates/private/alexkey.pk8
```

I run Linkerd version 1.3.6:

```
$ ./linkerd-1.3.6-exec linkerd.yml -log.level=DEBUG
```

and then curl

```
curl localhost:4140
```

And everything seems to work correctly.  Note that `default_md` is set to `sha512` for both the ca and the cert.

**Comment by Capitrium** [comment]
@adleong Thanks for taking the time to look into this, we'll try and reproduce it again ourselves shortly and report back - in the meantime, can you share the version of openssl you're using just so we can make sure we're doing everything in exactly the same way?

**Comment by adleong** [comment]
I'm running

```
$ openssl version
LibreSSL 2.2.7
```

on MacOS 10.13.3

**Comment by Capitrium** [comment]
@adleong we're not able to reproduce this anymore either. This issue originally came up since we're having trouble using certs that are generated using our pre-existing TLS pipeline powered by `cfssl`, which we've used to generate SHA512 certs that are currently used by components in our Kubernetes cluster (etcd, apiservers, etc.).

Are there any other config options (when generating certs, or in linkerd itself) that you can think of which would cause the errors we're seeing on linkerd using our `cfssl`-generated certs? We've been trying to get linkerd running for a few weeks now, and we're running out of ideas.

```
E 0309 15:23:41.199 UTC THREAD120 TraceId:0ea20f703404c448: service failure: Failure(null at remote address: /10.0.24.7:4141. Remote Info: Not Available at remote address: /10.0.24.7:4141. Remote Info: Not Available, flags=0x09) with RemoteInfo -> Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /10.0.24.7:4141, Downstream label: %/io.l5d.k8s.daemonset/linkerd/incoming/l5d/#/io.l5d.k8s/default/http/consumer, Trace Id: 0ea20f703404c448.0ea20f703404c448<:0ea20f703404c448
I 0309 15:28:50.204 UTC THREAD68 TraceId:9023d4a952049423: FailureAccrualFactory marking connection to "%/io.l5d.k8s.daemonset/linkerd/incoming/l5d/#/io.l5d.k8s/default/http/consumer" as dead. Remote Address: Inet(/10.0.24.7:4141,Map(nodeName -> ip-10-0-24-7.ec2.internal))
```

**Comment by briansmith** [comment]
If you can, email the certificate chain that doesn't work, *without the private keys*, to brian@buoyant.io.

**Comment by Capitrium** [comment]
@briansmith My coworker emailed you the non-working cert chain the other day; let us know if you're able to find anything!

**Comment by briansmith** [comment]
@Capitrium That's right, I got them! Thanks! I don't see anything out of the ordinary with those certificates. I actually just filed #1876 to make our example certificates look more like what you sent!

I'm now going to attempt to create my own root CA and end-entity certificate with CFSSL and see if I can reproduce the issue with CFSSL-generated certificates in linkerd.

**Comment by briansmith** [comment]
> I don't see anything out of the ordinary with those certificates.

I was wrong! `openssl x509 -in linkerd.pem -text` shows:

```
            X509v3 Subject Alternative Name:
                DNS:
```

Your certificate has a `subjectAltName` field with one `dNSName` entry that is blank (length == 0)! There are two problems here:

1. A `dNSName` field cannot be blank! It must be a valid DNS name.
2. If your certificate includes a subjectAltName extension at all then the `CN` of the `subject` will be ignored.

To fix this, when you use CFSSL, you need to pass the hostnames that you want your certificate to be valid for on the command line as explained in the CFSSL documentation. In particular, CFSSL seems to always create a subjectAltName field, which is good practice, so trying to use the Subject `CN` field will not work.

**Comment by briansmith** [comment]
That is, either use `cfssl gencert -ca cert -ca-key key -hostname=linkerd csr.json` or use the `hosts` field in your JSON config file. Probably using the `-hostname` command line option is better because then you can use the same configuration file for all certificates.

**Comment by Capitrium** [comment]
@briansmith Thanks for the info! I'll regenerate our test certs when I'm back in the office on Monday and report back. Getting X509v3 certs working with linkerd is one of the last remaining blockers we have for deploying it to prod (I had some concerns with using X509v1... :stuck_out_tongue:) 

On a side note, I did just check another cert that we created for linkerd using Vault that gave us similar problems, and there are no blank `dNSName` entries in the `subjectAltName` field; however I'm still sorting out some other issues with our Vault configuration, so I'm hoping those are related.

**Comment by Capitrium** [comment]
Looks like the empty `dNSName` field was the issue with our CFSSL certs - thanks again @briansmith for looking into that!

**Comment by briansmith** [comment]
Great! I'm glad I could help and I'm glad there's no bug to fix here!

**Comment by Capitrium** [comment]
@briansmith Turns out we jumped the gun a little here, we're still having TLS issues - should we open a new bug report or reopen this one?

**Comment by briansmith** [comment]
> @briansmith Turns out we jumped the gun a little here, we're still having TLS issues - should we open a new bug report or reopen this one?

It's fine to keep this open. Please email me the new certificates (without the private keys). Thanks!

**Comment by a-kinder** [comment]
hey @briansmith just wondering if you had any luck with finding the issue with those certs?

**Comment by a-kinder** [comment]
Just wanted to make note here: we've implemented linkerd-tls with cfssl certs that work fine.

**Comment by Capitrium** [comment]
@briansmith Any updates on this? Hate to keep bugging you, but I need something to bring back to my project manager so we can start working on a backup plan in case linkerd won't be compatible with cfssl or vault certs anytime soon.

As a side note, we've validated that we can use both our cfssl-generated certs and our vault-generated certs with openssl's `s_client`/`s_server` tools to setup a working TLS connection.

**Comment by briansmith** [comment]
I emailed the contact that emailed me the certificate. Please provide the *exact* steps to reproduce here, starting from the `kubectl apply` step(s) that add the things being tested, along with the exact YAML input file for `kubectl apply`, and the commands you used to trigger the failing requests (`curl`?). Thanks!

**Comment by wmorgan** [comment]
@a-kinder Great! And thanks for the writeup.
