### ISSUE TITLE
Routing with Nginx Ingress

### ISSUE THREAD

**Issue by eroji** [linkerd/linkerd#1864]
Issue Type:

- [ ] Bug report
- [ ] Feature request

**What happened**:
This is not a bug or feature request. It's purely a question and my lack of understanding on how to get linkerd to route correctly. I have an application that has a API path of `/app1/api/v1/lookup/12345` which then looks up the value `12345` and returns a result. This will be just one of the microservices running under the same hostname `https://services.example.com`. So ultimately, my request URL looks like this `https://services.example.com/app1/api/v1/lookup/12345`. If I create an nginx ingress resource as `https://services.example.com` to svc/l5d on port 4140, when I try to request `/app1/api/v1/lookup/12345` I get the following output.

`No hosts are available for /svc/services.example.com, Dtab.base=[/srv=>/#/io.l5d.k8s/default/http;/host=>/srv;/svc=>/host;/host/world=>/srv/world-v1], Dtab.local=[]. Remote Info: Not Available`

So it appears that linkerd service does not know it is bound to the hostname via ingress and tries to route to a svc with that name and fails.

I tried adding a value in the dtab to route `/services.example.com => /svc` but that doesn't seem to work and yields the same error.

**What you expected to happen**:
I'd like to linkerd to route incoming requests through ingress controller to my services. 

**How to reproduce it (as minimally and precisely as possible)**:
As described above.

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files: 1.3.6
- Platform, version, and config files (Kubernetes, DC/OS, etc): 1.9.3
- Cloud provider or hardware configuration: vSphere

**Comment by eroji** [comment]
Sorry for the confusion. I was not entirely sure if I was clear in my explanation as well.

So I will be running multiple applications each has a API with its own respective paths. For instance:

```
app1 -> /app1/api/v1/...
app2 -> /app2/api/v1/...
app3 -> /app3/api/v1/...

```
I want them all to sit behind linkerd service mesh and also gather useful metrics of each. I have a ingress rule using nginx ingress to point all requests to `https://services.example.com` to linkerd service, port 4140. My expectation is that then if I try to navigate to `https://services.example.com/app1/api/v1/...` it takes me to app1 and respectively for all other applications.

**Comment by hawkw** [comment]
Ah, okay, that makes more sense. Can I see your Linkerd config file in order to better understand what's going on here?

**Comment by eroji** [comment]
The config is currently default.

```
apiVersion: v1
data:
  config.yaml: |-
    admin:
      ip: 0.0.0.0
      port: 9990

    namers:
    - kind: io.l5d.k8s
      host: localhost
      port: 8001

    telemetry:
    - kind: io.l5d.prometheus
    - kind: io.l5d.recentRequests
      sampleRate: 0.25

    usage:
      orgId: linkerd-docmagic-daemonset

    routers:
    - protocol: http
      label: outgoing
      dtab: |
        /srv        => /#/io.l5d.k8s/default/http;
        /host       => /srv;
        /svc        => /host;
        /host/world => /srv/world-v1;
      interpreter:
        kind: default
        transformers:
        - kind: io.l5d.k8s.daemonset
          namespace: linkerd
          port: incoming
          service: l5d
          hostNetwork: true
      servers:
      - port: 4140
        ip: 0.0.0.0
      service:
        responseClassifier:
          kind: io.l5d.http.retryableRead5XX

    - protocol: http
      label: incoming
      dtab: |
        /srv        => /#/io.l5d.k8s/default/http;
        /host       => /srv;
        /svc        => /host;
        /host/world => /srv/world-v1;
      interpreter:
        kind: default
        transformers:
        - kind: io.l5d.k8s.localnode
          hostNetwork: true
      servers:
      - port: 4141
        ip: 0.0.0.0
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"admin:\n  ip: 0.0.0.0\n  port: 9990\n\nnamers:\n- kind: io.l5d.k8s\n  host: localhost\n  port: 8001\n\ntelemetry:\n- kind: io.l5d.prometheus\n- kind: io.l5d.recentRequests\n  sampleRate: 0.25\n\nusage:\n  orgId: linkerd-docmagic-daemonset\n\nrouters:\n- protocol: http\n  label: outgoing\n  dtab: |\n    /srv        =\u003e /#/io.l5d.k8s/default/http;\n    /host       =\u003e /srv;\n    /svc        =\u003e /host;\n    /host/world =\u003e /srv/world-v1;\n  interpreter:\n    kind: default\n    transformers:\n    - kind: io.l5d.k8s.daemonset\n      namespace: linkerd\n      port: incoming\n      service: l5d\n      hostNetwork: true\n  servers:\n  - port: 4140\n    ip: 0.0.0.0\n  service:\n    responseClassifier:\n      kind: io.l5d.http.retryableRead5XX\n\n- protocol: http\n  label: incoming\n  dtab: |\n    /srv        =\u003e /#/io.l5d.k8s/default/http;\n    /host       =\u003e /srv;\n    /svc        =\u003e /host;\n    /host/world =\u003e /srv/world-v1;\n  interpreter:\n    kind: default\n    transformers:\n    - kind: io.l5d.k8s.localnode\n      hostNetwork: true\n  servers:\n  - port: 4141\n    ip: 0.0.0.0"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2018-03-09T01:39:30Z","name":"l5d-config","namespace":"linkerd","resourceVersion":"4330504","selfLink":"/api/v1/namespaces/linkerd/configmaps/l5d-config","uid":"b6194b2a-233a-11e8-9633-0050568f4635"}}
  creationTimestamp: 2018-03-13T09:00:16Z
  name: l5d-config
  namespace: linkerd
  resourceVersion: "4975581"
  selfLink: /api/v1/namespaces/linkerd/configmaps/l5d-config
  uid: f2d9e807-269c-11e8-92ed-0050568f0a75
```

I tried a number of different dtab rules but none of them seemed to have worked and all resulted in the similar error

```
No hosts are available for /svc/services.example.com, Dtab.base=[/srv=>/#/io.l5d.k8s/default/http;/host=>/srv;/svc=>/host;/host/world=>/srv/world-v1], Dtab.local=[]. Remote Info: Not Available
```

**Comment by hawkw** [comment]
Okay, right now it looks like the dtab for Linkerd's `incoming` router is configured to route requests to a Kubernetes service called "world-v1":
```
        /srv        => /#/io.l5d.k8s/default/http;
        /host       => /srv;
        /svc        => /host;
        /host/world => /srv/world-v1;
```

What you need to do is change the dtab to route to your services. If you want routing like
```
app1 -> /app1/api/v1/...
app2 -> /app2/api/v1/...
app3 -> /app3/api/v1/...
```
you want to use the [path identifier](https://linkerd.io/config/1.3.6/linkerd/index.html#http-1-1-identifiers) rather than the host identifier, which is currently configured. So you'll want to change the `incoming` router to something like this: 
```yaml
- protocol: http
  label: incoming
  identifier:
    kind: io.l5d.path
    segments: 1
    consume: true
  dtab: |
    /srv        => /#/io.l5d.k8s/default/http;
    /svc        => /srv
  interpreter:
    kind: default
    transformers:
    - kind: io.l5d.k8s.localnode
      hostNetwork: true
  servers:
  - port: 4141
    ip: 0.0.0.0
```

This will configure Linkerd to take the first path segment from the request path, and use that as the name of a Kubernetes service to route the request to. The `io.l5d.k8s.localnode` transformer will ensure that Linkerd routes to a pod in that service that's running on the same node as the Linkerd instance.

**Comment by eroji** [comment]
I'll give it a try. Does this also mean that the outgoing dtab needs to match?

**Comment by hawkw** [comment]
The outgoing router in this case controls how requests made by services running on the same node as a Linkerd instance are routed. If you want to route these requests the same way you route incoming requests, then yes. If these requests should be routed differently, then you'll want the configuration for this router to reflect that. If your services are not routing outgoing requests through Linkerd, then you can remove that router from the config file.

**Comment by eroji** [comment]
To configure services outgoing request through linkerd, is that a configuration in linkerd or the application?

**Comment by hawkw** [comment]
@eroji you'll need to configure your application to use Linkerd as a proxy. Many (but not all) applications and frameworks support a `http_proxy` environment variable; otherwise, they'll likely have their own method of configuring a HTTP proxy. See https://linkerd.io/getting-started/k8s/#configure-your-application for more information.

You might also be interested to note that, unlike Linkerd, the [Conduit](https://conduit.io/) service mesh can be transparently injected into Kubernetes pods without requiring you to set it as a proxy; it will set `iptables` rules so that all outgoing requests are routed through Conduit automagically. However, it doesn't currently support the kind of policy-based routing we discussed above, but this is on the roadmap.

**Comment by eroji** [comment]
Thank you. I think this answers all my questions.
