### ISSUE TITLE
 Configure log rotation policy for HTTP2 access logs

### ISSUE THREAD

**Issue by DipeshMitthalal** [linkerd/linkerd#1865]
# Configure log rotation policy for HTTP2 access logs #

Issue Type:

- [ ] Bug report
- [x] Feature request

Possiblity of configuring HTTP2 accesslog rotation policy via config file

**What you expected to happen**:
Expose the log rotation policy to be configurable

**Comment by hawkw** [comment]
Hi @DipeshMitthalal, thanks for the feature request!

**Comment by leozc** [comment]
This is a good request, for now, to work around we are using logrotated

**Comment by adleong** [comment]
Fixed by #1893
