### ISSUE TITLE
Feature: Marathon services failing health checks should fail over in name tree resolution

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd#1868]
## Filing a Linkerd issue ##

Issue Type:

- [ ] Bug report
- [x] Feature request

Currently, the `useHealthChecks` option to the Marathon namer filters out services failing health checks by removing them from the returned bound name. If all replicas of a service are failing health checks, then the returned bound name will be Empty. Dtab alternation will not trigger on an empty name, so if a dtab is configured with an alternate path, Linkerd will route to the empty name, resulting a "no hosts available" exception. If the returned name was Neg instead, then Linkerd would fail over to the alternate path instead.

In order to implement failover, we may want to consider adding an option to treat this case as though the service for which all replicas are failing does not exist in service discovery.

**Comment by jayeve** [comment]
Looking to take a stab at this one. There are certainly engineers more familiar with this specific codebase; specifically @siggy and @adleong. I'm fairly proficient with scala code and can certainly adopt the patterns I've seen used in the linkerd repo; however, I would benefit tremendously if either of you could provide some insight as to where the relevant changes need to be made to address this issue. Thank you in advance for any guidance you may provide. It would be great to contribute to an open source project like this one!

**Comment by hawkw** [comment]
I think it might be worthwhile to consider making this change in a way that can benefit more than just the Marathon namer; similar failover-on-empty-addrs might be useful with other service discovery backends as well?

**Comment by adleong** [comment]
I'm not sure about that.  Finagle explicitly differentiates between Empty (the service exists but has 0 instances) and Neg (the service does not exist).  I'm not sure if we always want to fallback on empty services.

For this issue in particular, take a look at `AppIdNamer.scala`.  We would want to return a `NameTree.Neg` in the case that the address set is empty.  You can find an example of this type of behavior in the Kubernetes namer in `EndpointsNamer.scala` in the `mkNameTree` method.

**Comment by hawkw** [comment]
@adleong I'm thinking this behaviour should be opt-in with a configuration setting --- sorry if that wasn't clear in the issue description!

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd/pull/1921
