### ISSUE TITLE
`idleTimeMs` and `idleTtlSecs` settings don't seem to have any effect on established H2 connections

### ISSUE THREAD

**Issue by nikolay-pshenichny** [linkerd/linkerd#1890]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
Linkerd is not expiring/terminating idle client HTTP2 connections after the timeouts configured in `idleTimeMs` and/or `idleTtlSecs` configuration options.

**What you expected to happen**:
The established Http2 connections from Linkerd to the server are expected to be closed if they were idling for more then the time indicated in the configuration.

**How to reproduce it (as minimally and precisely as possible)**:
1. Set the idleTtlSecs to 60 seconds
2. Make a single request from a grpc client to a grpc server through Linkerd
3. Observe the number of connections in Linkerd for more than 60 seconds. The number will stay == 1
4. Check the `netstat`'s output to see that there's and ESTABLISHED connection from Linkerd to the server.

Docker-compose and configuration files that can help to reproduce the issue - https://github.com/nikolay-pshenichny/linkerd-idleTtlSecs_and_idleTimeMs

**Anything else we need to know?**:

New context (2018-04-10 2:50pm): Linkerd will always keep 1 client open, even if it has been idle for longer than the ttl. The issue is requesting that that behavior be changed or made configurable.
cc: @adleong 

**Environment**:
- linkerd/namerd version, config files:  linkerd v 1.3.7; sample config files can be found using the link above. 
- Platform, version, and config files (Kubernetes, DC/OS, etc): Seeing this in Vagrant; Docker; Kubernetes;
- Cloud provider or hardware configuration:

**Comment by nikolay-pshenichny** [comment]
@adleong , thx for the update!
I haven't done much testing around Http1 and won't be able to confirm that part.
But with Http2 - yes, we are seeing a single connection being present after a single request went through... That connection is never closed.


>My recommendation for a fix would be to change the singleton connection pool that is used by HTTP/2 to close the singleton connection after it has been idle for idleTimeMs. What do you think?

From your description, it sounded like Http1 pool is doing a similar job - ie. the pool will only close the excess connections after the timeout and will hold all other connections. So the Singleton Pool appears to be working as designed. And since it is defined in Finagle-Core, I am not sure I completely understand the idea of fixing it.

From the design perspective of Linkerd, should the connection pools be responsible for tracking and closing idle connections, or is it ok for the connections to expire on their own?

I did some digging and found that `com.twitter.finagle.buoyant.H2.Client` supports ClientSession params underneath. A change in the `io.buoyant.linkerd.protocol.H2ClientConfig` to support `ExpiringService` params appears to be working properly for our use case. But i haven't had a chance to look at the Http1 side yet.

```
trait H2ClientConfig extends ClientConfig with H2EndpointConfig {
  var forwardClientCert: Option[Boolean] = None
  var lifeTimeMs: Option[Int] = None // ExpiringService properties for client connections
  var idleTimeMs: Option[Int] = None // ExpiringService properties for client connections

  @JsonIgnore
  override def params(vars: Map[String, String]): Stack.Params = {
    val result = withEndpointParams(super.params(vars))
      .maybeWith(forwardClientCert.map(ForwardClientCertFilter.Enabled))
      .maybeWith(Some(new ExpiringService.Param(
        lifeTime = lifeTimeMs.map(x => Duration.fromMilliseconds(x)).orElse(Some(Duration.Top)).get,
        idleTime = idleTimeMs.map(x => Duration.fromMilliseconds(x)).orElse(Some(Duration.Top)).get
      )))

    result
  }
}
```

I can prepare a PR with the ^ change, to give you more context on the scope of the change; or I can try looking at the connection pool changes, but will need more context on that.

**Comment by adleong** [comment]
Great find!  ExpiringService sounds like a perfect fit.  I would be more than happy to take a look at such a PR.

**Comment by nikolay-pshenichny** [comment]
@adleong , preliminary PR - https://github.com/nikolay-pshenichny/linkerd/pull/1/files
I want to clean the things up a little and expand the support to H1. After that I will create a PR against the official repository.

Pls let me know if I am moving in the right direction.

**Comment by adleong** [comment]
Yes, overall direction looks great here!

**Comment by nikolay-pshenichny** [comment]
@adleong , I cleaned up the PR that I had. Here is the latest version - https://github.com/linkerd/linkerd/pull/1903
Please take a look when you have a chance. Thx!

**Comment by nikolay-pshenichny** [comment]
@adleong , could you please tell me when is the next scheduled release date for Linkerd (1.3.8) ? 
We are trying to decide if we need to apply a temporary workaround or wait till the next release  (assuming that all review comments are addressed and there are not issues with the PR).

Thank you.

**Comment by adleong** [comment]
My goal is to cut a release candidate this week, get some folks to test it, and hopefully do a full release sometime next week.  If you're able to help us test the RC once it's ready, that would be super helpful!

**Comment by nikolay-pshenichny** [comment]
> My goal is to cut a release candidate this week, get some folks to test it, and hopefully do a full release sometime next week. If you're able to help us test the RC once it's ready, that would be super helpful!

@adleong , what is required for testing ?
I am going to be away for a few days, but other people from my team can help with the tests.

**Comment by joeyb** [comment]
@adleong - I’m working with @nikolay-pshenichny to test this on our end. Do you have an ETA on that release candidate for 1.3.8? We’re ready to give it a shot.

**Comment by adleong** [comment]
We will have a release candidate available very soon: early this week.

**Comment by adleong** [comment]
The release candidate is now available: https://github.com/linkerd/linkerd/releases/tag/1.4.0-rc1
Please try it out and let us know how it goes.

**Comment by joeyb** [comment]
@adleong - Did the release candidate get a full push to maven central? I'm not seeing any artifacts for 1.4.0-rc1: http://central.maven.org/maven2/io/buoyant/linkerd-core_2.12/

**Comment by adleong** [comment]
the artifacts have been pushed to maven central and hopefully should show up soon.

**Comment by joeyb** [comment]
@adleong - FYI, our smoke tests of this have been baking for a few days and we haven't seen any issues.

**Comment by wmorgan** [comment]
@joeyb Great to hear!
