### ISSUE TITLE
Running Linkerd in DC/OS doc update

### ISSUE THREAD

**Issue by dadjeibaah** [linkerd/linkerd#1910]
Running Linkerd in DC/OS may require some additional configuration to allow some features of Linkerd to work properly e.g. graceful shutdown (#1887). This issue has detailed instructions on how to properly configure Linkerd. We should update the Linkerd docs to highlight.

**Comment by jacob-go** [comment]
@dadjeibaah which section exactly do you want to change? 
You have the the main README in the DC/OS folder of linkerd-examples (https://github.com/linkerd/linkerd-examples/tree/master/dcos). Should it be already highlighted there?

**Comment by dadjeibaah** [comment]
@jacob-go Yes. I think that should be a good place to highlight the steps you outlined in #1887

**Comment by dadjeibaah** [comment]
This issue is fixed based on PR https://github.com/linkerd/linkerd-examples/pull/220. Closing this issue.
