### ISSUE TITLE
Linkerd cannot connect to SNI servers when using Namerd

### ISSUE THREAD

**Issue by xinyuliu-glu** [linkerd/linkerd#1920]
- [ ] Bug report

**What happened**:
From a Linkerd instance running on EC2, messages are routed to an AWS API Gateway endpoint with a private domain name. API Gateway creates HTTP endpoints for Lambda functions through CloudFront CDN. The connection failed due to a TLS handshake failure. However, we tried curl and a Java HttpsClient program on the same EC2 instance, they both connected to API Gateway private domain name without any issue.

**What you expected to happen**:
Linkerd should be able to connect to API Gateway endpoints through TLS + SNI.

**How to reproduce it (as minimally and precisely as possible)**:
Create an API Gateway endpoint which proxies requests to a Lambda function - serverless architecture. 
In Linkerd, route requests to the API Gateway endpoint with a custom domain name, an alias of the CloudFront domain name.

**Anything else we need to know?**:
Linkerd gives this error message: `Received+fatal+alert%3A+handshake_failure+at+remote+address%3A+server-54-222-19-212.iad12.r.cloudfront.net%2F54.222.19.212%3A443`
that suggests to me that it’s trying to connect to `server-54-222-19-212.iad121.r.cloudfront.net/54.230.19.212:443`
and potentially sending that as the server_name instead of `bulkupload.integration.mycompany.services`.

**Environment**:
- linkerd/namerd version, config files:
1.3.6
client:
    tls:
      commonName: "integration.mycompany.services"
      disableValidation: true

- Platform, version, and config files (Kubernetes, DC/OS, etc):
EC2 ubuntu14 and 16

- Cloud provider or hardware configuration:
AWS

**Comment by xinyuliu-glu** [comment]
It seems our namerd resolves the dtab to an IP address.
/http/ou_route_v11/us-east-1/integration/bulkupload
/srv#/us-east-1/integration/bulkupload
/#/io.l5d.consul/us-east-1/integration/bulkupload
52.84.128.91:443

**Comment by xinyuliu-glu** [comment]
@wmorgan thank you for looking into this issue. 
A slice of the Linkerd config.
interpreter:
    kind: io.l5d.fs
    dtabFile: /opt/linkerd/namerfs/bulkupload
  servers:
  - port: 4142
    ip: 0.0.0.0
  client:
    tls:
      commonName: "integration.abcd.services"
      disableValidation: true

Content of dtabFile: /opt/linkerd/namerfs/bulkupload,
/https/ou_route_v11/us-east-1/integration/bulkupload => /$/inet/bulkupload-regional.integration.abcd.services/443;

When I do 
curl -i https://bulkupload.integration.abcd.services:443
200 Response is returned from the endpoint hosted by AWS API Gateway.

While, curl -i  http://localhost:4142/ou_route_v11/us-east-1/integration/bulkupload
403 forbidden message is returned.

AWS API Gateway requires SNI for TLS connections.

**Comment by adleong** [comment]
Wireshark may be useful to examine the difference between the request that Linkerd makes (which the gateway responds to with a 403) and the request that curl makes (which the gateway responds to with a 200).

**Comment by adleong** [comment]
oh yeah, of course.  What about from the gateway logs?  Basically determining why the gateway is returning a 403 is an application level issue.

**Comment by xinyuliu-glu** [comment]
We have both API Gateway log and access log turned on. But nothing was recorded for those 403 requests from L5D.

**Comment by adleong** [comment]
I'm not sure we can help you very much with the 403s.  You'll need to understand your gateway's behavior in order to determine why it is returning those.  

However, the SNI issue is a real shortcoming of the interface between Linkerd and Namerd where server name information is not passed along from Namerd to Linkerd.  This causes the TLS handshake to fail in cases where Linkerd needs to provide the server name but it had used Namerd to resolve the address.

**Comment by wmorgan** [comment]
Should we capture the lack of server name passing in an issue?
