### ISSUE TITLE
Enable plugins to emit stat into L5D stat trees for Announcer

### ISSUE THREAD

**Issue by leozc** [linkerd/linkerd#1922]
Issue Type:

- [ ] Bug report
- [ X] Feature request

We are writing multiple plugins for our L5D mesh, there are needs to initialize a finagle client to perform RPC, however there is no way to submit the stat into L5D metrics system.

Suggestion: Is it possible to enable this user scenario?

``` 
def getClient(withRequestTimeoutMS: Int =  1000 , addr: InetSocketAddress, path:Path): Service[http.Request, http.Response]  = {
    val monitor: Monitor = new Monitor {
      def handle(t: Throwable): Boolean = {
        logger.error(t, t.getMessage, t.getStackTrace)
        true
      }
    }
    val metrics = MetricsTree() // possible to get the metrics tree from global 
    val stats = new MetricsTreeStatsReceiver(metrics) // register this stat object to be collected?
    Http.client
      .withStatsReceiver(stats)
      .withHttpStats
      .withRequestTimeout(Duration.fromMilliseconds(withRequestTimeoutMS))
      .withMonitor(monitor)
      .newService(s"${addr.getHostName()}:${addr.getPort()}", "hc_client")

  }
```

**Comment by edio** [comment]
If the intention is to see stats under `admin/metrics.json`, then it is already possible with linkerd.

Usually (I'd say, always, but maybe some type of plugins miss that still) plugin factory method receives `Stack.Params` as an argument, and one can obtain `StatsReceiver` from it:

```
val stats = params[param.Stats].statsReceiver
```

**Comment by adleong** [comment]
@leozc does @edio's comment give you what you need?

**Comment by leozc** [comment]
I am working on plugins base on`AnnouncerInitializer` and 'IdentifierInitializer'  - I don't see the factory method sreceive Stack.Params.

**Comment by adleong** [comment]
@leozc should we close this now that params are being passed to Announcer plugins?  Or are there other types of plugins that need this change as well?

**Comment by leozc** [comment]
We need to work on the identifier type as well - should I open another bug
or reuse this one ?

I am happy to work on the identifier plugin improvement as well.

**Comment by adleong** [comment]
@leozc whichever is easier for you is fine with me.  Looking forward to your PR.

**Comment by leozc** [comment]
Working perfectly - after picking up 1.4.1 and rebuild - now my announcer can emit the stat to the router it attaches to.
e.g.
  "rt/svc_ingress/announcer_hc_cln/http/response_size.p9990" : 166,
  "rt/svc_ingress/announcer_hc_cln/http/response_size.p9999" : 166,
  "rt/svc_ingress/announcer_hc_cln/http/response_size.sum" : 3320,
  "rt/svc_ingress/announcer_hc_cln/http/response_size.avg" : 166.0,
  "rt/svc_ingress/announcer_hc_cln/http/status/400" : 131,
  "rt/svc_ingress/announcer_hc_cln/http/status/4XX" : 131,
  "rt/svc_ingress/announcer_hc_cln/http/time/400.count" : 20,
  "rt/svc_ingress/announcer_hc_cln/http/time/400.max" : 65,

**Comment by leozc** [comment]
Close this - and keep Identifier work in #1963

**Comment by leozc** [comment]
Resolved!
