### ISSUE TITLE
Server-side l5d will see rare (<1%) ArrayIndexOutOfBoundsException errors on TLS traffic

### ISSUE THREAD

**Issue by shakti-das** [linkerd/linkerd#1936]
## Filing a Linkerd issue ##

Issue Type:

- [ ] Bug report
- [ ] Feature request

**What happened**:
Server-side l5d will see rare (<1%) ArrayIndexOutOfBoundsException errors when servicing high concurrency (>couple hundred req/sec) TLS traffic with the ForwardClientCertFilter enabled. Likely cause is [use of a singleton MessageDigest instance](https://github.com/linkerd/linkerd/blob/66fa4d24932f6ebbde401c83a1a84aaaf4fc0a43/router/base-http/src/main/scala/io/buoyant/router/http/ForwardClientCertFilter.scala#L16) by multiple threads, which is [known to be incorrect usage](https://bugs.openjdk.java.net/browse/JDK-8009635).

java.lang.ArrayIndexOutOfBoundsException
at sun.security.provider.DigestBase.engineUpdate(DigestBase.java:114)
at java.security.MessageDigest$Delegate.engineUpdate(MessageDigest.java:584)
at java.security.MessageDigest.update(MessageDigest.java:335)
at java.security.MessageDigest.digest(MessageDigest.java:410)
at io.buoyant.router.http.ForwardClientCertFilter.$anonfun$apply$1(ForwardClientCertFilter.scala:21)
at io.buoyant.router.http.ForwardClientCertFilter.$anonfun$apply$1$adapted(ForwardClientCertFilter.scala:18)

**What you expected to happen**:
No errors when servicing high concurrency TLS traffic.

**How to reproduce it (as minimally and precisely as possible)**:
Server-side l5d servicing high concurrency (>couple hundred req/sec) TLS traffic

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files:
- Platform, version, and config files (Kubernetes, DC/OS, etc):
- Cloud provider or hardware configuration:

**Comment by shakti-das** [comment]
We faced this issue recently and have a solution for it. Creating a PR with the same changes that fixed the internal issue.

**Comment by dadjeibaah** [comment]
@shakti-das thanks for filing this issue! PRs are always welcome :)

**Comment by dadjeibaah** [comment]
Hi @shakti-das, to make our DCO bot happy, do you mind signing off your last commit like so 
```bash
git commit --amend --no-edit -s
git push -f origin <branch name>
```
 
That should take your previous commit and added your signoff so you can pass the DCO bot check. Thanks!
