### ISSUE TITLE
Traffic to gRPC endpoints gradually stop being routed

### ISSUE THREAD

**Issue by yoitsro** [linkerd/linkerd#1958]
Issue Type:

- [x ] Bug report
- [ ] Feature request

**What happened**:
With linkerd being used as an ingress controller for gRPC, the daemonset gradually stops routing gRPC requests.

**What you expected to happen**:
Linkerd should not stop routing gRPC requests.

**How to reproduce it (as minimally and precisely as possible)**:
Our setup:
3 node Kubernetes cluster running linkerd in a daemonset.

**Anything else we need to know?**:
Stats for my daemonset over the past 7 days
![image](https://user-images.githubusercontent.com/3006852/40278591-be461f38-5c2b-11e8-88e2-fb8c23d5fa13.png)

There is currently nothing collecting the telemetry data.

**Environment**:
- linkerd/namerd version, config files:

This configuration is based on the concept of having an internal namespace and a public namespace. The public namespace contains publicly accessible microservices which talk to the internal microservices using linkerd as the mesh to link them all.

<details>
<summary>Configuration</summary>
<p>

```
admin:
  ip: 0.0.0.0
  port: 

namers:
- kind: io.l5d.k8s
  experimental: true
  host: localhost
  port: 8001

telemetry:
- kind: io.l5d.prometheus
- kind: io.l5d.recentRequests
  sampleRate: 0.25

usage:
  orgId: l5d-linkerd

routers:
- protocol: h2
  label: out-public
  experimental: true
  dtab: |
    /srv        => /#/io.l5d.k8s/production-public/grpc;
    /grpc       => /srv;
    /svc        => /$/io.buoyant.http.domainToPathPfx/grpc;
  identifier:
    kind: io.l5d.header.path
    segments: 1
  interpreter:
    kind: default
    transformers:
    - kind: io.l5d.k8s.daemonset
      namespace: production-l5d
      port: in-public
      service: "l5d-linkerd-internal"
  servers:
  - port: 4140
    ip: 0.0.0.0
    clearContext: true
    tls:
      certPath: /io.buoyant/linkerd/certs/tls.crt
      keyPath: /io.buoyant/linkerd/certs/tls.key

- protocol: h2
  label: in-public
  experimental: true
  dtab: |
    /srv        => /#/io.l5d.k8s/production-public/grpc;
    /grpc       => /srv;
    /svc        => /$/io.buoyant.http.domainToPathPfx/grpc;
  identifier:
    kind: io.l5d.header.path
    segments: 1
  interpreter:
    kind: default
    transformers:
    - kind: io.l5d.k8s.localnode
  servers:
  - port: 4141
    ip: 0.0.0.0

- protocol: h2
  label: out-internal
  experimental: true
  dtab: |
    /srv        => /#/io.l5d.k8s/production-internal/grpc;
    /grpc       => /srv;
    /svc        => /$/io.buoyant.http.domainToPathPfx/grpc;
  identifier:
    kind: io.l5d.header.path
    segments: 1
  interpreter:
    kind: default
    transformers:
    - kind: io.l5d.k8s.daemonset
      namespace: production-l5d
      port: in-internal
      service: "l5d-linkerd-internal"
  servers:
  - port: 4142
    ip: 0.0.0.0
    clearContext: true

- protocol: h2
  label: in-internal
  experimental: true
  dtab: |
    /srv        => /#/io.l5d.k8s/production-internal/grpc;
    /grpc       => /srv;
    /svc        => /$/io.buoyant.http.domainToPathPfx/grpc;
  identifier:
    kind: io.l5d.header.path
    segments: 1
  interpreter:
    kind: default
    transformers:
    - kind: io.l5d.k8s.localnode
  servers:
  - port: 4143
    ip: 0.0.0.0

- protocol: http
  label: http-out-int
  dtab: |
    /srv        => /#/io.l5d.k8s/production-internal/http;
    /host       => /srv;
    /svc        => /host;
  interpreter:
    kind: default
    transformers:
    - kind: io.l5d.k8s.daemonset
      namespace: production-l5d
      port: http-in-int
      service: "l5d-linkerd-internal"
  servers:
  - port: 4240
    ip: 0.0.0.0
    clearContext: true

- protocol: http
  label: http-in-int
  interpreter:
    kind: default
    transformers:
    - kind: io.l5d.k8s.localnode
  dtab: |
    /srv        => /#/io.l5d.k8s/production-internal/http;
    /host       => /srv;
    /svc        => /host;
  servers:
  - port: 4241
    ip: 0.0.0.0
```
</p>
</details>

- Platform, version, and config files (Kubernetes, DC/OS, etc):
Kubernetes v1.9.6
Linkerd 1.3.7

- Cloud provider or hardware configuration:
Google Container Engine

- Related issues:
https://github.com/linkerd/linkerd/issues/1730#issuecomment-386816067
https://github.com/linkerd/linkerd/issues/1582

**Comment by wmorgan** [comment]
Thanks, @yoitsro. We'll dig intpo this.

**Comment by dadjeibaah** [comment]
Thanks for filing this issue @yoitsro. Out of curiosity, do you have any log information that you could provide w.r.t the problematic linkerd instance(s)? Do you see any errors pop up when Linkerd stops routing gRPC traffic?

**Comment by yoitsro** [comment]
I have the logs, but I'll send them to you via Slack.

**Comment by adleong** [comment]
@yoitsro it's interesting that disk usage keeps growing like that.  Do you know where that disk usage is coming from?  Is there a particular file or directory that is growing?

**Comment by yoitsro** [comment]
Hey @adleong. I'm not sure where the disk usage is coming from. Next time an instance starts acting funny, I'll dig into it.

**Comment by adleong** [comment]
Thanks, @yoitsro.  It seems like disk usage is correlated with the issue so I think that's the easiest place to start.

**Comment by dadjeibaah** [comment]
@yoitsro, I took a look at the logs you sent me, and I didn't seem to find what the cause might have been. One thing that was weird was, Linkerd failed to connect to the `kubectl` proxy sidecar. I am not sure if it is a red herring, but I think it would be useful to view the container logs for the `kubectl` proxy to see if there is anything fishy going on.

**Comment by yoitsro** [comment]
It looks like the issue is surfacing again, albeit with the requests eventually getting through. It seems as though the connections to the gRPC services die, and then upon the first subsequent request, they eventually get routed again. I think that over time, reconnections stop happening altogether.

I found it interesting that the CPU usage of the kubectl pod increases, though not by much as far as actual CPU shares go!

![image](https://user-images.githubusercontent.com/3006852/40389985-aeb31f30-5e0b-11e8-8132-52055d6c808b.png)

**Comment by adleong** [comment]
@yoitsro any luck finding out where that disk usage is going?

**Comment by yoitsro** [comment]
I can't see anything. The disk usage increases rarely enough to make it difficult for me to track down.

I've just seen this error surface though:

```
I 0522 21:24:16.614 UTC THREAD10: Reaping /svc/hops.Organisations
I 0522 21:24:16.643 UTC THREAD10: Reaping %/io.l5d.k8s.localnode/10.8.2.177/#/io.l5d.k8s/production-public/grpc/organisations
W 0522 21:24:34.426 UTC THREAD17 TraceId:4aeff0294f9d06d6: Exception propagated to the default monitor (upstream address: /10.154.0.2:51653, downstream address: localhost/127.0.0.1:8001, label: client).
com.twitter.io.Reader$ReaderDiscarded: This writer's reader has been discarded
	at com.twitter.finagle.netty4.http.StreamTransports$$anon$1.discard(StreamTransports.scala:71)
	at com.twitter.finagle.http.DelayedReleaseService$$anon$2$$anon$3.discard(DelayedReleaseService.scala:58)
	at com.twitter.finagle.http.DelayedReleaseService$$anon$2$$anon$3.discard(DelayedReleaseService.scala:58)
	at io.buoyant.k8s.Watchable.$anonfun$watch$5(Watchable.scala:133)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at com.twitter.util.Try$.apply(Try.scala:15)
	at com.twitter.util.Future$.apply(Future.scala:166)
	at io.buoyant.k8s.Watchable.$anonfun$watch$4(Watchable.scala:133)
	at com.twitter.util.Closable$$anon$5.close(Closable.scala:144)
	at com.twitter.util.Closable$$anon$6.close(Closable.scala:148)
	at com.twitter.util.Var$$anon$4.$anonfun$closable$1(Var.scala:399)
	at com.twitter.util.Closable$$anon$5.close(Closable.scala:144)
	at com.twitter.util.Closable$.com$twitter$util$Closable$$safeClose(Closable.scala:67)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:125)
	at com.twitter.util.Closable$$anon$3.onTry$1(Closable.scala:122)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:128)
	at com.twitter.util.Closable$$anon$3.close(Closable.scala:134)
	at com.twitter.util.Closable$$anon$6.close(Closable.scala:148)
	at io.buoyant.k8s.Watchable.$anonfun$activity$10(Watchable.scala:299)
	at com.twitter.util.Closable$$anon$5.close(Closable.scala:144)
	at com.twitter.util.Var$$anon$4.$anonfun$closable$1(Var.scala:399)
	at com.twitter.util.Closable$$anon$5.close(Closable.scala:144)
	at com.twitter.util.Closable$.com$twitter$util$Closable$$safeClose(Closable.scala:67)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:125)
	at com.twitter.util.Closable$$anon$3.onTry$1(Closable.scala:122)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:128)
	at com.twitter.util.Closable$$anon$3.close(Closable.scala:134)
	at com.twitter.util.Closable$.com$twitter$util$Closable$$safeClose(Closable.scala:67)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:125)
	at com.twitter.util.Closable$$anon$3.close(Closable.scala:134)
	at com.twitter.util.Var$$anon$4.$anonfun$closable$1(Var.scala:399)
	at com.twitter.util.Closable$$anon$5.close(Closable.scala:144)
	at com.twitter.util.Closable$.com$twitter$util$Closable$$safeClose(Closable.scala:67)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:125)
	at com.twitter.util.Closable$$anon$3.onTry$1(Closable.scala:122)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:128)
	at com.twitter.util.Closable$$anon$3.close(Closable.scala:134)
	at com.twitter.util.Closable$.com$twitter$util$Closable$$safeClose(Closable.scala:67)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:125)
	at com.twitter.util.Closable$$anon$3.close(Closable.scala:134)
	at com.twitter.util.Closable$.com$twitter$util$Closable$$safeClose(Closable.scala:67)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:125)
	at com.twitter.util.Closable$$anon$3.close(Closable.scala:134)
	at com.twitter.util.Closable$.com$twitter$util$Closable$$safeClose(Closable.scala:67)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:125)
	at com.twitter.util.Closable$$anon$3.close(Closable.scala:134)
	at com.twitter.util.Closable$$anon$6.close(Closable.scala:148)
	at com.twitter.util.Closable$.com$twitter$util$Closable$$safeClose(Closable.scala:67)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:125)
	at com.twitter.util.Closable$$anon$3.onTry$1(Closable.scala:122)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:128)
	at com.twitter.util.Closable$$anon$3.close(Closable.scala:134)
	at com.twitter.util.Closable$$anon$6.close(Closable.scala:148)
	at com.twitter.util.Closable$.com$twitter$util$Closable$$safeClose(Closable.scala:67)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:125)
	at com.twitter.util.Closable$$anon$3.onTry$1(Closable.scala:122)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:128)
	at com.twitter.util.Closable$$anon$3.close(Closable.scala:134)
	at com.twitter.util.Closable$$anon$6.close(Closable.scala:148)
	at com.twitter.util.Closable$.com$twitter$util$Closable$$safeClose(Closable.scala:67)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:125)
	at com.twitter.util.Closable$$anon$3.onTry$1(Closable.scala:122)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:128)
	at com.twitter.util.Closable$$anon$3.close(Closable.scala:134)
	at com.twitter.util.Closable$$anon$6.close(Closable.scala:148)
	at com.twitter.util.Closable$.com$twitter$util$Closable$$safeClose(Closable.scala:67)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:125)
	at com.twitter.util.Closable$$anon$3.onTry$1(Closable.scala:122)
	at com.twitter.util.Closable$$anon$3.closeSeq(Closable.scala:128)
	at com.twitter.util.Closable$$anon$3.close(Closable.scala:134)
	at com.twitter.util.Closable.close(Closable.scala:20)
	at com.twitter.util.Closable.close$(Closable.scala:20)
	at com.twitter.util.Closable$$anon$3.close(Closable.scala:101)
	at com.twitter.util.Closable$$anon$1.run(Closable.scala:161)
W 0522 21:24:34.426 UTC THREAD17: retrying k8s request to /api/v1/namespaces/production-public/endpoints/organisations on error com.twitter.io.Reader$ReaderDiscarded: This writer's reader has been discarded
httputil: ReverseProxy read error during body copy: context canceled
```

Does that mean anything to you?

**Comment by adleong** [comment]
That error message is harmless and can be safely ignored.  It has been removed from the logs in Linkerd 1.4.0 (https://github.com/linkerd/linkerd/pull/1901).

**Comment by yoitsro** [comment]
Fair enough. At the moment, I'm struggling to track down the source of the increasing disk usage. If anyone else is experiencing a similar issue, I wonder if they've seen any increased disk usage.

**Comment by adleong** [comment]
@yoitsro can you use unix tools such as `du` to determine where the disk usage is going?

**Comment by yoitsro** [comment]
@adleong I've tried but there's nothing significant enough in size for me to track it down. Where does linkerd write its logs?

**Comment by adleong** [comment]
Standard out, by default

**Comment by wmorgan** [comment]
@yoitsro are you setting `httpAccessLog` in your config, or anything else like that?

**Comment by yoitsro** [comment]
I'm not. And I guess if I add it now, it'll require a restart and the problem will go away, right?

**Comment by yoitsro** [comment]
```
root@l5d-linkerd-5c6k2:/io.buoyant/linkerd/1.3.7# df
Filesystem     1K-blocks     Used Available Use% Mounted on
overlay         47259264 26238264  21004616  56% /
tmpfs            7702980        0   7702980   0% /dev
tmpfs            7702980        0   7702980   0% /sys/fs/cgroup
/dev/sda1       47259264 26238264  21004616  56% /etc/hosts
shm                65536        0     65536   0% /dev/shm
tmpfs            7702980        8   7702972   1% /io.buoyant/linkerd/certs
tmpfs            7702980       12   7702968   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            7702980        0   7702980   0% /sys/firmware
```

```
root@l5d-linkerd-5c6k2:/# du | sort -n -r
du: cannot access './proc/3246/task/3246/fd/4': No such file or directory
du: cannot access './proc/3246/task/3246/fdinfo/4': No such file or directory
du: cannot access './proc/3246/fd/3': No such file or directory
du: cannot access './proc/3246/fdinfo/3': No such file or directory
734128	.
630440	./usr
338152	./usr/lib
262828	./usr/share
167900	./usr/lib/x86_64-linux-gnu
116780	./usr/lib/jvm
116772	./usr/lib/jvm/java-8-openjdk-amd64
116744	./usr/lib/jvm/java-8-openjdk-amd64/jre
116168	./usr/lib/jvm/java-8-openjdk-amd64/jre/lib
101236	./usr/share/locale
59124	./usr/share/icons
47692	./io.buoyant
47688	./io.buoyant/linkerd
47664	./io.buoyant/linkerd/1.3.7
41588	./usr/share/icons/Adwaita
37300	./usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64
33076	./usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server
32968	./usr/share/doc
30888	./usr/share/vim
30868	./usr/share/vim/vim80
30580	./var
28392	./var/lib
27260	./usr/bin
24516	./usr/lib/python3.5
20568	./usr/lib/python2.7
16844	./usr/lib/x86_64-linux-gnu/dri
15948	./usr/share/icons/gnome
15828	./var/lib/apt
15792	./var/lib/apt/lists
13160	./lib
12852	./lib/x86_64-linux-gnu
12456	./var/lib/dpkg
11780	./usr/share/icons/Adwaita/cursors
11688	./var/lib/dpkg/info
10028	./usr/share/fonts
10024	./usr/share/fonts/truetype
10020	./usr/share/fonts/truetype/dejavu
.
.
.
```

**Comment by wmorgan** [comment]
Sounds like disk usage was a red herring.

**Comment by yoitsro** [comment]
I would agree. At the moment, the daemonset is still broken. I'm more than happy to grant temporary access to our set up if it'd help someone investigate.

**Comment by adleong** [comment]
@yoitsro sorry about the red hearing!

There are a few things to investigate next.
* Were you able to get the logs from the `kubectl proxy` pod as @dadjeibaah suggested?
* Can you tell me a bit more about what happens when Linkerd stops routing gRPC requests?  When you issue a request to Linkerd does it return an error response?  or hang?  or timeout?  can you supply some sample output from issuing some requests?
* Can you provide the output of `/admin/metrics.json` from a Linkerd that has stopped routing gRPC requests?

**Comment by yoitsro** [comment]
Here are the logs from the pod:
[kubectl.log.zip](https://github.com/linkerd/linkerd/files/2069968/kubectl.log.zip)

Here are the metrics:
[metrics.json.zip](https://github.com/linkerd/linkerd/files/2069992/metrics.json.zip)

Here's a trace from the iOS app:
```
Error Domain=io.grpc Code=16 "Received RST_STREAM with error code 2" UserInfo={io.grpc.HeadersKey={
}, NSLocalizedDescription=Received RST_STREAM with error code 2, io.grpc.TrailersKey={
    "l5d-success-class" = "1.0";
    via = "h2 linkerd, h2 linkerd";
}}
```

**Comment by adleong** [comment]
I see a lot of `http: proxy error: dial tcp 10.11.240.1:443: getsockopt: connection refused` in your `kubectl proxy` logs.  Is that the address of your Kubernetes API server?  If `kubectl` is not able to connect to the Kubernetes API then Linkerd will not be able to get up-to-date information about the location of pods.

**Comment by yoitsro** [comment]
That is the address of my Kubernetes API server. That explains a lot, but here it is with timestamps:

[kubectl.log.zip](https://github.com/linkerd/linkerd/files/2070054/kubectl.log.zip)

They seem to occur frequently, but then disappear quickly. Would it be helpful to see more recent logs?

**Comment by adleong** [comment]
Do the connection errors to the Kubernetes API correlate with times where Linkerd failed to route requests?

**Comment by yoitsro** [comment]
I'm not certain with these specific logs, but I've just been back to a time when I can remember linkerd failing, and there are none of the logs complaining about not being able to reach the API server.

**Comment by adleong** [comment]
It's hard to debug this because it's difficult to differentiate errors in Linkerd from errors in the application.  From your iOS logs we see that a client received a stream reset with code 2 (internal error).  We also see from the metrics that Linkerd sent a stream reset (internal error) on port 4140 but there are no client or service metrics to indicate where this error came from.  This is possibly because that service became idle and its metrics expired.

In order to debug this effectively, I think you need to isolate the problem a bit more.  If you look at logs (Linkerd, Kubectl, client application, and server application) immediately after the issue occurred, something might jump out at you.  You can also look at Linkerd's metrics immediately after the issue occurred and look for `reset` stats which are non-zero.  This should tell you where the reset is coming from.  If all else fails, you can look at tcpdumps of the H2 traffic and see if Linkerd is sending or receiving resets.

I hope this helps!

**Comment by yoitsro** [comment]
So I'm taking a look at the dashboard now and I can see that requests are being successfully received by linkerd, they're being received by the application, but then the application calls to linkerd again to reach the internal microservices contained in a different namespace. It seems to be at this point that the failure occurs.

The first request returns a `14 UNAVAILABLE: TCP Read failed` error.

Subsequent requests return a `Received RST_STREAM with error code 2` error.

So just to clarify, a typical request lifecycle would be as follows:

| external world | public linkerd ingress | public namespace | internal linkerd ingress | internal namespace |
| --- | --- | --- | --- | --- |
| give me data from service A | | | | |
| | route this request to service A in `public namespace` | | | |
| | | get data from internal service X | | |
| | | | route this request to service X in `internal namespace` | |
| | | | | retrieve data from database, manipulate it and return it |
| | | | <--- | |
| | | manipulate retrieved data and combine with other sources if necessary | | |
| | <--- | | | |
| handle data | | | | |

**Comment by yoitsro** [comment]
I can also see that the first failed request manages to reach the internal linkerd service, but subsequent requests don't seem to reach the internal service.

Is this an application level thing, or is this behaviour a result of linkerd deciding that because of the first failure, it's not going to try to route subsequent requests?

**Comment by yoitsro** [comment]
I've just been continually hitting the services and eventually, each service recovers. However, the services which have not been touched are still inaccessible.

Here are the logs:
[l5d.log.zip](https://github.com/linkerd/linkerd/files/2073746/l5d.log.zip)

**Comment by adleong** [comment]
`com.twitter.finagle.RequestTimeoutException: exceeded 10.seconds to 0.0.0.0/4142 while dyn binding /svc/internal.Shoals`

This error indicates that Linkerd was not able to resolve the service.  This could be because of the connectivity problem between `kubectl proxy` and the Kubernetes API.

**Comment by yoitsro** [comment]
Here are the logs from the kubectl instances:

[kubectl.log.zip](https://github.com/linkerd/linkerd/files/2073882/kubectl.log.zip)

**Comment by yoitsro** [comment]
And now requests to the services which were working are now failing again. Repeatedly requesting the services seems to eventually restore connectivity.

**Comment by yoitsro** [comment]
After chatting with @adleong, I've upgraded linkerd to version 1.4.1 and upgraded the kubectl sidecar to at least 1.8.5. That should allow for the new diagnostics metrics and perhaps some stability improvements.

I'll keep you updated. Thanks for your support and help so far.

**Comment by yoitsro** [comment]
An update:

Things seem much more stable. 5 days in and I've not had any problems yet. The high level metrics look good too:

![image](https://user-images.githubusercontent.com/3006852/41201428-bc7b4810-6caf-11e8-8823-4fdd5bf515c6.png)

Memory usage seems more stable and disk usage seems more stable (though I suspect this is down to Linkerd 1.4.1's reduced logging).

I can't explain the CPU 'spikes', but to be honest, the size of the spikes are relatively insignificant so I'm not worrying about it. Once it gets to 7 days with no problems, I'm happy to close this issue.

**Comment by wmorgan** [comment]
Still looking good?

**Comment by yoitsro** [comment]
It's looking good so far. Happy to close this but will let you know if we experience anything else strange. Thank you all!

**Comment by yoitsro** [comment]
An update - this kept happening. I've migrated to linkerd2 now, but it's really strange behaviour. Really wish I could have gotten to the bottom of it, but never mind!

**Comment by wmorgan** [comment]
Well... that's one way to fix the issue :)
