### ISSUE TITLE
Enable plugins to emit stat into L5D stat trees for Identifier 

### ISSUE THREAD

**Issue by leozc** [linkerd/linkerd#1963]
Issue Type:

- [ ] Bug report
- [ X] Feature request

This is the alternative code path for feature request similar to #1922 

1.  #1922  is done for `Announcer`
2. this bug is to track for `Identifier`

Here are the comments copied from #1922
We are writing multiple plugins for our L5D mesh, there are needs to initialize a finagle client to perform RPC, however there is no way to submit the stat into L5D metrics system.

Suggestion: Is it possible to enable this user scenario?

``` 
def getClient(withRequestTimeoutMS: Int =  1000 , addr: InetSocketAddress, path:Path): Service[http.Request, http.Response]  = {
    val monitor: Monitor = new Monitor {
      def handle(t: Throwable): Boolean = {
        logger.error(t, t.getMessage, t.getStackTrace)
        true
      }
    }
    val metrics = MetricsTree() // possible to get the metrics tree from global 
    val stats = new MetricsTreeStatsReceiver(metrics) // register this stat object to be collected?
    Http.client
      .withStatsReceiver(stats)
      .withHttpStats
      .withRequestTimeout(Duration.fromMilliseconds(withRequestTimeoutMS))
      .withMonitor(monitor)
      .newService(s"${addr.getHostName()}:${addr.getPort()}", "hc_client")

  }
```

**Comment by leozc** [comment]
```
https://github.com/linkerd/linkerd/blob/fe822302d38f249533d1af326ea06efd842bf9b4/linkerd/protocol/http/src/main/scala/io/buoyant/linkerd/protocol/HttpConfig.scala#L247
```
Here should be where the identifier being construed

**Comment by leozc** [comment]
PR: https://github.com/linkerd/linkerd/pull/1964

**Comment by leozc** [comment]
Reenable - pull the latest linkerd and debug through and found out the statReceiveer is NullStatReceiver:

Here is the corresponding section from `http://linkerd:9990/admin/registry.json`
```
            "NackAdmissionFilter" : {
              "statsReceiver" : "NullStatsReceiver/common_auth/l5d_authIdentifier",
              "window" : "2.minutes",
              "nackRateThreshold" : "0.5"
            },
```

**Comment by adleong** [comment]
@leozc Please take a look at https://github.com/linkerd/linkerd/compare/master...alex/params and let me know if that fixes it for you

**Comment by leozc** [comment]
Thanks @adleong , this seems to be a right fix - now I can also see `adminhttp/*` metrics in additional to private metrics.
