### ISSUE TITLE
Since 1.4.1 underscores in match patterns of io.l5d.rewrite no longer work

### ISSUE THREAD

**Issue by bkreitch** [linkerd/linkerd#1969]
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
Since 1.4.1 underscores in match patterns of io.l5d.rewrite no longer work:

Works:
```
- kind: io.l5d.rewrite
  prefix: /rewrite
  pattern: "/*/{service}"
  name: "/grpc/{service}"
```

Doesn't (worked in 1.4.0 and before):
```
- kind: io.l5d.rewrite
  prefix: /rewrite
  pattern: "/*/{service_name}"
  name: "/grpc/{service_name}"
```

**What you expected to happen**:
To work also with underscores as in 1.4.0 and before.

**How to reproduce it (as minimally and precisely as possible)**:

```
- kind: io.l5d.rewrite
  prefix: /rewrite
  pattern: "/*/{service_name}"
  name: "/grpc/{service_name}"
...
  dtab: |
    /svc => /#/rewrite;

```

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files:
Linkerd 1.4.1
- Platform, version, and config files (Kubernetes, DC/OS, etc):
- Cloud provider or hardware configuration:
Bare metal

**Comment by dadjeibaah** [comment]
Thanks for submitting this @bkreitch. We will take a look at this.
