### ISSUE TITLE
POSTing null routes to dtab succeeds

### ISSUE THREAD

**Issue by utrack** [linkerd/linkerd#1974]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
Adding `null` route succeeds.

**What you expected to happen**:
Either `400 Bad Request` or `null` route being omitted.

**How to reproduce it (as minimally and precisely as possible)**:
`curl -X 'POST' -d '[null,{"prefix":"/foo","dst":"/bar"}]' -H 'Content-Type: application/json' 'http://localhost:8001/api/v1/namespaces/linkerd/services/namerd:4180/proxy/api/1/dtabs/some-test-router' `
-- 200 OK

```
curl 'http://localhost:8001/api/v1/namespaces/linkerd/services/namerd:4180/proxy/api/1/dtabs/some-test-router'
[null,{"prefix":"/foo","dst":"/bar"}]
```

**Anything else we need to know?**:

**Environment**:
`buoyantio/linkerd:1.4.1` w/ namerd 1.4.1 on bare-metal k8s setup.

**Comment by dadjeibaah** [comment]
Thanks for submitting the issue @utrack! We will take a look at this.
