### ISSUE TITLE
Feature Request - Requests/Response logging

### ISSUE THREAD

**Issue by mikebz** [linkerd/linkerd#1979]
Issue Type:

- [ ] Bug report
- [x] Feature request

**What happened**:
I am trying to replace a home grown system that supports routing, retries and logging.  LinkerD handles routing, retries and many other things a lot better (plus we can leverage the community and learn/contribute).

The missing feature is request/response logging.  Obviously doesn't make sense to log everything but it would be nice to turn on request/response logging when something is not working.

**What you expected to happen**:
The way this feature would work is similar to tracing:
- developer could configure logging (maybe define a log target)
- whenever LinkerD picks up the config changes it would start logging out to that log target
- developer can then examine the logs in the target and see full requests/responses and be able to debug the issues.

**Environment**:
- this is a new feature so no platform, but I assume it would be something cross platform because logging is pretty universal.

**Comment by dadjeibaah** [comment]
@mikebz thanks for submitting this feature request. We love to see the community come up with feature requests such as this. We also love to see PRs from the community too! Would you be open to submitting a PR for this?

**Comment by adleong** [comment]
This could be done as a Request Authorizer plugin.

**Comment by mikebz** [comment]
@dadjeibaah I'd love to contribute, I am not a Scala developer though - if it was Python/Plain Java/C#/Node - I'd be of more help.

@adleong can you help me with a pointer on how to achieve that?  That'd be much appreciated.

**Comment by wmorgan** [comment]
We've got an example you may be able to crib from here:

https://github.com/linkerd/linkerd/blob/master/linkerd/protocol/http/src/main/scala/io/buoyant/linkerd/protocol/http/istio/IstioRequestAuthorizer.scala

(and 
https://github.com/linkerd/linkerd/blob/master/istio/src/main/scala/io/buoyant/k8s/istio/IstioRequestAuthorizerFilter.scala and some other related files)

**Comment by wmorgan** [comment]
We've got an example you may be able to crib from here:

https://github.com/linkerd/linkerd/blob/master/linkerd/protocol/http/src/main/scala/io/buoyant/linkerd/protocol/http/istio/IstioRequestAuthorizer.scala

(and 
https://github.com/linkerd/linkerd/blob/master/istio/src/main/scala/io/buoyant/k8s/istio/IstioRequestAuthorizerFilter.scala and some other related files)

And docs on how to build plugins are here: https://linkerd.io/advanced/plugin/

**Comment by adleong** [comment]
Given that the exact logging needs will vary quite a bit from user to user, I think this probably makes more sense as a 3rd party plugin rather than something built into Linkerd directly.  @mikebz does that make sense to you?

**Comment by mikebz** [comment]
Yes that makes sense.  I think after digging into this for a minute I figured that for me to contribute I need to get up to speed on Scala, the configuration system and also the logging system.  I don't know if I am the best candidate for implementing this feature, but all your guys' comments are spot on.

**Comment by adleong** [comment]
I'm going to close this issue since I don't think there's anything to be done here for Linkerd itself.  If you do put together a logging plugin we'd be more than happy to add it to the list of external plugins: https://github.com/linkerd/linkerd/blob/master/PLUGINS.md
