### ISSUE TITLE
gRPC default response classifier is incomplete

### ISSUE THREAD

**Issue by rmichela** [linkerd/linkerd#1993]
Issue Type:

- [ ] Bug report
- [X] Feature request

The `io.l5d.h2.grpc.default` response classifier is incomplete in its classification of retryable gRPC responses. According to the gRPC specifications, the following events are considered retryable:

* [gRPC `UNAVAILABLE` response](https://github.com/grpc/proposal/blob/master/A6-client-retries.md)
* [HTTP/2 429, 502, 503, and 504 responses](https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md)
* [HTTP/2 `RST_STREAM:REFUSED_STREAM`](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#errors)

The `default` response classifier only retries the first case, where a gRPC server explicitly issues an `UNAVAILABLE` response. This happens when requests are received by the server while it is in the process of shutting down. gRPC`UNAVAILABLE` responses can also be returned explicitly by the service developer to signal availability.

The second case occurs when intermediate HTTP/2 forward or reverse proxies fail, but don't understand the gRPC protocol. Raw HTTP/2 responses are returned instead.

I found the third case occurs when two L5d instances sit between a client and server (one on each side of the connection), and the server-side L5d encounters an error talking to the Server. We saw this in a partially initialized Kubernetes pod, where L5d was running but the service container was in a crash-backoff loop. In this scenario, the client-side L5d observed a `RST_STREAM:REFUSED_STREAM` when the client tried to connect. The HTTP/2 connection between the client and server L5ds was fine, but the individual streams within that connection were failing.

**Comment by adleong** [comment]
Fixed by #1994
