### ISSUE TITLE
Malformed HTTP/2 responses break Linkerd

### ISSUE THREAD

**Issue by rmichela** [linkerd/linkerd#2004]
Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:
If L5d receives an HTTP/2 response with an invalid response code, multiple internal exceptions are thrown and the process can no longer be terminated using CTRL+C. Killing L5d with a SIGTERM results in even more exceptions.

**What you expected to happen**:
L5d correctly handles the malformed response, passing it off to response classification for possible retry.

**How to reproduce it (as minimally and precisely as possible)**:
1. I wrote a Jetty HTTP/2 service to intentionally respond with errors.
2. I set the error service to respond with response code 14, which is an invalid HTTP/2 response code.
3. Using filesystem discovery, I configured L5d to proxy requests to the error service.

**Anything else we need to know?**:

Reproducing program and stack trace are at https://gist.github.com/rmichela/1b8ac226c9c3336862ccc373831d8632

**Environment**:
- linkerd/namerd version, config files: Linkerd 1.4.3

**Comment by dadjeibaah** [comment]
Hi, @rmichela thanks for filing this issue. We have taken a look at it and have this WIP PR you can track or leave any helpful feedback. Thanks again!
