### ISSUE TITLE
Increased service latency when collecting stats with large number of services

### ISSUE THREAD

**Issue by chrisgoffinet** [linkerd/linkerd#2009]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
When collecting stats from /admin/metrics.json or the /admin/metrics/prometheus we see added latency at the high percentiles (p999, max).  This happens with a large number of services (I picked 800 for example)

We noticed when using /admin/metrics/prometheus it makes it even worse. We observe through `slow_cooker` and other clients added overhead.
 
**What you expected to happen**:
Not increase p999, max latency.

**How to reproduce it (as minimally and precisely as possible)**:

1. setup linkerd w/ dtab below
2. use `slow_cooker` with -interval 1s -qps 100 -concurrency 10 -host <generate a list of 800 names comma separated> http://linkerd:8080
3. give it about 2 minutes to setup all stats
4. watch the slow_cooker latency, you should see <10ms
5. start curling /admin/metrics.json every second, the max will goto about 70ms~
6. if you start curling the /admin/metrics/promethesus endpoint the slow_cooker latency will go even higher

I also confirmed seeing a higher `request_latency.max` from the stats being a bit higher than `slow_cooker` but its very easy to see a push in latency by just hitting those endpoints. If you stop curling all together the latency DROPs back <10ms

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files:
```admin:
  port: 9990
  ip: 0.0.0.0

telemetry:
- kind: io.l5d.prometheus

routers:
- protocol: http
  client:
    failureAccrual:
      kind: none
  dtab: |
    /svc/* => /$/inet/172.18.0.3/80;
  servers:
  - port: 8080
    ip: 0.0.0.0
```

- Platform, version, and config files (Kubernetes, DC/OS, etc):
- Cloud provider or hardware configuration:

**Comment by adleong** [comment]
Thanks, @chrisgoffinet!  I will reproduce this locally and start investigating.  Serving a large number of metrics means a lot of string allocation... do you have evidence for or against the latency being GC related?

**Comment by chrisgoffinet** [comment]
@adleong interesting point. I am using the defaults which sets `Xms` to 32MB and grows to 1gb. I re-ran the tests and forced `Xms == Xmx` and latency for /admin/metrics.json went from 70ms to <30ms.

I took your PR#2006, latency went down there too. So that helped.

**Comment by chrisgoffinet** [comment]
I think what's going on here is that `/admin` runs in the same Finagle/netty pool of critical path of requests. Since we are looking at tail latencies -- when running those endpoints it makes sense that if a request tried to come in it would be blocked until the handlers in Admin finished processing the stats output which currently do take anywhere from 70ms to 300ms depending what's being run (/admin/metrics vs /admin/metrics/prometheus)

**Comment by zackangelo** [comment]
I think a secondary issue we may be observing is that the data structures required to write out the prometheus response are taking up a relatively large amount of heap. In this dump below, you can see that although they are marked for collection, there's ~48MB of responses sitting in the heap. 

![image](https://user-images.githubusercontent.com/688990/41678511-17822fd0-7480-11e8-996c-16ffc9feaec2.png)

For this particular instance, the current committed heap is 212MB so it represents roughly 23%. 

One thing that's puzzling is that even though we have the max heap set to 1GB the JVM has not raised the committed heap on any of our instances. We'll definitely tune around this by setting `Xms=Xmx`. But I suspect that either these responses are unnecessarily fragmenting the young generation or the JVM allocator may be deciding to drop these buffers directly into the old generation.

**Comment by chrisgoffinet** [comment]
@adleong Thanks for the quick turn around on this! Here is a graph after applying the PR #2010.

We can close this out after this gets merged. Latency dropped to <10ms as expected!

![linkerd client latency](https://user-images.githubusercontent.com/26450453/41688042-688edad0-74b8-11e8-92c9-3dab80001151.png)

**Comment by zackangelo** [comment]
Related to the previous comment, it does appear that linkerd is a lot happier with a constant committed heap.

The dramatic drop in full GCs (indicated by red triangles) can be seen here: 
![image](https://user-images.githubusercontent.com/688990/41691529-e961e16a-74af-11e8-81b3-ebd366ac8288.png)

**Comment by zackangelo** [comment]
GC performance seems much improved on a node we're running with Alex's two PRs. In the three hours we've been running it we've only seen _one_ full GC 😮:

<img width="672" alt="screen shot 2018-06-21 at 2 19 09 pm" src="https://user-images.githubusercontent.com/688990/41746295-a807b046-755e-11e8-819a-a7b7ab9ccb98.png">

**Comment by adleong** [comment]
Can we close this now that https://github.com/linkerd/linkerd/pull/2006 has merged?

**Comment by chrisgoffinet** [comment]
Yes go ahead.
