### ISSUE TITLE
merge conduit into linkerd as linkerd 2.0

### ISSUE THREAD

**Issue by wmorgan** [linkerd/linkerd#2018]
(As discussed on the Linkerd maintainers mailing list)

This is a tracking ticket for merging Conduit (https://github.com/runconduit/conduit) into the Linkerd org, as the basis of Linkerd 2.0. 

cc @adleong @olix0r @rmars @Ashald @zackangelo @ccmtaylor

**Comment by olix0r** [comment]
The conduit repo has been [moved](https://github.com/runconduit/conduit/pull/1298) to github.com/linkerd/linkerd2. The github.com/linkerd/linkerd2-proxy repo has been split out, containing the rust proxy; and the github.com/linkerd/linkerd2-proxy-api repo has been split out containing only the gRPC bindings (and related utilities) needed by the proxy and core projects.

Once basic docs (README, etc) have been restored and the proper access groups have been established, the repos will be unlocked. The github.com/linkerd/linkerd2 repo still needs a fair amount of work before Linkerd 2.0-RC1 can be released.
