### ISSUE TITLE
Consul namer returns Single IP if node provides a hostname

### ISSUE THREAD

**Issue by leozc** [linkerd/linkerd#2030]
Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:
Consul namer returns a single IP address even the hostname in the node is backed by multiple address (e.g. ELB A record)

**What you expected to happen**:
Return a list of IPs of the DNS record and hence it can be used by client side load balancing in later stage

**How to reproduce it (as minimally and precisely as possible)**:
1. consul contains a single return, which the host is a host name => e.g. microsoft.com
2. Namerd points to consul
3. Use Dtab tool to resolve the path.

**Anything else we need to know?**:
IMHO, it is an interesting context, should we ever use host name in the host filed in Consul? DNS is a separate level redirection hierarchy this brings additional implication.
 
**Environment**:
- linkerd/namerd version, config files: latest version
- Platform, version, and config files (Kubernetes, DC/OS, etc): EC2 ony
- Cloud provider or hardware configuration: AWS

**Comment by leozc** [comment]
May be worth to note  InetAddress.getAllByName does return IPv4 and IPv6 address entries for the same host - we may want to add a parameter to indicate which class of address to use.

```
$ export _JAVA_OPTIONS="-Djava.net.preferIPv4Stack=true"
$ scala
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Welcome to Scala 2.12.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> import java.net.{InetAddress, InetSocketAddress, UnknownHostException}
import java.net.{InetAddress, InetSocketAddress, UnknownHostException}

scala> InetAddress.getAllByName("api.mixerbox.com").toTraversable.map(singleIP => new InetSocketAddress(singleIP, 443))
res0: Traversable[java.net.InetSocketAddress] = ArrayBuffer(api.mixerbox.com/54.88.94.148:443, api.mixerbox.com/54.152.138.221:443, api.mixerbox.com/107.23.90.88:443)
```

without the IPv4 only Option
```
scala> InetAddress.getAllByName("api.mixerbox.com").toTraversable.map(singleIP => new InetSocketAddress(singleIP, 443))

scala> InetAddress.getAllByName("api.mixerbox.com").toTraversable.map(singleIP => new InetSocketAddress(singleIP, 443))
res22: Traversable[java.net.InetSocketAddress] = ArrayBuffer(api.mixerbox.com/54.88.94.148:443, api.mixerbox.com/107.23.90.88:443, api.mixerbox.com/54.152.138.221:443, api.mixerbox.com/2600:1f18:6705:7c1f:7c20:eac8:de83:4048:443, api.mixerbox.com/2600:1f18:6705:7c18:732e:d3c0:71:4862:443, api.mixerbox.com/2600:1f18:6705:7c20:6a79:c479:c7e0:b573:443)
```

**Comment by adleong** [comment]
@leozc was there a problem with returning both IPv4 and IPv6?  I haven't specifically tested IPv6 but, at least theoretically, it should work.

**Comment by leozc** [comment]
It works - my concern may be artificial - as in the example on working with
ELB, each ELB instance returns one IPv4 and IPv6 address - from load
balancing prospective - it should still fine.

Leo

**Comment by leozc** [comment]
Fixed
