### ISSUE TITLE
l5d-add-context TRACE: ignore server esponse if chunked response is returned

### ISSUE THREAD

**Issue by utrack** [linkerd/linkerd#2038]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
I've tried to do an -XTRACE on a server that always responds with chunked messages, expecting a trace output - but I've received HTTP 500.
```
* Rebuilt URL to: http://some-host.ozon.ru/
*   Trying ip-here...
* TCP_NODELAY set
* Connected to some-host.ozon.ru (ip-here) port 80 (#0)
> TRACE / HTTP/1.1
> Host: some-host.ozon.ru
> User-Agent: curl/7.60.0
> Accept: */*
> l5d-add-context: 1
> Content-Type: text/json
>
< HTTP/1.1 502 Bad Gateway
< l5d-err: Cannot+set+content+on+Chunked+message
< Content-Length: 37
< Content-Type: text/plain
<
* Connection #0 to host some-host.ozon.ru left intact
Cannot set content on Chunked message
```

**What you expected to happen**:
Tracing info should be returned

**How to reproduce it (as minimally and precisely as possible)**:
`curl -v -XTRACE -H 'l5d-add-context: 1' -H 'Host: some-host.ozon.ru' -H 'Content-Type: text/json' 'http://some-host.ozon.ru'`
where `some-host.ozon.ru` returns chunked response.

**Anything else we need to know?**:
I understand that the response of server is forwarded by proxy in case there's another linkerd proxy behind the resolved IP - but it's a good idea to discard a response if it's chunked and return what proxy had resolved up to this point instead of crashing to HTTP 500.

**Environment**:
- linkerd/namerd version, config files: v1.4.2

**Comment by dadjeibaah** [comment]
@utrack thanks for filing this! You are right that Linkerd should handle chunked responses as a special case when running a diagnostic trace. We will work on fixing this.
