### ISSUE TITLE
Can namerd namespaces contain slashes?

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#205]
Either we should forbid slashes in namerd namespaces, or we should ensure that storage mechanisms (i'm looking at you, zk) handle slashes properly

**Comment by adleong** [comment]
namespaces may contain slashes.  zk treats the name as a path.  this means that to create `foo/bar/bas`, `foo` and `foo/bar` must already exist

**Comment by gtcampbell** [comment]
Currently, k8s storage can *not* handle slashes.

**Comment by adleong** [comment]
closed in favor of #848
