### ISSUE TITLE
Add a Linkerd docker build with Eclipse's OpenJ9 JDK to release artifacts

### ISSUE THREAD

**Issue by dadjeibaah** [linkerd/linkerd#2058]
Preliminary experiments in #1881 show that Linkerd can work with OpenJ9. However, there is more testing and vetting that needs to be done to make sure it is a viable option for users. In an effort expose this new configuration for testing, we need to add the OpenJ9 JDK into the build assembly process so that we release docker images with the JDK. This change is depending on #2057 as there are changes in Finagle 18.7.0 that are needed to get Linkerd to work with the JDK.

**Comment by olix0r** [comment]
FWIW, this *should* (in theory) be as easy as setting the [`dockerJavaImage`](https://github.com/linkerd/linkerd/blob/master/project/Base.scala#L190) setting at build-time

**Comment by dadjeibaah** [comment]
True. The idea was to have the configuration similar to the `LowMem` docker image build process. Or we could manually use the dockerJavaImage setting at build time and push the images manually.
