### ISSUE TITLE
namerd: Support linkerd2-proxy's discovery interface

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#2060]
[`linkerd2-proxy`](https://github.com/linkerd/linkerd2) supports discovery via the [`io.linkerd.proxy.Destination`](https://github.com/linkerd/linkerd2-proxy-api/blob/master/proto/destination.proto) gRPC service.

Namerd can likely implement this interface over its interpreters so that existing Linkerd deployments can start experimenting with linkerd2-proxy.

This likely requires a new identifier-like interface that maps destination requests names to paths.

**Comment by wmorgan** [comment]
cc @Ashald @zackangelo. This might be a starting point for using the linkerd2 proxy outside of K8s.

**Comment by adleong** [comment]
My guess is that this would allow global dynamic routing by updating the dtabs in namerd.  But I don't believe this API allows per-lookup, or per-request overrides of any kind.

**Comment by Ashald** [comment]
Hm, do you think it's possible per-request dynamic routing will work ever with linkerd2-proxy & namerd? We rely on that feature heavily.

**Comment by adleong** [comment]
Unclear.  There are still a lot of more fundamental pieces to routing that need to be nailed down for Linkerd2.

**Comment by dadjeibaah** [comment]
As of 1.4.6, Namerd now implements the destination API from Linkerd 2 https://github.com/linkerd/linkerd/pull/2091. Closing this issue.
