### ISSUE TITLE
where can I find the utility namer, example /$/io.buoyant.rinet  /$/inet/?

### ISSUE THREAD

**Issue by carlo8090** [linkerd/linkerd#2061]
# Thanks for your help improving the project! #

My outgoing config:
    /ph => /$/io.buoyant.rinet ;
    /srv => /ph/80 ; 
    /srv => /$/io.buoyant.porthostPfx/ph ; 
    /srv => /#/io.l5d.k8s/default/http ;
    /svc => /srv ;

But I Do not understand the  /$/io.buoyant.rinet meaning, I not fount it  in the document ，who can tell me the url?[doc](https://linkerd.io/config/head/linkerd/index.html#rewriting-namers)

**Comment by wmorgan** [comment]
Hm, I don't think the `rinet` namer is documented anywhere. We should fix that. The short story is that it does a DNS lookup.

In the dtab config you give, Linkerd will first look for a service name in Kubernetes (in the `default` namespace only), then will fall back to a DNS lookup, using port 80 if not specified.
