### ISSUE TITLE
x-forwarded-client-cert in external request isn't (always) filtered out

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd#2068]
- [x] Bug report

**What happened**:

linkerd doesn't remove the `x-forwarded-client-cert` header field from inbound requests.

**What you expected to happen**:

When linkerd receives a `x-forwarded-client-cert` header field in a request, it must remove it or it must reject the request. It must never forward the `x-forwarded-client-cert` header field because that would allow any client to forge the identity of other clients if the inner application is relying on the `x-forwarded-client-cert` header field. (Also some applications may look at the `x-forwarded-client-cert` to determine if the request was sent over HTTPS or HTTP.)

**Anything else we need to know?**:

This could be a security-sensitive issue for any application relying on the `x-forwarded-client-cert` being accurate.

This filtering probably must happen regardless of the setting that enables linkerd's injection of the header field.

There may be other header fields that need to be always replaced/filtered in a similar way.

**Comment by dadjeibaah** [comment]
I am curious to know if there are certain cases where we want this behavior to happen and whether it should be tied to a configuration setting.  Could the `x-forwarded-client-cert` be cleared when `clearContext` is set to true? i.e. When Linkerd is configured for ingress?

**Comment by adleong** [comment]
I can't think of any case where we'd want to forward the `x-forwarded-client-cert`, internally or at the edge.  @dadjeibaah did you have a scenario in mind where forwarding that header _would_ be appropriate?

**Comment by dadjeibaah** [comment]
IIUC, based on #1153,  the `x-forwarded-client-cert` is intended to allow downstream services make some decision about a request forward by a TLS terminated Linkerd. If you had two Linkerd's routing a request in a servicemesh configuration, the first Linkerd (outgoing) would generate the header but, the second Linkerd (incoming) would clear that header and the terminal service would not be able to handle the request appropriately. Would that scenario be affected by this change?
