### ISSUE TITLE
Question: Current state of Istio integration?

### ISSUE THREAD

**Issue by krancour** [linkerd/linkerd#2092]
I'm wondering what the current state of integration with the Istio control plane is, with that project having just gone 1.0 and, I'm assuming, including breaking changes.

Is continuing the Istio integration work started in 1.1.1 and continued in 1.3.1 an ongoing project goal?

**Comment by wmorgan** [comment]
The current state is that Istio support hasn't really advanced beyond the work in 1.1.1 (the 1.3.1 thing was a one-off to support a specific API). Linkerd's Istio integration effectively deprecated and we should probably mark it as such, outside of the the 1.3.1 precondition check stuff. Though if there are more specific API features like that, I'm certainly not opposed to adding them.

**Comment by krancour** [comment]
@wmorgan can you comment at all on why Istio integration would be deprecated? There's no judgement implied in the question-- just curiosity. A Bouyant blog post from a year ago proposed that Istio (its control plane) and Linkerd complemented one another like peanut butter and jelly. That seemed to make sense, so I'm just trying to wrap my head around what changed.

**Comment by wmorgan** [comment]
In short, we never found anyone who was actually interested in using it. (Plus it was a huge amount of work and there were some real impedance mismatches.)

Do you have a specific use case for Linkerd + Istio? Or is this more of an academic question?

**Comment by krancour** [comment]
It's _partly_ academic. I have seen a lot of Istio v Linkerd comparison, but based on the blog post I referenced, I'd believed them to be complementary.

Linkerd does not seem to expose its own control plane via k8s CRDs, which makes it harder to configure the mesh through a manifest or a Helm chart, for instance. (Although, I guess, maybe this can be done via ConfigMaps?) To the extent that I understood Istio to be providing a universal service mesh control plane (or attempting to), I quite enjoyed the notion of policies being decoupled from the underlying mesh via such an abstraction. I was looking forward to someday using those CRDs (or similar) with a mesh of my choosing, or even better, allowing me to configure policies without having to even know that the underlying mesh _is_.

Linkerd's integration with Istio had seemed to speak to that vision.

**Comment by wmorgan** [comment]
That sounds 100% academic :)

If we mark this integration as deprecated we should probably also put a note on the blog post.

**Comment by wmorgan** [comment]
Addressing in #2103.
