### ISSUE TITLE
Documentation site is broken (HTTP 404 to css file)

### ISSUE THREAD

**Issue by vguhesan** [linkerd/linkerd#2093]
Hello - looks like one of the needed style sheets is not there for the documentation site to render correctly.

You will see it if you visit this link: 
[https://linkerd.io/1/advanced/routing/](https://linkerd.io/1/advanced/routing/)

Link to missing 404:
[https://linkerd.io/css/gen/index-61bcae7.css](https://linkerd.io/css/gen/index-61bcae7.css)

![screencapture-linkerd-io-1-configuration-2018-08-07-16_05_59 1](https://user-images.githubusercontent.com/193960/43799569-e3f53ad4-9a5b-11e8-9b66-c13ddc18bda0.png)

I know it's not a BIG deal for me to read but when first timers are looking and evaluating Linkerd - for them a snazzy site will create the eye appeal to consider this product over some other open source option. And sometime curb-appeal makes all the difference.

Thanks

**Comment by grampelberg** [comment]
Well that's embarrassing. Should be back to working now. Thank you for the report!

**Comment by vguhesan** [comment]
@grampelberg Sorry to bring this up - but now I'm seeing SCSS errors on other parts of the site.

Example links:
[https://linkerd.io/](https://linkerd.io/)
[https://linkerd.io/1/advanced/dtabs/](https://linkerd.io/1/advanced/dtabs/)

![2018-08-07_16-25-25](https://user-images.githubusercontent.com/193960/43800532-91ee4ea8-9a5e-11e8-8316-efc2f7091dd2.jpg)

**Comment by grampelberg** [comment]
@vguhesan this isn't my day apparently. It *should* be working for reals now and I believe I've got a permanent solution to make sure this never happens in the future.

(tldr. is that I'm fighting with sass locally, the *.css is cached, CDN isn't flushing the cache because the name isn't changing)

**Comment by adleong** [comment]
Thanks for the report, @vguhesan!  Please let us know if you see something like this again.
