### ISSUE TITLE
Error rate of DnsSrvNamer goes up for long running namerd process

### ISSUE THREAD

**Issue by leozc** [linkerd/linkerd#2095]
PR (work in progress) #2111 
Issue Type:

- [X] Bug report
- [ ] Feature request

Version: namerd 1.4.5

**What happened**:
Our Namerd cluster setup and to support SRV Namerd, the SRV Namerd works perfectly fine initially and then error rate goes up till it starts to fail resolving consistently;

**What you expected to happen**:
It should work fine for prolong period.
<img width="1919" alt="screen shot 2018-08-09 at 4 20 33 am" src="https://user-images.githubusercontent.com/1513416/43895928-d8526752-9b8b-11e8-9440-c879ee83819d.png">

**How to reproduce it (as minimally and precisely as possible)**:
It shows up in our staging and integration environments, which can take from 1 - 3 days to surface.
SRV record: implemented in Route53 (AWS)

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files:
`admin:
  port: 9990
  ip: 0.0.0.0

namers:
  - kind: io.l5d.rewrite
    prefix: /io.l5d.rewrite
    pattern: "/{dc}/{stage}/{service}"
    name: "/#/io.l5d.dnssrv/{service}.{stage}.offerup.services"

  - kind: io.l5d.dnssrv
    experimental: true
    refreshIntervalSeconds: 5

  - kind: io.l5d.consul
    host: consul.staging.offerup.services
    experimental: true
    port: 8500
    includeTag: true
    setHost: false
storage:
  kind: io.l5d.consul
  host: consul.staging.offerup.services
  experimental: true
  port: 8500
  pathPrefix: /namerd/staging/dtabs
  datacenter: us-east-1
  failFast: true
  readConsistencyMode: stale
  writeConsistencyMode: stale
interfaces:
  - kind: io.l5d.thriftNameInterpreter
    ip: 0.0.0.0
    port: 4100
  - kind: io.l5d.httpController
    ip: 0.0.0.0
    port: 4180

telemetry:
- kind: io.l5d.prometheus
`
- Platform, version, and config files (Kubernetes, DC/OS, etc):
AWS

Note: attached the Grafana dash to show the data;

**Comment by leozc** [comment]
This shows the DNS record is there but Namerd failed to resolve - please note when it fails - it doesn't fail all destination but only a random specific one (e.g. while resolving foo1.srv.bar fails ,  foo2.srv.bar can be resolvable - the failure is partial.

<img width="1920" alt="fail-resolve" src="https://user-images.githubusercontent.com/1513416/43896005-2b3a3ba2-9b8c-11e8-9e7b-90f628341dda.png">

<img width="628" alt="r53" src="https://user-images.githubusercontent.com/1513416/43896006-2b4d1218-9b8c-11e8-8255-b2fc3a15566e.png">

**Comment by leozc** [comment]
When a namerd got into an error status
We can see this from tracing

`Aug 09 11:30:24 ip-172-25-181-97 namerd[14732]: D 0809 11:30:24.778 UTC THREAD10 TraceId:d92a95fa1320eb49: SRV lookup failure: no results for webapp.staging.offerup.services`

And from DTAB
<img width="1446" alt="screen shot 2018-08-09 at 4 31 39 am" src="https://user-images.githubusercontent.com/1513416/43896363-5f98eb90-9b8d-11e8-92a6-17d6446422a7.png">

After restarting
<img width="1440" alt="screen shot 2018-08-09 at 4 32 27 am" src="https://user-images.githubusercontent.com/1513416/43896372-66b56ba6-9b8d-11e8-826a-7d23bc552d68.png">


Hence I am pretty sure the bug is in where SRV namer

**Comment by leozc** [comment]
Added:
`Environment="JVM_OPTIONS=-Dsun.net.inetaddr.ttl=30 -Djava.net.preferIPv4Stack=true"` to namerd startup script and continue to monitor...

**Comment by dadjeibaah** [comment]
Thanks for filing this @leozc, Let us know if you run into the issue after settings change.

**Comment by leozc** [comment]
Add more verbose logging:

```Aug 09 17:56:58 ip-172-25-181-97 namerd[20367]: D 0809 17:56:58.491 UTC THREAD9 TraceId:981ecf34ec0ff32b: SRV lookup failure: no results for shipping.staging.offerup.services return type: 4 address: shipping.staging.offerup.services```

4 means
```
/** The host exists, but has no records associated with the queried type. */
public static final int TYPE_NOT_FOUND = 4;
```

**Comment by leozc** [comment]
When capturing the packet:
```sudo tshark -f "udp port 53"```
for the DNS experiencing the bug - I cannot see the query being dispatched

yet for normal one I do see the proper response:
```
  581 150.320323586 172.25.181.97 → 172.25.0.2   DNS 91 Standard query 0x5e38 SRV webapp.staging.offerup.services
  582 150.323167736   172.25.0.2 → 172.25.181.97 DNS 139 Standard query response 0x5e38 SRV webapp.staging.offerup.services SRV 1 1 4141 ip-172-25-41-71.ec2.internal
```

**Comment by adleong** [comment]
Very interesting.  @ccmtaylor any ideas?  Have you seen anything like this before?

**Comment by ccmtaylor** [comment]
> Very interesting. @ccmtaylor any ideas? Have you seen anything like this before?

no, we haven't seen this behaviour. Our setup is a bit different though; we don't run namerd and configure linkerd to use the dnssrv directly.

@leozc, in your debugger screenshot, is the cache you highlighted part of the dnsjava library? NXRRSET is a very unexpected response from the DNS server: afaict, it's related to dyndns updates, so I don't know how that should occur. The value of the `expire` field looks like a timestamp. This is just a guess, but if dnsjava is caching bad responses for a long time (could be verified by comparing that timestamp to "now"), that may explain the behaviour we're seing here.

@leozc another question: are the "SRV lookup failure: no results for ..." log messages repeated every refresh interval, or do you see the message once, and then namerd is stuck forever?

**Comment by leozc** [comment]
It seems it is related to the cache in the DNS.Lookup cache - which if I
disabled the cache (set it null), the code works fine (in past 6 hours)

I also investigated the bad response - as far as I can tell - the TTL looks
reasonable.

As it is for now - I am 90% sure it is cache related.

NXRRSET is from route53 - this is so far I can tell ...
Christopher Taylor <notifications@github.com>于2018年8月14日 周二03:58写道：

**Comment by leozc** [comment]
Still some problems - go deeper in the problem by digging into Lookup class within dnsjava lib - when a DNS gets into an issue - in the response we observed SOA record instead of a SRV record (!) - when I intercepted the code path - manually run the query again (resolver,send(query) before the actual query code path - the resolver returns correct result and THEN the subsequent resolution is also correct  -- amazing - seems some serious pollution somewhere

![screen shot 2018-08-20 at 2 54 35 pm](https://user-images.githubusercontent.com/1513416/44368839-0f5c9280-a489-11e8-8395-f7903b4f390d.png)

**Comment by dadjeibaah** [comment]
That is strange @leozc, you should be seeing a lookup for a non-existent DNS to always be called based on the `refreshInterval` configured for the DNS Namer. The Lookup is always executed and is not dependent on the results of the DNS query. One way to verify that the namer is periodically running the lookup is to view the DNS namer stats on `admin/metrics.json` and look for the `lookup_failures_total` field. That total should be always increasing.

**Comment by leozc** [comment]
@dadjeibaah 

> That is strange @leozc, you should be seeing a lookup for a non-existent DNS to always be called based on the refreshInterval configured for the DNS Namer. The Lookup is always executed and is not dependent on the results of the DNS query. One way to verify that the namer is periodically running the lookup is to view the DNS namer stats on admin/metrics.json and look for the lookup_failures_total field. That total should be always increasing.

This is what I thought, but the fact is - it is not the case - for domain name doesn't exist - it looks up and fail then never retry 

The trace looks like this:
> Aug 21 01:56:27 ip-172-25-182-212 namerd[15348]: D 0821 01:56:27.845 UTC THREAD28 TraceId:0dd0da7dcf39f614: thread admin-2 id: 28 dns: abcdefg.staging.offerup.services lookup org.xbill.DNS.Lookup@3dc45a4a iteration: 0
Aug 21 01:56:27 ip-172-25-182-212 namerd[15348]: D 0821 01:56:27.846 UTC THREAD28 TraceId:0dd0da7dcf39f614: in doUnit: message no results for abcdefg.staging.offerup.services return type: 3 host not found iteration: 0
Aug 21 01:56:27 ip-172-25-182-212 namerd[15348]: D 0821 01:56:27.846 UTC THREAD28 TraceId:0dd0da7dcf39f614: SRV lookup failure: no results for abcdefg.staging.offerup.services return type: 3 host not found iteration: 0  address: abcdefg.staging.offerup.services pattern: Path(abcdefg.staging.offerup.services)


As you may notice I have a Sequence number `iteration: 0` which I put that in to keep trace of the life cycle of the timer loop, and this number increases if I repeat the same search for the non-exist DNS (+1) - hence I am pretty sure the loop is there but doesn't run.

**Comment by leozc** [comment]
By disabling DNS Lookup cache from dnsjava lib (within java process) - I am not seeing any perf issue

also based on the implementation we are using (a background pulling model) - perf shouldnt be an issue

```
  "namer/#/io.l5d.dnssrv/#/io.l5d.dnssrv/request_duration_ms.count" : 132,
  "namer/#/io.l5d.dnssrv/#/io.l5d.dnssrv/request_duration_ms.max" : 13,
  "namer/#/io.l5d.dnssrv/#/io.l5d.dnssrv/request_duration_ms.min" : 0,
  "namer/#/io.l5d.dnssrv/#/io.l5d.dnssrv/request_duration_ms.p50" : 1,
  "namer/#/io.l5d.dnssrv/#/io.l5d.dnssrv/request_duration_ms.p90" : 2,
  "namer/#/io.l5d.dnssrv/#/io.l5d.dnssrv/request_duration_ms.p95" : 3,
  "namer/#/io.l5d.dnssrv/#/io.l5d.dnssrv/request_duration_ms.p99" : 9,
  "namer/#/io.l5d.dnssrv/#/io.l5d.dnssrv/request_duration_ms.p9990" : 13,
  "namer/#/io.l5d.dnssrv/#/io.l5d.dnssrv/request_duration_ms.p9999" : 13,
  "namer/#/io.l5d.dnssrv/#/io.l5d.dnssrv/request_duration_ms.sum" : 158,
  "namer/#/io.l5d.dnssrv/#/io.l5d.dnssrv/request_duration_ms.avg" : 1.196969696969697,
```

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd/pull/2111
