### ISSUE TITLE
Linkerd command not found

### ISSUE THREAD

**Issue by DevoRia** [linkerd/linkerd#2105]
Hello, I'm tring to run linkerd
`sudo ./linkerd-1.4.6-exec linkerd.yaml`
 but, I've got in out that
`sudo: ./linkerd-1.4.6-exec: command not found`
Why?

**Comment by dadjeibaah** [comment]
@DevoRia that is more a command line error rather than an error in linkerd. Check the current directory you are in to make sure the `linkerd-1.4.6-exec` binary is present.

**Comment by dadjeibaah** [comment]
Also, do you mind describing how you have your environment set up? i.e. Are you using docker? is this command run in a docker container? Are you just running this locally? From my understanding, you do not need to add `sudo` to your the linkerd-exec binary.
