### ISSUE TITLE
Turn GC logging on by default

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#2110]
GC logging is an essential source of information when debugging Linkerd performance.  We should enable GC logging by default by adding the following settings:

```
-XX:+PrintGCDetails
-XX:+PrintGCDateStamps
-XX:+PrintHeapAtGC
-XX:+PrintTenuringDistribution
-XX:+PrintGCApplicationStoppedTime
-XX:+PrintPromotionFailure
-Xloggc:/var/log/linkerd/gc.log
-XX:+UseGCLogFileRotation
-XX:NumberOfGCLogFiles=10
-XX:GCLogFileSize=10M
```

**Comment by wmorgan** [comment]
For non-SSD hosts, given that `/var/log` is typically not a candidate for tmpfs, is this the best place for the logs to go? cc @chrisgoffinet
