### ISSUE TITLE
Small UseCase on Header Token identifier

### ISSUE THREAD

**Issue by dhruvmphatek** [linkerd/linkerd#2112]
We have 2 Services A & B, 4 instances of each service and Linkerd announces both _Service A_ and _Service B_ and structure will look like container _P_ contains all the elements and _W, X, Y, Z_ containing only a single instances for **_Service A_** and similar structure for **_Service B_** as well. 
Instance 2 of _Service B_ is communicating with a dedicated Instance 3 of _Service A_ using **Header Token identifier** which resides in container Y.  What if Instance 3 of _Service A_ goes down, in that case first attempt will fail, then using the **http.retryableRead5XX** and now we want to retry the same request but now we want to change the container  with the container _P_, which contains all the instances of _Service A_ to pick any other instance to pass the request of _Service A_.

**Comment by adleong** [comment]
Hi @dhruvmphatek!  I have to admit, I don't totally follow all the details of the scenario that you're describing.  If Linkerd is sending traffic to service A, it should be load balancing requests to each instance of service A.  If a request fails and is retried, the retry will likely go to another instance of service A.

I'm not sure if this answers your question but hopefully it is helpful.

**Comment by adleong** [comment]
@dhruvmphatek I hope my answer was helpful.  Please reopen if you have further questions.
