### ISSUE TITLE
Create a new Linkerd interpreter that reads dtabs directly from a Consul discovery service.

### ISSUE THREAD

**Issue by dadjeibaah** [linkerd/linkerd#2116]
Namerd, sometimes falls into an out-of-sync state when reading dtabs from a consul dtab store. One to fix this situation is by introducing a new interpreter config for Linkerd that reads dtabs from a Consul SD. 
We need to investigate and see if we can reuse some of the implementation already available on Linkerd and layout what the configuration options would look like.

**Comment by wmorgan** [comment]
cc @zackangelo

**Comment by dadjeibaah** [comment]
@zackangelo Sorry, there hasn't been much progress on this issue but, I wanted to check in and see if there is still a need for this feature. Are you still running into issues were you are seeing stale Dtabs in Namerd?
