### ISSUE TITLE
Poor error reporting when HTTP2 stream pool is exhausted

### ISSUE THREAD

**Issue by utrack** [linkerd/linkerd#2120]
Issue Type:
- Bug report

**What happened**:
We've started to receive intermittent `Exceeded 10.seconds binding timeout while resolving name: /svc/<svcname>` errors when trying to connect to our services.

After debugging we've found out that the reason behind it was our `k8s-apiserver` that had config parameter `--http2-max-streams-per-connection` set to 250.

It seems that l5d opens separate stream for every service that is deployed to k8s (first time it is called via l5d?), reusing a single HTTP2 connection. When number of services exceeds the limit, l5d stops creating new streams, thus making newly deployed services unavailable.

**What you expected to happen**:
Proper error reporting OR automatic mitigation via creation of a second HTTP2 connection to the apiserver.

**How to reproduce it (as minimally and precisely as possible)**:
Set `--http2-max-streams-per-connection` to `n`, deploy `n+1` services and try to access them all.

**Environment**:
- linkerd/namerd version, config files: 1.4.5
- Cloud provider or hardware configuration: bare-metal

**Comment by dadjeibaah** [comment]
@utrack thanks for filing this. By default, linkerd has no limit to the number of streams it creates per connection. https://api.linkerd.io/1.4.6/linkerd/index.html#http-2-server-parameters. Out of curiosity, how do you have your H2 router configured?

**Comment by utrack** [comment]
Nono, the limit is not on linkerd side, but on k8s side: see `--http2-max-streams-per-connection` @ https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ .
Linkerd exhausts apiserver's limits and stops resolving k8s addresses.

We don't have any H2 routers, only gRPC one.

**Comment by adleong** [comment]
@utrack I think this is the intended behavior.  When Linkerd is not able to initiate a request to the Kubernetes API (in this case because the stream limit has been reached) it will continuously retry until the binding timeout is exhausted.

Linkerd should print error logs indicating the problem.

Opening a second connection would defeat the purpose of the max-streams-per-connection.  I recommend simply increasing max-streams-per-connection on your API server.

**Comment by utrack** [comment]
Yeah, on a second thought, aux connections feel like a hack. Logging would definitely help tho :) 

Why l5d uses a separate stream for every service/deployment/hostname? It seems that it brings an unnecessary cap on the service count.

**Comment by adleong** [comment]
This allows us to manage subscriptions individually.  The Kubernetes API should be able to handle a very large number of concurrent streams.  Is there any reason why you need to artificially limit it to 250?

**Comment by utrack** [comment]
It is a default setting in Go, see https://github.com/golang/net/blob/master/http2/server.go#L57

**Comment by adleong** [comment]
@utrack interesting!  I'm surprised that the stream limit is so low by default.  Anyway, if you want to watch more services, you'll need to increase the stream limit.
