### ISSUE TITLE
Upgrade to Finagle 18.9.0

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#2122]
Notably, 18.9.0 adds support for SO_REUSEPORT which could potentially allow for Linkerd to restart without dropping requests.

It also now defaults to using Linux's native epoll.

**Comment by zackangelo** [comment]
Anecdote: we've manually switched over to using native epoll in production and haven't seen any issues with it.

**Comment by adleong** [comment]
Closed by #2127
