### ISSUE TITLE
HTTP/2 stack creates excessive latency and throughput overhead

### ISSUE THREAD

**Issue by zackangelo** [linkerd/linkerd#2125]
Issue Type: *Bug report*

Linkerd introduces a significant amount of overhead in terms of both throughput and latency for gRPC services versus two processes communicating directly. 

Here is a max qps [strest-grpc](http://github.com/buoyantio/strest-grpc) run for each scenario: 

#### Direct

```bash
> ./strest-grpc server --address "127.0.0.1:9999"
> ./strest-grpc client --address "127.0.0.1:9999" --totalRequests 100000 --streams 100 
{
  "good": 100000,
  "bad": 0,
  "bytes": 0,
  "latency": {
    "p50": 3,
    "p75": 4,
    "p90": 5,
    "p95": 5,
    "p99": 8,
    "p999": 19
  },
  "jitter": {
    "p50": 0,
    "p75": 0,
    "p90": 0,
    "p95": 0,
    "p99": 0,
    "p999": 0
  }
}
```

#### Via Linkerd

```bash
> ./strest-grpc client --address "127.0.0.1:4143" --totalRequests 100000 --streams 100 
{
  "good": 100000,
  "bad": 0,
  "bytes": 0,
  "latency": {
    "p50": 46,
    "p75": 53,
    "p90": 76,
    "p95": 122,
    "p99": 229,
    "p999": 412
  },
  "jitter": {
    "p50": 0,
    "p75": 0,
    "p90": 0,
    "p95": 0,
    "p99": 0,
    "p999": 0
  }
}
```

#### Configuration:
```yaml
admin:
  port: 9990
  ip: 0.0.0.0

routers: 
  - label: h2-in
    protocol: h2
    experimental: true
    client:
      initialStreamWindowBytes: 1048576
      failureAccrual:
        kind: none
    servers:
      - port: 4143
        ip: 0.0.0.0
        maxConcurrentStreamsPerConnection: 2147483647
        initialStreamWindowBytes: 1048576
    dtab: |
       /svc/* => /$/inet/127.0.0.1/9999;
    identifier:
      kind: io.l5d.header.path
      segments: 1
```

In addition to using strest-grpc, I also wrote a custom but crude benchmarking tool of my own, [echobench](http://github.com/zackangelo/echobench),  so that I could experiment with gRPC channel settings and socket options.

The custom tool also reports a significant amount of overhead when using linkerd: 

#### Direct
```
=== summary ===
threads: 10 (5000 reqs per thread)
requests: 50000
throughput: 2922.804486159504/s
errors: 0
latency:
- min: 1ms
- max: 17ms
- median: 2.0ms
- avg: 2.8737975505112257ms
- p95: 7.0ms
- p99: 11.0ms
```

#### Via Linkerd
```
=== summary ===
threads: 10 (5000 reqs per thread)
requests: 50000
throughput: 629.5124804747321/s
errors: 0
latency:
- min: 6ms
- max: 34ms
- median: 13.0ms
- avg: 13.981156425923315ms
- p95: 20.0ms
- p99: 27.0ms
```

Checking the `metrics.json` endpoint after a test run shows an interesting discrepancy between request and stream latencies. Stream latencies appear to be much higher: 

#### Request latencies
```
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/request_latency_ms.count": 53932,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/request_latency_ms.max": 54,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/request_latency_ms.min": 0,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/request_latency_ms.p50": 6,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/request_latency_ms.p90": 16,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/request_latency_ms.p95": 22,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/request_latency_ms.p99": 31,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/request_latency_ms.p9990": 41,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/request_latency_ms.p9999": 50,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/request_latency_ms.sum": 390436,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/request_latency_ms.avg": 7.239412593636431,
```

#### Stream latencies
```
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/response/stream/stream_duration_ms.count": 53945,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/response/stream/stream_duration_ms.max": 139,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/response/stream/stream_duration_ms.min": 10,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/response/stream/stream_duration_ms.p50": 46,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/response/stream/stream_duration_ms.p90": 59,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/response/stream/stream_duration_ms.p95": 63,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/response/stream/stream_duration_ms.p99": 79,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/response/stream/stream_duration_ms.p9990": 104,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/response/stream/stream_duration_ms.p9999": 135,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/response/stream/stream_duration_ms.sum": 2538980,
  "rt/h2-in/client/$/inet/127.0.0.1/9999/service/svc/echo.EchoService/response/stream/stream_duration_ms.avg": 47.06608582815831,
```

Another interesting peculiarity is there is only ever one stream indicated as open back to the test service, despite several threads sending requests simultaneously: 

```
"rt/h2-in/client/$/inet/127.0.0.1/9999/stream/open_streams": 1
```

After discovering the overhead I attempted several configuration and code changes to alleviate this issue, including: 

* Manually defining max concurrent stream values to maximum values on both ends of the connection
* Manually expanding HTTP/2 flow control window sizes to maximum allowable values on both ends of the connection
* Setting the retry buffer sizes to 0
* Removing the `ClassifiedRetries` module from the finagle client stack entirely in code
* Manually expanding the maximum frame size to maximum allowable values
* Removing the [DelayedReleaseService](https://github.com/linkerd/linkerd/blob/master/finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/DelayedReleaseService.scala)  from the finagle client stack in code

None of these changes made a noticeable impact on the latency and throughput. 

I took several tcpdumps to examine the behavior of the service communication under both scenarios.  A big difference number of captured packets immediately jumps out: 2966 for direct and 22542 for linkerd. 

Looking at the tcpdumps in Wireshark confirms why: when communicating directly the client is able to multiplex HTTP/2 frames from ~120 streams into a single TCP packet. Linkerd, by comparison, creates a TCP packet for each HTTP/2 stream frame.

#### Linkerd packets 
![image](https://user-images.githubusercontent.com/688990/45782389-63919880-bc28-11e8-9b9e-aac070b46316.png)

#### Direct packets
![image](https://user-images.githubusercontent.com/688990/45782382-5d032100-bc28-11e8-841f-595f3106fb9c.png)

The discrepancy in latency and throughput could be attributed to the additional syscall and packetization overhead required to forward HTTP/2 traffic in this way.

I found the discrepancy surprising given that both linkerd and grpc-java are based on the netty4 HTTP/2 stack primitives. It turns out that when the grpc-java stack was being developed, they identified a problem with netty4’s H2 stack flushing too frequently. 

They identified and fixed the issue in these places: 

* [HTTP2 remote flow controller flushing is too eager · Issue #3688 · netty/netty · GitHub](https://github.com/netty/netty/issues/3688)
* [HTTP/2 shouldn’t flush automatically · Issue #3670 · netty/netty · GitHub](https://github.com/netty/netty/issues/3670)
* [Disable flushing on frame write in flow-controller by louiscryan · Pull Request #3691 · netty/netty · GitHub](https://github.com/netty/netty/pull/3691)
* [Reduce number of flushes · Issue #305 · grpc/grpc-java · GitHub](https://github.com/grpc/grpc-java/issues/305)
* [Implement writes to the channel using a dedicated write queue by louiscryan · Pull Request #431 · grpc/grpc-java · GitHub](https://github.com/grpc/grpc-java/pull/431)

The benchmarks listed in the write queue PR indicate this change unlocked a significant jump in throughput, especially in the case of many streams (16806.718 ops/s versus 55975.008 ops/s for 1000 streams). 

I don’t have an easy way to confirm how much a write queue will reduce the performance overhead I’m observing. I’m open to suggestions for a quick and dirty way to get more confidence in this as a potential solution.

I did try enabling Nagle’s (removing the `TCP_NODELAY` option) from the client socket in linkerd and after a few subsequent test runs was able to get the throughput to increase in a single threaded use-case.

**Comment by wmorgan** [comment]
Wow. Thank you for the excellent writeup!

**Comment by adleong** [comment]
I've been experimenting with a branch that adds a write queue to the transport, inspired by what was done in https://github.com/grpc/grpc-java/pull/431/files

https://github.com/linkerd/linkerd/compare/alex/write-queue?expand=1

This uses a queue to buffer writes and schedules flushing them on the event loop.  This results in larger packets being sent with many frames per packet.  This gives us about a 30% increase in throughput and a slight improvement in latency.  Here are the raw results from slowcooker:

```
### DIRECT ###

$ strest-grpc client --address "127.0.0.1:9999" --totalRequests 200000 --streams 100
2018-09-25T14:43:09-07:00    0.0B 190817/0 10s L:   0 [ 10  14 ]   64 J:   0   0
2018-09-25T14:43:19-07:00    0.0B   9183/0 10s L:   0 [ 10  15 ]   33 J:   0   0
{
  "good": 200000,
  "bad": 0,
  "bytes": 0,
  "latency": {
    "p50": 4,
    "p75": 6,
    "p90": 8,
    "p95": 10,
    "p99": 14,
    "p999": 64
  }
}

### LINKERD MASTER ###

$ strest-grpc client --address "127.0.0.1:4143" --totalRequests 200000 --streams 100
2018-09-25T14:38:41-07:00    0.0B    996/0 10s L: 542 [2119 2221 ] 2248 J:   0   0
2018-09-25T14:38:51-07:00    0.0B   2000/0 10s L: 254 [905 1030 ] 1045 J:   0   0
2018-09-25T14:39:01-07:00    0.0B   2764/0 10s L: 191 [758 842 ]  892 J:   0   0
2018-09-25T14:39:11-07:00    0.0B   5380/0 10s L: 106 [282 453 ]  663 J:   0   0
2018-09-25T14:39:21-07:00    0.0B   8871/0 10s L:  36 [282 301 ]  373 J:   0   0
2018-09-25T14:39:31-07:00    0.0B   7329/0 10s L:  39 [261 390 ]  465 J:   0   0
2018-09-25T14:39:41-07:00    0.0B   8674/0 10s L:  35 [193 251 ]  367 J:   0   0
2018-09-25T14:39:51-07:00    0.0B   7172/0 10s L:  66 [259 323 ]  423 J:   0   0
2018-09-25T14:40:01-07:00    0.0B  10084/0 10s L:  24 [146 202 ]  249 J:   0   0
2018-09-25T14:40:11-07:00    0.0B  11993/0 10s L:  32 [124 152 ]  202 J:   0   0
2018-09-25T14:40:21-07:00    0.0B   9164/0 10s L:  46 [218 345 ]  406 J:   0   0
2018-09-25T14:40:31-07:00    0.0B   9173/0 10s L:  36 [181 201 ]  299 J:   0   0
2018-09-25T14:40:41-07:00    0.0B  10339/0 10s L:  41 [134 156 ]  202 J:   0   0
2018-09-25T14:40:51-07:00    0.0B   6543/0 10s L:  47 [301 362 ]  408 J:   0   0
2018-09-25T14:41:01-07:00    0.0B  10744/0 10s L:  39 [133 181 ]  369 J:   0   0
2018-09-25T14:41:11-07:00    0.0B  11476/0 10s L:  25 [132 168 ]  303 J:   0   0
2018-09-25T14:41:21-07:00    0.0B   8619/0 10s L:  35 [250 291 ]  425 J:   0   0
2018-09-25T14:41:31-07:00    0.0B  10814/0 10s L:  35 [127 173 ]  232 J:   0   0
2018-09-25T14:41:41-07:00    0.0B  10284/0 10s L:  23 [205 289 ]  351 J:   0   0
2018-09-25T14:41:51-07:00    0.0B  12546/0 10s L:  26 [128 197 ]  294 J:   0   0
2018-09-25T14:42:01-07:00    0.0B  14762/0 10s L:  24 [ 99 123 ]  172 J:   0   0
2018-09-25T14:42:11-07:00    0.0B  15359/0 10s L:  25 [ 88 108 ]  163 J:   0   0
2018-09-25T14:42:21-07:00    0.0B   4914/0 10s L:  34 [185 301 ]  347 J:   0   0
{
  "good": 200000,
  "bad": 0,
  "bytes": 0,
  "latency": {
    "p50": 88,
    "p75": 116,
    "p90": 176,
    "p95": 242,
    "p99": 559,
    "p999": 2249
  }
}

### LINKERD WITH WRITE QUEUE ###

$ strest-grpc client --address "127.0.0.1:4143" --totalRequests 200000 --streams 100
2018-09-25T14:30:47-07:00    0.0B   2794/0 10s L: 213 [517 1449 ] 1468 J:   0   0
2018-09-25T14:30:57-07:00    0.0B   4699/0 10s L: 119 [373 437 ]  584 J:   0   0
2018-09-25T14:31:07-07:00    0.0B   8635/0 10s L:  29 [237 316 ]  381 J:   0   0
2018-09-25T14:31:17-07:00    0.0B  17322/0 10s L:  14 [ 94 116 ]  148 J:   0   0
2018-09-25T14:31:27-07:00    0.0B  16772/0 10s L:  16 [ 97 115 ]  166 J:   0   0
2018-09-25T14:31:37-07:00    0.0B  14754/0 10s L:  17 [133 178 ]  325 J:   0   0
2018-09-25T14:31:47-07:00    0.0B  21097/0 10s L:  13 [ 71  85 ]  231 J:   0   0
2018-09-25T14:31:57-07:00    0.0B  20959/0 10s L:  17 [ 70  95 ]  138 J:   0   0
2018-09-25T14:32:07-07:00    0.0B  16081/0 10s L:  15 [133 180 ]  263 J:   0   0
2018-09-25T14:32:17-07:00    0.0B  20414/0 10s L:  15 [ 74  93 ]  142 J:   0   0
2018-09-25T14:32:27-07:00    0.0B  20515/0 10s L:  10 [ 71  89 ]  112 J:   0   0
2018-09-25T14:32:37-07:00    0.0B  17408/0 10s L:  11 [119 218 ]  281 J:   0   0
2018-09-25T14:32:47-07:00    0.0B  18550/0 10s L:  14 [ 72  88 ]  183 J:   0   0
{
  "good": 200000,
  "bad": 0,
  "bytes": 0,
  "latency": {
    "p50": 50,
    "p75": 63,
    "p90": 97,
    "p95": 146,
    "p99": 300,
    "p999": 1468
  }
}
```

**Comment by adleong** [comment]
Even with a write queue, the amount of overhead that Linkerd is adding here is much higher than I would expect.  As far as I can tell, most of the time seems to be tied up in slow socket writes.  Further investigation is required to determine why the socket writes are so slow.

**Comment by evhfla** [comment]
Is this same issue present in the OpenJ9JDK version?  If it is not, is that version good enough to run in production?

**Comment by zackangelo** [comment]
@evhfla yes, we see the issue regardless of JVM (we use OpenJ9 in production).

**Comment by evhfla** [comment]
Thanks for the quick reply @zackangelo ...hoping that Alex can have a fix soon.
