### ISSUE TITLE
Restart consul watches after a timeout

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#2131]
When Linkerd/Namerd establishes a watch on Consul, it issues a long polling request that is satisfied when the watch fires.  There have been reports of issues where Linkerd does not receive a response when the watch fires and then keeps the long polling request open forever, resulting in holding on to stale data.  (e.g. https://github.com/linkerd/linkerd/issues/2121)

To mitigate the impact of that scenario, we should time out these long polling requests after a certain period and re-issue them.  This guarantees that we will eventually get up to date, even if a watch fails to fire.

**Comment by richard-pounder-ck** [comment]
Should/Does this apply to watches used for the K8S? Although not 100% confirmed we have seen issues getting updates that look similar when used K8S as the store.

**Comment by adleong** [comment]
It's not exactly the same because the K8S API uses streaming responses whereas the consul API uses blocking responses.
