### ISSUE TITLE
linkerd-proxies are not collecting metrics and giving `Error attempting to establish underlying session layer` error 

### ISSUE THREAD

**Issue by antonmatsiuk** [linkerd/linkerd#2154]
## Filing a Linkerd issue ##
Issue Type:
-  Bug report

**What happened**:
linkerd is not collecting any metrics. 
linkerd -n linkerd stat deploy:
NAME         MESHED   SUCCESS   RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TLS
controller      1/1         -     -             -             -             -     -
grafana         1/1         -     -             -             -             -     -
prometheus      1/1         -     -             -             -             -     -
web             1/1         -     -             -             -             -     -

linkerd-proxies in linkerd deployments report followig errors:
`linkerd2_proxy::control::destination::background::client controller error: Error attempting to establish underlying session layer`
 
The following commands output expected results and no errors: 
linkerd check --pre
linkerd check
kubectl -n linkerd get deploy

**What you expected to happen**:
linkerd-proxy metrics being sent to prometheus.

**How to reproduce it (as minimally and precisely as possible)**:
Follow https://linkerd.io/2/getting-started/ guide

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files:
linkerd version  
Client version: stable-2.0.0
Server version: stable-2.0.0

- Platform, version, and config files (Kubernetes, DC/OS, etc):
- kubernetes cluster bootstrapped with kubeadm:
kubeadm version 1.11.1
kubernetes version  1.11.1
- Kubernetes Network plugin: Calico Version v3.2.0
kubelet extra config:
Environment="KUBELET_EXTRA_ARGS=--authentication-token-webhook"

- Cloud provider or hardware configuration:
VMs on VMWare vCloud with PhotonOS 2.0

**Comment by dadjeibaah** [comment]
@antonmatsiuk I created a new [https://github.com/linkerd/linkerd2/issues/1791] in the [linkerd2](github.com/linkerd/linkerd2) that is a direct copy of this one. Please feel free to comment on that issue. I am going to go ahead and close this one.
