### ISSUE TITLE
linkerd can not router for grpc request when consul down

### ISSUE THREAD

**Issue by Allen0710** [linkerd/linkerd#2160]
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [1 ] Bug report
- [ ] Feature request

**What happened**:
linkerd can not router for grpc request when consul down， it will return consul datacenter 'dc1' service 'simple' observation error Failure( at remote address: /x.x.x.x:8500. Remote Info: Not Available, flags=0x08) with RemoteInfo -> Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /x.x.x.x:8500., Downstream label: client, Trace Id: 6c475a159b32c611.6c475a159b32c611<:6c475a159b32c611. Last known state is Pending

**What you expected to happen**:
I want whether can usr local cache consul service provider host when consul center down
**How to reproduce it (as minimally and precisely as possible)**:
kill consull service
**Anything else we need to know?**:

**Environment**:
admin:
  ip: 127.0.0.1
  port: 9990

namers:
- kind: io.l5d.consul
  host: 127.0.0.1
  port: 8500
  useHealthCheck: false
  healthStatuses:
    - "passing"
    - "warning"
  failFast: true
##- kind: io.l5d.fs
  ##rootDir: disco

routers:
- protocol: h2
  label: outcoming
  dtab: |
    /svc => /#/io.l5d.consul/dc1
   ## /svc => /#/io.l5d.fs
  identifier:
    kind: io.l5d.header.path
    ##header: grpc-header
    segments: 2
  ##interpreter:
    ##kind: io.l5d.namerd
    ##namespace: grpc
    ##dst: /$/inet/127.0.0.1/4290
  ##h2AccessLog: /work/logs/h2access.log
  experimental: true
  servers:
  - port: 4140
    ip: 127.0.0.1

- protocol: thrift
  label: /host/thrift-framed
  thriftProtocol: binary
  dtab: |
    /host => /#/io.l5d.fs;
    /svc  => /host/thrift-framed;
  client:
    thriftFramed: true
  servers:
  - port: 4141
    ip: 127.0.0.1
    thriftFramed: true

- protocol: thrift
  label: /host/thrift-buffered
  thriftProtocol: compact
  dtab: |
    /host => /#/io.l5d.fs;
    /svc  => /host/thrift-buffered;
  client:
    thriftFramed: false
  servers:
  - port: 4142
    ip: 127.0.0.1
    thriftFramed: false

**Comment by adleong** [comment]
Hi @Allen0710!

Linkerd will only cache resolutions that it has already looked up (it doesn't keep a complete cache of Consul's entire registry).  This means that if you resolve a service while Consul is up, and then Consul goes down, Linkerd will continue to be able to route to that service.

However, if you attempt to route to a service that Linkerd has not routed to yet while Consul is down, Linkerd will not be able to resolve it.  Is it possible that this is what you're experiencing?  This would be my guess based on the log message: `Last known state is Pending`.

**Comment by adleong** [comment]
Hi @Allen0710.  I'm going to close this due to inactivity.  Please feel free to re-open if you have more information to provide.
