### ISSUE TITLE
Can't start linkerd in java9+ 

### ISSUE THREAD

**Issue by taer** [linkerd/linkerd#2165]
If I startup linkerd with a JAVA_HOME targetting java9+, I get this error:
```
# /io.buoyant/linkerd/linkerd
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'PrintGCDateStamps'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

It seems to be related to this PR: 
https://github.com/linkerd/linkerd/pull/2119

Java 9+ has a whole new logging system for GC logging. Probably need to make this new logging optional or switch based on java version

**Comment by siggy** [comment]
@taer Thanks for the report. As a workaround, try setting Linkerd's `JVM_OPTIONS` environment variable to override the default flags:

https://github.com/linkerd/linkerd/blob/b38a9a0f60fb9f92a49a0f17672928b6b02b5b77/project/LinkerdBuild.scala#L716

https://github.com/linkerd/linkerd/blob/b38a9a0f60fb9f92a49a0f17672928b6b02b5b77/project/LinkerdBuild.scala#L237-L261

**Comment by taer** [comment]
That workaround works
