### ISSUE TITLE
namerd stops watching dtabs in k8s if apiserver intermittently throws 404

### ISSUE THREAD

**Issue by thedebugger** [linkerd/linkerd#2167]
## Filing a Linkerd issue ##

Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:
namerd stops watching dtabs if k8s apiserver throws 404 for dtabs custom resource

**What you expected to happen**:
Bare minimum, namerd should log a WARNING that says it stopped watching dtab resource so that operator can diagnose the issue easily. Perhaps, namerd should continue to try to restart the watch

**How to reproduce it (as minimally and precisely as possible)**:
We are still trying to figure out why apiserver throws 404 when it shouldn't because resource exists. But for now, do the following
1) create k8s dtabs custom resource
2) start namerd
3) add new dtabs
4) delete the custom resource
5) namerd stops watching without logging any WARN/INFO/ERROR message

**Anything else we need to know?**:
Most likely this [line of code](https://github.com/linkerd/linkerd/blob/c03116375eace9b3ec4acaf60e5f671083903314/k8s/src/main/scala/io/buoyant/k8s/resources.scala#L235) is the culprit

**Environment**:
- linkerd/namerd version, config files: 1.5.0
- Platform, version, and config files (Kubernetes, DC/OS, etc): k8s 1.10.5
- Cloud provider or hardware configuration: doesn't matter

Let me know if you need more information!

**Comment by thedebugger** [comment]
@dadjeibaah so it does retry depending on where namerd receives 404. If it receives 404 during watchable, it tries to restart the watch. But restarting a watch requires a GET on the resource which if it fails with 404, namerd stops watching. That is what we are seeing. I can't reproduce the same scenario. The closest i can come up with is above steps. Let me know if you more questions.

**Comment by dadjeibaah** [comment]
@thedebugger, I've added some additional log lines to for each dtab watch event and can be viewed here in this PR #2192. I looked through the code once more to make sure I wasn't missing something in regards to Namerd not restarting watches and it looks like even in situations where we get a 404 and Namerd is issuing a`restartWatch`, the API still makes a call to the apiserver to make sure that the resource is in sync. Here is the [specific line that does that](https://github.com/linkerd/linkerd/blob/master/k8s/src/main/scala/io/buoyant/k8s/Watchable.scala#L242). Let me know if you have any more info.

**Comment by dadjeibaah** [comment]
@thedebugger, I looked into this more and I think you were correct that there is indeed some weird behavior going on during the `restartWatches` method. It looked like during, restartWatch, namerd would silently fail and stop watching the apiserver. I will put a PR for you to review and see if that fixes your issue.

**Comment by thedebugger** [comment]
i gave it another try on namerd 1.5.2 but i didn't see above log line. Here are the namerd [logs](https://gist.githubusercontent.com/thedebugger/0d3db4c0bbc78c4b0557659e0be71840/raw/9e87b3826f6b541dff82a6cfbff45d3b8c780301/gistfile1.txt)

I just follow the same steps as above
1. bootup namerd with some dtabs. let it run for few mins.
2. kubectl delete crd/dtabs.l5d.io. Here is [crd spec](https://gist.github.com/thedebugger/0d3db4c0bbc78c4b0557659e0be71840#file-namerd-crd] 
3. namerd logs the following line
```
W 0128 23:49:17.122 UTC THREAD45 TraceId:f4ee3042e6688020: k8s failed to watch resource /apis/l5d.io/v1alpha1/namespaces/ck-system/dtabs: 404 Not Found
D 0128 23:49:17.139 UTC THREAD11 TraceId:f4ee3042e6688020: k8s restarting watch on /apis/l5d.io/v1alpha1/watch/namespaces/ck-system/dtabs, resource version Some(1268327) was too old
```
4. But no logs after that indicates the watch has been stopped

Let me know if you folks need more information. Thanks!

**Comment by adleong** [comment]
@thedebugger am I understanding you correctly that you actually delete the dtab CRD itself (rather than a specific dtab resource)?  What would you expect the behavior to be in this case?  Do you eventually re-create the CRD?
