### ISSUE TITLE
User Defined gRPC Status Codes for Failure Accruals Needed

### ISSUE THREAD

**Issue by evhfla** [linkerd/linkerd#2183]
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [ ] Bug report
- [ X] Feature request

**What happened**:
Linkerd does not allow a user to specify which grpc exceptions are counted toward failure accrual.

**What you expected to happen**:
Linkerd should allow a user to custom configure which grpc exceptions will count toward failure accrual.  Currently, all grpc status codes other than 0 are counted as failures.  In my view, status codes such as Invalid Argument or NotFound should not count as failures.  Counting those as failures will cause nodes to be marked as dead unnecessarily.   So, just like Linkerd allows the specification of gRPC User-Defined Retryable Status Codes, there should also be an ability to specify user-defined status codes for failure accrual.

**How to reproduce it (as minimally and precisely as possible)**:
Call a grpc service more than 5 times that returns a status of notfound.

**Anything else we need to know?**:
Nope

**Environment**:
- linkerd/namerd version, config files: Linkerd 1.5.2
- Platform, version, and config files (Kubernetes, DC/OS, etc): Kubernetes 1.11.3
- Cloud provider or hardware configuration: Azure Acs-Engine

**Comment by wmorgan** [comment]
Thanks @evhfla! Adding this is a good idea.
