### ISSUE TITLE
Upgrade and test Linkerd with Finagle 18.12.0

### ISSUE THREAD

**Issue by dadjeibaah** [linkerd/linkerd#2184]
Finagle 18.11.0 now has support for streaming requests of non-chunked bodies, we need to test that out to see if that works with Linkerd's current HTTP streaming functionality.

**Comment by adleong** [comment]
I think 18.12.0 is coming out very soon.

**Comment by dadjeibaah** [comment]
Keeping this open until version 18.12.0 comes out. Current master now has Finagle 18.11.0.
