### ISSUE TITLE
How to do linkerd and grpc ?

### ISSUE THREAD

**Issue by chenhaibocode** [linkerd/linkerd#2191]
How to do linkerd and grpc ? have is one demo ?

**Comment by dadjeibaah** [comment]
Hi @chenhaibocode, there are tons of examples of how to run Linkerd in various configuration [here](https://github.com/linkerd/linkerd-examples). One example is running Linkerd with a few grpc apps. You can take a look at the Readme here https://github.com/linkerd/linkerd-examples/tree/master/docker/helloworld
