### ISSUE TITLE
Revise maxRequestKB and maxResponseKB meaning after #2189

### ISSUE THREAD

**Issue by edio** [linkerd/linkerd#2196]
Issue Type:

- [ ] Bug report
- [x] Feature request

Do you think it makes sense to revise the necessity or behavior of `maxRequestKB`  and `maxResponseKB` after #2189 ?

I don't know the initial motivation behind those, but I guess that it may be to protect linkerd from OOMs.

To me it would make sense to have following set of properties:

* `streamAfterContentLengthKB` - current behavior. Effectively defines how much space in heap large unchunked request can take at most
* `maxRequestKB`, `maxResponseKB` - max request/response size, both chunked and unchunked. Having it only for unchunked requests as it is now does not have much sense, since we already have `streamAfterContentLengthKB` (unless of course the motivation behind those properties is something else than preventing OOM). Having these limits for all requests/responses on the other hand, makes total sense for me: we may want to protect services in our service mesh from unreasonably large requests without polluting services logic.
However in this case, I believe, we should make it unlimited by default (right now finagle allows 2 GiB max, but I think we can try discussing this with finagle team).

**Comment by dadjeibaah** [comment]
Thanks for filing this @edio. My understanding is that `maxRequestKB` and `maxResponseKB` were initially added to tame large requests from being sent to the router according to this PR https://github.com/linkerd/linkerd/pull/557. Having these configurations with `streamAfterContentLengthKB` seems a bit redundant, however, I do agree with you that these configs could be used to protect services from large requests. I did some digging too and it looks like some if not all of these http configs in the past were discussed in some form. Issue #1327 further discusses the `maxResponseKB` and `maxRequestKB` params.

**Comment by adleong** [comment]
I'm actually a bit confused about the behavior of `maxRequestKB` and `maxResponseKB`.  I think the next steps for this ticket are to verify the behavior of these properties in all different cases:
* chunked message
* non-chunked message
* non-chunked streaming message

**Comment by dadjeibaah** [comment]
This investigation may result in the removal of `maxRequestKB` and `maxResponseKB` as config parameters and may be a breaking change in Linkerd just as a heads up.

**Comment by zaharidichev** [comment]
will give you a bit more clarity on that one shortly
