### ISSUE TITLE
io.l5d.serversets discovery zookeeper is invalid

### ISSUE THREAD

**Issue by chenhaibocode** [linkerd/linkerd#2197]
I tried it as a document, but I still couldn't. I wanted to use zookeeper as my disco, and then Linkerd routed the service IP port through zookeeper.

**console log:** 
![image](https://user-images.githubusercontent.com/41729597/50272175-e1f11700-0471-11e9-96f3-8d44a135bcd1.png)

**postman:**
![image](https://user-images.githubusercontent.com/41729597/50272176-e3224400-0471-11e9-8162-d2497719b49a.png)

**linkerd.yaml:**
![image](https://user-images.githubusercontent.com/41729597/50272523-ff72b080-0472-11e9-9207-0274fa14b0b6.png)

**zookeeper data:** 
![image](https://user-images.githubusercontent.com/41729597/50272386-90955780-0472-11e9-8017-0a9e09d60b28.png)

**Comment by dadjeibaah** [comment]
Thanks for filing this @chenhaibocode, this is strange since you have everything wired up correctly and that logical path results in a `(neg)`. We will dig into this.

**Comment by chenhaibocode** [comment]
@dadjeibaah ok, thank you.

**Comment by chenhaibocode** [comment]
@dadjeibaah  Is it related to the zookeeper version?

**Comment by adleong** [comment]
Hi @chenhaibocode.  What library are you using to populate the serverset entries into Zookeeper?  Or are you populating it manually?  I believe the serversets protocol requires that entries in a serverset should be ephemeral znodes as children of the service name.  So in your example, the service endpoint data should live in an emphemeral child of `/discovery/prod/test`.

**Comment by adleong** [comment]
Hope my previous comment was helpful.  Please re-open this issue if that doesn't work for you.
