### ISSUE TITLE
Allow namerd to survive intermittent consul "no path to datacenter" error

### ISSUE THREAD

**Issue by edio** [linkerd/linkerd#2200]
## Filing a Linkerd issue ##

Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
https://github.com/linkerd/linkerd/pull/2186 allows _namerd_ to fallback to last known state of an observed service in _consul_, unless consul responds with `500: No path to datacenter`.

This allows _namerd_ to reply immediately with `Neg` if queried DC is not known to consul. This behavior is required for correct cross-dc fallbacks for example.

However, consul responds with the same error when network partition occurs. Hence, even if DC exists, but consul cluster is intermittently in a bad shape, namerd will update all services to `Neg`.

**What you expected to happen**:
_Namerd_ won't update services to `Neg`, if they are already resolved and consul responds with `500: No path to datacenter`. Only `Pending → Neg` transition should be allowed on that response from _consul_.

More details are in the corresponding pull-request
https://github.com/linkerd/linkerd/pull/2186

**Comment by dadjeibaah** [comment]
Thanks for filing this @edio! Should be easy to get a PR up for this. We will take a look at this soon.

**Comment by adleong** [comment]
I'm a bit torn on this.  Special casing the Pending -> Neg transition doesn't seem correct to me.  It also makes the logic more stateful and difficult to understand and reason about.

In particular, the proposed solution does not allow for DCs to be deleted.  This may be rare in practice, but it maps logically to the error message.

I don't operate Consul in production so it's hard for me to know which use-cases to focus on, but I'm hesitant to making this code more complex than it already is.

**Comment by edio** [comment]
@adleong 
I do agree, that logic becomes more stateful and (a little bit) more complex.
The patch, however, is extremely simple

```
-          case Throw(e: UnexpectedResponse) if e.rsp.contentString == DatacenterErrorMessage =>
+          case Throw(e: UnexpectedResponse) if e.rsp.contentString == DatacenterErrorMessage && currentValueToLog != Addr.Pending  =>
```

> In particular, the proposed solution does not allow for DCs to be deleted. This may be rare in practice, but it maps logically to the error message.

Usually mapping to DC happens in Dtabs:
```
/svc/foo=>/dc/a/foo | /dc/b/foo | /dc/c/foo | !
```

Now, if we want to delete dc `b`, we'll want to cleanup our dtab:
```
/svc/foo=>/dc/a/foo | /dc/c/foo | !
```

Removal of DC in consul is a huge (and yes, unusual) event, and preparation to it is required. Cleaning up dtabs is not a big deal, and, ideally, should be performed as a part of DC removal procedure, ideally before removing DC in consul. I'd say, such order of events is not even a workaround, but, rather, a normal clean way of removing DC.

Network partitions, however, happen without our knowledge and happen quite often, we can't workaround them in any way. So I strongly believe, that namerd should handle such situations in the namer code.

**Comment by adleong** [comment]
After thinking very long on this, I'm not as opposed to it as I was initially.  This is the best solution that I can think of to deal with these intermittent consul errors.  Your argument about DC deletion is compelling as well.  @dadjeibaah, what do you think?
