### ISSUE TITLE
Runtime error usr/bin/java: No such file or directory

### ISSUE THREAD

**Issue by mrezaei00** [linkerd/linkerd#2207]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
[As of version `1.6.0`](https://github.com/linkerd/linkerd/blame/6702ab00c1baf025a7695dcab8208be6330d98f5/project/LinkerdBuild.scala#L377) both Namerd and Linkerd runtime shows an error regarding Java environment:
```
/io.buoyant/linkerd/1.6.0/bundle-exec: line 26: [: /io.buoyant/linkerd/1.6.0/bundle-exec: line 24: usr/bin/java: No such file or directory: integer expression expected
...
```

**What you expected to happen**:
I expected the exec to find Java at `/usr/bin/java` at the minimum. `JAVA_HOME` is also set correctly, it was also expected for the exec to find it correctly:
```
[root@bbf7d35ca033 1.6.0]# echo $JAVA_HOME 
/opt/java/latest
[root@bbf7d35ca033 1.6.0]# which java
/bin/java
[root@bbf7d35ca033 1.6.0]# /usr/bin/java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**How to reproduce it (as minimally and precisely as possible)**:
I ran this against our internal build of Namerd/Linkerd, that's replacing the base Java image:
```
./sbt ';set assemblyOutputPath in assembly in (namerd, Bundle) := file("~/namerd-<version>-exec");set Base.dockerJavaImage in (namerd, Bundle) := "<java_base_image>"' namerd/docker
```
With that image, ran a simple docker run (without any configuration for simplicity):
```
$ docker run <local_registry>/buoyantio/linkerd:1.6.0
/io.buoyant/linkerd/1.6.0/bundle-exec: line 26: [: /io.buoyant/linkerd/1.6.0/bundle-exec: line 24: usr/bin/java: No such file or directory: integer expression expected
-XX:+AggressiveOpts -XX:+AlwaysPreTouch -XX:+CMSClassUnloadingEnabled -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSParallelRemarkEnabled -XX:+CMSScavengeBeforeRemark -XX:GCLogFileSize=10485760 -XX:InitialHeapSize=33554432 -XX:MaxHeapSize=1073741824 -XX:MaxNewSize=174485504 -XX:MaxTenuringThreshold=6 -XX:NumberOfGCLogFiles=10 -XX:OldPLABSize=16 -XX:+PerfDisableSharedMem -XX:+PrintCommandLineFlags -XX:+PrintGC -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintHeapAtGC -XX:+PrintPromotionFailure -XX:+PrintTenuringDistribution -XX:+ScavengeBeforeFullGC -XX:-TieredCompilation -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseGCLogFileRotation -XX:+UseParNewGC -XX:+UseStringDeduplication
...
```

**Anything else we need to know?**:
No.

**Environment**:
- linkerd/namerd version, config files: N/A
- Platform, version, and config files (Kubernetes, DC/OS, etc): Kubernetes 1.10.9
- Cloud provider or hardware configuration: GCP

**Comment by dadjeibaah** [comment]
@mrezaei00 there is a PR that fixes the missing forward slash issue. However, I was unable to reproduce the issue of JAVA_HOME not having the path to the java binary at runtime. I tried starting up a linkerd docker image with JAVA_HOME set to nothing and it picked up the default path of `/usr/bin/java`.
