### ISSUE TITLE
Support PING frame in H2

### ISSUE THREAD

**Issue by chrisgoffinet** [linkerd/linkerd#2219]
In the HTTP/2 spec (https://http2.github.io/http2-spec/#PING) there is support for handling PING frames. I suggest we support this for the mesh interpreter. The biggest reason would be for users of Linkerd who put Namerd in front of a load balancer. In cloud environments like GCP where they provide elastic load balancing, they have a fixed idle timeout of 600s that isn't configurable. I've also seen this problem happen in action, so it's not theoretical. We've had to fallback to the ThriftMux interpreter because Finagle implements its own ping like mechanism to keep the connection open.

I've considered the option of enabling `SO_KEEPALIVE` on the client socket, but the issue we face here is that currently Netty/Finagle does not expose the ability to set custom keepalive settings (intv, probes, etc) which means that _even_ if we were to support this option, it would require the user to adjust their TCP settings at the host level and for large infrastructure environments, this is a non-starter. I think overall it makes since that the H2 implementation support `PING` instead of relying on the transport.

**Comment by thedebugger** [comment]
I just want to add that both client (linkerd) and server (namerd) should support enabling the ping frame

**Comment by dadjeibaah** [comment]
Thanks for pointing that out. While working on this the assumption I worked
with was that the client side would ping Namerd. But it shouldn’t be
difficult for Namerd to do that as well.

**Comment by dadjeibaah** [comment]
@chrisgoffinet @thedebugger #2221 is a working PR that implements H2 PINGs and implements a failure detector.
