### ISSUE TITLE
How to   cross-DC failover for Linkerd

### ISSUE THREAD

**Issue by yeyincai** [linkerd/linkerd#2225]
linkerd version: 1.6.1
I want to use  cross-DC failover for product evn ,but not find  configuration , how to  cross-DC failover for Linkerd ,thanks?

**Comment by JustinVenus** [comment]
I *think* you are looking for [delegation tables](https://linkerd.io/1/advanced/dtabs/).  Which would apply to this section of a [static namer config](https://github.com/linkerd/linkerd/blob/master/linkerd/examples/static_namer.yaml#L5).

**Comment by yeyincai** [comment]
@JustinVenus      thank you  , found  for [delegation tables](https://linkerd.io/1/advanced/dtabs/)

**Comment by dadjeibaah** [comment]
Hi @yeyincai, does @JustinVenus' suggestion help out in anyway?

**Comment by yeyincai** [comment]
@dadjeibaah yes , I have solved it，but it is done by changing the Linkerd  loadbalancer code.

**Comment by dadjeibaah** [comment]
That's interesting, do you mind sharing how you solved the issue?

**Comment by yeyincai** [comment]
@dadjeibaah  Linkerd has a variety of load balancing algorithms, using roundrobin as an example，I   changing   RoundRobinBalancer.pick() ,add   cross-DC failover logic . Create address with metadata
```java
    private[this] val (localDC: Vector[Node], remoteDC: Vector[Node]) =
      vector.partition(item => item.factory.address.asInstanceOf[Inet].metadata.get(CrossLabel).isEmpty)
  
    private[this] val (remoteUp: Vector[Node], remoteDown: Vector[Node]) = remoteDC.partition(
      _.isAvailable
    )

  private[this] val (localUp: Vector[Node], localDown: Vector[Node]) = localDC.partition(
      _.isAvailable
    )

   def pick(): Node = {
      var selections = Vector.empty[Node]
      if (localUp.nonEmpty) {
        selections = localUp
      } else {
        if (remoteUp.nonEmpty) {
          selections = remoteUp
        }
      }
      ..........
   }
```

Changed  RoundRobinBalancer.class  is need  Balancers.class  reconfigure.
Hope it can help you!

**Comment by dadjeibaah** [comment]
That's pretty neat! Thanks for the explanation. I am glad to know you were able to get that working. I am going to go ahead and mark this as closed then.
