### ISSUE TITLE
Namerd access log

### ISSUE THREAD

**Issue by chrisgoffinet** [linkerd/linkerd#2255]
This is more of a feature request for providing better visibility into what's going on with Namerd. It would be helpful to implement an access log, so that we can see all the requests coming in. There have been cases where we've seen a flood of requests from Linkerd and haven't been able to understand why and what services caused the blip

**Comment by dadjeibaah** [comment]
@chrisgoffinet, gonna be picking this up pretty soon. I had some questions about what you'd like to show for these access logs.

- I presume that we are looking for access logs in the common log format. Is there additional information you'd want to see displayed from the incoming request?
- Are these logs going to stdout? If so what log level is the most appropriate. Already, the `TRACE` log level is pretty noisy when looking at HTTP/2 related modules in Linkerd. 
- Another sort of related questions was, Are you thinking this would look like the `h2AccessLogger` for H2 routers?
