### ISSUE TITLE
Linkerd.log rolling policy

### ISSUE THREAD

**Issue by chihaiaalex** [linkerd/linkerd#2256]
Hi,

Recently we've encountered some problems with a Linkerd instance that stopped unexpectedly. 

We have reasons to belive that this crash might be related to the size of the linkerd.log file, which grew up to 6.1Gb in size.

We found something that might be related to this in the log files, but we are not 100% sure:

```
2019-03-19 10:11:28 +0000] log queue overflow - record dropped
Java HotSpot(TM) 64-Bit Server VM warning: [2019-03-19 10:11:37 +0000] log queue overflow - record droppedAttempt to protect stack guard pages failed.
```

On the other hand, the http access log file is pretty small, somewhere around 2.9 Mb from the same period of time. We will also configure a rolling policy for this file.

My question is:
Is there a way we can configure a similar rolling policy for the linkerd.log file? We don't want to simply just delete the file.

Thanks!

**Comment by adleong** [comment]
Hi @chihaiaalex!  Linkerd just sends logs to standard output and therefore is not involved in log file rotation.  Collecting those logs into a file and rotating those log files can be done by a process external to Linkerd.  Does that make sense?
