### ISSUE TITLE
interpreter state admin endpoint fails with BufferUnderflowException on few nodes

### ISSUE THREAD

**Issue by thedebugger** [linkerd/linkerd#2259]
## Filing a Linkerd issue ##

Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:
Call to `http/interpreter_state/io.l5d.namerd/httproutes.json` fails with 500 - linkerd logs BufferUnderflowException. 

**What you expected to happen**:
It should return the state of all watches

**How to reproduce it (as minimally and precisely as possible)**:
We are seeing it on a few nodes that have this problem. It fails all the time on the nodes that have the problem.

**Anything else we need to know?**:
Exception stack trace https://gist.github.com/thedebugger/416ddb566d482d840ac1d94491553bf2

**Environment**:
- linkerd/namerd version, config files: both 1.5.2  
- Platform, version, and config files (Kubernetes, DC/OS, etc): 1.10.11
- Cloud provider or hardware configuration: shoudn't matter

**Comment by adleong** [comment]
It looks like this can happen when the interpreter state endpoint is accessed before Linkerd has received a response from Namerd.  When Linkerd sends requests to Namerd, it sends a `stamp` field which indicates the most recent version of the data it has received.  On the first call to Namerd, `stamp` is empty and on all subsequent calls, `stamp` will contain a `long` from the previous Namerd response.

In the case where no response from Namerd has been received and the stamp field is empty, attempting to read a long from it will cause a buffer underflow: https://github.com/linkerd/linkerd/blob/master/namerd/iface/interpreter-thrift/src/main/scala/io/buoyant/namerd/iface/ByteBufferSerializers.scala#L15

This exception should have no effect on the traffic Linkerd is proxying and should have no effect on the communication between Linkerd and Namerd.  The interpreter state endpoint should be the only thing affected.  The interpreter state endpoint will work properly again once Linkerd receives a response from Namerd.

We should fix the interpreter state rendering code to gracefully handle the case when the stamp is empty.
