### ISSUE TITLE
Namerd checkes

### ISSUE THREAD

**Issue by solinex** [linkerd/linkerd#2267]
Suggest some Runtime check to Namerd.Binding test.
Wanted to know Does Namerd actually work even though the service is up.
How do I check this.
Please advice.

# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [ ] Bug report
- [ ] Feature request

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files:
- Platform, version, and config files (Kubernetes, DC/OS, etc):
- Cloud provider or hardware configuration:

**Comment by adleong** [comment]
Hi @solinex, I don't understand your question.  Could you provide some more detail please?

**Comment by SaiAbhinay** [comment]
I see Namerd service is up but it is not working as expected.
How to test if it is working properly?

**Comment by adleong** [comment]
Hi @SaiAbhinay and @solinex.  We need a lot more information in order to give a helpful response.  When creating a new issue there is a template to fill out.  For your convenience, I've copied the template into this issue's description.
