### ISSUE TITLE
Return meta attached to consul service in consul namer response

### ISSUE THREAD

**Issue by edio** [linkerd/linkerd#2269]
Issue Type:

- [ ] Bug report
- [x] Feature request

**What happened**:
Service registered in consul with metadata attached
```
$ curl --request PUT --data '\
{\
"ID": "foo-1",\
"Name": "foo",\
"Address": "10.10.10.10",\
"Port": 10101,\
  "Meta": {\
    "foo": "bar"\
  },\
}' http://127.0.0.1:8500/v1/agent/service/register
```
When querying via namerd, metadata from consul isn't returned by the namer:
```
{
"type": "bound",
"addrs": [
  {
    "ip": "10.10.10.10",
    "port": 10101,
    "meta": {
      "endpoint_addr_weight": 1
    }
  }
],
"meta": {}
}
```

**What you expected to happen**:
I'd expect `"foo": "bar"` meta attached to the consul service to be present in the namerd response.

**Anything else we need to know?**:
Currently meta in consul namer response carries some finagle-specific data. We need to make sure, that metadata from consul can't clash with the meta-data namer already stores.

**Comment by dadjeibaah** [comment]
Thanks for opening this issue @edio! exposing the meta field through Namerd could be useful. 

> Currently meta in consul namer response carries some finagle-specific data. We need to make sure, that metadata from consul can't clash with the meta-data namer already stores.

What are your thoughts on mitigating this issue, it sounds like it is highly unlikely but is definitely possible. Would prefixing any meta key from Consul with some unique value suffice, or is there a better way to differentiate the two types of meta information.

**Comment by edio** [comment]
@dadjeibaah , the main driver behind this was `ServiceMeta`, and actually, I think, right now consul namer doesn't write anything to `meta` field in response. So no issues with that.

If we, however are to add `NodeMeta`, which should be returned as `addrs[*].meta`, then we may have a collision.

I haven't looked in details, but I see, that `Addr.Metadata` accepts pairs of `(String, Any)`. What if we write consul metadata as a map. So the resulting response would look like
```
{
"type": "bound",
"addrs": [
  {
    "ip": "10.10.10.10",
    "port": 10101,
    "meta": {
      "endpoint_addr_weight": 1,
      "node_meta": {
        "foo": "bar"
      }
    }
  }
],
"meta": {}
}
```
(i.e. nested map)

Not sure if this'll work, just the first idea, that comes to mind.
