### ISSUE TITLE
l5d-err response body may include un-sanitized request header values

### ISSUE THREAD

**Issue by bagelswitch** [linkerd/linkerd#2276]
Issue Type:

- [*] Bug report
- [ ] Feature request

**What happened**:
A security scanning appliance in our environment makes requests to linkerd and fuzzes header values. In the event that any such header is used by an identifier (eg. the MethodAndHostIdentifier using the value of the Host header) and naming fails, the linkerd error response may include an un-sanitized value, resulting in a XSS vulnerability:

```
HTTP/1.1 502 Bad Gateway l5d-err: %22%3E%3Cscript%3Ealert%28document.domain%29%3C%2Fscript%3E+%28of+class+java.lang.String%29 Content-Length: 69 Content-Type: text/plain Strict-Transport-Security: max-age=63072000; includeSubDomains; preload "><script>alert(document.domain)</script> (of class java.lang.String)
```

**What you expected to happen**:
A sanitized error response that doesn't include the raw script provided in the request.

**How to reproduce it (as minimally and precisely as possible)**:
Configure linkerd w/ an indentifier that relies on the value of a request header provided by the client to perform identification, such that naming ultimately fails if an invalid value is provided for the header. Make a request to linkerd and provide script (eg. "<script>alert(document.domain)</script>") in the header value.

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files: linkerd 1.4.6 in our case, but affects multiple versions
- Platform, version, and config files (Kubernetes, DC/OS, etc): Ubuntu 18, we're using nomad and a consul namer, but any identifier that uses a header as input to a namer and produces a routing failure should reproduce
- Cloud provider or hardware configuration: AWS

**Comment by dadjeibaah** [comment]
Great find @bagelswitch! We will take a look at this and have a PR ASAP.

**Comment by dadjeibaah** [comment]
Hi @bagelswitch, I tried to reproduce this issue with Linkerd 1.6.3 and I was unable to. I setup a regular linkerd process to use the `io.l5d.methodAndHost` identifier and sent this request.
```bash
curl -H "Host: <script>alert(document.domain)</script>" -v http://localhost:4140
```

And got back this error with curl:

```bash
* Rebuilt URL to: http://localhost:4140/
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 4140 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4140 (#0)
> GET / HTTP/1.1
> Host: <script>alert(document.domain)</script>
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 502 Bad Gateway
< l5d-err: Unable+to+route+request%21%0A%0Aservice+name%3A+%2Fsvc%2F1.1%2FGET%2F%5Cx3c%5Cx73%5Cx63%5Cx72%5Cx69%5Cx70%5Cx74%5Cx3e%5Cx61%5Cx6c%5Cx65%5Cx72%5Cx74%5Cx28%5Cx64%5Cx6f%5Cx63%5Cx75%5Cx6d%5Cx65%5Cx6e%5Cx74%5Cx2e%5Cx64%5Cx6f%5Cx6d%5Cx61%5Cx69%5Cx6e%5Cx29%5Cx3c%5Cx2f%5Cx73%5Cx63%5Cx72%5Cx69%5Cx70%5Cx74%5Cx3e%0Adtab%3A%0A%0Abase+dtab%3A%0A++%2Fsvc+%3D%3E+%2F%23%2Fio.l5d.fs%0Aoverride+dtab%3A%0A%0A
< Content-Length: 267
< Content-Type: text/plain
<
Unable to route request!

service name: /svc/1.1/GET/\x3c\x73\x63\x72\x69\x70\x74\x3e\x61\x6c\x65\x72\x74\x28\x64\x6f\x63\x75\x6d\x65\x6e\x74\x2e\x64\x6f\x6d\x61\x69\x6e\x29\x3c\x2f\x73\x63\x72\x69\x70\x74\x3e
dtab:

base dtab:
  /svc => /#/io.l5d.fs
override dtab:

* Connection #0 to host localhost left intact
```
Can you confirm if you can reproduce the bug you encountered with the latest Linkerd version?

**Comment by adleong** [comment]
Hi @bagelswitch.  I don't think you can assume that responses from Linkerd have been sanitized and I would recommend sanitizing any data before injecting it into content.  Alternatively, you can use the `clearContext` server parameter to have Linkerd remove the error message from the response entirely.

**Comment by bagelswitch** [comment]
Hi, sorry for the slow response - @dadjeibaah I haven't tested on the latest version yet, but will do so.

@adleong we aren't injecting any response into content, it's the error body itself that is problematic, the only way we could suppress this (unless fixed in latest versions or supressable via configuration) is by inspecting and manipulating all linkerd responses w/ a proxy, which wouldn't be very performant.

Re. the clearContext parameter - unless I misunderstand how that works, it wouldn't help for eg. the Host header - stripping that ahead of eg. the MethodAndHostIdentifier would just prevent the identifier from functioning, wouldn't it?

**Comment by adleong** [comment]
Perhaps I've misunderstood the vulnerability.  The content-type of the response is text/plain so no one should be interpreting the body as html or javascript.  

The clearContext option also turns off the printing of Linkerd error messages in the response body.  It does not strip the host header.

**Comment by bagelswitch** [comment]
I'm not sure I'd call it a vulnerability at all, so much as a corporate compliance problem :)

"security" scanners fuzz inputs w/ script, and if they see any of that in a response, they complain - the "no UA would ever execute this" argument is one I've made, unsuccessfully. In our environment Qualys appliances are in use for this purpose, a popular choice.

Anyway, sounds like clearContext may be all we need, I'll try that - thanks again!

**Comment by adleong** [comment]
Awesome!  I'll close this out for now.  Please re-open if `clearContext` doesn't do what you need.
