### ISSUE TITLE
Upgrade to Finagle 19.2.0 + 

### ISSUE THREAD

**Issue by yif3sty** [linkerd/linkerd#2278]
**What happened**:
It has happened a lot in our production and sandbox environment that calls randomly fail with a 502 and `java.lang.IllegalArgumentException: bound must be greater than origin` message. I found this issue https://github.com/twitter/finagle/issues/754, it seems to be introduced around Finagle 18.12.0 and is fixed in 19.2.0. 

**What you expected to happen**:
Please upgrade to Finagle 19.2.0+ to have the fix.

**How to reproduce it (as minimally and precisely as possible)**:
I don't have a consistent reproduction steps for this issue, as it happens sporadically. Please refer to the Finagle issue link above for more details.

**Comment by dadjeibaah** [comment]
Fixed by #2284
