### ISSUE TITLE
Support configuration for writing access logs to console and setting log level

### ISSUE THREAD

**Issue by jisooh** [linkerd/linkerd#2282]
Issue Type:

- [ ] Bug report
- [x] Feature request

**What happened**:
With our current setup in Kubernetes, we read logs from console and ship them to Logstash and Elasticsearch. We can use mount points to map the access log directory to the docker filesystem for consumption, but based on the Kubernetes guidelines, this approach is not recommended. We would like to read the access logs directly from console.

Linkerd does not have the ability to write http and h2 access logs to the console. There are configs to enable access logging to the filesystem but not to the console.

Also, there is no way to set the log level through the configs.

**What you expected to happen**:
Configs should support logging with different types of appenders. We should be able to write access logs to a file and/or console based on the configs.

We should also be able to set the log level for each type of appender individually. The log level for each type of appender should be configurable from the Linkerd admin dashboard.

Currently, system logs are also output to console, but in our situation this does not matter. As long as the access logs have the log level appended, we are able to differentiate the type of log.

**Proposal**:
Config structure proposal for both http and h2 routers:

```
routers:
- protocol: http | h2
  logAppenders:
  - type: console
    level: INFO
  - type: file
    level: INFO
    path: access.log
    rollPolicy: daily
    append: true
    rotateCount: -1
```
  
This structure proposes being able to state a list of different log appenders we want to configure. The file appender will support the currently supported features in addition to a configurable log level. The console appender will simply write logs to the console with the specified log level.

For each entry of logAppenders, the type must be specified.

**Anything else we need to know?**:
Current log configs:
h2: https://api.linkerd.io/1.6.3/linkerd/index.html#http-2-protocol
http: https://api.linkerd.io/1.6.3/linkerd/index.html#http-1-1-protocol

**Comment by dadjeibaah** [comment]
@jisooh, thanks for filing this issue. I think to start, it'd be good to divide this issue into two concerns. The first is figuring out how to send **access** logs to console and second, how to configure log appenders for **process** logs I think the first issue of sending access logs to console can be solved by setting the path in the config to `stdout`. So basically something like this in the configs:
```yaml
- protocol: http
  httpAccessLog: /dev/stdout
  httpAccessLogRollPolicy: daily
  httpAccessLogAppend: true
  httpAccessLogRotateCount: -1
```

One caveat is that these logs will end up being interspersed in Linkerd's process logs since it too logs to `stdout`. It sounds like this should be fine in your use case. IIUC, doing the using the above-mentioned config should take care of the first issue i.e.

> read the access logs directly from console

Now for the second issue, Linkerd does allow you to set log levels dynamically, through the admin dashboard under the logging tab. But it sounds like it'd be good to do this through the configs as well?
Is the goal to set up logging so that it outputs to a file? Linkerd currently gives you the ability to dynamically change log levels through the admin dashboard, you can also set up a flag to set the log level at startup which feels similar to setting log levels in a config file.

**Comment by jisooh** [comment]
@dadjeibaah, thanks for the reply. I agree that we can probably separate these into two issues.

Are you saying that writing to console is already supported via the configs? If so, this is great news. But I think there is still an issue of the configuration not supporting writing to both console and a file.

The goal for us is to write logs to console, but also have the log level be set in the configs. I guess for us, we are more used to having the log level be configurable via configs and see our configs as the final say, but I can see why this might be harder to support since you guys have an admin dashboard where these can be set dynamically.

**Comment by jisooh** [comment]
The current h2 access log seems to give minimal information regarding the call. We are able to see which endpoint was hit but do not get information on which service was actually hit.

We are routing our calls through a `service-name` header. Is there any way we can improve the logging so we can get more information on the h2 request?

**Comment by adleong** [comment]
Thanks for filing this @jisooh.  I think there are a few separate issues here:

I wasn't aware of Kubernetes guidelines around not using log files.  As long as you're using an in-memory file system such as tmpfs, I don't see why this would be an issue.  I'd love to hear more about why this might be a problem.

As you note, the Linkerd access log is *just* an access log: it records the requests that Linkerd receives and does not include information about what happens to that request when it is routed.  To track the flow of requests as they are routed (and even as they move between services) I would recommend looking at using tracing (Zipkin).

Lastly, I haven't tried this, but it may be possible to configure the behavior of the access logger with the [log4j.properties file](https://github.com/linkerd/linkerd/blob/master/linkerd/main/src/main/resources/log4j.properties).  The access logger uses a logger named "access_foo" where foo is the name of the router.  It may be possible to configure the appenders this logger uses with properties scoped under `log4j.loggers.access_foo.appender` in the log4j.properties file.  I would recommend looking into this option and seeing if this works.

Hope this information helps!

**Comment by jisooh** [comment]
Thanks for the reply @adleong

We were able to get the access logs to write to the console by setting the path as `/dev/stdout`. In regards to being able to customize the access logs to potential output headers, is this something we do not want to support?

**Comment by adleong** [comment]
My preference would be to keep access logging simple and single purpose.  For richer data about requests, I'd recommend either using tracing, or implementing a custom logger as a RequestAuthorizer plugin.

**Comment by jisooh** [comment]
That's understandable. We'll look into implementing a custom logger.

From my understand, we would have to extend this class https://github.com/linkerd/linkerd/blob/master/linkerd/protocol/h2/src/main/scala/io/buoyant/linkerd/protocol/h2/H2RequestAuthorizerConfig.scala and then set our custom plugin in the linkerd configs?

**Comment by adleong** [comment]
That's right.  More details can be found in [the docs](https://linkerd.io/1/advanced/plugin/).

**Comment by adleong** [comment]
@jisooh Since you're now looking into the custom logger approach, are you good with closing this issue?

**Comment by jisooh** [comment]
@adleong Yes, I think this ticket can be closed right now. However, we would still like to see customizable log levels via configs instead of the admin UI.

I can create a new ticket for this specifically.

**Comment by MartinKosicky** [comment]
Hmm in kubernete if i have a daemonset how do i configure trace logging level on all linkerd instances at once without config file ? Also im talking about linkerd 1.7

**Comment by cpretzer** [comment]
@MartinKosicky you can enable the trace log level by adding an argument to the `args` section of the PodSpec YAML file.

For example, have a look at line 139 of the [daemonset example YAML](https://github.com/linkerd/linkerd-examples/blob/master/k8s-daemonset/k8s/linkerd.yml#L139). 

In this case, setting the trace log level is a matter of adding a new array element under the `args` section, which would look like this:

```
...
   args:
   - /io.buoyant/linkerd/config/config.yaml
   - -log.level=TRACE
...
```

Let me know how it goes!

**Comment by MartinKosicky** [comment]
Ah thanks ! Actually I never tryied launching linkerd with --help or something like that. I always started at the linkerd reference pages. Probabbly would be nice to document that somewhere in the configuration reference page.

**Comment by cpretzer** [comment]
That makes sense. We'd love a pull request, if you're up for it.
