### ISSUE TITLE
Namerd unable to lookup service endpoints

### ISSUE THREAD

**Issue by bercikr** [linkerd/linkerd#2293]
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
Attempted to route service traffic via namerd. Namerd does not appear to be able to lookup the endpoint of the service we are testing.

```
W 0710 22:02:45.833 UTC THREAD30 TraceId:107da13e35d2959c: k8s ns deploy:4340 service echo-service endpoints resource does not exist, assuming it has yet to be created
```

**What you expected to happen**:
I would expect the service to be found using the 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files:

RBAC configuration

```
# RBAC configs for linkerd
---
# grant linkerd/namerd permissions to enable service discovery
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-endpoints-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["endpoints", "services", "pods"] # pod access is required for the *-legacy.yml examples in this folder
    verbs: ["get", "watch", "list"]
  - apiGroups: [ "extensions" ]
    resources: [ "ingresses" ]
    verbs: ["get", "watch", "list"]
---
# grant namerd permissions to custom resource definitions in k8s 1.8+ and third party resources in k8s < 1.8 for dtab storage
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: namerd-dtab-storage
rules:
  - apiGroups: ["l5d.io"]
    resources: ["dtabs"]
    verbs: ["get", "watch", "list", "update", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: default
    namespace: deploy

roleRef:
  kind: ClusterRole
  name: linkerd-endpoints-reader
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: namerd-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: default
    namespace: deploy
roleRef:
  kind: ClusterRole
  name: namerd-dtab-storage
  apiGroup: rbac.authorization.k8s.io```

- Platform, version, and config files (Kubernetes, DC/OS, etc):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:05:01Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

linkerd 1.6.3
namerd 1.6.3

- Cloud provider or hardware configuration:

**Comment by adleong** [comment]
Hi @bercikr!  The log message: `k8s ns deploy:4340 service echo-service endpoints resource does not exist, assuming it has yet to be created` indicates that you are trying to lookup the `echo-service` service in the `deploy:4340` namespace.  I'm guessing that `deploy:4340` isn't the namespace that you want.  

The Kubernetes namer expects names in the form `/#/io.l5d.k8s/<namespace>/<port>/<service>`.  For more info on this, check out the [docs](https://api.linkerd.io/head/linkerd/index.html#kubernetes-service-discovery).  A good way to debug this and verify that your dtab is resolving to the correct name is to use the dtab playground in the Linkerd or Namerd admin pages.

**Comment by dadjeibaah** [comment]
@bercikr was @adleong's comment helpful for you?
