### ISSUE TITLE
Marathon namer seems to ignore "login_endpoint" attribute in DC/OS service account JSON

### ISSUE THREAD

**Issue by agaffney** [linkerd/linkerd#2302]
Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:

When configuring the Marathon namer to use host `marathon.mesos` *and* enabling DC/OS service account auth, the namer seems to ignore the `login_endpoint` attribute in the service account JSON blob and tries to login to Marathon directly (I assume). I spent hours trying to debug why I was getting a stacktrace containing the following, which implies a failure to get a login token.

```
io.buoyant.marathon.v2.Api$UnexpectedResponse
  at io.buoyant.namer.marathon.Authenticator$Authenticated.$anonfun$getToken$1(Authenticator.scala:89
```

When I switched the Marathon namer to go through the DC/OS adminrouter (host `leader.mesos` and URI prefix `/marathon`) to talk to Marathon, service account auth all of a sudden started working.

While I was not able to verify my hunch (and I don't really want to go back and try to reproduce it at this point, because I've already spent too much time on this), it seems that the Marathon namer was constructing a login URL based on the configured Marathon host/URL rather than using the `login_endpoint` field in the service account JSON.

**What you expected to happen**:

linkerd/namerd should use the `login_endpoint` attribute from the service account JSON when trying to obtain a login token.

**How to reproduce it (as minimally and precisely as possible)**:

Configure linkerd/namerd to talk to `marathon.mesos` on port `8080` (as works fine without service account auth) and defined the `DCOS_SERVICE_ACCOUNT_CREDENTIAL` env var with a valid DC/OS service account JSON blob.

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files: 1.6.4
- Platform, version, and config files (Kubernetes, DC/OS, etc): DC/OS
- Cloud provider or hardware configuration: AWS

**Comment by agaffney** [comment]
Additionally, debugging this issue was very difficult, because the error does not include any information about the HTTP status code or the URL that it tries to hit, even with the log level set to DEBUG. For some reason, I also could not see the requests via strace (when attaching to the running namerd process with `strace -p <pid> -f -e trace=network`).

**Comment by adleong** [comment]
Interesting.  It's been a while since I've looked at this code, but I believe that the marathon namer should be loading the `login_endpoint` from your `DCOS_SERVICE_ACCOUNT_CREDENTIAL` environment variable.  The code which does so is here: https://github.com/linkerd/linkerd/blob/master/namer/marathon/src/main/scala/io/buoyant/namer/marathon/MarathonInitializer.scala#L46

Do you know what URL Linkerd is actually using?  How did you deduce that Linkerd is not using the correct login_endpoint?  Can you share the contents of your `DCOS_SERVICE_ACCOUNT_CREDENTIAL` env variable (with the private key redacted)?

**Comment by agaffney** [comment]
I do not know what URL that namerd was actually using, but I know it wasn't going through `leader.mesos` as configured in the service account JSON until I configured the Marathon namer to use `leader.mesos`.

The service account JSON is:

```
{"private_key": "-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----\n", "scheme": "RS256", "uid": "namerd_dcos_svc_acct", "login_endpoint": "https://leader.mesos/acs/api/v1/auth/login"}
```

**Comment by agaffney** [comment]
All I *really* know is that I was getting the reported traceback and nothing was showing up in the DC/OS adminrouter logs.

**Comment by adleong** [comment]
It really would be great if Linkerd's error message contained more useful information about the request and response in this case.  Is it possible for you to use wireshark to see what's really going on?

**Comment by agaffney** [comment]
I tried using tcpdump, but I was not able to put together a filter that captured the traffic (partially because I was making incorrect assumptions about where it was trying to send the requests). At this point, I *really* don't want to revert the config to try to reproduce and capture the traffic.

As a side note, we're currently using permissive mode in DC/OS, which allows (but does not require) service account auth and TLS. This configuration change was to prepare for eventually switching to strict mode.

**Comment by agaffney** [comment]
I think it would be sufficient to add some additional log output for this failure to let the user know what the unexpected response was and what URL was tried. That information probably would have shaved hours off of my troubleshooting.

**Comment by adleong** [comment]
Dang, sorry you lost so much time to this.  Let's use this ticket to track improving the logging for this case.

When you eventually switch back to service account auth, we'll get to the bottom of what's going wrong.

**Comment by agaffney** [comment]
I actually already have service account auth enabled and working, now that I've switched the namer configuration to go through adminrouter (`leader.mesos`). In order to test this again, I'd have to purposely break it by reverting the namer config to using `marathon.mesos`. I'll see if I can find some time tomorrow to try this out, but no guarantees.

**Comment by adleong** [comment]
Ah, thanks for sending your service account json, I think I see the issue.  The marathon namer assumes that the login_endpoint will just contain a URL path and that the configured host and port should be used to address the server.  E.g. it expects `login_endpoint` to only contain `/acs/api/v1/auth/login` and it uses the same http client to fetch the token as it does to make the apps requests.

**Comment by agaffney** [comment]
I will note that I'm using a custom script to generate the service accounts and the corresponding JSON, but it's based on the JSON that the `dcos` CLI utility creates. I'm fairly sure that it's *supposed* to contain a full URL, as other use cases may not have a separate hostname configured like there is in linkerd/namerd.

**Comment by adleong** [comment]
@agaffney would you mind trying out https://github.com/linkerd/linkerd/pull/2314 and verifying if it fixes this issue?  Unfortunately, I don't have a DC/OS cluster so this is difficult for me to test myself.

**Comment by agaffney** [comment]
I can't easily test this against our DC/OS clusters, but it's fairly easy to create a test DC/OS cluster.

https://docs.d2iq.com/mesosphere/dcos/1.13/installing/evaluation/
https://minidcos.readthedocs.io/en/latest/index.html

**Comment by adleong** [comment]
Thanks @agaffney!  We haven't had any luck getting the minidcos installer to work locally.  I was hoping that you could help us out with getting this tested, either in a staging cluster or minidcos.  Please let me know if you're able to help!  I'm hesitant to merge any changes to this code that we haven't tested against a "real" marathon instance.
