### ISSUE TITLE
idleTimeMs configuration value accepts a String

### ISSUE THREAD

**Issue by zackangelo** [linkerd/linkerd#2339]
## Filing a Linkerd issue ##

Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:

We tried to explicitly configure a linkerd client's `idleTimeMs` with the value `forever` (the default, per the docs) and linkerd successfully starts up instead of rejecting the value. After running for a bit, it begins to fail requests with this error: 

```
E 1004 20:57:46.962 UTC THREAD46 TraceId:6723b609aaad111f: service failure: java.lang.ClassCastException: java.lang.String incompatible with java.lang.Integer
```

![image](https://user-images.githubusercontent.com/688990/66239921-eb213c80-e6af-11e9-9cdc-7364b16f67e1.png)

It looks like we use `DefaultPool`'s value for `idleTimeMs` by default, which is `Duration.Top`: https://github.com/twitter/finagle/blob/fe669e56f7a5b271b3e349748aaf4116dcf2bef6/finagle-core/src/main/scala/com/twitter/finagle/client/DefaultPool.scala#L124

**What you expected to happen**:
Linkerd to reject the configuration as invalid at boot time.

**How to reproduce it (as minimally and precisely as possible)**: Configure `idleTimeMs` with the value `forever`

**Comment by zaharidichev** [comment]
Ahh.. This is a [known problem](https://github.com/FasterXML/jackson-module-scala/wiki/FAQ) in Jackson that I have seen before. Can be fixed. Will think of a best way to do that.
