### ISSUE TITLE
linkerd high cpu with tls

### ISSUE THREAD

**Issue by zhqworld** [linkerd/linkerd#2354]
Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:
Exactly same tls request loads with same clients, if the tls request sending to back-end application directly, CPU utilization (the application process) is around 50% of 1 core; but if same tls request load sending to linkerd as proxy, terminate tls and then route plain http to application, CPU utilization (the linkerd process) is around 120%.

**What you expected to happen**:
The linkerd process CPU utilization should be similiar as the back-end application instead of more than 2X.
**How to reproduce it (as minimally and precisely as possible)**:
1) Prepare a back-end application, in my case tomcat
a) with a static response page, in my case webapps/ROOT/ecv-api.html  (content size: 7K)
b) have port 8080 on http and 8333 on https:

``` 
        <Connector
                executor="tomcatThreadPool"
                port="8080"
                protocol="HTTP/1.1"
                compressableMimeType="text/html,text/xml,application/xml,application/json,text/json,text/css,image/png,image/jpg,image/gif"
                compression="on"/>

        <Connector
           protocol="org.apache.coyote.http11.Http11NioProtocol" port="8333" maxThreads="200"
           scheme="https" secure="true" SSLEnabled="true"
           keystoreFile="/${DIR}/keystore" keystorePass="${PASSWORD}" clientAuth="false" sslProtocol="TLS"/>

```
c) start the back-end application.

2) prepare linkerd:
a) download linkerd 1.7
b) have following l5d/config.yaml for linkerd config

```
admin:
  ip: 0.0.0.0
  port: 9990
routers:
- protocol: http
  experimental: true # for older linkerds
  dtab: /svc => /$/inet/127.1/8080
  servers:
  - ip: 0.0.0.0
    port: 4146
    tls:
      certPath: l5d/linkerd_certs/cert.pem
      intermediateCertsPath: l5d/linkerd_certs/cert.pem
      keyPath: l5d/linkerd_certs/cert.pkcs8.key

telemetry:
- kind: io.l5d.prometheus
```
c) start linkerd by: 

```
./l5d/linkerd-1.7.0/linkerd-1.7.0-exec l5d/config.yaml
```

3) run tests

a) test direct tls traffic to back-end application:

```
./slow_cooker -noreuse -qps 10 -concurrency 5 -interval 10s  https://localhost:8333/ecv-api.html

# sending 50 GET req/s with concurrency=5 to https://localhost:8333/ecv-api.html ...
#                         iter   good/b/f t   goal%   min [p50 p95 p99  p999]  max bhash change
2019-11-04T22:01:24-08:00    0    495/0/0 500  99% 10s   9 [ 11  14  20   34 ]   34      0 +
2019-11-04T22:01:34-08:00    1    500/0/0 500 100% 10s   8 [ 12  13  14   15 ]   15      0
2019-11-04T22:01:44-08:00    2    500/0/0 500 100% 10s   7 [ 12  15  17   18 ]   18      0
2019-11-04T22:01:54-08:00    3    500/0/0 500 100% 10s   8 [ 12  15  16   16 ]   16      0
2019-11-04T22:02:04-08:00    4    500/0/0 500 100% 10s   8 [ 12  15  17   19 ]   19      0
2019-11-04T22:02:14-08:00    5    500/0/0 500 100% 10s   8 [ 13  15  16   18 ]   18      0
2019-11-04T22:02:24-08:00    6    500/0/0 500 100% 10s   8 [ 12  15  19   20 ]   20      0
^C{
  "p50": 12,
  "p75": 13,
  "p90": 14,
  "p95": 15,
  "p99": 17,
  "p999": 34
}

And monitor the cpu of the application process id by top -pid <pid>; 
Observed cpu is around 50%
``` 
b) run test with traffic to linkerd:

```
./slow_cooker -noreuse -qps 10 -concurrency 5 -interval 10s  https://localhost:4146/ecv-api.html

# sending 50 GET req/s with concurrency=5 to https://localhost:4146/ecv-api.html ...
#                         iter   good/b/f t   goal%   min [p50 p95 p99  p999]  max bhash change
2019-11-04T22:03:43-08:00    0    495/0/0 500  99% 10s  22 [ 30  36  43   54 ]   54      0 +
2019-11-04T22:03:53-08:00    1    500/0/0 500 100% 10s  24 [ 30  37  48   52 ]   52      0
2019-11-04T22:04:03-08:00    2    500/0/0 500 100% 10s  23 [ 32  40  46   49 ]   49      0
2019-11-04T22:04:13-08:00    3    500/0/0 500 100% 10s  23 [ 31  41  57   58 ]   58      0
2019-11-04T22:04:23-08:00    4    500/0/0 500 100% 10s  22 [ 29  36  45   49 ]   49      0
2019-11-04T22:04:33-08:00    5    500/0/0 500 100% 10s  22 [ 31  41  49   51 ]   51      0
2019-11-04T22:04:43-08:00    6    500/0/0 500 100% 10s  22 [ 30  42  52   56 ]   56      0
2019-11-04T22:04:53-08:00    7    500/0/0 500 100% 10s  23 [ 29  38  47   48 ]   48      0
2019-11-04T22:05:03-08:00    8    500/0/0 500 100% 10s  22 [ 30  42  52   55 ]   55      0
{
  "p50": 29,
  "p75": 31,
  "p90": 35,
  "p95": 37,
  "p99": 48,
  "p999": 5627
}

And monitor the cpu of the linkerd process id by top -pid <pid>; 
Observed cpu is around 120%
```

**Anything else we need to know?**:

Note: All tests the client is closing connections, with ./slow_cooker -noreuse

**Environment**:
- linkerd/namerd version, config files:
The jvisulvm CPU profiling snaphost is attached, so you can see details of java version, linkerd version, JVM parameters, threads hotspot, method call stack and cpu time etc.

[l5d-high-cpu-snapshot-1572934457592.nps.zip](https://github.com/linkerd/linkerd/files/3807667/l5d-high-cpu-snapshot-1572934457592.nps.zip)

- Platform, version, and config files (Kubernetes, DC/OS, etc):
- Cloud provider or hardware configuration:

**Comment by zhqworld** [comment]
<img width="1357" alt="Screen Shot 2019-11-04 at 10 17 46 PM" src="https://user-images.githubusercontent.com/6413938/68186673-8f213080-ff59-11e9-8e11-0efce3833eba.png">

**Comment by adleong** [comment]
Hi @zhqworld!  It looks like you're running slow cooker with the `-noreuse` flag which will establish a new connection for each request rather than reusing existing connections.  Establishing connections, especially TLS ones is very expensive but should be a relatively rare event in most real world scenarios due to connection caching and reuse.  I believe that if you remove the `-noreuse` flag, you should see greatly improved performance.  If you have a use-case that requires accepting a high rate of new TLS connections with low CPU utilization, I don't think Linkerd is the right solution for that problem.

**Comment by zhqworld** [comment]
Thanks @adleong for quick update.
Yes we have use case which clients has to close connections so "-noreuse" is needed for test.

**Comment by zhqworld** [comment]
In comparison with requests to application directly (TLS and close after each request as well), requests to linkerd took 2X higher CPU which is a little bit too much.

One thing I observed is linkerd has a dependency "netty-tcnative-boringssl-static" and seems it contributes to high CPU, if I remove this dependency from linkerd, then CPU utilization is much lower (around 70%)

Any insides or suggestions of using linkerd for our use case?

**Comment by adleong** [comment]
It's interesting that removing "netty-tcnative-boringssl-static" results in a performance improvement for you, but I don't have any specific guidance around this.

**Comment by robertpanzer** [comment]
I guess this ticket can be closed.
We figured the problem:
The tls server configuration was missing the caCertPath.
As a result Linkerd (indirectly) uses the system truststore, which in our case had a lot more certificates (4 vs >100).
And copying these into the OpenSSL data structures took a considerable amount of time.

@zhqworld Correct me if I'm wrong

**Comment by zhqworld** [comment]
Yes this can be closed.
