### ISSUE TITLE
Release tgz of v1.7.1 is incomplete

### ISSUE THREAD

**Issue by sw0x2A** [linkerd/linkerd#2371]
Latest release tarball is broken and doesn't contain a valid `linkerd-1.7.1-exec`. File size of [`linkerd-1.7.1.tgz`](https://github.com/linkerd/linkerd/releases/download/1.7.1/linkerd-1.7.1.tgz) is only 21.8 KB. Please fix the release file.

**Comment by cpretzer** [comment]
@sw0x2A Thanks for the report. I'm looking in to this now

**Comment by cpretzer** [comment]
@sw0x2A That was a great catch! I've updated the release: https://github.com/linkerd/linkerd/releases/tag/1.7.1
