### ISSUE TITLE
Allow a baseQuery() to be defined when creating Query objects

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd#238]
Address Greg's comment in https://github.com/BuoyantIO/linkerd/pull/232#discussion_r58599470

**Comment by olix0r** [comment]
@rmars is this still worth pursuing?

**Comment by rmars** [comment]
It's mostly a cleanup/polish ticket - It's not super important, but might be nice to address

**Comment by rmars** [comment]
Moving metrics on the frontend to using the metricstree structure will remove the need to create query regexes, so this will soon be unneeded.
