### ISSUE TITLE
What does RichNoBrokersAvailableException exception mean?

### ISSUE THREAD

**Issue by MartinKosicky** [linkerd/linkerd#2383]
Since linkerd is lacking some kind of documentation of most errors, currently I am getting RichNoBrokersAvailableException. Can someone explain what that means?

```
Server Send Error: com.twitter.finagle.naming.buoyant.RichNoBrokersAvailableException: Unable to route request! service name: /svc/namespace/prod/ce-sts-v63-89 dtab: base dtab: override dtab: /svc/config-engine-service => /#/io.l5d.k8s/prod/grpc/ce-api-sts-v63 . Remote Info: Not Available
```

**Comment by cpretzer** [comment]
@MartinKosicky the `RichNoBrokersAvailableException` is an class that provides more detailed information about an underlying `NoBrokersAvailableException`

The "Rich" indicates that the exception writes a richer [error message](https://github.com/linkerd/linkerd/blob/master/router/core/src/main/scala/com/twitter/finagle/naming/buoyant/RichNoBrokersAvailableException.scala
) with information about the underlying dtab.

It is used in the [DstBindingFactory](https://github.com/linkerd/linkerd/blob/master/router/core/src/main/scala/com/twitter/finagle/naming/buoyant/DstBindingFactory.scala#L165) class.

Is there other log info or configuration that you can share? Please join us on https://slack.linkerd.io for more help

**Comment by cpretzer** [comment]
@MartinKosicky since this is more of a question than an issue, I'm going to close this.

Come say hi on Slack if you have more questions
