### ISSUE TITLE
Future of Linkerd 1.x 

### ISSUE THREAD

**Issue by peterfroehlich** [linkerd/linkerd#2418]
I wanted to open a discussion what the future holds for Linkerd 1.x. 

Even though Kubernetes is all the rage now, I don't think the need for a flexible, transparent proxy with integrated service discovery like Linkerd1 is going away. The only other product that can compare is Traefik but they put some of the more advanced features in their paid Enterprise edition. 

With their efforts shifted to Linkerd2, what are Buoyant Inc. plans for the project? 

Even if the feature development stalls, there still is a need for maintenance releases to update components. There are already a few components that would profit from an update like Finagle, netty or even sbt.

**Comment by cpretzer** [comment]
@peterfroehlich Thanks for bringing this up, these are all good points.

We have been doing maintenance releases for security and bug fixes, which often involve upgrading finagle and netty, and it's my understanding that those will continue to happen, but I can't say for how long.

Per the conversation in #2416 , it would be great to add maintainers who would like to continue to use Linkerd 1.

**Comment by wmorgan** [comment]
Thanks for raising this @peterfroehlich. Speaking from the Buoyant perspective, as Charles points out, Buoyant itself is increasingly focusing most of our resources on Linkerd 2.x. We've been doing the occasional maintenance release on 1.x and in the near term this will continue. Speaking from the Linkerd perspective, though, this is not a long-term solution. Long-term to avoid deprecating 1.x we need maintainers from outside of Buoyant..

We *are* willing to devote time and energy to anyone who wants to become a maintainer. The process will look like what we've outlined for becoming a 2.x maintainer:

https://github.com/linkerd/linkerd2/blob/main/GOVERNANCE.md#becoming-a-maintainer

Let me know if you, or anyone else, wants to get involved--we will do our best to make this happen.

**Comment by peterfroehlich** [comment]
Gladly. We use Linkerd1 and Namerd in multiple Instances and are very happy with it.
Sadly I'm not at all proficient in Scala so it would be difficult to help out. But I'll try to spread the word.
