### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [linkerd/linkerd#2430]
Hi team,

I am trying to use the **buoyantio/linkerd** image on the arm64 platform but it is not available for arm64 in [dockerhub](https://hub.docker.com/r/buoyantio/linkerd). There is no dockerfile available in this git repository and it seems feature development from v2.x is now happening in the [linkerd2](https://github.com/linkerd/linkerd2), but latest v1.x tags are released in **buoyantio/linkerd**. 

May I know where I can get dockerfile and how I can build and publish v1.x linkerd images for arm64?

**Comment by adleong** [comment]
Hi @odidev! The dockerfile is created programmatically by sbt during the build.  See: https://github.com/linkerd/linkerd/blob/main/project/Base.scala#L176

As far as I know, arm64 images have never been published for Linkerd 1.x so you're a bit in uncharted water there.
