### ISSUE TITLE
Does Linkerd implement SPIFFE ID? 

### ISSUE THREAD

**Issue by nathanawmk** [linkerd/linkerd#2433]
Does Linkerd implement SPIFFE ID? Is it on the roadmap? Saw it somewhere in the issues and wondering if its been implemented?

**Comment by cpretzer** [comment]
@nathanawmk is this question for Linkerd 1.x or [Linkerd 2.x](https://github.com/linkerd/linkerd2)

In either case I don't believe that the SPIFFE ID is not implemented, although it would be possible with Linkerd 1.x through the plug-in system. That being said, Linkerd 1.x is in maintenance mode and there is no active feature development.

Linkerd 2.x uses service accounts for identity. I'm not well versed enough with SPIFFE to know if/how it can be used to integrate with the service accounts.
