### ISSUE TITLE
limit namerd thrift client to communicate with a single instance

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#295]
A namerd thrift client will not behave well when it communicates with multiple namerd instances to observe a single name.  This is because stamps are not alligned across instances, so if i get back stamp 32 from one service and then poll again with stamp 32, this stamp is not guaranteed to be relevant on any other instance.  Rather than introduce additional coordination, I suggest that we just limit the connection pool to 1 connection.

Really, we'll need to move to a streaming API, but I'd like to wait to do that with gRPC

**Comment by olix0r** [comment]
In kubernetes, this isn't a problem because we can rely on LoadBalancer Services to give us a single L3-loadbalancer so clients only maintain a single connection.  In other environments, we can use DNS RR, but this is still error prone and doesn't provide for resiliency.

The desired behavior is to accept a list of namerd endpoints but to only operate on a single endpoint at a time (i.e. as long as it's healthy).  This could be accomplished by:
- using the newClient api to obtain a ServiceFactory instead of a Service. This would require the namerd client to recover connections after failures.
- or, writing a LoadBalancer implementation that only chooses a single endpoint at a time (basically, pushing this logic down into the load balancer.
- or, as I said earlier, moving to a streaming response implementation.  Either gRPC, a mux streaming implementation, maybe plain-old HTTP/1.1 streaming.

@mosesn do you have any thoughts on how best to address this?  We don't want request-level load balancing nearly--we want to ensure that we have exactly one healthy connection to a logical service, similar to how a zookeeper client manages its connection to a zk cluster.

**Comment by mosesn** [comment]
Aperture size one?

**Comment by olix0r** [comment]
@mosesn aperture currently only supports a minSize. I suppose it could be modified to support a maxSize as well

**Comment by mosesn** [comment]
You can specify a maxLoad of Int.MaxValue or similar, and it'll behave like it's of size one.

**Comment by olix0r** [comment]
@mosesn ah, thanks! i'll give that a shot.

**Comment by adleong** [comment]
closing this in favor of moving towards the `io.l5d.mesh` api.
