### ISSUE TITLE
configurable prometheus metrics path

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd#396]
make prometheus metrics path configurable, allowing users to standardize on prometheus metrics paths across all services in a cluster.

it's currently hard coded at `/admin/metrics/prometheus`.

**Comment by olix0r** [comment]
Does it perhaps make more sense just to change the default? While it's nice for this to be configurable, if prometheus has a default location it looks, perhaps we should just use that?

**Comment by siggy** [comment]
Sure, default is `/metrics`.

**Comment by olix0r** [comment]
Well, that's not confusing ;p I was hoping it was /prometheus or something...

**Comment by lsjostro** [comment]
Another option could be to listen on a specific port?

**Comment by wmorgan** [comment]
@lsjostro I think you're the Prometheus expert here--is it difficult or irritating to use the existing `/admin/metrics/prometheus` endpoint?

**Comment by lsjostro** [comment]
@wmorgan no it's fine as it is.. just more convenient not to have special config for each service in your prometheus configuration, especially when you have hundreds(maybe thousands?) of micro services. You just want to deploy and get automatically metrics from it.

**Comment by wmorgan** [comment]
Gotcha. Probably makes sense to have it be configurable including the port, then. (At the expense of adding yet another configuration format.)

**Comment by ccmtaylor** [comment]
this is fixed in #1634. I think this issue can be closed now.
