### ISSUE TITLE
Support LB'ing external IIS-hosted virtual hosts

### ISSUE THREAD

**Issue by garysweaver** [linkerd/linkerd#509]
Our team has two external IIS-hosted virtual hosts that we wanted to EWMA load balance via Linkerd, but unfortunately that won't work currently for us without a lot of trouble.

While the mapping of logical name to concrete is working as we expected, the destination service (on the IIS nodes) is expecting a specific Host: header, e.g. "node1.domain.com" for node1.domain.com and "node2.domain.com" for node2.domain.com. However, Linkerd instead just passes the logical-name on as the Host header. We can't just specify the node name in the logical-name, because then a request with Host header "node1.domain.com" might get routed to node2.domain.com which is expecting Host header "node2.domain.com" (since Linkerd is trying to LB those nodes).

@olix0r said that getting this to work would be tricky to accomplish at the moment, but that Linkerd could perhaps find a way to add a filter into the client stack that modifies Host values based on the destination address similar to how TLS naming works in Linkerd to try to address this use case.

**Comment by wmorgan** [comment]
Yeah, this is a bit outside the current use case, where we assume that load-balancing happens over a pool of identical replicas.

As a short-term hack, would it make sense to introduce something like nginx to rewrite those  headers? Not a great solution, but might be enough for testing purposes to see if EWMA buys you a performance gain.

**Comment by garysweaver** [comment]
@wmorgan Thanks! We’re looking into alternate solutions for now until this can be fixed.

**Comment by aclemmensen** [comment]
Couldn't you just add additional bindings to the site in IIS? Make both servers bind the site to the same name and it should work, right? Except if you can't control what `Host` header Linkerd will use when forwarding the requests as this will have to match the binding you are configuring.

**Comment by wmorgan** [comment]
@garysweaver this ticket is a bit old... are you still interested in pursuing this? I would like to talk to you a bit offline if so.

**Comment by olix0r** [comment]
Closing this for now.  Please feel free to reopen this if you think it's worth pursuing.
