### ISSUE TITLE
Telemeter plugins for zipkin

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#648]
We should be able to configure zipkin in the `telemetry` section (so that we can begin to deprecate the `tracers` section).

@klingerf has discussed doing this for each zipkin transport so we would ideally want a scribe plugin, a kafka plugin, an http plugin, etc.

**Comment by klingerf** [comment]
👍  Here's the repo that contains all of the implemented finagle-zipkin transports:

https://github.com/openzipkin/zipkin-finagle

**Comment by klingerf** [comment]
I've put together a new repo that provides Zipkin HTTP and Kafka tracers by way of linkerd telemeter plugins. Reviewable here:

https://github.com/linkerd/linkerd-zipkin/pull/1
