### ISSUE TITLE
Advertise HTTP/1.1 Correctly

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#680]
From https://www.mnot.net/blog/2011/07/11/what_proxies_must_do

> HTTP/1.1 is the current version spoken on the Internet, and as long as the proxy implements it correctly (in particular, it handles chunked encoding correctly), it should always advertise itself as HTTP/1.1 conformant.
> 
> This means that the top line of requests and responses should always contain HTTP/1.1 as the version identifier, even when talking to something that says it’s HTTP/1.0.
> 
> The reason for this is that HTTP 1.1 defines not only how to talk to 1.1 devices, but also to 1.0 ones. When a HTTP/1.0 message contains a 1.1 mechanism like Cache-Control, its meaning doesn’t change, and should still be respected.
> 
> See [the spec](http://tools.ietf.org/html/draft-ietf-httpbis-p1-messaging-14#section-2.5) for more information.

**Comment by adleong** [comment]
This is done.
