### ISSUE TITLE
Linkerd does not try the fallback (or second) Namer, when Health API returns empty list of addresses.

### ISSUE THREAD

**Issue by ManishMaheshwari** [linkerd/linkerd#709]
**Configuration used:**

```
namers:
- kind: io.l5d.consul
  experimental: true
  host: 127.0.0.1
  port: 8500
  useHealthCheck: true
  failFast: true  
  includeTag: false
routers:
- protocol: http
  httpAccessLog: logs/access.log
  label: int
  dstPrefix: /http
  baseDtab: |
    /consul =>  /#/io.l5d.consul/dc1 | /$/inet/load-balancer-dc1/80;
    /host => /consul;
    /http/1.1/* => /host; 
```

**Given:** That dtab is configured with alternate namers
**When:** The Health API is configured to return only passing instances
**And:** When there are no passing instances to return by the Health API.
**Expectation:** Linkerd must update the binding cache with NameTree.Neg, and fall back to the second namer configured in dtab.
**Observation:** Linkerd does not fallback to the second namer, and continues to responds the client with HTTP 502:

```
No hosts are available for /http/1.1/GET/someservice, Dtab.base=[/consul=>/#/io.l5d.consul/dc1 | /$/inet/load-balancer-dc1/80;/host=>/consul;/http/1.1/*=>/host], Dtab.local=[]. Remote Info: Not Available
```

**Comment by adleong** [comment]
Fixed by #744
