### ISSUE TITLE
h2 stats equivalence

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#731]
the h2 codec has has a hodgepodge of stats, some of which aren't even instrumented properly.

Make sure we're monitoring the right things and that, at the very least, the admin dashboard works with h2 routers.

**Comment by olix0r** [comment]
stream stats added in https://github.com/BuoyantIO/linkerd/pull/784

**Comment by adleong** [comment]
Done as of the 1.1.3 release
