### ISSUE TITLE
[question]  Session affinity or client ip hashing support

### ISSUE THREAD

**Issue by bobymicroby** [linkerd/linkerd#752]
Hi guys, do you support/plan to support routing to stateful backend services ?

**Comment by olix0r** [comment]
Welcome to the project, @bobymicroby.

While linkerd doesn't explicitly provide features for this sort of stateful routing, it is possible to achieve this sort of configuration with linkerd.

Specifically, the _Identifier_ plugin system may be used to determine the destination for a given request (i.e. by client IP, cookie, etc).  linkerd's load balancers are not aware of any such affinity, and so each backend would have to represented as its own target cluster.

**Comment by OleksandrBerezianskyi** [comment]
@olix0r so, let's say we are using any service discovery. In this case the destination is dynamic and the only way to support "session stickiness" is it add custom loadbalancer, correct?

**Comment by alinvasile** [comment]
Do you have an example of client IP-based load balancing with the Identifier plugin?

**Comment by olix0r** [comment]
@OleksandrBerezianskyi It's probably helpful to get a little more detailed about this use case. I don't think it should be necessary to write a custom load balancer to accomplish this sort of thing... For instance, a combination of an Identifier and Namer may be paired to route requests the the appropriate backend.  The important thing to consider in this case is that we would expect service discovery to be organized in terms of logical shards --- linkerd treats service discovery strictly as _replica sets_.  In truly stateful services, we might be inclined to expose each instance as its own replica set with size=1 -- distribution of load to these replicas is moved up to the identifier/namer logic.   I don't have any examples of this offhand, but I think it's something we can support in linkerd.

@alinvasile I don't have an examples ready offhand.  I believe that com.twitter.finagle.http.Request objects expose the client address, so this could be accessed and used to build the destination name.

**Comment by bobymicroby** [comment]
@olix0r  Hi Oliver, here is one use-case. We need to route requests based on user location to the most appropriate backend server. Most appropriate in our case means a server that have announced via service discovery as the handler for a certain geo region.  So based on the service discovery records we need calculate the closest route for the user request.

**Comment by OleksandrBerezianskyi** [comment]
@olix0r so the use case. We have a **ton** of microservices. Each microservice is caching downstream data. Each microservice have at least 4 instances to support high availability (have instances in all availability zones). We have an idea to develop some sort of session stickiness to improve cache hit statistics. In our case 'userId' is the most important part of the context and a part of cache key. The idea itself was to always route requests for the same session to the same endpoints if possible. I understand that such idea conflicts the main purpose of load balancing to distribute the load as evenly as possible. So the stickiness rule should only be applied up to a certain threshold. 

The same story about physical distance to the endpoints. We want to route traffic to the node-local microservices first, then to endpoints in the same availability zone and only then to other instances in the same region. 

All in all we want to optimize the route for the best possible latency.

**Comment by adleong** [comment]
I think the session stickiness problem and the geo locality problem probably have different solutions.

I think it would be possible to build a consistent hashing load balancer that accepts a hashing function and tries to route requests with the same hash value to the same endpoint.  

For the geo stuff, I'll echo what @olix0r said about setting up a service discovery entry for each zone/region.  Dtab rules can then be used to prefer more local clusters and fall back to more remote ones if necessary.

**Comment by alinvasile** [comment]
Having entries for each zone sounds like a good idea, so I gave it a try:

 baseDtab: |
    /default => /#/io.l5d.serversets/deployments/192.168.10.1;
    /standby => /#/io.l5d.serversets/deployments/192.168.10.10;
    /http/*/*/* => /default | /standby;

/deployments/192.168.10.1 will contain a serverset entry, same for /deployments/192.168.10.10

With this configuration I discovered that the requests are never sent to /standby if the /default server responds with 5xx or suddenly goes down (until the zookeeper timeout deleted the server set in zk).

**Comment by adleong** [comment]
That's correct, fallback won't trigger until /default leaves service discovery (zk).

**Comment by alinvasile** [comment]
That is acceptable when the server dies, but if  it returns 500s they will be retried on the same server until they are echoed to the client.

**Comment by adleong** [comment]
Some good discussion here but I don't think anything actionable.

**Comment by elecnix** [comment]
For what it's worth, I experimented with a Finagle patch that allows requests to be routed to /standby when /default "breaks-circuit".
