### ISSUE TITLE
move json parsing code into a more generic location

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd#762]
motivated by: https://github.com/BuoyantIO/linkerd/pull/759#discussion_r84173420

**Comment by olix0r** [comment]
Is there a problem with the existing setup or is it just a little duplicated code?  It's such a tiny bit of boiler plate that it doesn't seem worth having a json library that's just like 10 lines...

**Comment by siggy** [comment]
it just feels like `io.buoyant.marathon.v2.Api` is kind of a odd place to have generic json parsing code.

**Comment by adleong** [comment]
I don't think this is a big enough issue to track by itself.  Please feel free to refactor and clean up code smell as you go.
