### ISSUE TITLE
allow ability to configure the max URI length via the configuration yaml

### ISSUE THREAD

**Issue by cemeyer2** [linkerd/linkerd#798]
TL;DR: please allow the configuration of the max URI length that linkerd will accept before returning a HTTP 414

Details: https://linkerd.slack.com/archives/linkerd/p1478044281004457

Thanks!

**Comment by fantayeneh** [comment]
Is this not covered by the config param `maxInitialLineKB`? 
see https://github.com/BuoyantIO/linkerd/blob/master/linkerd/docs/protocol-http.md

**Comment by klingerf** [comment]
@fantayeneh is correct that this is covered by `maxInitialLineKB`. Going to close.
