### ISSUE TITLE
gRPC API for namerd

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#842]
Have namerd expose a gRPC API for naming (bind, addr, delegate, etc.)

**Comment by olix0r** [comment]
A working end-to-end gRPC Interpreter Service & Client is up on the [ver/namerd-grpc](https://github.com/BuoyantIO/linkerd/tree/ver/namerd-grpc) branch.  Additionally, I've generated and tested a Go client for this interface.  It all works.

This branch needs more automated tests. This branch needs https://github.com/BuoyantIO/linkerd/pull/932 to ship. This will eventually need to be extended to support the explain api.  We need to expose a `grpc.runtime.Stream.reset` method that allows the consumer to cancel a stream explicitly.

On the API itself:
- I've tried to strip out things that don't belong in the API: specifically stamps and client ids from thrift.  client ids can manifest as request metadata and don't need to be explicit in the API.
- Still would like to think through the Controller API a bit more before solidifying Interpreter api.
