### ISSUE TITLE
namerd API redesign

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#848]
Initial usage of namerd has shown some deficiencies in its control API.

### Unit of change

Those who write to the API typically want to change a narrow portion of a Dtab---usually a single logical service.  However, linkerd routers need to consume a _federated_ Dtab so that they may name multiple services.

Furthermore, users may want to create per-client namespaces so they can control traffic in a per-source fashion.  For instance, a linkerd identifier may can be crafted to construct per-client names like:
```
/src/bird/dst/birdNest
/src/snake/dst/birdNest
```
Then, naming is scoped so that an operator may construct a Dtab that prevents snakes from reaching the bird nest while allowing birds to get there. Or perhaps snakes can go to bird nests but they can only go to nests in us-central1-b...

In such a scenario, we use prefixing to carve out resolution scopes, which surfaces yet more units of change:
- Change how a client like snake or bird views services (e.g. _fail %5 requests from snake to birdNest_)
- Change how birdNest is exposed to all clients (e.g. _incrementally deploy a new version of birdNest_)
- Change some global policy (e.g. _start using a new service discovery backend_)

We have prototyped a few ideas around this, each with tradeoffs (usually, confusing/opaque).

### Dtab encoding is tricky

It would be really nice if we had a protobuf that described Dtabs so that there was a canonical representation for non-scala apps.

### Streaming

Our poll-watching loop over thrift is a bit janky.  Alex has been working on an HTTP streaming API, but it would be really nice to use something like gRPC streams here.

**Comment by Ashald** [comment]
Sounds like a big thing. It also reminds me that we have similar discussion last, hm, Spring? :)

Let me share what we came up with - maybe it will help in some way. As you know, we heavily use Consul so we decided to leverage Consul KV storage to solve this problem. ATM we don't use Namerd control API to modify Dtab and rather update things directly in Consul (although, with some adjustments to our Dtab storage plugin that would be possible as well).

Essentially we've separated concepts of `namespace` and `Dtab`:
1) a namespace `X` is a list of "references", for simplicity let's describe them as simple strings:
```
/namerd/dtabs/base
/namerd/dtabs/shared?dc=us-east1
/namerd/dtabs/shared
/namerd/dtabs/local
```

so essentially each entry in namespace definition is a path in Consul KV store and optional parameter for cross-datacenter query. Obviously, a namespace Dtab is composed in the order paths defined.
Each of paths is queried using a recursive query and we rely on lexicographical sorting to ensure stable, repeatable and easy to grasp sorting/behavior.

We found that it's essential to be able to define some (a) generic stuff, (b) something unique to environment and (c) something that can be shared with other environments.

2) Service definitions
Among aforementioned paths most are "more or less static" and essentially version-controlled and populated with Terraform. The "automatic" part is contained within `/namerd/dtabs/shared/services`.
Given a service name `foobar` the one would expect to find its definition under `/namerd/dtabs/shared/services/foobar`.

Of course it's an opinionated approach tied to our needs, but if we put away details such as naming of particular things I think we can derive an "API" or a "framework" for managing Dtabs. Judging from our experience we found that the most important part that allows a lot of flexibility is an ability to combine Dtabs (that can be manipulated separately) into "bigger dtabs".

The only problem that is not addressed with this approach is "change of view based on client" but I believe it can be implemented using a special identifier that would select particular "namespace" based on some properties of request (this comes from an assumption that 1 L5d per host deployment approach is used for efficiency).

Hope this helps. May you need any other details - feel free to ping me.

**Comment by elecnix** [comment]
I'm looking for a way to inject a dtab entry that is specific to the host where Linkerd is running. That is similar to per-request routing with the `l5d-dtab` HTTP header, but here it would be static for a client. 

In consul at least, perhaps that could be done by merging two namespaces: one that contains a global namespace, and the other a host-specific dtab.

**Comment by Ashald** [comment]
@elecnix there are just a few idea that I can give you as of today:
1) implement a custom identifier plugin that will do the trick
2) put another proxy (like nginx lol) in front of Linkerd that will do that
3) try to handle that with Dtab-magic (you can get some inspiration from https://blog.buoyant.io/2017/04/25/announcing-linkerd-1.0/ and the `PER-CLIENT CONFIGURATION` section)

IMO this is another use cases for a "new plugin interface" for Linkerd that would allow modifying requests or even rejecting them even before the identification happens so that we don't need to build custom identifiers for such cases.

**Comment by elecnix** [comment]
Thanks @Ashald. I don't understand what dtab magic you're referring to. Let me just throw in an other idea: a [rewriting namer](https://linkerd.io/config/1.0.0/linkerd/index.html#rewriting-namers) that inserts the local host name into the path.

**Comment by Ashald** [comment]
@elecnix yeah, that's another option - and great idea!

**Comment by Ashald** [comment]
So, what is the answer to:
> Can namerd namespaces contain slashes?
? :)

**Comment by adleong** [comment]
The answer today is: it depends on the store.  In the redesigned API we'll be more thoughtful about it.

**Comment by Ashald** [comment]
So no decision so far for the future API, right? We're working on a new Dtab-Store plugin and want to ensure compatibility with the new API. We're planning to play with a new idea for it so we will share our experience with you once it's ready. ;)

**Comment by adleong** [comment]
That's right.  We'd definitely love to hear about what you try and how it works out for you.
