### ISSUE TITLE
32-bit Docker images caused problems under SELinux

### ISSUE THREAD

**Issue by stevej** [linkerd/linkerd#852]
From the linkerd slack (user thewmo)

> hey guys - we're hitting an issue deploying the standard buoyantio/linkerd image in Openshift (which runs containers as non-root) where the underlying hosts have SELinux enabled. there's a library reloc happening with the JVM lib that SELinux doesn't like: "Error: failed /usr/lib/jvm/java-8-openjdk-i386/jre/lib/i386/server/libjvm.so, because /usr/lib/jvm/java-8-openjdk-i386/jre/lib/i386/server/libjvm.so: cannot restore segment prot after reloc: Permission denied"

The workaround was to rebuild linkerd on stock java 8 base.

**Comment by stevej** [comment]
Another workaround is to whitelist specific libraries using SELinux although I'm not clear how to do this with containers

http://www-01.ibm.com/support/docview.wss?uid=swg21268209

**Comment by thewmo** [comment]
Thanks for filing the issue. Here is a grab-bag of information from one of our nodes:

```
~]$ uname -r
3.10.0-327.36.3.el7.x86_64
~]$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
~]$ sudo docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64
~]$ openshift version
openshift v1.2.1
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5
```

**Comment by thewmo** [comment]
Another workaround may be a 32-bit JVM built with PIC so it doesn't need to be reloc'ed.

**Comment by thewmo** [comment]
Did some poking around today on this question - some poking and prodding with objdump and friends had me convinced the 32-bit libjvm.so in CentOS7 might not require a reloc, but after building an image and trying it out I hit the same issue. Later I found a number of old OpenJDK tickets and discussions about libjvm.so not being built with -fPIC on ia32 and why. Long story short I don't expect there will be a workaround on the JVM end, not without building our own JVM (um, no thanks).

**Comment by adleong** [comment]
@stevej is this issue still valid and is there anything we can do about it?

**Comment by stevej** [comment]
I don't think we want to be responsible for building and updating a custom JVM build, I think the workaround is to run linkerd on a stock 64-bit JVM. I think we should close this ticket.
