### ISSUE TITLE
Remove `experimental` from h2 protocol

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#854]
We need to get a richer set of integration tests and get some real-life usage before promoting.

- [ ] https://github.com/BuoyantIO/linkerd/issues/840 -- use pooled buffers
- [x] https://github.com/BuoyantIO/linkerd/issues/731 -- h2 stats equivalence
- [x] https://github.com/BuoyantIO/linkerd/issues/732 -- h2 tracing
- [ ] #1776 -- h2 access logging

**Comment by adleong** [comment]
I don't think we're going to block this on #840.

**Comment by adleong** [comment]
At the same time as we move h2 out of experimental, we should also move the namerd mesh interpreter out of experimental as well.

**Comment by hawkw** [comment]
Issue #1776 now tracks adding access logging for HTTP/2.
