### ISSUE TITLE
`namer` stats mis-scoped

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#863]
We see stats in the form `namer/namer/#/io.l5d.k8s/default/success` -- I think because we scope stats in linkerd, and then again in the namer itself.  Namers shouldn't add a `namer` prefix explicitly, as it's set in the parent configurator.  (We should check that namerd scopes namer stats properly, too)

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd/pull/1330
