### ISSUE TITLE
Tranformer client stats not scoped properly

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#864]
We see stats like `clnt/daemonsetTransformer/available`.  These stats should be scoped under the namer they apply to and use the full module name like _io.l5d.k8s.daemonset_ -- maybe something like `[namer, io.l5d.k8s, trans, io.l5d.k8s.daemonset]` ?

**Comment by adleong** [comment]
Transformers are not (necessarily) scoped under namers.  Transformers *can* be attached to namers, but more often they are attached to name interpreters.  I would expect the stat scoping to be something like `[transformer, io.l5d.k8s.daemonset]`

**Comment by olix0r** [comment]
Transformers should just get the stats scope from whatever their parent is, probably.  When under the interpreter, the interpreter's stats scope; when under the namer, the namers stats scope.
