### ISSUE TITLE
More delineation in admin dashboard

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#918]
The admin dashboard represents the following type of tree structure:
```
Routers
+- RouterA
|    +- Clients
|    |    +- Client1
|    |    +- Client2
|    +- Servers
|         +- Server1
+- RouterB
     +- Clients
     |    +- Client3
     |    +- Client4
     +- Servers
          +- Server2
```

However, I find this structure difficult to see when scanning the page due to lack of delineation between sections and small headings.

It's hard to notice where one router begins an another ends.  There is a slightly thicker blue bar separating them but it doesn't really stand out to me and looks pretty similar to the thinner colored bars on the clients:
![screen shot 2017-01-11 at 11 18 01 am](https://cloud.githubusercontent.com/assets/3979810/21862851/d6bd6830-d7ef-11e6-9ca1-5edb86a1ac20.png)
A larger router header might help more clearly signal the start of a router section.

Clients are servers are hard to tell apart.  The "Clients" and "Servers" headings are smaller than their children which makes it hard to see how things are grouped.  In the screenshot below the colored horizontal line looks like the beginning of a section that encompasses everything below it until the next horizontal line.  In other words it looks like both the client and server stats are children of a section called "/#/io.l5d.fs/proxy".
![screen shot 2017-01-11 at 11 21 09 am](https://cloud.githubusercontent.com/assets/3979810/21863015/8fa31692-d7f0-11e6-9334-969997c2eb95.png)

(possibly related to https://github.com/BuoyantIO/linkerd/issues/915)

**Comment by wmorgan** [comment]
+1

**Comment by rmars** [comment]
![pasted image at 2017_01_24 09_25 am](https://cloud.githubusercontent.com/assets/549258/22260185/1aa5cc7c-e21d-11e6-9c73-b417500193f4.png)
