### ISSUE TITLE
auto-upgrade/downgrade support for ThriftMux protocol

### ISSUE THREAD

**Issue by hangfu** [linkerd/linkerd#919]
Finagle's ThriftMuxServer could automatically upgrade/downgrade ThriftMux to/from plain Thrift upon protocol negotiation with client. It would be nice to have this feature in Linkerd.

A typical use case is like this request flow:
A fingale client (mux) -> Linkerd A (mux) -> Linkerd B (mux) -> A service (only serves raw thrift requests)

**Comment by wmorgan** [comment]
Thanks, @hangfu! I thought we had this in place already, but apparently we do not.

**Comment by apakulov** [comment]
@wmorgan @olix0r we would be happy work on this implementation, if it is not a priority for you at the moment. Can you share your vision on how you would like to get it done? 

We're also looking for the following scenario with service topology like: finagle (mux) -> linkerd-sidecar-a (mux) -> service-a (thrift, non-jvm) -> linkerd-sidecar-b(mux) -> service-b (thrift, non-jvm). And we want to have mux all the way to service-b to preserve tracing for zipkin.

It would be great to have **linkerd** to handle protocol upgrade from thrift to mux and maintain zipkin traces for the service internally.

**Comment by wmorgan** [comment]
@apakulov that's awesome, maybe @olix0r or @adleong can write up a few pointers here.

**Comment by olix0r** [comment]
I'm not too clear on the details of how ThriftMux does protocol upgrade/downgrade.

If I were going to start working on this, I'd probably create a new protocol plugin, thriftmux, and figure out how to implement a Router that does the right thing.  I think the wrinkle is that when you typically instantiate a ThriftMux service in finagle, you bind the service to a specific Thrift service.  In linkerd, we can't do this, so we need to figure out how to create a Thrift service with a ThriftOrMux transport.  It _might_ be possible to just add this into the thrift router directly, but it'll probably be easier to sort out the details in its own module.

**Comment by apakulov** [comment]
@wmorgan @olix0r just created PR for thriftmux support, please check it out: https://github.com/linkerd/linkerd/pull/1022

**Comment by wmorgan** [comment]
@apakulov awesome!

**Comment by apakulov** [comment]
@olix0r you can close this ticket, thanks!

**Comment by olix0r** [comment]
thanks @apakulov
