### ISSUE TITLE
Improve Prometheus exporter to move instance/service from metric name to label

### ISSUE THREAD

**Issue by somejfn** [linkerd/linkerd#927]
Today Prometheus metrics name contain unique instance properties and this is making the integration with Prometheus harder to use when building queries.

For instance, this is a metric for a kubernetes service "grafana", on the "http" port in the "universe" namespace.

rt:http:dst:id:_:io_l5d_k8s:universe:http:grafana:request_latency_ms_p9999 0

I would rather have the specific instance properties moved to labels so something like:

rt:http:dst:id:_:io_l5d_k8s:request_latency_ms_p9999 0 {service="grafana", namespace="universe", port="http"}

Similarly:

rt:http:dst:path:http:1_1:GET:grafana_universe_dev1_domain_io:retries:per_request{stat="count"} 0

could be

rt:http:dst:path:http:1_1:retries:per_request{stat="count", method="GET", path="grafana_universe_dev1_domain_io"} 0

**Comment by wmorgan** [comment]
As discussed on Slack. Thanks for filing this, @somejfn!

**Comment by adleong** [comment]
We did some of this in https://github.com/linkerd/linkerd/issues/938.  We probably won't add namer specific labels such as namespace, service name, and port.
