### ISSUE TITLE
Add a `server` configuration option to clear context.

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#939]
Some servers -- for instance those exposed on the public network -- should not accept linkerd context.  Make it so that servers clear their context when this option is set.

Ideally, this would be implemented as a protocol-agnostic stack module that clears contexts (rather than a protocol-specific header-aware deal).

**Comment by wmorgan** [comment]
+1

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd/pull/1057
