### ISSUE TITLE
grpc.runtime.Stream should expose a `def reset(e: GrpcError): Unit`

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#944]
Stream consumers should be able to cancel a stream.  Improve the io.buoyant.grpc.runtime.Stream api to accept a `def reset(e: GrpcError): Unit`.  We'll need to introduce a GrpcError type, as well.

@stevej has done some work on this, I think

**Comment by stevej** [comment]
Yes, some of this is in-progress in the `stevej/grpc-interop` branch

**Comment by olix0r** [comment]
fixed https://github.com/linkerd/linkerd/commit/7cb015954d1f9d90ec16da5daf15fb3fa5d7b2de
