### ISSUE TITLE
Changing timezone for logging timestamps

### ISSUE THREAD

**Issue by robbfoster** [linkerd/linkerd#945]
Currently, the logs use two different formats of dates

* Jan 18, 2017 1:40:43 PM
* I 0118 21:40:43.751

which also come out in different UTC offsets.  If we could configure a timezone that both types of log messages obeyed or added an offset, that would make these dates much more usable.

**Comment by ManishMaheshwari** [comment]
+1. Different time formats posing issues with Splunk.

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd/pull/1049

**Comment by stevej** [comment]
This was released with today's 0.9.0 release, please let us know if you find other log lines that aren't uniform or are lacking a timezone. Specific examples are the most helpful. Thanks!
