### ISSUE TITLE
Introspection for Dtab consistency

### ISSUE THREAD

**Issue by robbfoster** [linkerd/linkerd#946]
Since the knowledge of the current namespace/dtab configuration is distributed (in our case, stored in Consul, fronted by Namerd, and replicated to the Linkerd instances), one of my concerns is the consistency of the routing information through the service mesh.  It would be useful to have a utility that could check on the state of the routing information across the service mesh to make sure, especially after an update, that the change has propagated correctly and completely.

**Comment by olix0r** [comment]
It may be difficult to measure this exactly as described, though I think we can come up with some good-enough heuristics and tools.  Let me explain:

When running with namerd, routing information isn't distributed to linkerd instances (i.e. linkerd never "downloads" a Dtab).  Instead, linkerd resolves individual _names_ through namerd, and maintains watches to receive updates. This allows the details of service discovery lookup to be centralized/cached in namerd (In the thrift interface, this is accomplished through long-polling, though the replacement for this--currently in testing--will use streaming responses).

It's fairly simple to expose a view of the namerd client's health in terms of success rate and throughput, which indicates whether the client has received _some_ updates but can't really answer the question of whether the instance has received _all_ updates for the following reason:

Not all linkerd instances observe the same names at the same time, and so updates are propagated unevenly. Consider a situation where appA runs with linkerdA, appB runs with linkerdB, and appA talks to appB through linkerdA.  linkerdA will have a watch for a name like `/s/appB`, but linkerdB will have no such watch.

In the near term, we can recommend namerd client metrics that indicate whether the client is generally healthy. We can probably augment this with additional diagnostic tools (i.e. that use linkerd's admin API) to allow you to ask deeper diagnostic questions of an individual running linkerd instances.

**Comment by adleong** [comment]
Namerd client metrics added here: https://github.com/linkerd/linkerd/pull/1060
