### ISSUE TITLE
Reference CNCF Code of Conduct

### ISSUE THREAD

**Issue by caniszczyk** [linkerd/linkerd#962]
Now that linkerd is under CNCF, we have our projects adopted a CNCF Code of Conduct:
https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc

https://github.com/cncf/foundation/blob/master/code-of-conduct.md

**Comment by olix0r** [comment]
https://github.com/linkerd/linkerd/wiki/Linkerd-code-of-conduct
