### ISSUE TITLE
Calculate counter deltas client side for the admin dashboard

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#966]
The admin dashboard makes calls to `/admin/metrics` every second to get delta values for a subset of counters.  It would simplify the metrics interface to not need to provide this and only provide `/admin/metrics.json` (the full list of metrics without any deltas).  The admin dashboard could store the previous value for counters and calculate diffs on the client side.

The deltas from `/admin/metrics` are not on a strict 1 second window, they refresh only when queried (up to a maximum of once per second).  Therefore, I don't think moving the delta calculation to the client will result in any loss of accuracy since the windowing was already driven by the rate at which the client queried.  

The result is that the server will no longer need to make any assumptions about the rate at which clients are querying.

**Comment by adleong** [comment]
Hey wait a minute.  The fact that `/admin/metrics` only refreshes the deltas when queried probably explains https://github.com/linkerd/linkerd/issues/379.  Moving to client side deltas is probably a more robust solution.

**Comment by adleong** [comment]
@rmars @esbie what do you think about the feasibility/level-of-effort for this?

**Comment by esbie** [comment]
extremely feasible/moderate amount of work (like a couple days worth)
