### ISSUE TITLE
Add "use node address" option to consul namer

### ISSUE THREAD

**Issue by markeijsermans** [linkerd/linkerd#967]
A service definition in consul can have an optional explicit IP address defined along side the host's node address. Currently linkerd does the right thing and defaults to using the service address if defined, and node address otherwise. In some situations it is needed to use the node address regardless.

As and example, we have an in-house routing solution which is similar the "linker to linker" model. 
We use the node address to route the request to the host, then use the service address to route to the required container locally.

Proposal:  add `useNodeAddress` option to `io.l5d.consul` namer. Defaults to `false` for current behavior.  

Code in question:
https://github.com/linkerd/linkerd/blob/0ab3f9f8cc6293893803f55085724b32a81295e6/namer/consul/src/main/scala/io/buoyant/namer/consul/SvcAddr.scala#L116

**Comment by olix0r** [comment]
This sounds reasonable to me. nitpick: are we instructing linkerd to use the node address? Or are we instructing it _not_ to use the service address?  It might be clearer to describe this as `ignoreServiceAddress` or something along those lines.

**Comment by markeijsermans** [comment]
I agree, `ignoreServiceAddress` is clearer with it's intention
