### ISSUE TITLE
Admin dashboard is slow

### ISSUE THREAD

**Issue by esbie** [linkerd/linkerd#973]
Opening this ticket to track slowness investigation. It routinely takes 1.5s to load an admin page on my dev machine. Given the server isn't even remote, I think we need to shoot for sub 1s on average.

Without having dug too deeply into the problem, I have some possible suspects:

* We're downloading too many small assets at once on page load.
* We're compiling too many Handlebar templates at page load.

Possible solutions we could implement (depending on root cause analysis):

* Bundle js/css assets
* Precompile templates
* Move app routing to the client

**Comment by adleong** [comment]
On my home network the call to `https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600` takes about 500ms and blocks further loading of the page while we wait for a response.  If we could not block on this we could probably shave those 500ms off.

**Comment by rmars** [comment]
(the  requirejs optimizer http://requirejs.org/docs/optimization.html will probably also be helpful)

**Comment by rmars** [comment]
Options:
- [ ] precompiling templates 
    - reduces current load times by ~1/3 
    - this is easy to do
    - doesn't require any changes to dev or release
- [ ] using r.js to optimize requirejs (serve all our js in a bundle)
    - reduces current load times by ~1/2
    - easy enough to do on the js side BUT
    - requires us to either set up a build tool or very manually switch between dev and the bundle we serve UNLESS we add some sort of flag when we run linkerd that will serve unbundled js
- adding a build tool e.g. grunt, gulp etc would add more complication to our dev process however then we could have nice things like es6 transpiling
-  for fonts, if we do move the font loading after the page loads, we get an unpleasant flicker as the whole page rerenders when the font loads

**Comment by wmorgan** [comment]
It's a nice font but blocking for 500ms seems like a lot. We could serve it locally...

**Comment by olix0r** [comment]
google claims that browsers should cache the fonts https://developers.google.com/fonts/faq#will_web_fonts_slow_down_my_page

Do we see this in practice?

re: build tool; As it is now, we only really depend on java/mvn, and then you run _./sbt linkerd/assembly_, and all of the dependency management just happens. I'm very squeamish about adding other build-time dependencies that can't be managed by sbt.  I just voliated this with protoc, in fact, and it's caused problems.  We can work around this by fetching/caching artifacts for the build (like we do with sbt) -- perhaps this could work for grung/gulp/etc, but I worry we biting off a bunch of dependencies.

How crazy of an idea is it to split the admin UI into a separate repo that produces a bundle of js,css,html assets? This way, linkerd can depend on a released tarball of the UI and  the UI buildchain can be separate. I think we could still make this work without making UI development much harder (but i'm guessing)--we'd have to start linkerd with a config that reads its admin json from e.g. _../linkerd-ui/assets_, but a build in the linkerd-ui repo would produce artifacts that could be served instantly from the running linkerd.  Is this crazy? Would it help?

**Comment by esbie** [comment]
I suggested the same thing in this thread for a related issue https://github.com/linkerd/linkerd/pull/1025#issuecomment-276824758

**Comment by esbie** [comment]
I'm with @wmorgan on serving the font locally

**Comment by adleong** [comment]
This relates to https://github.com/linkerd/linkerd/issues/1035.  Ideally we can find optimizations that play nicely with modularity.  Keep in mind that plugins outside the linkerd repo may provide functionality to the admin site, so some kind of "dynamic linking" is needed.

**Comment by rmars** [comment]
@olix0r I do like the idea of the admin UI in a separate repo that produces an asset bundle. Seems like it could be a clean separation. Not sure yet how that's going to work with plugins that provide functionality to the admin site. Would it be too messy to have contributors of a plugin also contribute to linkerd-ui and have some way for the ui to know which plugins are being used?

@esbie what do you think?

**Comment by esbie** [comment]
My general thought is a separate repo fits all the requirements we've put in place around dev productivity and modularity. I will provide a more in-depth analysis in #1035

**Comment by adleong** [comment]
I think we're happy with where performance is for now.  We can re-open or create a new issue if we feel like doing more in the future.
