### ISSUE TITLE
Recommended way to rate limit gRPC clients

### ISSUE THREAD

**Issue by haggag** [linkerd/linkerd#975]
What is the recommended way to rate limit gRPC clients using Linkerd; based on the client IP and/or client id?

**Comment by olix0r** [comment]
Hi @haggag.  Good question.  At the moment, linkerd doesn't expose any good primitives for this.  I believe that some users have implemented some form of rate limiting by implementing an _Identifier_ plugin that fails requests in some conditions, but this isn't a great solution.

I have some concrete ideas on how I'd like to solve this in the near future, and I've opened https://github.com/linkerd/linkerd/issues/1006 to track this.

I'm going to close this issue out for now, but feel free to reopen if you have further questions!
