### ISSUE TITLE
Consider collapsing client and server tracing spans

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#997]
Linkerd's current handing of span IDs is different than how spans are handled in most Finagle services. Typically, when a finagle service receives a request, it does not advance the span ID. This means that all annotations added by the server are attached to caller's client span, and the server only advances the span ID when it initiates a new client call. By contrast, Linkerd advances the span ID when it first receives a request, such that the server annotations are added to a child of the caller's client span, instead of the caller's client span itself. This doubles the number of spans that we report to tracing systems.

We should investigate if it makes sense for linkerd to stop advancing the ID on server spans. As part of this, we should also consider changing the RPC name that we attach to the consolidated span. Right now we use the router label for the server span and the HTTP method name for the client span. For the consolidated span, I propose that we use the router label + the dst path for the current request.

**Comment by klingerf** [comment]
Ok, have pushed the [`kl/span-ids`](https://github.com/linkerd/linkerd/compare/kl/span-ids) branch, which collapses span IDs as described in the description for this issue.

For comparison, here's a trace in the Zipkin UI with the existing span behavior:

![screen shot 2017-01-27 at 10 40 56 am](https://cloud.githubusercontent.com/assets/9226/22384367/def09a8c-e482-11e6-8d2e-874438869b3d.png)

And here's the same call pattern with the proposed new behavior:

![screen shot 2017-01-27 at 10 50 31 am](https://cloud.githubusercontent.com/assets/9226/22384380/e8a9f94c-e482-11e6-8221-1e9ec729b3f5.png)

You can see that the number of spans has dropped from 10 to 6, which is the result of the first and last spans being unmodified, and the middle 8 spans being collapsed to 4. I've also changed the span labels to provide more information.

Here's my attempt to describe the spans in the first trace:

```
1  external client          => external linkerd server (server receive)
2  external linkerd client => web service              (client send)
3  web service             => outgoing linkerd server  (server receive)
4  outgoing linkerd client => incoming linkerd server  (client send)
5  outgoing linkerd client => incoming linkerd server  (server receive)
6  incoming linkerd client => books service            (client send)
7  books service           => outgoing linkerd server  (server receive)
8  outgoing linkerd client => incoming linkerd server  (client send)
9  outgoing linkerd client => incoming linkerd server  (server receive)
10 incoming linkerd client => authors service          (client send)
```

Whereas for the second trace, we have:

```
1 external client         => external linkerd server                  (server receive)
2 external linkerd client => web service => outgoing linkerd server   (client send / server receive)
3 outgoing linkerd client => incoming linkerd server                  (client send / server receive)
4 incoming linkerd client => books service => outgoing linkerd server (client send / server receive)
5 outgoing linkerd client => incoming linkerd server                  (client send / server receive)
6 incoming linkerd client => authors service                          (client send)
```

Overall, the new trace format seems like an improvement to me, but I am concerned that by collapsing spans, we're losing two "services" in the zipkin UI: "inet/web" and "inet/books". "inet/authors" still appears as a service, since it does not make any downstream requests. But since web and books both make downstream requests, the downstream client annotations are being collapsed into their upstream callers, which creates a sort of gap in the UI where the services should be.

Put another way, looking at the second trace description above, spans 2 and 4 seem incorrect to me, since they span a service boundary. On the other hand, collapsing spans 3 and 5 seems appropriate, since those represent linker-to-linker requests. It would be really great if we could distinguish between these two types of spans and make the decision to collapse or not collapse accordingly, but I don't know of a good way to do that offhand.

**Comment by klingerf** [comment]
After thinking more about the collapsing issue outlined for the approach above, I think it's a blocker to collapse spans across service boundaries. Hence we will need to do some sort of conditional collapsing, or not collapse at all.

I added a workaround (d8146f52) to my branch that detects whether or not the incoming request came directly from another linkerd process, and only collapses linker-to-linker request spans. This produces the following trace in the Zipkin UI:

![screen shot 2017-01-27 at 2 33 58 pm](https://cloud.githubusercontent.com/assets/9226/22390497/3201ff5a-e4a0-11e6-98db-6f55a9d4e988.png)

As expected, this trace has 8 spans, since it's collapsing half as many spans as the original approach, and none of the spans cross service boundaries. I've also further tweaked the span labels to try to better represent what is going on. I like this result the best, but curious to know what others think.

**Comment by olix0r** [comment]
That's an interesting workaround, kevin. I think if we were going to do something like that, we should generalize it as `l5d-local-*` and mandate that services not forward these headers

**Comment by klingerf** [comment]
@viglesiasce Per our discussion in the linkerd slack a few days ago, I created the [kl/span-ids](https://github.com/linkerd/linkerd/compare/kl/span-ids) branch to experiment with span collapsing and relabeling. I'm pretty satisfied with where it's at now. Want to give it a try in your setup to see if it's an improvement in stackdriver?

**Comment by klingerf** [comment]
@olix0r Good thinking. Yeah, I was definitely trying to come up with a naming convention to help prevent users from inadvertently forwarding headers that are not meant to be forwarded.

**Comment by klingerf** [comment]
Ok, following an in-person discussion, we agreed that collapsing linker-to-linker spans would be a slight UI improvement that we should consider making configurable in the long run. In the meantime, we're just going to focus on relabeling the RPC names for each span, and keep the current collapsing behavior. Will post a branch for the relabeling change.

**Comment by viglesiasce** [comment]
Sounds good @klingerf, will test when its ready.

**Comment by klingerf** [comment]
Here's a screenshot from the Zipkin UI that shows the updated labeling:

![screen shot 2017-01-30 at 12 44 47 pm](https://cloud.githubusercontent.com/assets/9226/22440902/10b22040-e6ea-11e6-9918-7ae1d81386eb.png)

Compare that to the same trace pattern with the existing labeling:

![screen shot 2017-01-27 at 10 40 56 am](https://cloud.githubusercontent.com/assets/9226/22384367/def09a8c-e482-11e6-8d2e-874438869b3d.png)

What do folks think about this approach?

**Comment by viglesiasce** [comment]
This looks great!! Is it possible for it to be configurable (templatized)?

**Comment by klingerf** [comment]
@viglesiasce Good thinking! I think we'll tackle that in a follow-up change though. I created #1014 to track it.

**Comment by esbie** [comment]
@klingerf can we close this issue now?

**Comment by klingerf** [comment]
Sure, will close this now. We can revisit if we decide to do any span collapsing in the future.
