### ISSUE TITLE
Negative incoming connection stat

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#998]
I loaded a linkerd dashboard for a kubernetes instance that had not received any traffic yet, and I saw a negative number in the client connections field, here:

![screen shot 2017-01-26 at 11 23 03 am](https://cloud.githubusercontent.com/assets/9226/22353656/63252eec-e3d6-11e6-82a6-7a448a06aac6.png)

Sure enough, the connections gauge for that router is negative in the metrics.json response:

```
$ cat negative_connections.txt | jq -S . | grep connections
  "clnt/daemonsetTransformer/connections": 1,
  "rt/incoming/srv/0.0.0.0/6161/connections": -793,
```

Not sure how it got into that state, but it seems incorrect. Here's the full stats payload from that instance:

[negative_connections.txt](https://github.com/linkerd/linkerd/files/733805/negative_connections.txt)

**Comment by adleong** [comment]
I think moving to MetricsTree should make this impossible.  Please reopen if you see it again.
